### ISSUE TITLE
When Kopernicus is installed, Kerbals sink to the bottom of the sea.

### ISSUE THREAD

**Issue by Retrograde115** [Kopernicus/Kopernicus#106]
Tested with Kopernicus + Outer Planets Mod installed. Kerbals are able to swim but unable to float.

**Comment by NathanKell** [comment]
Are you sure you are on the current version? This sounds like a very old bug.
Make sure:

1. You're on KSP 1.0.5 build 1028+ (check BuildID.txt in your KSP folder)
2. You're on Kopernicus 0.6.2.

**Comment by KillAshley** [comment]
just tested fresh install of kopernicus 0.6.2 and KSP 1.0.5, issue did not appear. Peraps you are using either; an outdated version of kopernicus, or, thre is some cfg error in OPM that creates this sink

**Comment by Retrograde115** [comment]
Ah, you're right. Outer Planets Mod is what's causing the bug. Kopernicus 0.6.2 by itself works fine. After going through the OPM forum post, turns out it works best on Kopernicus 0.5.2. (Damn small print) Rolling back solves the issue.

Sorry for the inconvenience!

**Comment by ThomasKerman** [comment]
Does this occur on Kopernicus-added Oceans or Stock ones too?
Could I please see your output_log.txt?

Reason is, that I haven't changed anything related to Oceans, IIRC, and I want to be sure that it will work.
