### ISSUE TITLE
Kopernicus won't allow changes to atmospheres

### ISSUE THREAD

**Issue by mferrie** [Kopernicus/Kopernicus#107]
This is on and off, but Kopernicus isn't letting me change planetary atmospheres or any other characteristics for that matter. Below is my config. When I start the game, the Tracking Station shows the stock information only, not my customized atmospheres. This is odd because I practically copied the code from the Other Planets Mod and customized it to my liking.

@Kopernicus:AFTER[KOPERNICUS]
{
	@Body[Eve]
	{
		@Atmosphere
		{
			altitude = 52000
			pressureCurve
			{
				key = 0 9300
				key = 4000 3421.2788028944
				key = 8000 463.0197358211
				key = 12000 170.3354416652
				key = 16000 62.6629070915
				key = 20000 23.052395243
				key = 24000 8.4805022797
				key = 28000 3.1198024395
				key = 32000 1.147711178
				key = 36000 0.4222193468
				key = 40000 0.1553258173
				key = 44000 0.0571411749
				key = 48000 0.0210210635
				key = 52000 0
			}
			temperatureCurve
			{
				key = 0 773.15 // Friggin' HOT
				key = 12000 273.15 // Sane
				key = 32000 173.15 // COLD
				key = 40000 223.15 //Temperature inversion?
			}
			atmosphereMolarMass = 0.04309
			// 96.5% carbon dioxide (molar mass 0.044),
			// 4.5% nitrogen (molar mass 0.014).
			// (0.965*0.044) + (0.045*0.014)
		}
	}
	@Body[Kerbin]
	{
		@Atmosphere
		{
			altitude = 35000
			pressureCurve
			{
				key = 0 101.325
				key = 3500 37.2753843767
				key = 7000 13.7128475739
				key = 10500 5.0446747024
				key = 14000 1.8558321104
				key = 17500 0.6827224797
				key = 21000 0.2511595643
				key = 24500 0.0923964402
				key = 28000 0.0339907508
				key = 31500 0.0125044984
				key = 35000 0
			}
		}
	}
	@Body[Duna]
	{
		@Atmosphere
		{
			altitude = 21000
			pressureCurve
			{
				key = 0 6
				key = 3000 2.207276647
				key = 6000 0.8120116994
				key = 9000 0.2987224102
				key = 12000 0.1098938333
				key = 15000 0.040427682
				key = 18000 0.0148725131
				key = 21000 0
			}
			temperatureCurve
			{
				key = 0 223.15
				key = 12000 123.15
				key = 18000 173.15
			}
			atmosphereMolarMass = 0.04329705
			// 96% carbon dioxide (0.044),
			// 1.9% nitrogen (0.014),
			// 1.9% argon (0.03995),
			// and 0.2% oxygen (0.016).
			// (0.96 * 0.044) + (0.019 * 0.014)
			// + (0.019 * 0.03995) + (0.002 * 0.016) = 0.04329705
		}
	}
	@Body[Jool]
	{
		@Atmosphere
		{
			temperatureCurve
			{
				key = 0 450
				key = 10000 125
				key = 20000 200
				key = 30000 150
				key = 35000 200
				key = 100000 950 //some sort of thermosphere
				key = 120000 800
				key = 150000 500
				key = 200000 120 //cold again because we're beyond the snow line
			}
			atmosphereMolarMass = 0.09245
			//chlorine trifluoride - Very explosive and very Kerbal!
		}
	}
	@Body[Laythe]
	{
		@Atmosphere
		{
			ambientColor = 0.8,0.56,0.32
			altitude = 22500
			{
				key = 0 147
				key = 2500 54.0782778522
				key = 5000 19.8942866358
				key = 7500 7.3186990501
				key = 10000 2.6923989166
				key = 12500 0.9904782089
				key = 15000 0.36437657
				key = 17500 0.1340466489
				key = 20000 0.0493130063
				key = 22500 0
			}
			atmosphereMolarMass = 0.01405175
			// 96% nitrogen (0.014),
			// 3.5% methane (0.01604),
			// 0.5% hydrogen (0.001007).
			// (0.96*0.014)+(0.035*0.01604)+(0.05*0.001007)=0.01405175
			temperatureCurve
			{
				key = 0 95
				key = 1000 80
				key = 2000 40
				key = 4000 80
				key = 6000 130
				key = 8000 140
				key = 10000 150
				key = 15000 160
				key = 20000 175
			}
		}
	}
}

**Comment by mferrie** [comment]
All tabs are correct in the code above, to my knowledge, at least in Notepad++.

**Comment by NathanKell** [comment]
Does an Atmosphere node exist in the original system.cfg?

**Comment by NathanKell** [comment]
i see it does. Post the Kopernicus section of your config cache? (ModuleManager.ConfigCache)

**Comment by mferrie** [comment]
Where would I find the config cache?

**Comment by NathanKell** [comment]
GameData root.

**Comment by ThomasKerman** [comment]
You are missing something here:
```altitude = 22500
{```
I think pressureCurve is missing.

Since this does not confirm with the specifications for a Config Node, MM aborts.

**Comment by mferrie** [comment]
DERP! Thanks for catching that, @ThomasKerman!
