### ISSUE TITLE
Not sure if this is a bug or if I'm doing something wrong

### ISSUE THREAD

**Issue by mferrie** [Kopernicus/Kopernicus#108]
I tried to change Ike's radius to something tiny like 5 km, and instead of scaling nicely, it became a weird spikeball. What should I be doing instead of just changing the radius in @Properties? Should I need to do some sort of PQS magic?

**Comment by ThomasKerman** [comment]
You have to scale down the deformity of the PQS Mods too.
@Sigma88 has made a nice tool for rescaling planets, SigmaDimensions
