### ISSUE TITLE
oblate stars

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#110]
oblate stars used to work but now I don't seem to be able to make them load.

this is the code I use: [AlgokB](https://github.com/Sigma88/Galactic-Neighborhood/blob/master/GameData/GalacticNeighborhood/StarSystems/Algok/Configs/AddStar_AlgokB.cfg)

and this is the [body.log](https://www.dropbox.com/s/vk3cxcp3rclbap4/Algok%20B.Body.log)

**Comment by ThomasKerman** [comment]
Could you please try to add a materialType value to the PQS node? The value doesn't matter, but it has to be parseable by Kopernicus.
The reason is that Kopernicus expects a surface material for PQS that are created from scratch.

**Comment by Sigma88** [comment]
tried with:
```
Body
{
	PQS
	{
		materialType = AtmosphericMain
	}
}
```
but it didn't work, same error as before

**Comment by ThomasKerman** [comment]
Oh, I just checked the commit history, and noticed that I fixed this bug one month ago, but it wasn't included in 0.6.3. That's why it works for me and not for you.
Will be fixed with 0.7

**Comment by Sigma88** [comment]
no need to keep this open then, good job thomas! :+1:
