### ISSUE TITLE
My Kopernicus Mod Doesn't Work

### ISSUE THREAD

**Issue by FerrariRunner** [Kopernicus/Kopernicus#111]
I made a mod that adds a single gas giant, Ianiedes. I loaded the game and there were no fatal gliches, but the planet didn't show up in the tracking station.
[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/129986/Logs.zip)

**Comment by GregroxMun** [comment]
I really don't think that's what this issue tracker is for. If you made a gas giant and it didn't work, it's probably your fault. Ask for help making a planet, not for fixing a bug that does not exist.

**Comment by FerrariRunner** [comment]
sorry i put this on the wrong thread.
