### ISSUE TITLE
hiding orbits

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#112]
while using mode=0 to hide orbits, orbits are hidden correctly untill you change sphere of influence, at which point they come back.
a scene change (eg. loading a save) resumes the hidden orbits.

**Comment by Sigma88** [comment]
also, it seems that the issue only happens if you change SoI while in flight mode.
if you change SoI while staying in map mode, the orbits stay hidden

**Comment by ThomasKerman** [comment]
Do you have access to 1.1? If yes, please try it again with latest dev, as this could / should be fixed with https://github.com/Kopernicus/Kopernicus/commit/031c52bf9558d8133408237bd90a5210bdd349c4#diff-9a76a04e855c2e5e783fc96235ef84d4R115

**Comment by Sigma88** [comment]
Solved, thanks Thomas!
