### ISSUE TITLE
1.1 and Kopernicus

### ISSUE THREAD

**Issue by swavkulinski** [Kopernicus/Kopernicus#113]
Reflection exception during loading.

Linux 64 bit, KSP.x86_64

Tested with MM 2.6.18 and 2.6.21

https://gist.github.com/swavkulinski/a0536426d41fe01e2f3022350f267c50

**Comment by yaus** [comment]
This version with MM 2.6.18 is not up-to-date for KSP 1.1.
Please be patient. Wait the updated Koprnicus  for KSP 1.1
