### ISSUE TITLE
Low FPS performance with 1.0.1

### ISSUE THREAD

**Issue by tomato3017** [Kopernicus/Kopernicus#118]
Kopernicus is dramatically decreasing FPS performance in 1.0.1, When using 1.0 this issue is not present. The only mods that were installed were GCMonitor and this mod.

**Comment by NathanKell** [comment]
LOG PLS.

Can't do nuthin without logs.

**Comment by ThomasKerman** [comment]
I think I know what he means. My RnD fixer runs all the time when you are in space center, but it didn't caused any performance issues for me.

Logs would be neat though.

**Comment by tomato3017** [comment]
Apologies for no logs, I didnt see the debug logs spewing any exceptions so I didn't think it would be of much use. However, I should of known better being in the log mangling business myself heh.

The issue is resolved on my end, FPS is back to ~180 range. Thanks!
