### ISSUE TITLE
Rings

### ISSUE THREAD

**Issue by imkSushi** [Kopernicus/Kopernicus#123]
Using this code:

angle = 25
lockRotation = true

the rings should rotate relative to the planet as the planet rotates, which it does, BUT:
In the KSC view, the rings stay stationary, and do not move.

**Comment by Devan-Kerman** [comment]
I have little experience modding so don't trust me on this and this is going to sound EXTREAMLY stupid but,
Make 131329793 moons and remove their icon thingy and BAM you have a ring!
Remember the lag though...

**Comment by Sigma88** [comment]
this was addressed in the latest patches
