### ISSUE TITLE
Textures of Planet Packs Using Kopernicus are all Yellow

### ISSUE THREAD

**Issue by thepowersss** [Kopernicus/Kopernicus#130]
I am using KSP version 1.1.2, and have installed several planet packs that use kopernicus. Attached is a screenshot of the mods I'm using.

![mods-installed](https://cloud.githubusercontent.com/assets/19959980/16095015/a831ce22-32f7-11e6-8bc5-45cc9be7ead3.JPG)

When I start up KSP and go to the tracking station and look at all of the new planets that were added using these modpacks (OPM and New Horizons), they all appear to be yellow. Attached here are some screenshots of what they look like.

![screenshot 2016-06-15 12 43 10](https://cloud.githubusercontent.com/assets/19959980/16095085/ee8b2378-32f7-11e6-91fe-84a03f4bc7e3.png)
![screenshot 2016-06-15 12 43 14](https://cloud.githubusercontent.com/assets/19959980/16095083/ee875de2-32f7-11e6-8f26-d152ce1649e2.png)
![screenshot 2016-06-15 12 43 17](https://cloud.githubusercontent.com/assets/19959980/16095088/ee8ef2be-32f7-11e6-9240-0a66e991b536.png)
![screenshot 2016-06-15 12 43 22](https://cloud.githubusercontent.com/assets/19959980/16095086/ee8b9e52-32f7-11e6-851d-3b55c7989ff5.png)
![screenshot 2016-06-15 12 43 36](https://cloud.githubusercontent.com/assets/19959980/16095084/ee8a8602-32f7-11e6-8f27-d01aa526bad9.png)
![screenshot 2016-06-15 12 43 40](https://cloud.githubusercontent.com/assets/19959980/16095087/ee8bb4aa-32f7-11e6-8c2c-2b65ec6c7eb3.png)
![screenshot 2016-06-15 12 43 44](https://cloud.githubusercontent.com/assets/19959980/16095089/ee98224e-32f7-11e6-8110-2e2ee9ba5c6e.png)
![screenshot 2016-06-15 12 42 58](https://cloud.githubusercontent.com/assets/19959980/16095092/eea1cc54-32f7-11e6-9b13-e2de6ae12673.png)
![screenshot 2016-06-15 12 43 00](https://cloud.githubusercontent.com/assets/19959980/16095091/eea1817c-32f7-11e6-8e95-679d12e1766f.png)
![screenshot 2016-06-15 12 43 03](https://cloud.githubusercontent.com/assets/19959980/16095090/ee9ecd6a-32f7-11e6-954e-704d73b1069a.png)

The strange thing is, all modded have the same pattern, and they're all yellow. However, vanilla planets like Jool or Kerbin are not affected. Is there a fix for this? Did I maybe mess up on installation? Restarting KSP and making a new save does not fix this , nor does restarting my computer.

**Comment by ThomasKerman** [comment]
As it turns out, this is related to an issue with graphics drivers, possibly linux only.

I can't do anything against it, as it is working for me properly. Check the Kopernicus thread for more info.

**Comment by aw1621107** [comment]
I'm getting this issue now, but I'm on macOS (10.13.1), and playing with RSS. Earth, the Moon, the Sun, and Vesta have normal surface textures, and a few planets (Jupiter, Saturn, Titan, and Neptune) have the yellow tiles on top of their normal textures:

<img width="1392" alt="screen shot 2017-12-04 at 11 16 25 pm" src="https://user-images.githubusercontent.com/566572/33628227-0cb3e046-d9ce-11e7-92ac-635a9eaa2455.png">

<img width="1392" alt="screen shot 2017-12-05 at 3 08 42 pm" src="https://user-images.githubusercontent.com/566572/33628288-3b6a029e-d9ce-11e7-908c-2fdfaa88578e.png">

<img width="1392" alt="screen shot 2017-12-05 at 3 09 44 pm" src="https://user-images.githubusercontent.com/566572/33628325-5bdb1d42-d9ce-11e7-9285-9a8a77d97bf9.png">

<img width="1392" alt="screen shot 2017-12-05 at 3 13 08 pm" src="https://user-images.githubusercontent.com/566572/33628533-0426566a-d9cf-11e7-9e97-8b7bed3d412f.png">

I'm fairly certain that things were working as expected before, but unfortunately I'm not sure when exactly the change happened, as there was a fairly long period where I played without visiting other planets in the map view. I've been on the same set of mods and macOS version for quite a while, so I'm not really sure what changed.
