### ISSUE TITLE
Kopernicus 1.1.3 is incompatible with 1.1.3

### ISSUE THREAD

**Issue by InterstellarOrbit** [Kopernicus/Kopernicus#137]
Hello,
I have followed the instructions on installing Kopernicus very much to detail, however, whenever I launch the game, it follows with a error message; "Mod might be Broken or incompatible".

**Comment by Sigma88** [comment]
logs?

**Comment by InterstellarOrbit** [comment]
Ah, Sorry, It appears to have been a mod incompatibility problem. Sorry for wasting your time.
