### ISSUE TITLE
Engine produce much less thrust with 1.2.0 release

### ISSUE THREAD

**Issue by Joonatanr** [Kopernicus/Kopernicus#139]
It seems that engines produce less thrust with Kopernicus than without it.
Possibly this could be due to increased drag when Kopernicus is enabled.

Occurs : Always (at least for me), removed all mods besides Kopernicus.
How to reproduce:
Use simple two stage rocket with 3 fuel tanks for lower stage, 1 for upper stage. 
Lower stage powered by single LVT-45 engine.

Without Kopernicus installed the rocket works fine.

With Kopernicus installed the LVT-45 engine is unable to lift the rocket, or
does so with great difficulty. 

Maybe this is related to drag. The issue is also very noticeable in the higher atmosphere, where
trajectory rapidly decays even if no engines are being fired.

**Comment by jmrd98** [comment]
Check your modular flight integrator version; I had a similar issue and found it as the cause. (Disclaimer: not blaming mfi, just anecdotal advice)

**Comment by ThomasKerman** [comment]
Seems to be a MFI bug indeed. 1.2.0-2 has the newest MFI bundled
