### ISSUE TITLE
Planet Not showing up After being Compiled

### ISSUE THREAD

**Issue by InterstellarOrbit** [Kopernicus/Kopernicus#142]
Hello, I recently made a planet that loves to not show up. There Appears to be no errors in the log. I have spent atleast two months trying to fix it by myself(And even using The Example Files), but it still does not show up. Can anyone help me? 

Dropbox With CFG and .dds files: https://www.dropbox.com/sh/ras701ut1xbnd2f/AABF5UyCn640nfDnNNNU5RToa?dl=0

Log file:
[KSP.txt](https://github.com/Kopernicus/Kopernicus/files/568146/KSP.txt)

**Comment by Sigma88** [comment]
in your ksp install folder there is a folder called "Logs" that contains more detailed informations about planets, if you could upload that folder as well it might be easier to spot were your planet went wrong

another good idea would be to start from a basic planet and then add piece by piece untill you see that the planet doesn't show up. so you know which part of the cfg breaks your planet

a very basic cfg would be like this: 

```
@Kopernicus
{
        name = Skyrite
        Template
        {
            name = Vall
        }
        Orbit
        {
            referenceBody = Sun
        }
}
```

notice that you didn't use any Template, that's probably why your planet fails to load

**Comment by Sigma88** [comment]
so I guess this is solved, can we close it?
