### ISSUE TITLE
See no Planets

### ISSUE THREAD

**Issue by FaPaDa** [Kopernicus/Kopernicus#150]
Hey Guys, my Problem:

After starting KSP and install the Kopernikus and the Outer Planets mod, everything looks ok. But then I zoom out at map. Eeloo isn't there (I now that is right) but the other planets behind Jool aren't there too. I deleted every mod I have in my KSP folder, (except Kopernikus and the Outer Planets mod) re-install both mods, but have still this Problem.

I don't know, is this a Problem with Kopernikus or with Outer Planets? And more important, how I fix it?

**Comment by Sigma88** [comment]
you'll need to post logs for us to take a look at, also if you are using Kopernicus 1.2.1-2 keep in mind that OPM is not yet compatible.

[here's a list of what we need to help you](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-121-kopernicus-release-1-november-3/&page=27#comment-2793409)
