### ISSUE TITLE
Solar Panels and Atmosphere update

### ISSUE THREAD

**Issue by FlyingBadger** [Kopernicus/Kopernicus#151]
Following yesterdays update I have a major noticable change....

All solar panels in game no longer charge my batteries! 
I have checked a variety of types both stock and mod derived and all of them can be pointed at Kerbol to get 100% coverage and sunlight but all of them say 0 charge and the batteries are all going flat.

Debug console mentioned the radiant flux in a Kopernicus piece of code (i'll post the error message etc in a moment).

Kopernicus is a fantastic mod and I really don't want to uninstall it.

KSP 1.2.1
Kopernicus updated yesterday (21st November) via CKAN

**Comment by FlyingBadger** [comment]
I went into KSP and I have both the error information and the exception information from the debug menu now here is what they say:

Errors:

> TimingFI threw during Update:
> System.NullReferenceException: Object reference not set to 
> an instance of an object 
> at Kopernicus.Components.KopernicusStar.SunBodyFlux 
> (ModularFI.ModularFlightIntegrator flightIntegrator) 
> [0x00000] in <filename unknown>:0 
> at ModularFI.ModularFlightIntegrator.CalculateSunBodyFlux() 
> [0x00000] in <filename unknown>:0 
> at FlightIntegrator.ThermoPercalculate() [0x00000] in 
> <filename unknown>:0 
> at FlightIntegrator.Update() [0x00000] in <filename 
> unknown>:0 
> at ModularFI.ModularFlightIntegrator.TimedUpdate() 
> [0x00000] in <filename unknown>:0 
> at TimingFI.Update() [0x000] in <filename unknown>:0

Exceptions:

> NullReferenceException: Object reference not set to an 
> instance of an object
> ArgumentNullException: Argument cannot be null.
> Parameter name: source

Hope this is useful

**Comment by infoman** [comment]
After the ninja-fix solar panels appear to be working, but ckan must be confused by another release with the same version name.
