### ISSUE TITLE
API for Kopernicus

### ISSUE THREAD

**Issue by StollD** [Kopernicus/Kopernicus#152]
@Sigma88's mods heavily interact with Kopernicus, and I think there are enough ideas for other ones. At some point, an API should exist that allows hooking into Kopernicus and replacing its behaviour.

**Comment by Sigma88** [comment]
<3

**Comment by Mrcarrot1** [comment]
Yeah, I want to make a plugin that enhance the OrbitLoader, but I don't know if I can

**Comment by Gordon-Dry** [comment]
It just came to my mind, that for example a sun flare is not rendered when mirrored in a chrome surface ...
Could this be made possible by such an API?

**Comment by sswelm** [comment]
An API might no longer be needed if you access the Kopernicus files directly. For myself, I have now created a [helper class](url=https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/FNPlugin/Resources/Kopernicus.cs) which retrieves all stars relative luminosities.

**Comment by Sigma88** [comment]
since there is a talk about APIs, I am working on a mod that will require me to hijack the LoadOnDemand system

now it works like this (roughly):
```
1- A planet becomes visible
2- Kopernicus triggers OnDemand
3- OnDemand Loads the Texture
4- Kopernicus applies the Texture
```

Ideally I want to insert myself like this:
```
1- A planet becomes visible
2- My mod decides which Texture to load and triggers OnDemand
3- OnDemand Loads the Texture
4- My mod processes the Texture
5- Kopernicus (or my mod) applies the Texture
```
