### ISSUE TITLE
The entire project is broken

### ISSUE THREAD

**Issue by mferrie** [Kopernicus/Kopernicus#153]
Kopernicus doesn't load when I install it, giving me the error "The classes could not be loaded". When I go into the source, everything is really outdated. Please update Kopernicus to be compatible with 1.2.

**Comment by Sigma88** [comment]
<a href="http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409">![Please Provide Logs](https://s3-us-west-1.amazonaws.com/umbrella-blog-uploads/wp-content/uploads/2015/09/s3_proxy.png)</a>

**Comment by FizzerUK** [comment]
Kids are out.. It's the weekend :-)

Thomas as you well know..

Kopernicus is AWESOME!!

Next payday coffee your way again  ;-)

**Comment by ThomasKerman** [comment]
@mferrie I have no idea what you are even talking about.

If you want to use the release build, check like the last 6 releases, which were for 1.2, 1.2.1 and 1.2.2. If you want to compile it from source make sure you got all dependencies in place and that you are using git properly

**Comment by Sigma88** [comment]
@mferrie  are you still experiencing this issue? can we close it?

if not, have you tried gathering the files we need to help you?
I can help you locate them if [this post](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409) is not clear enough

**Comment by mferrie** [comment]
Ok, I just tried rebuilding the project with the source from the current release, and it threw all kinds of "This feature is obsolete and will be removed" errors, as well as about 2000 "Interface is not an interface" errors or something silly like that.

**Comment by ThomasKerman** [comment]
Please describe me exactly what you are doing in order to build the repository from scratch

**Comment by mferrie** [comment]
I download the source zip, update the references by clicking on the projects and clicking "update references", then going to my KSP 1.2.1 install's "managed" folder and selecting the appropriate DLL's, then I try to build the project by clicking "Build" in the main window. The output window then fills with thousands of messages.

**Comment by ThomasKerman** [comment]
This repository uses git submodules. Downloading the zipball **wont** work. Please use git correctly and clone the repository

**Comment by mferrie** [comment]
I honestly should have updated you a lot earlier, but 64K is not working
perfectly. I have a whole slew of mods working currently.

On Friday, December 9, 2016, Sigma88 <notifications@github.com> wrote:
> <
https://ci5.googleusercontent.com/proxy/9Id0apytDlAF1Pk5KAPzrvgHNOH39fPFIyo-NOUYiELnDrzoxp7xod-7sX4CJVdbYmpY-vmxTOSnk7SHerkOErblu2lI6km0rausTw1Zg0HsjJzKCCYLzkpnO--P1ruUfkRN6F5f3-aJFd-z-WpdoZK_iiHFeOlZq8ZbGli7yEsOx3QMpPFfQsVi_tUSewsLMjxATrHS5mla_JPIz7FYmlTqCyN_6uHGTLbmk_ScWQWK-SWuV7qzf_ads5xSQvy8gRATZivFU1gd3NIGA74k9rVih2qYhiyXcKCKXVPdoU-9v9-sihV61DTs3Gt6YfhTJCRTvA33SYHgBfsF3EKD5EzgAs-RUkXw89v9ALhNQXVazRtxhh0aDTxNhdK4QpAkD3Fv=s0-d-e1-ft#https://camo.githubusercontent.com/c20cd6443352d0c69f0f9639405b620c72c31876/68747470733a2f2f73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f756d6272656c6c612d626c6f672d75706c6f6164732f77702d636f6e74656e742f75706c6f6164732f323031352f30392f73335f70726f78792e706e67
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/DVcjmQEcmC7DFmCQ26YxVlo5eFBM8a93s8NlWx9gfOtW4BHyHyqaiHKK3CExxWdA2XZihDSWf9MmbhRhu4yvjhVyzLWqfp51409fHI2IzY1tzwHOHbURZoeThHCjNfZoUNTdzXacMCxSQWB1YpBmI6mhlD6eyA=s0-d-e1-ft#https://github.com/notifications/beacon/AOUAb83BauW7VH6FwDplzNYHQQLafoRDks5rGc1BgaJpZM4LJY71.gif>
