### ISSUE TITLE
Kopernicus spams NRE's under Linux

### ISSUE THREAD

**Issue by kaa253** [Kopernicus/Kopernicus#158]
Steps to reproduce.
1. Clean install KSP 1.2.2 for Linux 64 bit.
2. Install Kopernicus into GameData from https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.2.2-2.
3. Go to flight scene and open debug console.
4. Press "M" to switch to map.
5. Observe NRE spam.

Log files attached.
[Player.log.zip](https://github.com/Kopernicus/Kopernicus/files/691418/Player.log.zip)
[KSP.log.zip](https://github.com/Kopernicus/Kopernicus/files/691419/KSP.log.zip)

**Comment by ThomasKerman** [comment]
Sory, haven't seen this. Could you please post your Logs/Kopernicus folder?

**Comment by kaa253** [comment]
No problem. Reading back through the forum thread I just became aware you may want the logs. Coming here I see you do. Sweet.
[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/700956/Kopernicus.zip)

**Comment by StollD** [comment]
This is... weird. I dont see anything in the logs that could have caused this, and I dont have this issue on my machine (windows).

Does this only occur when installing the raw Kopernicus, or with planet packs too?

**Comment by kaa253** [comment]
It occurs with raw Kopernicus and with OPM too. It does not occur in tracking station view only in the in-flight map view and although it is spamming NREs continuously in the map view I don't actually notice a performance hit to speak of so I am persevering with it.

**Comment by byaka** [comment]
maybe same issue with [SVT](http://forum.kerbalspaceprogram.com/index.php?/topic/143828-122-stock-visual-terrain-v202/&do=findComment&comment=2967501)
[KSP.log](https://dl.dropboxusercontent.com/u/49471009/KSP.log)
[Player.log](https://dl.dropboxusercontent.com/u/49471009/Player.log)

**Comment by mikeloeven** [comment]
Also encountering this under windows 
https://youtu.be/EO1388cNs6g

[KSP.txt](https://github.com/Kopernicus/Kopernicus/files/802669/KSP.txt)

**Comment by StollD** [comment]
Both of your logs contain an exception while loading the Kopernicus Configs, which makes me think that this is an issue with the respective planet mods (one time the error occurs while loading Eve, and the other time while loading a body named "1")

**Comment by mikeloeven** [comment]
Yep I posted it on the TBG forum as well but thanks for confirming its an issue with world generation and not kopernicus it's self

**Comment by Sigma88** [comment]
Have you managed to solve this issue?

**Comment by canisdirusleidy** [comment]
Looks like the root of the problem here lies in "Modular Flight Integrator" mod. Check (on Linux) with KSP 1.2.2 and 1.3 and latest (1.2.2-7 and 1.3.0-2) Kopernicus:  everything is normal without MFI, but then MFI is installed I get "Kopernicus.RuntimeUtility.LateUpdate () [0x00000] in <filename unknown>:0" spam after switching to map mode in flight.

[KSP122log.zip](https://github.com/Kopernicus/Kopernicus/files/1056747/KSP122log.zip)
[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/1056748/Kopernicus.zip)

**Comment by Sigma88** [comment]
Without mfi kopernicus disables itself.

So everything is indeed "normal" as in "not modified by kopernicus" :)

**Comment by Monchoman45** [comment]
I also have this problem in 1.3.0 with release-1.3.0-2 using only Kopernicus (no OPM or anything else). Interestingly, everything is fine if you have a level 1 tracking station; NREs only show up when you upgrade to level 2.

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/1065515/KSP.txt)

**Comment by StollD** [comment]
Please try it with this build and send me your logfiles. Just copy the files in the zip in GameData/Kopernicus/Plugins
[DebugSpam.zip](https://github.com/Kopernicus/Kopernicus/files/1065686/DebugSpam.zip)

**Comment by frencrs** [comment]
That build prints '4' to the log before each NullRefException. The first '4' is printed to the log before the first NullRefException.


[KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/1066222/KSP.log.txt)

**Comment by Monchoman45** [comment]
Here it is. The magic number is 4, apparently.

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/1066316/KSP.txt)

**Comment by StollD** [comment]
I hope my last commit fixed this issue. Here is the build for you, so you can test it.
[MaybeFixed.zip](https://github.com/Kopernicus/Kopernicus/files/1066364/MaybeFixed.zip)

**Comment by Monchoman45** [comment]
LGTM, no more NREs.

**Comment by frencrs** [comment]
Awesome that works, would that fix be easy to add to the 1.2.2 backport?

**Comment by canisdirusleidy** [comment]
But it broke compatibility with SigmaDimensions (at least under Linux): exceptions begins at game loading and endless loop of NREs then trying to start new game/load savefile from main menu.
[KSP_logs.zip](https://github.com/Kopernicus/Kopernicus/files/1067688/KSP_logs.zip)

**Comment by StollD** [comment]
@canisdirusleidy I need the logs from Logs/Kopernicus too please

**Comment by Sigma88** [comment]
the modulemanager cache file also can help

**Comment by canisdirusleidy** [comment]
Here they are.
[Kopernicus_logs.zip](https://github.com/Kopernicus/Kopernicus/files/1069216/Kopernicus_logs.zip)
[ModuleManager_logs.zip](https://github.com/Kopernicus/Kopernicus/files/1069217/ModuleManager_logs.zip)

**Comment by Sigma88** [comment]
I think this should have been addressed in one of the latest patches, are you still seeing this issue?

**Comment by kaa253** [comment]
Sorry about the slow follow up. I have been without internet for a couple of months.
It looks very much like this is now fixed. Thank you Dorian, Sigma88 and All!

**Comment by Sigma88** [comment]
glad to hear!
