### ISSUE TITLE
Can't finish loading when there are rss and kopernicus in the gamedata folder

### ISSUE THREAD

**Issue by NecessarilyCaution** [Kopernicus/Kopernicus#167]
The game keeps loading,it's all blackness besides the loading icon is rolling at the bottom.
KSP: 1.2.2 (Win64) - Unity: 5.4.0p4 - OS: Windows 10 (10.0.0) 64bit
KSP-AVC Plugin - 1.1.6.2
ModularFlightIntegrator - 1.2.2
RealSolarSystem - 12.0

**Comment by StollD** [comment]
You will need to post your output_log.txt and your Logs/Kopernicus folder

**Comment by Sigma88** [comment]
[logs please](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409)

**Comment by NecessarilyCaution** [comment]
@StollD @Sigma88  there are 28 projects in Logs/Kopernicus folder and my Internet is not good so I can't upload the  output_log.txt. You can point out what information you need and I will copy

**Comment by StollD** [comment]
Sorry, we need the whole logs to figure out what is wrong.

Have you tried to (7-)zip the files?

**Comment by NecessarilyCaution** [comment]
[new zip.zip](https://github.com/Kopernicus/Kopernicus/files/966203/new.zip.zip)

**Comment by StollD** [comment]
Ok
* The modlist you posted in the first post is just wrong. You have 50 mods in your gamedata.
* Your KSP / Kopernicus cannot load the biome maps RSS needs. So either, the RSS-Textures folder is somehow misplaced, or that your system cant load the textures because of another reason.
* In fact, your system is crashing because it hasn't got enough memory while loading the planets

Something is going on with your install. I recommend a restart and a reinstall

**Comment by NecessarilyCaution** [comment]
[new.zip](https://github.com/Kopernicus/Kopernicus/files/966209/new.zip)
@StollD

**Comment by StollD** [comment]
This is interesting: `[Kopernicus] texture does not exist! C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/KSP_x64_Data/../GameData/RSS-Textures/PluginData/EarthBiomes.png`

Try to move everything from the RSS-Textures/Biomes folder into the RSS-Textures/PluginData folder

**Comment by NecessarilyCaution** [comment]
all the biomes folder or only the projects in it？

**Comment by Sigma88** [comment]
also, sometimes having the install in program files causes issues

**Comment by StollD** [comment]
@NecessarilyCaution Only the files in it. If you copy the path I posted (C:/Program Files/...) into your adress bar on the explorer, a file must open.

@Sigma88 When you install steam, it sets the correct permisssions for steamapps, so no problem there.

**Comment by NecessarilyCaution** [comment]
The issue was solved,thanks!
