### ISSUE TITLE
Year/Day/Hour/Minute are hadcoded to Kerbin time in the ClockFormatter

### ISSUE THREAD

**Issue by magico13** [Kopernicus/Kopernicus#169]
See the source code here: https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus/Kopernicus/RuntimeUtility/ClockFixer.cs#L451

These properties are hard coded to use Kerbin time no matter what the Formatter is actually set to. Any mod that uses these values for their own time formatting will show invalid times when using the formatter (see [MagiCore](https://github.com/magico13/MagiCore/blob/master/MagiCore/MagiCore.cs#L24) and subsequently Kerbal Construction Time). Although MagiCore should probably just call some of the existing methods for time formatting (which appear to be defined correctly), those properties should be corrected.

**Comment by Sigma88** [comment]
If I didn't mess up my PR the properties should now return the custom values calculated by kopernicus
Or the standard ksp values in case kopernicus doesn't change them

It's worth noting how kopernicus can not only change day and year, but also all the other time units (second included)

And can change the names of those units in addition to the "lenght"

**Comment by magico13** [comment]
Does anyone ever change the value of a second? That could really mess with things since a lot of things are stored internally as seconds and just formatted later (outside of my mods as well). I don't know that it would fully break KCT, but it would certainly mess with the UI.

**Comment by Sigma88** [comment]
Time is still stored in real life seconds, and laws of physics still apply as usual. The only difference is that the clock can be changed to display custom units of time, so if you wanted a system where the unit of time is (for example) a blorg which lasts 0.5 real life seconds, when the game time reaches 10 seconds the clock would display 
Year 1, Day 1, 00:00:20

**Comment by magico13** [comment]
Alright. I'll have to keep that in mind for the future. My code's all old and ultimately goes back to 0.23. I'll have to investigate whether my clocks will line up correctly or not, but with those properties corrected my stuff should at least be a lot closer to lining up. Thanks!

**Comment by Sigma88** [comment]
For what it's worth nobody currently changes the names or values of seconds/minutes/hours (as far as I know)

The only two changes are day and year which can be changed by kopernicus to fit the rotation/revolution of the home planet
