### ISSUE TITLE
rings issues

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#171]
Multiple reports from @KillAshley  and @GregroxMun

- in UL, Kerbin rings are not visible from kerbin's surface
- in NH Sonnah rings are not visible from Kerbin's surface
- in OPM Sarnus rings are not visible from Tekto's surface, [GregLogs](https://www.dropbox.com/s/46r5l2yx3njw6kv/Ringfail.zip?dl=1)

I've asked for logs, if I don't get any I will produce them myself later tonight

**Comment by Sigma88** [comment]
rings seem to still have problems, see discussion on IRC
(can't provide backlog since kiwi sucks)

**Comment by Sigma88** [comment]
updating the title, @galileo88 / @ohiobob any logs from your test will be apreciated

if you could reproduce that issue on a simple system 
like, try to add rings to jool on a stock install 
and upload the logs on here
that would help speeding up the process 

otherwise we need to reproduce the issue on our own, which depending on our free time could result in a much longer wait

you can find what we need [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/)

**Comment by Sigma88** [comment]
@galileo88 said on IRC that

> **Galileo88:** The ring issue doesnt happen in a stock system :/

this seems to indicate that the bug you are experiencing is due to an incompatibility issue rather than a base kopernicus issue

it also means that we will need you to pinpoint the minimum amount of mods that cause the bug to appear, I assume it's only 1 extra mod on top of a standard kopernicus install... but you never know...

**Comment by StollD** [comment]
Gah, I forgot to revert that one commit

**Comment by Sigma88** [comment]
From @OhioBob via private mesaage on the forums, regarding the new dev version of kopernicus:

> **OhioBob:** I just finished running some tests and I think all the ring problems are fixed.  Every test I ran looked perfect.
