### ISSUE TITLE
Solar panels not working at all, and more

### ISSUE THREAD

**Issue by Devan-Kerman** [Kopernicus/Kopernicus#174]
I have been playing with mods that add more star systems and I've always had the problem that solar panels don't work, They generate no electric charge even when the have exposure, also occasionally I have large drops in framerate, the ksc glitches out, also sunrise and sunset does not work properly in the ksc or in other places and this happens with and without mods installed.

So far the only way I'm able to play is deleting visual mods and rely on RTGs or nuclear reactors.
I must admit they are pretty cool but, solar panels are cool too. :)

**Comment by Devan-Kerman** [comment]
![image](https://cloud.githubusercontent.com/assets/28693059/26038328/a8a81886-38cb-11e7-8954-2d74dc4aaeee.png)

**Comment by Devan-Kerman** [comment]
I have kss at the mod I am using

**Comment by Sigma88** [comment]
solar panels work fine in kopernicus where there is only one star (the Sun)

when there are more then one star solar panels have issues, this is know and we are working on it.

KSS is also known to be buggy, there are a number of bugs they need to fix on their end

**Comment by Devan-Kerman** [comment]
Ok, thanks!

**Comment by Devan-Kerman** [comment]
And as a suggestion, can you add an option to not load planets at all until viewed. The reason is that this creates a big framerate drop but, it breaks Scatterer and other visual mods.

**Comment by Devan-Kerman** [comment]
![image](https://cloud.githubusercontent.com/assets/28693059/26038433/e1ee0b62-38cd-11e7-9169-8a5d7e0b37a3.png)
oh, and another image, but with the exposure. :)

**Comment by Sigma88** [comment]
closing this and merging with #166
