### ISSUE TITLE
cbNameLater

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#177]
I had some time to play around with displayName and I came to the conclusion that it can completely replace cbNameLater.

I propose, for backwards compatibility's sake, to leave cbNameLater as a valid Kopernicus input, but having it just change displayName internally.

I will prepare a pull-request, in the meantime if anyone has objections to this, you can comment here

**Comment by Sigma88** [comment]
pinging here some people I know use the feature:

@NathanKell  (RSS)
@GregroxMun (various)
@Galileo88 / @Ohiobob (GPP)

the only downside to this change would be with science definition.

right now, using cbNameLater, science defs need to point at the final name, so

> EarthSrfLanded = def

instead of

> KerbinSrfLanded = def

using displayName you would need to use the "name" regardless of what the displayName is.

so all packs that rename the homeplanet should use

KerbinSrfLanded


I think this is a small price to pay since displayName seems to be a much more stable option over cbNameLater.

I've already moved on to use displayName in my mods that were using cbNameLater and I've yet to see any downsides.

**Comment by StollD** [comment]
I don't want to remove it, at least not now.

The reason is simple: It works. And displayName works too, so the planet makers can decide when they will switch. The only thing we should do is to say, that cbNameLater can be removed in every update and that the planet makers should switch to displayName as soon as possible.

**Comment by Sigma88** [comment]
that's cool by me, I've already switched anyways

**Comment by NathanKell** [comment]
Thing is I would like to keep Earth called Earth in data as well as
visually, so I'd like to stay on cbnamelater

**Comment by Sigma88** [comment]
@NathanKell  is there some places where the real name of the planet could come up?

**Comment by Sigma88** [comment]
I'd say there's enough interest to keep cbNameLater, so I'll just close the issue

**Comment by NathanKell** [comment]
Sorry I didn't get back (saw you closed it) but did want to state for the record that even if the only place it's used is the save file, that's still very useful when trying to debug a save. But it's very possible that there's legacy code in mods, even if not in KSP itself, where name not displayname is used.

**Comment by Sigma88** [comment]
yes that's what I was thinking.
I don't really care about that, mods can always be updated, but I can understand how for a mod like RSS you might want to avoid go through the changes

**Comment by NathanKell** [comment]
Yep, also has a worrying effect on saves without a conversion plugin I think (due to science records as you say, and also body progress trees).
