### ISSUE TITLE
Kopernicus not loading planets and requires reinstall

### ISSUE THREAD

**Issue by TurretProblems** [Kopernicus/Kopernicus#179]
Alright, ill post a log if requested but I thought it may have a simpler solution (maybe I'm just doing something wrong, although everything appears to be installed correctly):

So when I launch KSP and loadings all done, it doesn't load planets, however, after reinstalling the same version, it works and even then its not all the time it does this, it appears to be random (both solving the issue with reinstall, and the issue occurring at all), however I was wondering if anyone else is having this issue and knows a solution?

Also getting alot of exceptions saying the game can't load certain files of various things.
Computer specs I do not wish to upload but know I'm able to handle high part count and many shaders.
I have one planet pack known as "Total rebuild"

Sorry for the wall of text

**Comment by StollD** [comment]
logs

**Comment by TurretProblems** [comment]
knew you were ganna say that ;), ill get em

**Comment by TurretProblems** [comment]
alright, heres the thing, its sporadic, it sometimes loads and sometimes doesn't load, when i launched it just now, its working fine, the day before, errors galore, maybe theres a way you can put this post on hold till it happens again?
i don't want to waste your time, I'm just terribly confused

**Comment by Sigma88** [comment]
we also need the Logs folder from your ksp install
(it's in the same folder that contains GameData)

**Comment by TurretProblems** [comment]
okey
will do ASAP

**Comment by Quarior** [comment]
For me, Kopernicus don't load configuration file if configurations are in folder without Plugins and Shaders. I test KopernicusExample for see the problem but doesn't work. I put Kopernicus and KopernicusExample to GameData folder. I restart the game but nothing.
Here the log find in Kerbal Space Program folder :
[KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/1055507/KSP.log.txt)
But where is output_log ?

**Comment by StollD** [comment]
> [LOG 17:07:44.675] Load(Assembly): /ModuleManager.2.6.5

Thats a very outdated ModuleManager. You should use the version that comes with Kopernicus (2.8.0)

**Comment by Quarior** [comment]
Yes but if I use the ModuleManager.2.8.0, the game crash if I use. Here the output_log.txt :
[output_log.txt](https://github.com/Kopernicus/Kopernicus/files/1055578/output_log.txt)
And the KSP.log :
[KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/1055588/KSP.log.txt)

**Comment by StollD** [comment]
You are running out of memory because you run the 32-bit executable. Use KSP_64.exe

**Comment by Quarior** [comment]
Thanks, is work.

**Comment by Maxybo** [comment]
Hi guys

I'm getting some issues with planets not loading, i have taken a look over the logs but i don't understand the errors regarding parsing, i have attached some logs, anyone see what my issue is?
[Moho.Body.txt](https://github.com/Kopernicus/Kopernicus/files/1069391/Moho.Body.txt)
[Kopernicus.txt](https://github.com/Kopernicus/Kopernicus/files/1069392/Kopernicus.txt)
[KSP.txt](https://github.com/Kopernicus/Kopernicus/files/1069394/KSP.txt)

**Comment by Sigma88** [comment]
I'd say that you might have a VertexColorMapBlend with a wrong texture path or file name

**Comment by Maxybo** [comment]
Any idea how I could go about fixing that?

**Comment by Sigma88** [comment]
use the correct path?

**Comment by Maxybo** [comment]
ok thanks, i could not find any other reference in the logs for VertexColorMapBlend other than where the parsing error was, sorry no idea how to check or changes paths for this.  Which cfg file would be of use?

Thanks

**Comment by Sigma88** [comment]
you linked the "Moho" log file, I assume you have some cfg in gamedata that change moho

in one of those you should find a node called "VertexColorMapBlend" at some point, in that node there should be a path for a file that is wrong.

**Comment by Maxybo** [comment]
Found the issue thanks to your pointer, turned put i had missing textures from the KSPRC mod, once added all working now.  Thanks again.
