### ISSUE TITLE
Problem if I move "the Sun" (the default sun) around a another object (star)

### ISSUE THREAD

**Issue by Quarior** [Kopernicus/Kopernicus#181]
I put for "the Sun" (the default sun) orbit around "the Sol" (our Sun) but when I load the game, almost all object is disappear and the "Space Center Menu" don't show the Space Center but in the space or maybe under the surface of Kerbin (I see Mun I think). Also, all asteroid I discover around "the Sun" orbit the Sol.....
![space center menu in space](https://user-images.githubusercontent.com/27765452/26841788-e3ba7960-4aea-11e7-83d5-fbc1d57cfc16.png)
![asteroids around the sol](https://user-images.githubusercontent.com/27765452/26841792-e8a57a88-4aea-11e7-81f8-7f913e328098.png)
The RealSolarSystem I use for test (I put "Sun" in the orbit hypothetic of Nemesis around the Sol) : [RealSolarSystem edit.zip](https://github.com/Kopernicus/Kopernicus/files/1055862/RealSolarSystem.edit.zip)
The log : [KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/1055866/KSP.log.txt)
My save game : [Quabox.zip](https://github.com/Kopernicus/Kopernicus/files/1055897/Quabox.zip)

**Comment by Sigma88** [comment]
you never move the sun

ksp hardcodes the central body to be called "sun" so if it's not, it breaks the game.

use "Properties/displayName" to change which name is visualized

also, it's not called KERBOL it's called "Sun" or "The Sun"

**Comment by Quarior** [comment]
So first, I know in game it is "Sun" (or "The Sun"), it is for you don't confuse between the default Sun and our Sun I name "Sol".

Next, I test your method, I replace the default Sun by Sol (I rename Sun) and make a new object star with the name Kerbol and move default planets to Kerbol.

And I have the same problem, asteroids orbit around "The Sun" instead "Kerbol" and worse, all the ships have disappeared even if I resume my backup (it is the same save in the previous post), I just have the flag that I put on Mun only.
![asteroids around the sun our sun instead kerbol](https://user-images.githubusercontent.com/27765452/26870449-4a202e68-4b70-11e7-8ca2-9cbe9a1423a3.png)
![the flag on mun](https://user-images.githubusercontent.com/27765452/26870459-50ba747c-4b70-11e7-9bb4-cc66b0e8ee5e.png)

I noticed also even if I disable the RSS mod that Kerbin havent a gravity of 1 g but 1.00034 g. It is normal ?
![kerbin don t have 1 g but 1 00034 g](https://user-images.githubusercontent.com/27765452/26870391-241ac6ba-4b70-11e7-84b9-8195227611a6.png)

And of course the same problem for the _Kerbal Space Center Menu_ but I read for now, is normal in the [readme](https://github.com/Kopernicus/Kopernicus/blob/master/README.md).
> Note - reparenting Kerbin or the Sun can cause the sky to be incorrect in the space center view. It is, however, correct in the flight view and the flight map view.

The log : [KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/1057436/KSP.log.txt)
The RSS edit : [RSS edit.zip](https://github.com/Kopernicus/Kopernicus/files/1057441/RSS.edit.zip)

So the solution are :
* Orbit Sol around the Sun (unrealist)
* Put the Sol System in a fixed position but don't orbit the Sun (if possible)

Also, how to create a barycenter and delete receptions (or relay fixed) by default on the Kerbin template ? I don't see in the [wiki](https://github.com/Kopernicus/Kopernicus/wiki/Template).

Thanks for answer.

**Comment by Sigma88** [comment]
You cannot change the name of the body at the center of the universe

If the variable "name" of the body at the center of the universe is anything but "Sun" (case sensitive) the game will break.

You can get ksp to display a different name by changing the displayName parameter in Body/Properties but under no circumstances you should change the "name" for the body at the center of the universe

**Comment by Sigma88** [comment]
Nevermind I misunderstood your question

If you are loading an old save yes, old asteroids will load in orbit around the wrong body

 craft save files define which body they orbit using the name. New asteroids will spawn in the location defined in the cfg

**Comment by Quarior** [comment]
OK, thanks for information so it is possible then for active/disable the modification for each save and the mod support a existing save with asteroids spawn before edit and ships (no Ships folder where are SPH and VAB) also the *Space Center Menu* ?

**Comment by Sigma88** [comment]
editing a save is not possible with kopernicus, but new asteroid will spawn following the rules defined in their cfg

for example, stock asteroids spawn near kerbin and near dres, this means that if you move kerbin to orbit something else, the asteroid will spawn there too.

if you, on the other hand, have custom-defined asteroids, you might need to change their orbit's referenceBody from "Sun" to whatever the name of the new referenceBody should be

**Comment by Quarior** [comment]
Ok, I understand for asteroids but why ship despite that they as parent Kerbin or Mun are not moved ? Should all the parents of the object be specified ?
Also in sfs, how to edit the REF (because is a number) ?

**Comment by Sigma88** [comment]
I don't know the flightglobals indexes, you will need to put marker ships in orbit around each one of the stock bodies and see what's saved in the save file.


honestly I would recommend against installing a planet pack halfway through a saved game

**Comment by Quarior** [comment]
So after read the history, I got this (I comment) :
[System.cfg.txt](https://github.com/Kopernicus/Kopernicus/files/1063686/System.cfg.txt)
So I reconfigurate the RSS system because there are the same _flightGlobalsIndex_ :
[RealSolarSystem edit.zip](https://github.com/Kopernicus/Kopernicus/files/1063698/RealSolarSystem.edit.zip)
I will test it just now because I'm going to eat, so I would tell you a while ago unless you test during this time.

**Comment by Sigma88** [comment]
ah yes I did not think of that

you should try to avoid having multiple planets with the same FGI defined, it might be that crafts load on weird places if more than one planet have the same FGI

you can safely remove all FGI definitions and you should be fine (unless you load saves that were generated on another planet pack)

**Comment by Quarior** [comment]
OK, so I test and doesn't work, I don't know why so I create a new game...
Have a nice day.

**Comment by Sigma88** [comment]
as I said, the best thing when changing the layout of the system is always to start a new game, if you removed all "flightGlobalIndex" from the planets, kopernicus will generate them automatically and that way you will not have issues with the new save

if you leave the flightglobalindex in the cfg, and you happen to have duplicates, KSP may save a craft in orbit around a planet but load it on another one (when they both have the same FGI)

**Comment by Quarior** [comment]
Ah OK, very big thanks. I create a game and load a sfs save of my old save and is work.
But at times, it moves the KSC for no reason (it also did it before I made a new game and that I but my backup) even if it's on the same basic planet (Kerbin), it moves it away even when I go to pilot a ship, the KSC has really moved to another place and I Know the cause so I hope this problem is corrected.
![ksc menu](https://user-images.githubusercontent.com/27765452/26984927-9b870ccc-4d41-11e7-9f54-0035a67a1ab4.png)
![ksc in runway](https://user-images.githubusercontent.com/27765452/26984938-a33d7582-4d41-11e7-893e-32f7b6680953.png)
![new ksc location mallard](https://user-images.githubusercontent.com/27765452/26984952-acdb0866-4d41-11e7-9724-f055425cd343.png)
[KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/1064669/KSP.log.txt)
It is the same RSS edit.

Have a nice day.
