### ISSUE TITLE
Kopernicus not setting biome displayname

### ISSUE THREAD

**Issue by DMagic1** [Kopernicus/Kopernicus#183]
In KSP 1.3 biomes now have a localized name field.

[CBAttributeMapSO.MapAttribute.displayName](https://kerbalspaceprogram.com/api/class_c_b_attribute_map_s_o_1_1_map_attribute.html#ac0c5207b4a1257f963f805274a094a47)

This is read for science results among other things.

The BiomeLoader class doesn't appear to handle this, only setting the regular name field.

An option to set a display name would be good for localization, but it should at least set the display name using the regular name field by default.

**Comment by StollD** [comment]
Done by @Sigma88
