### ISSUE TITLE
Can't view Space Center

### ISSUE THREAD

**Issue by ApolluZed** [Kopernicus/Kopernicus#185]
I recently made an addon where a gas giant replaces the spot where Kerbin is relative to the Sun and Kerbin along with the Mun orbits the gas giant. For some reason when I make kerbin's relative body the gas giant, the Kerbal Space Center menu is blue. Is there a workaround for this?

**Comment by ApolluZed** [comment]
Neverm

**Comment by Sigma88** [comment]
You should not change kerbin referenceBody
Instead you should use

PostSpawnOrbit
{
    referenceBody =
}

To change kerbin's parent
