### ISSUE TITLE
compiling under linux

### ISSUE THREAD

**Issue by omgbebebe** [Kopernicus/Kopernicus#187]
I trying to build Kopernicus from master branch against KSP-1.3.0 libs. Project is compiling fine, but with lot of warnings about shaders `Creating materials from shader source string is no longer supported. Use Shader assets instead.`. Then when I try to start KSP with compiled Kopernicus I get bunch of NREs in KSP.log. If I try to start KSP with prebuilded Kopernicus-1.3.0-4 from releases then it works fine without any errors.
I tryed to compile via `make release` according to the documentation and via `xbuild Kopernicus.sln` with same results.
Could you point me to what I doing wrong and which important build steps I've missed?
[build log and KSP.log](https://gist.github.com/omgbebebe/7790d30dac5f44a5b1f759e3337f10ff)

**Comment by StollD** [comment]
I don't think that you missed any buildsteps, but you've done some things different. For example I don't compile against the .NET / mono dlls shipped with KSP but the ones from mono itself (_mono-reference-assemblies-3.5_ I think). And my compiler version is fairly outdated. (but I am too lazy to update it)

Could you maybe attach your compiled .dll's? Maybe the decompiler shows something

**Comment by omgbebebe** [comment]
Thx for the reply! I'll try to experiment with .NET libs and compiler version. Here is[ my compiled dlls](https://drive.google.com/file/d/0B6xXLVZaE9k4N1k4QVFiMTFvSGM/view?usp=sharing).

**Comment by omgbebebe** [comment]
Experiments showed that the problem in mono compiler. I've tryed various mono versions: 4.2, 4.4, 4.6, 5.x with the same result. Then I build latest stable Roslyn and compile with it and the issue is gone. Maybe it is something similat to https://bugzilla.xamarin.com/show_bug.cgi?id=36839 I don't know.
I think that this issue can be closed. Sorry for disturbing and thanks for your help!

**Comment by Sigma88** [comment]
Ok, happy to see you solved your issue :)
