### ISSUE TITLE
Land Control issue

### ISSUE THREAD

**Issue by Galileo88** [Kopernicus/Kopernicus#189]
As you may have read the conversation between me an @Sigma88 on the forum thread, the last two versions of kopernicus  (1.3.0-3 and 1.3.0-4) have essentially disabled the LandControl  PQS.  I have donr multiple tests to see if it was on my end and nothing I do has solved it. Sigma88 looked through the logs and has determined that its beyond him as well as there is nothing in the logs showing an error and asked me to create this issue for you.
Here are all of the logs and cfgs I have posted in the thread.

This was a test in stock
https://www.dropbox.com/s/hy9lqr6nuotmpj7/KopernicusLCtest.zip?dl=0

**Comment by gordonfpanam** [comment]
I don't suppose this is related to my use of the BUILTIN_kerbin_height_new texture in LandControl to make a clone Kerbin, and then being unable to reuse this in VertexHeightMap? If I attempt this in 1.3.0-4 I get an [exception](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-130-122-kopernicus-release-4-june-15/&do=findComment&comment=3106714) telling me there's a problem with the current state of the object.

**Comment by Sigma88** [comment]
the correct syntax is:

>heightMap = BUILTIN/kerbin_height_new

if you use that one it should work (but possibly it won't since it has reported as a bug)

**Comment by Sigma88** [comment]
it's also possible that squad changed the name of the texture
I will need to check that

**Comment by gordonfpanam** [comment]
I think I caused a distraction actually; Galileo's original problem was the LandControl PQS not working and no scatter objects showing up. I just wondered if LandControl was messing with the built-in texture so no other PQS could use it.

**Comment by Sigma88** [comment]
the name is correct, maybe there's an issue in how the texture is loaded

**Comment by Sigma88** [comment]
using this cfg on a stock install (+Kopernicus) I don't get any errors and the logs are clean

so the issue must be somewhere else
```
@Kopernicus
{
	@Body[Kerbin]
	{
		%PQS
		{
			%Mods
			{
				LandControl
				{
					heightMap = BUILTIN/kerbin_height_new
				}
			}
		}
	}
}
```

**Comment by gordonfpanam** [comment]
OK I submitted my problem under a different issue, #190, to avoid confusing my problem with Galileo's missing scatter objects problem. These do appear to be different problems, because I can reproduce Galileo's problem whether I use a BUILTIN heightMap or not. Scatter objects appear up to 1.3.0-2, and stop appearing with 1.3.0-3 and 1.3.0-4.

**Comment by Sigma88** [comment]
this issue should have been solved, if it passes some more tests it will most likely be included in the next release

**Comment by Avera9eJoe** [comment]
Sounds good Sigma, Spectra will look a lot better with trees again!

**Comment by Galileo88** [comment]
Definitely fixed
