### ISSUE TITLE
Specify index number for each Body?

### ISSUE THREAD

**Issue by gordonfpanam** [Kopernicus/Kopernicus#194]
GregroxMun just released a 1.0 of Alien Space Programs that includes a home world switching option. He tells us the option is good for switching between home worlds in one saved game, but I figured (and verified) that this wouldn't hold because the index numbers would change depending on which world was the home world, and any craft in orbit of or landed on a specific body would move to a different body with the same index.

I seem to remember someone saying The Sun has to be index 0 and Kerbin (or whatever the home world is) has to be index 1, then the rest are loaded in a certain order. Can this order be changed, or can an index number be specified for each Body?

**Comment by Sigma88** [comment]
I think this could be achieved by specifying fgi in the cfg

The homebody still needs to have fgi=1 (afaik) but at least you can keep the others consistent
