### ISSUE TITLE
Kopernicus causing game to soft lock on loading screen

### ISSUE THREAD

**Issue by Ownage7428** [Kopernicus/Kopernicus#195]
This all started a couple of days ago, I installed Kopernicus a couple of weeks ago with a planet pack and everything worked fine except for one thing. Kopernicus took away the light created by the sun and placed the source of the light so far away out of the solar system for some reason that the game was unplayable it was so dark. So I decided to just reinstall Kopernicus with the latest version (1.3.0-4). Now KSP will soft lock when loading a save when Kopernicus is in my GameData files. Sounds play and it sounds as if everything is ready, but the game is stuck on the loading screen with the little spinning solar system in the bottom right. The logs spam this message:  NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate ()

KSP.log attached: 
[KSP.txt](https://github.com/Kopernicus/Kopernicus/files/1153423/KSP.txt)

I would like some help fixing this bug or figuring out what is causing it please??? Thank you. 

EDIT: I tried Kopernicus 1.3.0-3 and everything works like a charm. Seems to be a problem with the current version or maybe my computer?

**Comment by Ownage7428** [comment]
Oh, I found a way around it. I was using Kopernicus 1.3.0-4. Using 1.2.2-9 fixes the bug.

**Comment by Sigma88** [comment]
could you provide also the files listed here?

**Comment by Vladimir-csp** [comment]
I have the same problem, but using 1.3.0-3 does not fix it.

I use Sigma Dimensions 0.8.2 with config:
```
```

[Player.log.txt](https://github.com/Kopernicus/Kopernicus/files/1156945/Player.log.txt)

**Comment by Sigma88** [comment]
you can't use SD v0.8.2 with kopernicus 1.3.0-3 because it is made to work with 1.3.0-4

**Comment by Vladimir-csp** [comment]
SD v0.8.0 also does not work.

**Comment by Vladimir-csp** [comment]
I've just installed latest versions of Kopernicus and Sigma once again and it started working. Maybe clearing  various MM caches helped.

**Comment by kilralpine** [comment]
Suffered from the soft load issue also, I ended up realizing it was a mistake I made during a fresh mod install. I forgot GPP Textures, I had downloaded them but forgot to install them. *facepalm* Running with 100 mods on kopernicus 1.3.0-5, GPP 1.4.0, and Sigma 0.8.2.
