### ISSUE TITLE
I can't get get kerponicus to work

### ISSUE THREAD

**Issue by FuryFire2004** [Kopernicus/Kopernicus#198]
When this mod is installed  the loading screen for everything but the start up file loader is locked forever. I have tried with out the mod and it loads fine  I tried no planet packs it has the same loading problem I look at the files it is all normal.

**Comment by FuryFire2004** [comment]
My kopernicus log

[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/1184164/Logs.zip)

**Comment by Sigma88** [comment]
your log is basically empty

could you please provide all the files listed [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-121-kopernicus-release-1-november-3/&page=27#comment-2793409)?

**Comment by FuryFire2004** [comment]
sorry no I have no  account there but is can put them here

**Comment by Sigma88** [comment]
yes you can upload anywhere you want and provide me the links on here.

anything is fine as long as I can download the files easily :)

**Comment by FuryFire2004** [comment]
or not I can not paste it over 10mb it says

**Comment by Sigma88** [comment]
the files I requested should not go over 10 mega

which of the files is the biggest?

**Comment by FuryFire2004** [comment]
my ksp game data?

**Comment by FuryFire2004** [comment]
oh you mean my mod file?

**Comment by FuryFire2004** [comment]
[Kopernicus-1.3.0-4.zip](https://github.com/Kopernicus/Kopernicus/files/1184313/Kopernicus-1.3.0-4.zip)
 there

**Comment by KillAshley** [comment]
if you need more than 10mb for some reason then upload the .zip to dropbox and link it here

**Comment by FuryFire2004** [comment]
my mod manager is in kerponicuse files

**Comment by Sigma88** [comment]
@FuryFire2004  I'm not sure what you uploaded there

what I need is:

- a list of the mods you have installed, complete of which version of KSP you are running
- KSP logs (I assume you know where to find them, if not I'll explain)
- the file **ModuleManager.ConfigCache** from GameData
- the whole "Logs" folder you can find in your KSP installation directory
- a screenshot of the content of your GameData folder

**Comment by FuryFire2004** [comment]
![capture](https://user-images.githubusercontent.com/30536275/28737509-cd8b8f4e-73bc-11e7-9dc8-cf5ca65c6efb.PNG)

**Comment by FuryFire2004** [comment]
[Logs (2).zip](https://github.com/Kopernicus/Kopernicus/files/1184339/Logs.2.zip)

**Comment by FuryFire2004** [comment]
[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/1184343/ModuleManager.zip)

**Comment by Sigma88** [comment]
you should not have the "Kopernicus-1.3.0-4" folder there

inside the Kopernicus archive you will find a "Kopernicus" folder and a "ModularFlightIntegrator" folder

those needs to be directly inside GameData

so, GameData/Kopernicus and GameData/ModularFlightIntegrator

**Comment by FuryFire2004** [comment]
oh wow...  I am a bit embarrassed that I didn't notice that

**Comment by Sigma88** [comment]
don't worry, I've seen worse
if this is solved you can close the issue

**Comment by FuryFire2004** [comment]
it worked I think..

**Comment by FuryFire2004** [comment]
nope when I put mod manager in it broke
