### ISSUE TITLE
Light bug

### ISSUE THREAD

**Issue by SamBelanger** [Kopernicus/Kopernicus#207]
Hello i think i found a bug, the proof

http://imgur.com/a/rEIZU

KSP: 1.3 (Win32) - Unity: 5.4.0p4 - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
BetterTimeWarpContinued - 2.3.8
Chatterer - 0.9.93.1804
Community Trait Icons - 0.1.2
DistantObjectEnhancement - 1.9.1
FShangarExtender - 3.5
Kerbal Engineer Redux - 1.1.3
HyperEdit - 1.5.4
KerbNet Controller - 1.0.3
Kopernicus - 1.3.0.5
KSP-AVC Plugin - 1.1.6.2
ModularFlightIntegrator - 1.2.4
NASA_CountDown - 1.3.2
Docking Port Alignment Indicator - 6.7
PlanetShine - 0.2.5.2
Portrait Stats - 1.0.15
RCS Build Aid - 0.9.1.2
ReentryParticleEffect - 1.2.0.1
OptionalAtmosphere - 1.4.5.1 (Pre-1.4.9)
Ship Effects Continued - 1.0.8.1
SmartActuation - 1.1.0.2
TakeCommandContinued - 1.4.9
TooManyOrbits - 1.1.1
Trajectories - 1.7
Kerbal Alarm Clock - 3.8.5
VesselMover - 1.5.1.4
Rover Wheel Sounds - 2.3
(Extrasolar)

**Comment by GregroxMun** [comment]
It looks fine to me, aside from the wrong color. Any stars will need to have their intensitycurve and scaledintensitycurve figured out to make them not too bright from a distance, and have their sunlightcolor changed to the proper color as well.

What exactly is the bug? Logs? Configs? More info needed.

**Comment by SamBelanger** [comment]
I know one thing is a graphical bug

**Comment by GregroxMun** [comment]
that doesn't help at all. Describe, in detail, what you expect to happen and what is different from the way it actually happened.

**Comment by Sigma88** [comment]
this is a new kopernicus feature and not a bug, you will need to wait for whoever is developing the planet pack you are using to add proper IntensityCurves to their planet pack.

this same point was addressed on the forums, you can find the links [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&do=findComment&comment=3154290) and [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&do=findComment&comment=3154480)

**Comment by Sigma88** [comment]
if you have other bugs you would like to report feel free to open a new issue,

but you will be asked to follow the guidelines described [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409)

**expecially the part about using the least amount of mods necessary**

**Comment by SamBelanger** [comment]
Opps
I made a mistake

**Comment by SamBelanger** [comment]
I promise you the next time I pay attention

**Comment by Sigma88** [comment]
don't worry, it's a brand new features so we expect it will take some time before every developer gets the hang of it

**Comment by SamBelanger** [comment]
Thanks a lot for your help

**Comment by SamBelanger** [comment]
But I find it very interesting for binary stars systems
