### ISSUE TITLE
Lag with large planet editions

### ISSUE THREAD

**Issue by Dannez** [Kopernicus/Kopernicus#208]
Using just vanilla KSP, Modular Flight Integrator, Kopernicus and a large planet addon pack such as Kerbal Galaxy or Total Rebuild, I get horrible FPS' on planets, even with smaller builds. I am running on a very low end PC (4GB ram, dual core 2.1Ghz processor), but its still very laggy. Any help?

**Comment by Sigma88** [comment]
either it's the planet pack that is done sub-optimally and so it's draining too much resources from your system, or your system is not up to the task.

either way there's little to nothing you can do to fix this, I'm sorry

**Comment by Sigma88** [comment]
if you don't have more questions on the topic I think we can close this issue
