### ISSUE TITLE
Kopernicus don't load on KSP 1.3 on Mac OS X

### ISSUE THREAD

**Issue by kayari75** [Kopernicus/Kopernicus#213]
Hi,

When I start a new game, try to load a saved one or try to access to settings menu, KSP get stuck on a black screen with the "loading..." logo and the background music.

I'm using the KSP version 1.3.0.1804 OSXPlayer from Steam.

I try to remove the other mods but Kopernicus still don't work.

Here my log file 
[Kopernicus.log.zip](https://github.com/Kopernicus/Kopernicus/files/1272168/Kopernicus.log.zip)

Any advice ?

Thanks.

**Comment by Sigma88** [comment]
we will need some more information to understand what's going wrong in your install

you can find the full list of what we need [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-121-kopernicus-release-1-november-3/&page=27#comment-2793409)

**Comment by Sigma88** [comment]
did you manage to solve your issue?
