### ISSUE TITLE
Solar Panel Targetting

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#214]
to test if there is an issue in solar panels targetting I did this:

1- add [this](https://pastebin.com/qNwG1Phq) custom config to get a second star
2- I built a simple craft (command module + GigantorXXL)
3- put the craft in orbit around kerbin so that the sun and the star are opposite to each other
4- quicksave/quickload to avoid hyperedit issues
5- open the solar panels while facing the sun

results:
once opened the solar panels point at the sun, show full exposure (1.0) and generate the correct amount of Ec/s (~25)

if I turn the craft so that the solar panels are facing the star, they switch from targetting the sun to target the new star showing full exposure (1.0) but no Ec/s is produced (because the star has a low luminosity

[EDITED OUT, SEE COMMENT BELOW](https://github.com/Kopernicus/Kopernicus/issues/214#issuecomment-326815731)
<strike>if I then turn the craft back to face the sun, the solar panels still try to focus on the dimmer star, showing lower exposures since I've put the craft in a position that does not allow full exposure for that star, and still showing 0 Ec/s produced even if they are partially illuminated by the sun</strike>

I guess there is some kind of error that occurs at some point during the calculation that prevents the solar panels to face the sun

[Logs](https://www.dropbox.com/s/8qt89brd2qbgx29/Logs.Kopernicus.Solar.Panels.zip?dl=1)

I will now try to test this with the sun turned off and two custom stars to see if the behaviour is the same

**Comment by Sigma88** [comment]
tagging people who might be interested
@StollD @galileo88 @poodmound

**Comment by Poodmund** [comment]
Test environment not as controlled but still relevant. Using KSP 1.3.0, Kopernicus 1.3.0-6, MFI 1.2.4, MM 2.8.1 and latest GPP dev build.

New save, launched directly up into orbit. On panel deployment half the panels tracked Grannus as exposure was 1.0 and the other half tracked Ciro.

http://imgur.com/a/zkMxV

**Comment by Sigma88** [comment]
I did some more tests and it turns out that, if you rotate the craft so that the solar panels face the brightest star, then they will start tracking that one

So I guess the issue is that the code only accounts for the current orientation of the solar panels, and not the whole sky

**Comment by Sigma88** [comment]
@StollD  I had some time to think and I think Kopernicus should automatically focus on the best star regardless of AOA

so, even if a star is behind the solar panels, the solar panels should still try to follow that one, instead of facing the best option in front of them

**Comment by Sigma88** [comment]
this is because in 99% of the cases you will have a close star and one or more distant stars, whenever you turn away from the closest star you will risk getting "stuck" on one of the far away stars that will provide infinitesimal amounts of Ec/s

the only issue of this would be if there are two stars that are similar in Ec/s production, but the one with highest flux is in a position that doesn't allow for 100% AOA

in that case you might want the solar panels to lock on the star with the lower flux if they can maximize AOA

this situation is much more unlikely than the other, so until we get the manual tracking to work I'd say that this change would help lessen the amount of bugreports for solar panels

**Comment by Poodmund** [comment]
I agree with Sigma's sentiments above entirely. In my reference case, the secondary star was/is pretty much never the better star to orient the panels to as it gives almost nil EC even when they have 1.00 exposure to that star.

If a check is already made to list available light sources and decide on which can provide most EC in its front 180 degrees field of view, is there anything stopping Kopernicus from determining the same from a 360 degree FOV?

**Comment by Poodmund** [comment]
Just tested the functionality on the new Manual Tracking and it seems I get runaway exposure in the values of thousands that can suddenly ramp up quickly then randomly start to drop back to the correct level. This can happen when coming out of time warp or just by simply spinning the craft around changing the angle of incidence between the panels and the tracked star.

This was occurring on an install of KSP 1.3, Kopernicus latest build, MFI 1.2.4, MM 2.8.1 and a barebones version of GPP.

Logs: https://www.dropbox.com/s/dbciiat645yv5cp/Kopernicus%20Solar%20Panel%20Logs.zip?dl=0

Screenshots: https://i.imgur.com/tmiOlAI.png https://i.imgur.com/eQTh82G.png

**Comment by Laurentyb** [comment]
Im also currently experiencing this issue, with only GPP and Kopernicus, planetshine, scatterer. Panels face the wrong way, or face the right way but dont have any energy flow even with exposure at .99

Seems totally random for most craft but my stations have now become unusable due to being unable to charge.

**Comment by Sigma88** [comment]
I tried the new features out of curiosity and I have a couple of suggestions:

1- make the button for "use relative exposure" stay down when the feature is enabled and up when it is disabled, or alternatively change the text to "use relative exposure" / "use absolute exposure"

2- the auto tracking seems a bit weird, in GN while in orbit around kerbin the star chosen is K-stor Cb even if the Sun is in clear view [screenshot](https://user-images.githubusercontent.com/12640834/30782299-a66937c2-a12f-11e7-8678-fa857ebe4acb.png)

[Logs.SolarPanels.zip](https://github.com/Kopernicus/Kopernicus/files/1327271/Logs.SolarPanels.zip)

**Comment by StollD** [comment]
1. should be fixed
2. can you please try it again? issue 1. might have caused this.

**Comment by Sigma88** [comment]
still targetting kstorcb

**Comment by Sigma88** [comment]
logs?

**Comment by Sigma88** [comment]
honestly, I think we can release kopernicus as it is now, and try to figure out what's going on later

the manual selection of targets is just enough


maybe we could add a button to "set all solar panels to the same target" to make it more convenient for big stations with a lot of panels

**Comment by Sigma88** [comment]
closing this

solved in v1.3.0-8
