### ISSUE TITLE
Undocumented config node 'Experiment' in terrain scatter configuration

### ISSUE THREAD

**Issue by TheWhiteGuardian** [Kopernicus/Kopernicus#215]
There seems to be a lack of documentation on how to add science to terrain scatters. It is clear that it involves the 'Science' boolean, and that the 'Experiment {}' config node has something to do with creating the 'actual' experiment, but there is no information on what the 'Experiment {}' node actually does, let alone how to use it, or how and where to set up the definitions for a specific scatter.

**Comment by StollD** [comment]
```
<Thomas> grumble
<Sigma88> what? :)
<Thomas> Sigma88: The syntax in the Experiment node is the same as ModuleExperiment (or so) in part.cfg
<Sigma88> ok thanks
<Thomas> Well, I returned 5 seconds after TWG quit
```

**Comment by Sigma88** [comment]
for completion's sake, the name of the MODULE is

ModuleScienceExperiment 

you can find it in PARTs like the goo experiment tube thingy

**Comment by TheWhiteGuardian** [comment]
So, to clarify: treat the Experiment node like a science module from a part? Ergo, one can just crosscopy from a 'scientific part' and edit the values, then set up experiment definitions with:
@EXPERIMENT_DEFINITION[*]:HAS[#id[X]]
Where X is the string value assigned to 'experimentID'?

**Comment by StollD** [comment]
Yes

**Comment by TheWhiteGuardian** [comment]
Alright. I'll try it, then post the results here.

**Comment by Sigma88** [comment]
except the EXPERIMENT_DEFINITION you are looking for doesn't exist so you need to create a new one

**Comment by TheWhiteGuardian** [comment]
Gotcha. I've set up the Experiment{} node, and the EXPERIMENT_DEFINITION. Testing it now.

**Comment by Sigma88** [comment]
let us know if you encounter problems with this feature!
