### ISSUE TITLE
[Bug]after install Kopernicus and some mods, Solarpannel not working

### ISSUE THREAD

**Issue by indoorsNB** [Kopernicus/Kopernicus#216]
The new release of Kopernicus let solar panel only have 0.0001 output, I think it is because of another sun or something. ( I install Kerbal Exoplanets)

**Comment by Sigma88** [comment]
this is a know issue that is being fixed right now in the development version

as a temporary solution, you need to try and rotate your ship until the solar panels are facing the closest star, then they should automatically lock onto that one

**Comment by Sigma88** [comment]
closing this since it's a duplicate of #214
