### ISSUE TITLE
Not installing or running or how do I use it

### ISSUE THREAD

**Issue by cclark7785** [Kopernicus/Kopernicus#224]
I copy the game data contents and put them into the game data folder in KSP version 1.3.0.1804 and I can see no changes to the game or if the mod is working. If it is working I have no Idea how to use the planet editor

**Comment by Sigma88** [comment]
this is not intended as a "easy to use editor"

it's a tool for modders who want to develop planet packs, if you are interested in getting started there are different guides on the forums, and if you have some specific questions you can always ask here or on the forum thread.

**Comment by cclark7785** [comment]
Sigma

Yah I found a how to video. Seems very involved but great. If I have any
questions I'll let you know.

Best
Carl
