### ISSUE TITLE
Issues with sun after kopernicus installation

### ISSUE THREAD

**Issue by annoluce** [Kopernicus/Kopernicus#228]
Hi, after installing kopernicus (v. 1.3.0-6) on my 1.3 KSP, I get sun texture completely gone. Please see this image:

https://imgur.com/a/50UHi

Please help. I'd like to installa kopernicus + SVT

**Comment by Sigma88** [comment]
hi, to be able to understand what's going on we will need some files

you can find everything explained in [this guide](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-130-122-kopernicus-release-6-aug-25/&page=27#comment-2793409)

**Comment by Sigma88** [comment]
[turns out this is not a kopernicus issue](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-130-122-kopernicus-release-6-aug-25/&do=findComment&comment=3174676)
