### ISSUE TITLE
biome changes are not applied unless biomemap is parsed

### ISSUE THREAD

**Issue by gordonfpanam** [Kopernicus/Kopernicus#236]
Biome names for non-stock worlds were not appearing in KerbNet's biome views as of 1.3.0-6. Is this, along with localization, supported in 1.3.0-7 now, and are there example configurations to look at?

**Comment by StollD** [comment]
This has been supported as of 1.3.0-5

**Comment by gordonfpanam** [comment]
Then I'm missing something in this config. Here's a re-homed KSC on Duna:

```
Body
{
	name = Kerbin
	cbNameLater = Duna
	cacheFile = AlienSpacePrograms/0Miscellany/Cache/Dunakerbin.bin
	Template
	{
		name = Kerbin
		removePQSMods = PQSLandControl,QuadEnhanceCoast,VertexHeightMap,VertexHeightNoiseVertHeightCurve2,VertexRidgedAltitudeCurve,VertexSimplexHeightAbsolute
		removeOcean = True
	}
	Debug
	{
		update = true
	}
	Properties
	{
		displayName = Duna
		displayname = Duna
		Biomes
		{
			Biome
			{
				name = MidlandSea
				displayname = Midland Sea
				displayName = Midland Sea
				value = 0
				color = 1,0.568627477,0.00784313772,1
			}
		}
	}
}
```

And here's a science report and KerbNet image:
![screenshot2](https://user-images.githubusercontent.com/25485283/30837137-66153500-a228-11e7-867b-c899a36ed09a.png)

The more complete example is [here](https://github.com/gordonfpanam/Alien-Space-Programs/blob/master/GameData/AlienSpacePrograms/DunaSpaceProgram/DunaSpaceProgram.cfg).

What am I missing to make biome names display correctly in KerbNet? And while I'm at it, I'm also missing something with gender because the crew report reads, "from MidlandSea of a Duna," instead of, "from Duna's MidlandSea." 

Maybe if Kittopia-tech was updated for KSP 1.3.0 we could get fresh dumps and working examples.

**Comment by Sigma88** [comment]
Are you sure kerbnet can display the displayname ?

**Comment by gordonfpanam** [comment]
When I go to an unmodified stock world with Kopernicus running, such as Ike in this configuration, biome names show up in KerbNet.

**Comment by Sigma88** [comment]
no idea, as far as I can tell the name is set correctly

**Comment by Sigma88** [comment]
the issue here is that the changes to the biomes are only applied if the biomeMap field is parsed

https://github.com/Kopernicus/Kopernicus/blob/79a2684303475ec924e3802ac9d3c969260ffab2/src/Kopernicus/Configuration/PropertiesLoader.cs#L223

(I suppose)

you didn't post your configs so that's my best guess

**Comment by Sigma88** [comment]
smh

apparently ``displayname`` is set from ``localizationTag``

I'll change that and submit a PR later

**Comment by gordonfpanam** [comment]
> the issue here is that the changes to the biomes are only applied if the biomeMap field is parsed

I just posted a short example. The full example is in the link that followed, and [here's another link](https://github.com/gordonfpanam/Alien-Space-Programs/blob/master/GameData/AlienSpacePrograms/DunaSpaceProgram/DunaSpaceProgram.cfg) to it.

I'll take a look at a test build if you'd like, after six hours from now when I'm off work.

**Comment by Sigma88** [comment]
this issue has been solved, it will be included in the next release
