### ISSUE TITLE
Infinite loop on loading of a save

### ISSUE THREAD

**Issue by roryyamm** [Kopernicus/Kopernicus#241]
This is a strange one. Running these mods:
![screenshot from 2017-10-04 18-19-45](https://user-images.githubusercontent.com/24758288/31202844-58c7fafc-a932-11e7-8e6b-3e0eb8e0442e.png)

(I remember Tantares, GPP, Bluedog Design Bureau, Hyperedit, KER, KJR, KIS, RealPlume, and TweakScale), I get a softlock. To get rid of it, I seemingly have to delete another mod. But after it loads correctly one time, the second time it loads up, I get _another_ softlock. 
[Player.log](https://github.com/Kopernicus/Kopernicus/files/1357525/Player.log)
I include this because it shows the infinite loop that Kopernicus seems to bury itself in:
````
[Kopernicus] No new objects this time. (Probablility is 15%)
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[Kopernicus] No new objects this time. (Probablility is 15%)
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[Kopernicus] No new objects this time. (Probablility is 15%)
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
````
However, my KSP.log shows a different culprit:
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/1357559/KSP.log)
It talks about BDB's Mercury Escape Tower last.
I'm putting this here because I've never had such a softlock before, and something as benign as a parts mod shouldn't do that.

**Comment by Sigma88** [comment]
``[Kopernicus] No new objects this time. (Probablility is 15%)``

is just a message regarding asteroid spawning that occurs every X ingame seconds (depends on what the planet packs set)
if they set a pretty high spawnrate it's plausible that the log would be filled by these messages


your issue is more likely linked to the nullrefs from HyperEdit and/or BDB
(not necessarily caused by them)

**Comment by roryyamm** [comment]
I repeated this with only the GPP, Kopernicus, ModularFlightIntegrator and Squad folders inside GameData. Not only does the soft-lock occur, it occurs when I start a _new_ save, as well.

**Comment by Sigma88** [comment]
which versions of Kopernicus, GPP and GPP_Textures did you use?

**Comment by roryyamm** [comment]
latest ones.

**Comment by Sigma88** [comment]
I have already run latest GPP multiple times and never had any issues

maybe it's a linux issue (in which case I can't help you)

**Comment by Sigma88** [comment]
> I repeated this with only the GPP, Kopernicus, ModularFlightIntegrator and Squad folders inside GameData. 

wait, did you have ModuleManager as well?

**Comment by roryyamm** [comment]
yep. even have the latest version I know, and _only_ the latest version I know.

**Comment by Sigma88** [comment]
can you share the logs from that game?

the previous ones are basically useless

**Comment by roryyamm** [comment]
well, now it works somehow. Plus, since my system has a temperamental log-writing habit, I don't have any logs newer.

**Comment by Sigma88** [comment]
oh well,

no harm, no foul :D

**Comment by roryyamm** [comment]
Thanks for the lightning response, even if you didn't actually have to do anything.

For those who come across this bug: Please attempt to verifiy your cache first. Then, delete all your mods, one by one, except for Kopernicus and any planet packs. If that doesn't work, remove some more planet packs. If _that_ doesn't work. file a bug.
