### ISSUE TITLE
IntensityCurve not working?

### ISSUE THREAD

**Issue by OhioBob** [Kopernicus/Kopernicus#243]
I don't think IntensityCurve is working as intended, or at least not as I understand it.  I recently tried an experiment in which I used different values for IntensityCurve and ScaledIntensityCurve, in the hope that I could create different lighting conditions in map/tracking station mode versus flight mode.  What I found is that the lighting in all modes is currently being controlled by ScaledIntensityCurve.  From what I could determine, IntensityCurve currently doesn't do anything.

**Comment by Sigma88** [comment]
I can confirm this issue but I can't really add anything to the discussion other than, this is not working :|

**Comment by StollD** [comment]
So this is funny.

KSP has never used two intensities. It has two seperate lights, but the intensity of the scaled space light is assigned to the local space light every frame. Back when I wrote Kopernicus star code, I copied the behaviour from KSP's original code, but I didn't notice this. That means, the local space intensity from the config, even when it still was a single number, got never used. Oh well.

Anyway, I fixed this, and the IVAIntensityCurve with https://github.com/Kopernicus/Kopernicus/commit/bdfc343b2c460780624a6421ed1612d51b572962

**Comment by Sigma88** [comment]
I have also noticed that the IVA color doesn't seem to affect the IVA of vessels

both the small preview in the lower right and the IVA view (default hotkey = [C]) always have white light

**Comment by OhioBob** [comment]
Thanks for the response.  So with this fix you've made, will IntensityCurve actually work now?  Also, what are the distance units in IntensityCurve and IVAIntensityCurve?  I know that ScaledIntensityCurve uses km/6000, but I've heard IntensityCurve might be just kilometers, and I don't know anything about IVAIntensityCurve.  Can you verify the correct units?

**Comment by StollD** [comment]
It will work and use kilometers

**Comment by OhioBob** [comment]
Thanks.  Are the IVA units kilometers also?

**Comment by StollD** [comment]
Yes

**Comment by OhioBob** [comment]
Oops, I just realized I made a mistake.  ScaledIntensityCurve uses meters/6000, or kilometers/6.  I think IntensityCurve and IVAIntensityCurve are suppose to use meters, not kilometers.  Is that right?
