### ISSUE TITLE
Not really an issue: detail presets

### ISSUE THREAD

**Issue by Galileo88** [Kopernicus/Kopernicus#248]
If Kopernicus could implement a way for planet modders to define detail presets in the settings cfg, that would be awesome. Basically to add something like this: https://www.dropbox.com/s/965m75n6r8hv89g/AdvancedSettings_GPP.zip?dl=1

**Comment by Poodmund** [comment]
This being the PQS mesh subdivision levels that apply to each body. Currently we have to use whatever preset the template is configured to use as per the player's settings file.
