### ISSUE TITLE
Kopernicus crashes the game on opening

### ISSUE THREAD

**Issue by Alaygrounds** [Kopernicus/Kopernicus#252]
Whenever I try to use kopernicus now, it loads up the game, but once it's done loading, it just crashes. everytime. the game, not the ships.

**Comment by DeltaDizzy** [comment]
https://images-ext-1.discordapp.net/external/sp-kWvUu-biYTvqUfRY62R1sDswQ5bm79oBhyma0lK0/https/tmsp.io/memes/ksp/logs

**Comment by Sigma88** [comment]
@Alaygrounds go [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409) and follow the instructions

**Comment by Alaygrounds** [comment]
Got it.

**Comment by Sigma88** [comment]
?
