### ISSUE TITLE
Planet packs fail to work when current directory is not KSP installation base

### ISSUE THREAD

**Issue by max630** [Kopernicus/Kopernicus#253]
Hi

I had a complain that the game fails to load when there is any planet pack. It was just hanging at the end of initialization screen.

In losg there were many different exceptions, but the first error was:

```
[LOG 20:25:56.933] [Kopernicus]: texture does not exist! /home/***/GameData/Extrasolar/ValentineSystem/Fust/PluginData/height.dds
[LOG 20:25:56.933] [OD] ERROR: Failed to load map height (G) for Fust at path Extrasolar/ValentineSystem/Fust/PluginData/height.dds
```

I was rather surprised to see such error, because the game installed to another directory. I have made a symlink (it is Linux) from real GameData to the home directory. The KSP succeeded to get to the menu, but there was a popup that the pack failed to load. In file `Logs/Kopernicus/Fust.Body.log` I have found an exception which I did not save but it was about out of bound argument in string.Replace(), called from `Kopernikus.OnDemand.OnDemandStorage.LoadTexture()`.

I have noticed that in beginning of the function, the path is initialized from `Directory.GetCurrentDirectory()`. So I tried to thange start directory for KSP to its installation path and the the plugin succeeded to run.

Could it be that instead of `Directory.GetCurrentDirectory()` should be `KSPUtil.ApplicationRootPath` or something? I don't have proper development environment to do debugging or patching, so cannot submit a fix myself.

**Comment by StollD** [comment]
This was solved some versions ago, just forgot to close the issue.
