### ISSUE TITLE
Kopernicus crash

### ISSUE THREAD

**Issue by ContraMuffin** [Kopernicus/Kopernicus#254]
Seems like there's a null reference somewhere.
I'm not running any custom planet mods. Current mods installed are: Better Time Warp Continued, EVE, Kopernicus, Precise Node, Scatterer, SVE, Module Manager, and SVT.
The warning upon reopening the game reads:

> Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your savegame is NOT recommended, because the missing planets could corrupt it and delete your progress.
Please contact the planet pack author or the Kopernicus team about the issue and send them a valid bugreport, including your KSP.log, your ModuleManager.ConfigCache file and the folder Logs/Kopernicus/ from your KSP root directory

I have included those files in the zip file attached. Meanwhile I'll make a backup copy of .../saves/default/ and then run the save to see what would happen 👍 

EDIT: oh right. This might be helpful information. I confirmed that KSP was working before with these mods: Better Time Warp Continued, EVE, Kopernicus, Precise Node, Scatterer, SVE, and Module Manager. Between that time and the game crash, I have done the following things: installed SVT, replaced SVE textures to high res textures, and enabled the Scatterer option for loading an atmosphere above clouds in Eve.
It also seems like loading the save file will simply soft lock the game in the loading screen. So that's something.

[KSP-Crash Logs.zip](https://github.com/Kopernicus/Kopernicus/files/1574022/KSP-Crash.Logs.zip)

**Comment by DeltaDizzy** [comment]
Did you try running the game with just Kopernicus and its dependencies?

**Comment by ContraMuffin** [comment]
Kopernicus, by itself, seems to work just fine (that is to say, I don't notice anything that isn't stock). Also, something possibly worthy of note is that I removed Module Manager 2.8.1 that came with Kopernicus in favor of Module Manager 3.0.1

**Comment by DeltaDizzy** [comment]
Yeah, MM 3 is breaking a lot of mods. I don't know if Kopernicus is affected or not, though. The only way to find out the cause is to look through the logs.(the fact you provided yours from the start makes this report far better than most.)

**Comment by Galileo88** [comment]
MM doesn’t affect Kopernicus at all, only the configs written for it by planet pack devs. If they don’t have they correct passes for the new MM then it will throw errors. To be honest, there is no reason to upgrade MM from 2.8.1. My personal feelings about the 3.0.x update is that it was done for no reason but to cause issues. There is no real benefit. I would stay with 2.8.1. 

As for your Kopernicus error message, that may be caused by SVT. I have yet to look at it with the latest MM and don’t know if I will any time soon. With that said, I would roll your MM back to 2.8.1.

**Comment by ContraMuffin** [comment]
Galileo88, thanks for the specification. I am new to KSP and especially new to modding. I will try rolling back MM to 2.8.1 and see what happens.

**Comment by Sigma88** [comment]
@contramuffin if you want anything more than speculations [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-121-kopernicus-release-1-november-3/&page=27#comment-2793409)'s what we need to debug your issue

**Comment by ContraMuffin** [comment]
Sigma88, I can't seem to replicate the issue with only Kopernicus. I also can't replicate the issue using MM 2.8.1. I can only conclude that it most likely has something to do with MM 3.0.1 messing with SVT. So, problem solved, I guess.

**Comment by Sigma88** [comment]
it seems unlikely that kopernicus would lock your game if you don't have any other mod installed (except for MM and FGI which are dependancies)

but feel free to share your logs, they might tell us what is going wrong in your install

**Comment by ContraMuffin** [comment]
I experimented with various combinations of my mods until I found out a likely cause to the crashes. It appears to be stemming from the interaction between SVT and Better Time Warp. Alone, they don't cause problems, but together, they crash or softlock the game. And the crash/softlock always happens during loading screens. Not sure if this is your playing field, so I'll let you decide if you wanna see the logs, but I'll try to get in touch with the Better Time Warp and/or CVT devs to see if there's a compatibility problem.

**Comment by Sigma88** [comment]
regardless of where you plan to post your logs, please ping me when you do so.

I'd like to be informed of what kind of bugs/solutions are linked to your issue so I know what to reply to people having this issue in the future

**Comment by ContraMuffin** [comment]
I suspect it's mostly a problem with Better Time Warp, so I went ahead and made a post in the Github issues section of that. I haven't gotten a response yet, but I'll just leave a link here for posterity.

https://github.com/linuxgurugamer/BetterTimeWarpContinued/issues/15

**Comment by StollD** [comment]
A bit late to the party, but this isn't an issue with BetterTimeWarp.

@Sigma88 @ContraMuffin actually did an exceptionally well bugreport by already including everything thats needed in the op when he created the issue. So it was pretty simple to find the bug in the loading process. (it's in Laythes body log)

> [LOG 18:47:37]: Exception Was Recorded: Out of memory

I am not sure how KSP manages to load past that, but it definitly kills Kopernicus loader.

@ContraMuffin You should probably try to start KSP through KSP_x64.exe which will allow it to use more than 4GB of RAM

**Comment by Sigma88** [comment]
ah I must have missed that, good catch

**Comment by ContraMuffin** [comment]
Confirmed, running 64-bit KSP does indeed solve the issue. Though it still seems to be a strange limitation.
