### ISSUE TITLE
Kopernicus fails to load

### ISSUE THREAD

**Issue by ShaunRodrigues** [Kopernicus/Kopernicus#255]
Kopernicus does not seem to work. After loading has completed it shows that Kopernicus was not able to load due to an exception in the loading process.
Here are the output and Kopernicus logs.

[output_log.zip](https://github.com/Kopernicus/Kopernicus/files/1582842/output_log.zip)
[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/1582845/Kopernicus.zip)

**Comment by StollD** [comment]
Could you please upload a screenshot from the contents of the Kopernicus folder in GameData?

**Comment by ShaunRodrigues** [comment]
[Screenshots.zip](https://github.com/Kopernicus/Kopernicus/files/1670107/Screenshots.zip)

Note: the screenshots are in a .bmp format.

**Comment by StollD** [comment]
Inside the Kopernicus zip there is a GameData folder with multiple folders. While you created a new folder in gamedata and dragged everything from the zip into it (right-click + extract here probably), you need to open the zip file, and merge your GameData with the one in the zip.

**Comment by ShaunRodrigues** [comment]
Thanks a lot! :) 
The error was solved.
