### ISSUE TITLE
Idea-Dump

### ISSUE THREAD

**Issue by StollD** [Kopernicus/Kopernicus#256]
Just a place for me to dump things that I want to do on the chaos branch, so I don't forget them.

- [x] Implement the generic noise parser from KopernicusExpansion in VertexPlanet (currently forced to use Ridged noise)
- [x] Rework the system that adds colliders and experiments to terrain scatter so it becomes modular and extendable
- [ ] Implement the Shuriken Particle System
- [x] Optimize the MapSO OnDemand loading by managing memory myself (so heightmaps only need to store one channel and not the whole texture)

**Comment by DeltaDizzy** [comment]
> Rework the system that adds colliders and experiments to terrain scatter so it becomes modular and extendable

**_yes_**

**Comment by Sigma88** [comment]
question:

is there any difference between using png or dds for OnDemand textures?

I noticed that some planet packs have some milliseconds of freezing every time a planet comes into view and I was wondering if pngs could be the cause of that

**Comment by StollD** [comment]
PNG's need to be decompressed to DDS before they are sent to the GPU, since thats what the GPU uses. So pngs are most likely the cause of that.

**Comment by Sigma88** [comment]
@GregroxMun I've seen that happen with some of your mods

Let me know if you need some conversions
