### ISSUE TITLE
Game stuck in loading screen after installing a planet pack

### ISSUE THREAD

**Issue by GenericDM** [Kopernicus/Kopernicus#257]
After installing the 'Interstellar Adventure Redux' pack for kopernicus, the game will go through the startup loading screen just fine, but instead of reaching the main menu it just shows the planets spinning loading screen. I've looked thru other issues here so I'll send the KSP.log and logs/ folder here too.
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/1610288/KSP.log)
[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/1610289/Logs.zip)

**Comment by Mrcarrot1** [comment]
Go bother ProtoJeb about it, it's probably caused by his mod
also, 
https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first

**Comment by GenericDM** [comment]
Even though CKAN said it would be compatible it looks like it was outdated. I'm just going to use another planet pack for now. Thanks for that forum thread also, it'll probably help me out in the future.
