### ISSUE TITLE
Light from stars is not working.

### ISSUE THREAD

**Issue by TomFancy** [Kopernicus/Kopernicus#258]
I don't know what causes it,any object in atmosphere is illuminated, but outside is completely black. It happened after installation of Kopernicus,GN, and OPM. If any log is needed, just write, i will send it

**Comment by Sigma88** [comment]
Going with memory, I don't think I updated GN for the latest Kopernicus.

You should try installing an earlier version of kopernicus.

Also, GN only supports OPM_Galileo, so make sure you are using that one

**Comment by TomFancy** [comment]
Thanks for help, I will test it.

**Comment by Sigma88** [comment]
this has been solved in the latest GN release
