### ISSUE TITLE
Extreme scary bug that tells me it might corrupt my data

### ISSUE THREAD

**Issue by KoolKidd123** [Kopernicus/Kopernicus#266]
So when i downloaded the Outer Planets Mod on KSP it needed (Kopernicus) So i downloaded the 1.3.1. version and then when i opened KSP it told me Warning *kopernicus can corrupt your data tell this to the developers* so i came to the bug page and i hope the devs will fix it please tell this to another website if this website is out of use :(

**Comment by Sigma88** [comment]
This is not helpful

If you want to provide a bug report that we can use to solve your issue follow the instructions [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-131-kopernicus-release-3-nov-30/&page=27#comment-2793409)
