### ISSUE TITLE
Kopernicus loading error

### ISSUE THREAD

**Issue by Hieywiey** [Kopernicus/Kopernicus#267]
Full error:
"Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your save game is NOT recommended, because the missing planets could corrupt it and delete your progress."
https://goo.gl/afaPm6

**Comment by Sigma88** [comment]
I haven't looked at your report yet but if you are using kopernicus v1.3.1-4 or -5 those version broke a lot of stuff so you should go back to kopernicus 1.3.1-3 and update only when all mods you are using that require kopernicus have been released for 1.3.1-5

**Comment by Hieywiey** [comment]
I still get the error even when I change Kopernicus versions, although I do not have the error when I remove all other mods (except those necessary to run OPM). Any idea what it is?

**Comment by Hieywiey** [comment]
I still get the same error even when I switch

**Comment by Sigma88** [comment]
to take a look at your issue we will need something more than that

follow the instructions [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409)

**Comment by Hieywiey** [comment]
[Bug Report Thingy.zip](https://github.com/Kopernicus/Kopernicus/files/1722157/Bug.Report.Thingy.zip)

**Comment by SpaceTater** [comment]
The same thing is happening to me.
So you know, i have deleted every mod, and it is still not working. it will get to the main menu, but when you try to load a game, it will just freeze on the loading screen.
