### ISSUE TITLE
update MM

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#270]
we are 3 versions behind 🤦

**Comment by StollD** [comment]
The update is automated now, releasing a Kopernicus version automatically updates MM to the latest version available on sarbians jenkins server.

**Comment by Sigma88** [comment]
1.3.1-6 still has MM 3.0.1 no?

**Comment by StollD** [comment]
> now

I literally updated the jenkins configs 2 minutes before posting that. :P
