### ISSUE TITLE
Windows messed up

### ISSUE THREAD

**Issue by khilde** [Kopernicus/Kopernicus#271]
For some reason when I update from 1.3.1-3 to 1.3.1-6 it messes up a bunch of my custom windows created by mechjeb and kerbal engineer. Half of them become invisible and my landing guidance window border exists but the inside text of the window is invisible. Going back to 1.3.1-3 of kopernicus fixes the issue. So i think there is something in 1.3.1-6 messing up the windows.

**Comment by StollD** [comment]
We need your KSP.log

**Comment by khilde** [comment]
Ok so when I initially had the problem I upgraded OPM and Kopernicus through CKAN. When I manually reverted to older versions the window problem went away. When I reinstalled the newest versions (manually)  I did not reproduce the problem. So not sure what the heck happened.

**Comment by khilde** [comment]
Ok I have had the problem pop up again. it makes one of my kerbal enginer redux windows invisible and makes it so I can not select a target location on minmus with mechjeb with auto land. I am not 100% sure its kopernicus (I don't really understand how mods are written, I just use them, I am a programmer though), but when I go back to 1.3.1-3 the problem goes away. 

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/1732383/KSP.log)

I have attached my KSP log

**Comment by khilde** [comment]
From looking at my ksp.log I beleive this issue is caused by the problem reported "the big biome breakage of 1.3.1-6"

**Comment by StollD** [comment]
You are correct. The issue was already fixed and the fix is currently being tested.

If everything goes well, I will release it tomorrow or on Sunday
