### ISSUE TITLE
the big biome breakage of 1.3.1-6

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#272]
continuation of this: https://github.com/thewebbooth/KSP-X-Science/issues/22#issuecomment-366281017

so, this is a complicated issue, the symptom is:

- calling `CBAttributeMapSO.GetAtt(lat,lon)` results in an `IndexOutOfRangeException: Array index is out of range.`
- this happens regardless of `useOnDemand` and `useManualMemoryManagement`

situations in which the issue does NOT appear:

- on a stock game with Kopernicus 1.3.1-6 but no planet packs
- on a stock game with Kopernicus 1.3.1-6 with an additional planet that uses a template, but doesn't change biomemap or biomes
-  on a stock game with Kopernicus 1.3.1-6 with an additional planet that uses a template, and changes the biomemap but not the biomes
-  on a stock game with Kopernicus 1.3.1-6 with an additional planet that uses a template, and changes the biomes but not the biomemap, while calling `CBAttributeMapSO.GetAtt(lat,lon)` on either the new planet or the template planet from the SpaceCenter scene
-  on a stock game with Kopernicus 1.3.1-6 with an additional planet that uses a template, and changes the biomes but not the biomemap, while calling `CBAttributeMapSO.GetAtt(lat,lon)` on the new planet from the Flight scene

to get the bug:

-  on a stock game with Kopernicus 1.3.1-6 add an additional planet that uses a template, and changes both the biomes AND the biomemap, then call `CBAttributeMapSO.GetAtt(lat,lon)` on the template planet while in the flight scene

this will throw the error listed above.

**Comment by Sigma88** [comment]
here is the planet I created for testing:

[GameData.zip](https://github.com/Kopernicus/Kopernicus/files/1732083/GameData.zip)


and the logs:

[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/1732081/Logs.zip)

**Comment by Sigma88** [comment]
here is a dev version of kopernicus that might or might not solve this issue

if anyone would provide feedback on this it would be much apreciated, thanks!

[Kopernicus-release-1.3.1-6-6-gb473f96-2018-02-16.zip](https://github.com/Kopernicus/Kopernicus/files/1732983/Kopernicus-release-1.3.1-6-6-gb473f96-2018-02-16.zip)

**Comment by jtulak** [comment]
I tried the dev version it and it fixed my issue with Minmus, SCANsat and OPM. Thanks. 👍

**Comment by Diesalot** [comment]
Dev version fixed all my biomes on The Mun.

**Comment by theonegalen** [comment]
I will be trying the dev version tomorrow.

**Comment by eberkain** [comment]
This seems to have resolved the issue I reported here.  
https://forum.kerbalspaceprogram.com/index.php?/topic/140580-131-kopernicus-release-6-feb-14/&do=findComment&comment=3296467

**Comment by theonegalen** [comment]
I attempted to play with the development version of Copernicus linked above, and found that I was missing some squares of ocean to the east of the KSC, as well as several mods not working together.

**Comment by Sigma88** [comment]
> I am not certain that these problems are related to the dev version of Copernicus

@theonegalen 

if you go back to the latest release (1.3.1-6) and have no issues, but see the issues with the dev.version then the bug might be related to some changes that occurred in the dev version.

otherwise I'd say this bug should be posted on a different issue.

Let us know so we know how to procede

**Comment by theonegalen** [comment]
@sigma88 
Rolling back to 1.3.1-6 did fix the bug.

**Comment by Sigma88** [comment]
@theonegalen since using a dev version could be messy, I would suggest you wait for a proper release, if the issue persists with the next release open a new github issue and follow [these instructions](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409) to help us working this out

**Comment by Sigma88** [comment]
I'd say this was solved. If anyone is still having issues feel free to re-open this issue
