### ISSUE TITLE
Failed To Load

### ISSUE THREAD

**Issue by axcess** [Kopernicus/Kopernicus#273]
I believe I'm having similar problems as others are with the failed to load notification when starting KSP.  I tried to use older versions (-5, -4 and -3) with no luck.  Same error.

I've added a zip of the logs requested when creating an issue work order.

I did install using CKAN and I selected Spectra to install.  Then, CKAN suggested/required many additional visual mods.  I tried to isolate it as much as possible to only the visual mods, so apologies for having to sift through a dozen mods.  I tried looking over the logs and noticed that there was always one planet never loading.  All, but one and it was always a different planet unable to load.

KSP 1.3.1 (Steam)
[Kopernicus Logs.zip](https://github.com/Kopernicus/Kopernicus/files/1733741/Kopernicus.Logs.zip)

Win10 64 bit, latest update
GTX 1070 (Not OC)
Intel i5-4690K (Not OC)
16 GB RAM

**Comment by axcess** [comment]
> older versions (-5, -4 and -3) with no luck. Same error.

Disregard the -3 version.  I must have loaded the -4 version, because 1.3.1-3 works.  It did not throw an error or fail to load notification.

**Comment by StollD** [comment]
The issue was already fixed in the master branch, I only need to release it.

**Comment by axcess** [comment]
Appreciate it, thank you for what you do!
