### ISSUE TITLE
SVT causing problems for kopernicus

### ISSUE THREAD

**Issue by modybird** [Kopernicus/Kopernicus#274]
Im trying to download kopernicus with SVT but every time i pair the two up it gives me this error https://imgur.com/rUM9b7M or just crashes my game alot.

I tried downloading earlier versions of both mods but it doesn't work

What do i do?

**Comment by Sigma88** [comment]
Have you tried kopernicus 1.3.1-3?

**Comment by lugerun** [comment]
I have the same problem, also with the latest version installed (only when SVT is in the GameData folder -> works again after removing) :
[ERROR.zip](https://github.com/Kopernicus/Kopernicus/files/1756725/ERROR.zip)

Are there other mods that replace planet textures I could try?

**Comment by Galileo88** [comment]
@lugerun SVT has not been updated to the latest Kopernicus. This has been said in the thread a few times now. Until I update it, stay on Kopernicus 1.3.1-3.

**Comment by StollD** [comment]
```
[LOG 21:36:11]: Exception Was Recorded: Out of memory
```
If you run KSP.x86_64, you can use your whole memory, and not just 4 GB.

**Comment by lugerun** [comment]
Thanks for the quick response. I run KSP with steam, but i'll figure it out!

**Comment by lugerun** [comment]
With Kopernicus 1.3.1-3 it was not working either, but after installing Texture Replacer it launched successfully. Even when I then replaced Kopernicus with the latest version it worked (I have not changed or deleted any old Logs/Kopernicus if that matters).

**Comment by Sigma88** [comment]
since there has been no update in more than 1 year I'll close this issue, if you still experience this issue feel free to reopen it
