### ISSUE TITLE
Kopernicus possibly causing issues with mechjeb automated landing on minmus with OPM.

### ISSUE THREAD

**Issue by GhastlyKerbal** [Kopernicus/Kopernicus#276]
https://nofile.io/f/MZAWEOxsSM1/output_log.txt
While in orbit around minmus picking a landing target does not display coordinates and only focuses on minmus. As far as I can tell, minmus is the only planet/moon affected. Disabling OPM/Kopernicus fixes this but its one of my favorite mods and I'd rather not play without it if possible. Below are two screenshots, one showing the mod working without OPM, the other showing that you cant see or select coordinates with OPM installed. https://nofile.io/f/MZAWEOxsSM1/output_log.txt
Without OPM and Kopernicus
![without opm](https://user-images.githubusercontent.com/36802807/36637621-1a7cb084-19ae-11e8-9244-2016d76abd34.jpg)
With OPM and Kopernics
![withopm](https://user-images.githubusercontent.com/36802807/36637625-24abe2c8-19ae-11e8-9692-2e780e228969.jpg)

**Comment by GhastlyKerbal** [comment]
I've noticed you've been messing around with minmus in your updates and I believe one of them may have caused this

**Comment by XaeroDT** [comment]
probably related to #272

**Comment by Sigma88** [comment]
test this with the latest release,

if it has been solved we can close this issue
