### ISSUE TITLE
Ocean bouyancy not occuring in 1.3.1 RSS/ScaledRSS Textures/Kopernicus -5,-6 or -7

### ISSUE THREAD

**Issue by Bornholio** [Kopernicus/Kopernicus#277]
**[Current Answer is "Stay with -3 if you want oceans"]**

Did not test with -4, previously -3 worked.

Other Mods involved, RO/RP0 (development) suite

Currently trying to isolate reason, but have seen a few others with similar issue and arrangement.

**Comment by Sigma88** [comment]
could you check with these setups:

- stock ksp + kopernicus
- stock ksp + kopernicus + SD + rescale! (10x)
- stock ksp + kopernicus + RSS

the first one to fail should give us an indication of what might be the issue

**Comment by Galileo88** [comment]
RSS doesn’t use SD or Rescale. My guess is something with RO/RP0 effecting the parts, causing them to “sink”

**Comment by Galileo88** [comment]
Not sure what he means by “ScaledRSS Textures” though...

**Comment by Bornholio** [comment]
@Sigma88 Will do, 
https://github.com/pap1723/ScaledRSS-Textures is needed for the newest master RSS

**Comment by Galileo88** [comment]
Gotcha, but you still probably don’t need to test with SD or Rescale

**Comment by Galileo88** [comment]
I would remove the RO/RP0 stuff and give it a try. I just ran RSS, without any other mods than what is required for RSS to work, and I didn’t have an issue.

**Comment by Bornholio** [comment]
**Test A**
Test with: Kop-7,  https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.3.1-7
MM 3.0.4
MFI 1.2.4.0

Result: Ocean works fine

**Test B**
Kop-7,  https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.3.1-7
MM 3.0.4
MFI 1.2.4.0
RSS Master https://github.com/KSP-RO/RealSolarSystem
https://github.com/pap1723/ScaledRSS-Textures/releases  1.4(8k) textures

Result: Ocean doesn't appear, ASL indicator goes red and craft falls to ocean floor, blue color when camera is below surface otherwise no water appears.  https://imgur.com/a/1ipXe

**Comment by Bornholio** [comment]
**Test C**
https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.3.1-3
MM 3.0.4
MFI 1.2.4.0
RSS Master https://github.com/KSP-RO/RealSolarSystem
https://github.com/pap1723/ScaledRSS-Textures/releases 1.4(8k) textures

Result: Ocean Works Fine 🥇

**Comment by Galileo88** [comment]
ok so the issue lies with the dev version of RSS which as far as I know isn't being actively worked on at the moment and isn't known to work with the lastest kopernicus. I suggest you use Kopernicus 1.3.1-3 or earlier.

**Comment by Bornholio** [comment]
Any thoughts on what we are doing wrong in it that changed from -3 to later?  @NathanKell and @eggrobin 's updates tested out good earlier.

Linked issue https://github.com/KSP-RO/RealSolarSystem/issues/127

**Comment by Galileo88** [comment]
I don't know what could be wrong. There have been a lot of changes after 1.3.1-3. It could be a number of things. I can take a look at the cfgs when I get some time

**Comment by Sigma88** [comment]
My suggestion would be to remove all rss configs except for those needed for the earth and go from there

**Comment by PhineasFreak** [comment]
What i noticed: using KittopiaTech, i checked the value of **radius** under the **KerbinOcean (PQS)** entry. For some reason it is set as **600000 m**, the radius of Kerbin. Manually setting this to be **6371000 m** allows the ocean to reappear and behave as expected.

**Comment by Bornholio** [comment]
Good find.

**Comment by PhineasFreak** [comment]
No, all bodies are loaded correctly, including their radii parameters. It looks more like if Kopernicus is ignoring the body radius value for the Ocean PQS and, instead, reusing the default (Kerbin) one.

Also, the above do not seem to apply to Titan: while the ocean is physically there upon landing (splash FX & physics) it is invisible. No matter what the radius is, it will always be invisible.

**Comment by Bornholio** [comment]
@PhineasFreak What patch do you need to set this manually?

**Comment by PhineasFreak** [comment]
None, i just played with the values that Kittopia exposes. I am not even sure if the ocean radius is exposed as a config parameter (it shouldn't - everything should be handled internally).

**Comment by PhineasFreak** [comment]
So, fortunately i was wrong. RSS just needed the missing Ocean{} nodes and now everything works perfectly!

**Comment by Sigma88** [comment]
glad you found a solution!
