### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by Scythees** [Kopernicus/Kopernicus#279]
Hi, when Kopernicus is installed i get this error message in the main menu and games can't be loaded or started

error message: Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

[Al other requested files.zip](https://github.com/Kopernicus/Kopernicus/files/1776938/Al.other.requested.files.zip)
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/1776939/KSP.log)

**Comment by DeltaDizzy** [comment]
Do you use any mods that change minmus?

**Comment by Scythees** [comment]
i do not, the galaxy is completely vanilla

[output_log.txt](https://github.com/Kopernicus/Kopernicus/files/1776958/output_log.txt)

**Comment by DeltaDizzy** [comment]
well i saw you have KSS installed

**Comment by Scythees** [comment]
oh, oops, thought it only added planets and stars

**Comment by Scythees** [comment]
sorry

**Comment by DeltaDizzy** [comment]
@Scythees you said your galaxy was completly vanilla, yet you have Kss. I don't know if kss does anything to minmus, so someone else will have to take it from here.

**Comment by Scythees** [comment]
bug report only seems to come up when KSS is installed

**Comment by DeltaDizzy** [comment]
well kss would seem to be the problem then

**Comment by Galileo88** [comment]
KSS is not compatible with the latest Kopernicus, you should be using the one that is linked in the KSS OP. 

If you are already doing this, then the issue is with KSS not Kopernicus, and I would go give them your bug report.

**Comment by Scythees** [comment]
okay, it was indeed the copernicus version mismatch, thank you for pointing this out.

Mod works now

**Comment by Terrabey** [comment]
Hello Kopernicus Team I have the same issue like with this KSS mod but have only Mods installed installed which need Kopernicus like Parallax, ScanSat and MechJeb2. Also when I want play a new Game or change settings the Game just loads for abaout 5 Million years
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/9514409/KSP.log)

**Comment by R-T-B** [comment]
> Hello Kopernicus Team I have the same issue like with this KSS mod but have only Mods installed installed which need Kopernicus like Parallax, ScanSat and MechJeb2. Also when I want play a new Game or change settings the Game just loads for abaout 5 Million years [KSP.log](https://github.com/Kopernicus/Kopernicus/files/9514409/KSP.log)

Hello.  The problem is how you have installed Kopernicus.

It is installed like this, according to the log (path to the dll file):

Kerbal Space Program\GameData\Kopernicus-1.12.1-139\GameData\Kopernicus\Plugins\Kopernicus.dll

It should be like this:

Kerbal Space Program\GameData\Kopernicus\Plugins\Kopernicus.dll

As you can see, you have extracted it wrong somehow.  Please delete the Kopernicus folder-1.12.1-139 folder and reattempt the install.

**Comment by kingisrie-cyber** [comment]
Hey i had the same problem with a mod called kss2 i just had to downgrade the version and it works perfectly fine. Maybe try to downgrade kopernicus or whatever mods your using.!
