### ISSUE TITLE
Terrain tiles disappearing on 1.3.1-7

### ISSUE THREAD

**Issue by gordonfpanam** [Kopernicus/Kopernicus#280]
While I first noticed this loading Galileo's Stock Visual Terrain, an installation with only Kopernicus 1.3.1-7 is doing this as well.

Terrain tiles disappear on Eve and Laythe at high altitudes and close approach. I haven't observed this at Kerbin. Terrain colliders are still present, so I can land on it, and I can observe scatter objects 'floating.'

![screenshot0](https://user-images.githubusercontent.com/25485283/36950636-6c8e27e8-1fbe-11e8-928a-dd53a840d17d.png)

Find attached KSP and Kopernicus logs, one from a stock install, and one from a stock plus Kopernicus 1.3.1-7 including the supplied editions of Modular Flight Integrator and Module Manager. The second set of logs should include the times when I observed the missing terrain tiles.

[Logs-Testing-131-7.zip](https://github.com/Kopernicus/Kopernicus/files/1778956/Logs-Testing-131-7.zip)

Testing environment was KSP_x64 on a Windows 10 1709 machine with 32 GB RAM and NVidia GTX 1080. No command line switches used, so I think it's using the stock Direct3D 9 mode.

**Comment by microstiff** [comment]
I get the exact same problem too. So far only found this 'tile missing problem' on Laythe. I use KSP_x64 with win10. Hope we can get a fix for this.

**Comment by EstrelaGaliza** [comment]
![image](https://user-images.githubusercontent.com/37704589/37857462-809d2f6c-2efb-11e8-88f4-a2367212876f.png)

Same here!

I cannot fix the problem. I tried many clean installs (Kopernicus + RSS + Squad)

**Comment by gordonfpanam** [comment]
This appears to have been resolved in Kopernicus 1.4.2-1. I wonder what the difference was.
