### ISSUE TITLE
Error on load using latest version

### ISSUE THREAD

**Issue by TheChosenEvilOne** [Kopernicus/Kopernicus#282]
I have New Horizons installed 
[failsToLoad.zip](https://github.com/Kopernicus/Kopernicus/files/1868526/failsToLoad.zip)

**Comment by StollD** [comment]
NewHorizons is not compatible with Kopernicus 1.3.1-4 and later versions.

**Comment by TheChosenEvilOne** [comment]
ah, good to know
are there any other mods that work with the new versions?

**Comment by TheChosenEvilOne** [comment]
ah, I found that it was caused by Tidus moon/planet

**Comment by StollD** [comment]
Things like this
```
Noise
{
...
    octaveCount = 4
...
}
```
need to be changed to
```
Noise:RidgedMultifractal
{
....
    octaves = 4
...
}
```

**Comment by TheChosenEvilOne** [comment]
well, yeah it was just that
works now

**Comment by TheChosenEvilOne** [comment]
So, now having all mods stops me from pressing any menu buttons. After removing Kopernicus and New Horizons it works
