### ISSUE TITLE
Kopernicus was not able to load the custom planetary system due to an exception in the loading process.

### ISSUE THREAD

**Issue by Draken84** [Kopernicus/Kopernicus#285]
KSP pops up a error-box with above in it.

it's installed from CKAN, all mods bar outer planetary system removed and it persists, i have, after zipping up the logs, tried without OPM and it still produces the error, it gives a black screen and endless loading when trying to load into the game.

i have tried grapping Kopernicus off the github and overwriting the CKAN version, it produces the same error.

[kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/1933232/kopernicus.zip)

**Comment by Galileo88** [comment]
Post a screenshot of your gamedata folder

**Comment by Draken84** [comment]
it had 52 folders, mostly left-over XML and CFG files, i have deleted everything not related to stock, the DLC and installed mods and now it's working, including the outer planets mod.

thus there's no point in this being open any-more, closing it, thanks for the help!
but it might be worth stuffing that little tidbit in the "How to get support" section for future CKAN newbs like myself. i figured it would clean up after itself, but it obviously doesn't :)
