### ISSUE TITLE
extreme performance drop after 1.4.3 mod's update

### ISSUE THREAD

**Issue by tonimark** [Kopernicus/Kopernicus#287]
so I updated kopernicus with the idea of fixing no solar power issue until I came up with other problem and is that suddenly my game performance dropped from 33fps down to 2-3 fps even and i am in vab and sph  so can someone help me with my performance

**Comment by RealKolago** [comment]
hit Alt-F12 to see if there are errors generated in the log. (red lines)

**Comment by tonimark** [comment]
k let me check

**Comment by tonimark** [comment]
wait about 30 minute so i cn load my game

**Comment by tonimark** [comment]
and nope performance drop and stock launch without any output log and clear console

**Comment by tonimark** [comment]
and i also don't own making history DLC

**Comment by Tutur716** [comment]
Mh weird, I know there is a few perf problems with KSP 1.4.x, you might have to wait the dev because at this point i already can't really help you lol

**Comment by tonimark** [comment]
k meanwhile you report this bug to squad

**Comment by Sigma88** [comment]
@tonimark  squad doesn't give a crap that your mod doesn't work with mods

[here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409) we have a list of files we need to debug issues, if you can provide those files to us, we will be happy to look into your problem

**Comment by Beetlecat** [comment]
1.4.3-2 provided noticeable improvement on my rig.
