### ISSUE TITLE
Today suddenly get warning messege

### ISSUE THREAD

**Issue by ultimatecrackdown** [Kopernicus/Kopernicus#288]
Hi,

I don't know what happens here. Yesterday I've tried 1.4.3 update from Steam, but then I decided to downgrade back to 1.4.2.2110 and played normally. Today I have warning messege from Kopernicus. 
I am sending You everything I've got including GameData and main directory screens.

It is possible that this is the result of my stupidity.

[Eve.Body.log](https://github.com/Kopernicus/Kopernicus/files/1963584/Eve.Body.log)
![gamedata](https://user-images.githubusercontent.com/7334381/39470888-786b44d8-4d40-11e8-850f-d2b43194e205.jpg)
![idkwhathappens](https://user-images.githubusercontent.com/7334381/39470890-78873828-4d40-11e8-84ce-e344b9bf3372.jpg)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/1963585/Kopernicus.log)
[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/1963586/Kopernicus.Runtime.log)

![main_ksp_dir](https://user-images.githubusercontent.com/7334381/39470892-78f49832-4d40-11e8-89bb-4ac352322138.jpg)

[Moho.Body.log](https://github.com/Kopernicus/Kopernicus/files/1963587/Moho.Body.log)
[Sun.Body.log](https://github.com/Kopernicus/Kopernicus/files/1963588/Sun.Body.log)
[bugreport.zip](https://github.com/Kopernicus/Kopernicus/files/1963599/bugreport.zip)

**Comment by ultimatecrackdown** [comment]
![main_ksp_dir](https://user-images.githubusercontent.com/7334381/39471038-4f2e797c-4d41-11e8-8312-0570ae60a747.jpg)

**Comment by ultimatecrackdown** [comment]
[bugreport.zip](https://github.com/Kopernicus/Kopernicus/files/1963598/bugreport.zip)

**Comment by Galileo88** [comment]
It’s an issue with SVE I need to fix. I just haven’t had time :/

**Comment by ultimatecrackdown** [comment]
Thanks for reply, I decided to delete whole GameData and paste backup from 1.4.1. Now it works like yesterday.

Good luck
