### ISSUE TITLE
Move (or duplicate???) DLC launch sites

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Kopernicus/Kopernicus#290]
7bbbaa0 provides a way for a planet mod to delete Making History's launch sites, but it would also be cool to have a `LaunchSite` block, analogous to the `SpaceCenter` block, that defines a new location and orientation for them.  Of course this leads to all sorts of scope-creeping goodness in my mind, like a way to support duplicating launch sites based on a "stock" template, even onto other planets (since the KSP API shows that the LaunchSite class includes a variable for its celestial body, i.e. they're not hard-coded to Kerbin), but that's for later.  In a couple weeks I'll have some time to tinker and I'll see if I can at least move them to new locations, but I wanted to toss this here for consideration while the idea is fresh in my mind.

**Comment by Sigma88** [comment]
I don't think this feature should be implemented in kopernicus like the "SpaceCenter" feature

that feature is not very good for compatibility, and it's basically a lot of very specific code for just one thing

it would be better to have a generic way to move PQSCity mods, which was already tried but it didn't ever work properly

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
