### ISSUE TITLE
Installation (Personal issue)

### ISSUE THREAD

**Issue by Crimsn2021** [Kopernicus/Kopernicus#292]
I have been trying to figure out how to install Kopernicus for A while now and haven't been able to find any page or any type of guide on how to install Kopernicus and get it to run. I was wondering if you could make a page or just help out with this as I have heard great things about this mod but just cant seem to figure out how to make it work.
Also I'm new to this site so I have no clue how to ask for help so if this isn't the proper way to ask for this type of help please tell me.

**Comment by TheWhiteGuardian** [comment]
It's very simple.
1. Navigate to your Kerbal Space Program directory. For Steam users for example, this is often found under C:/Program Files(x86)/Steam/SteamApps/common/Kerbal Space Program
2. In the KSP directory, open up the GameData folder.
3. Open up another Finder or Explorer window (make sure you don't close the GameData one), navigate to the downloaded Kopernicus ZIP-file (for example, Kopernicus-1.4.3-2.zip), open it up, and inside the downloaded zip, open up the GameData folder.
4. Now you should have two GameData folders opened up. One is in your KSP directory, the other in the downloaded zip file. What you want to do is drag and drop all of the files from the 'zip file GameData' into the 'ksp directory GameData'
5. Ensure the GameData folder in your KSP directory now contains the folders 'Kopernicus' and 'ModularFlightIntegrator', as well as a version of 'ModuleManager.dll'. What version of ModuleManager is not that important, just ensure that it works with the KSP version that you use.
6. Profit.

Note that Kopernicus does nothing on it's own. It is the engine, not the driver. With Kopernicus in place, you can install any (compatible) user-created planet pack you like. Personal recommendations are:
- KillAshley's planet packs
- Galileo's Planet Pack
- Gameslinx' planet packs
- GregroxMun's planet packs

**Comment by Galileo88** [comment]
Or use CKAN. It’s demographic is the people that have issues installing things manually.

**Comment by Sigma88** [comment]
I'll go ahead and recommend @TheWhiteGuardian 's planet packs since he omitted them :D

**Comment by Crimsn2021** [comment]
Thank you that does help
