### ISSUE TITLE
ksp 1.4.4?? 

### ISSUE THREAD

**Issue by sibberia** [Kopernicus/Kopernicus#296]
doesnt work with 1.4.4 when will it come out?

**Comment by Mrcarrot1** [comment]
Kopernicus is intentionally version-locked to the version of KSP it was compiled for. You'll have to be patient and wait for a 1.4.4 release.

**Comment by Brochar** [comment]
Is there any way of determining how long itll take for this to be updated? Is this something that isnt going to happen?

**Comment by Mrcarrot1** [comment]
You'll just have to wait patiently; the dev does have a real life, but he does have an experimental version that he's compiled for 1.4.4.

**Comment by rjy7wb** [comment]
no the dev does not care, it probably won't be updated till atleast 1.5, i'm not sure why this mod is version locked though seems to be a purposely spiteful choice.

**Comment by Mrcarrot1** [comment]
"probably won't be updated" You say this when he's already got an experimental version in 1.4.4? You, sir, do not know how these things work, nor, apparently, why mod developers do the things they do. He does care, but if he cared about the mod more than his real life, he would be a person to pity greatly. Just wait. Everyone else is doing it just fine. Why can't you?

**Comment by marr75** [comment]
In steam, open the game properties. Go to the betas tab, pick the previous_1.4.3 version in the drop-down, use that until this updates.

**Comment by gjnelson7030** [comment]
Yeah, I'll be using KSP V1.4.3 to play until the release of the new Kopernicus. I love that feature in Steam.

**Comment by storyd** [comment]
at 20 days with no dev feedback on the ticket, is this even the right place to look?

**Comment by yaus** [comment]
For developer, it already able compile the latest source code. For public release, please be patient.

**Comment by Sigma88** [comment]
we have no ETA on a 1.4.4 release, summertime is a difficult period for mods because it's when school/exams are concentrated, also work in the summer gets more taxing than other months

I personally haven't even had time to look at ksp 1.4.4 for now. but as soon as we get the time to get everything ready to go the mod will be released

**Comment by marr75** [comment]
There's talk that a 1.4.5 version is coming out almost immediately so I don't know how high a priority this update should even be for the team. Read my instructions on how to continue to use 1.4.3 and enjoy.

**Comment by Sigma88** [comment]
I would have expected 1.4.5 to have arrived already given that currently KSP does not seem to be GDPR compliant.
