### ISSUE TITLE
New kopernicus + OPM fails to load (1.4.5-1)

### ISSUE THREAD

**Issue by Corfiot** [Kopernicus/Kopernicus#300]
[logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/2242750/logs-Kopernicus.zip)
[KSP-log.zip](https://github.com/Kopernicus/Kopernicus/files/2242752/KSP-log.zip)
[ModuleManager-configcache.zip](https://github.com/Kopernicus/Kopernicus/files/2242754/ModuleManager-configcache.zip)

Hi, getting a scary message not to load my save and lots of exceptions in the log. Following instructions, here's the information.

BTW thanks for the update mid-summer. Now if we can get it to work with OPM it'd be great.

**Comment by Corfiot** [comment]
Seems to be sigma binary related, although there are no errors related to that in the log.

**Comment by Sigma88** [comment]
seeing this is a new release of kopernicus and both OPM and SB have not been updated yet I would not be surprised if one or both mods have some issue working with the new kopernicus

when you say it seems to be sigma related, do you mean OPM loads fine when SB is not installed?

**Comment by Corfiot** [comment]
Removing only the SB mod makes the scary error message go away. I have ~60 mods. 
Just running opm+kopernicus+SB throws a reflection-related exception in the log for SB, which I do *not* see otherwise. It's confusing.

**Comment by Sigma88** [comment]
yeah, it's probably due the fact that SB is not designed to work with this version of Kopernicus

you can either wait for a new SB release or just drop SB for the time being (should not affect your game much to remove SB as long as everything else work properly)

**Comment by Corfiot** [comment]
Thank you. Closing issue.

**Comment by Corfiot** [comment]
Small note, this combination produced duplicates for karen and karen-orbit in the config, triggering an IOException in Kopernicus (multiple bodies, same name, see #302). Thus the scary warning and the OPM planets not loading. The pull request makes this config work as is on my machine with KSP1.4.5, without a newer version of SB. Haven't travelled to karen in-game but it seems to be there and the log indicates 

[LOG 00:10:18.986] [SigmaLog]: Binary System Completed
ReferenceBody: Sun
   Barycenter: Plock-Karen
      Primary: Plock
    Secondary: Karen

**Comment by Sigma88** [comment]
There should be no duplicates using sb,
It is expected that duplicates will break kopernicus. So this is probably an issue with either SB (Plugin) or with the sb configs and the new mm
