### ISSUE TITLE
Patched Conics no longer accurately reflect final destination when auto-warping.

### ISSUE THREAD

**Issue by MechBFP** [Kopernicus/Kopernicus#308]
Hey there,

I was running into a problem were I would be traveling to another planet, and when auto-warping (using the "warp to maneuver node", or "warp to" features) my destination would suddenly change for no reason.

For example, my Periapsis at the Mun could be 14,320m, and then after warping it would end up at 14,595m. Not a big deal for something like a Mun transfer, but anything further away means you can completely miss the planet when it moves on you.

I was able to narrow this problem down to Kopernicus through trial and error by removing 1 mod at a time. 

From a clean stock install I installed Module Manager, Modular Flight Integrator, and Kopernicus.
With all 3 installed, I was able to reproduce the problem.
After uninstalling Kopernicus, I was unable to reproduce the problem.

To reproduce:
1) Burn so that you are doing an intermoon or interplanetary transfer.
2) Note your Periapsis at the destination.
3) Make a random maneuver node somewhere near the new planet/moon.
4) Make a quick save.
5) Auto-warp using the "warp to maneuver node", or "warp to" features.
6) Stop the warp, and make a note of the Periapsis and see if it changed.
7) Repeat steps 5 & 6 multiple times and you should see the problem.
8) If necessary, load the quick save and try steps 5 & 6 again, as it seems to be more of an issue after loading a save game, but that could just be luck.

Version Information:
KSP 1.4.5
Kopernicus 1.4.5-4

**Comment by MechBFP** [comment]
Yes, I have. I was unable to reproduce the issue in a pure stock KSP install.

**Comment by sswelm** [comment]
This usually happens when passing through SOI at high time warp. What might help is slowing down timewarp when approaching the edge of the SOI before accelerating again at high timewarp

**Comment by Sigma88** [comment]
since there has been no update in more than 1 year I'll close this issue, if you still experience this issue feel free to reopen it
