### ISSUE TITLE
kopernicus.tmsp.io returns 502 Bad Gateway

### ISSUE THREAD

**Issue by gordonfpanam** [Kopernicus/Kopernicus#322]
Anyone check on the Kopernicus Wiki recently? The depreciated one here has no information, and the tmsp.io link only returns HTTP 502.

**Comment by StollD** [comment]
Thanks for the heads up, it is running again.

**Comment by gordonfpanam** [comment]
Sorry to re-open this, but as of 17 NOV 2018 I'm getting 502 Bad Gateway again at kopernicus.tmsp.io.
