### ISSUE TITLE
Kopernicus Failed to Load Planetary System

### ISSUE THREAD

**Issue by Vatruvius** [Kopernicus/Kopernicus#324]
Hello,

I am having a slight issue getting Kopernicus to work with my current mod list at the moment. I am running KSP 1.3.1 and am using CKAN to install all my mods. As it stands, Kopernicus is a required mod for another mod to function, in this case, Spectra and Stock Visual Terrain. There was a similar issue brought up in this issue report: https://github.com/Kopernicus/Kopernicus/issues/274

I am not sure exactly how to fix this issue. I have tried what was suggested in the linked issue but with zero success. The interesting thing is if I uninstall Spectra and install PlanetShine and Stock Visual Enhancements instead I do not get this error. However, I would rather use Spectra. I will attach the necessary logs below.

Any help will be greatly appreciated,
~ Vatruvius

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/2502548/KSP.log)
[ModuleManager.ConfigCache.txt](https://github.com/Kopernicus/Kopernicus/files/2502560/ModuleManager.ConfigCache.txt)
[Bop.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502566/Bop.Body.log)
[Dres.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502567/Dres.Body.log)
[Duna.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502568/Duna.Body.log)
[Eve.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502569/Eve.Body.log)
[Gilly.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502570/Gilly.Body.log)
[Ike.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502571/Ike.Body.log)
[Jool.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502572/Jool.Body.log)
[Kerbin.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502573/Kerbin.Body.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/2502574/Kopernicus.log)
[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/2502575/Kopernicus.Runtime.log)
[Laythe.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502576/Laythe.Body.log)
[Minmus.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502577/Minmus.Body.log)
[Moho.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502578/Moho.Body.log)
[Mun.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502579/Mun.Body.log)
[Pol.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502580/Pol.Body.log)
[Sun.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502581/Sun.Body.log)
[Tylo.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502582/Tylo.Body.log)
[Vall.Body.log](https://github.com/Kopernicus/Kopernicus/files/2502583/Vall.Body.log)

**Comment by Sigma88** [comment]
since there has been no update in more than 1 year I'll close this issue, if you still experience this issue feel free to reopen it
