### ISSUE TITLE
Solar Panels not working

### ISSUE THREAD

**Issue by Moonthrower** [Kopernicus/Kopernicus#325]
Solar panels are not gathering a charge. Last release, I updated the hotfix and it solved the issue, but 1.5.1 just came out and they are busticated again!

Love the mod, works great still with Astronomer's Visual Pack. Couldn't ever go back to stock planets again!

**Comment by Valareos** [comment]
I can confirm Solar Panels not working.

Built the 1.5.1 dll's from source.  Solar panels not charging.

disabled Config/SolarPanels.cfg to turn off the Korpernicus solar panels.  Solar Panels Charging again.

I appreciate all the hard work you do.  This is a great mod, and worth the wait to have it done right.

**Comment by Moonthrower** [comment]
By disabling config/solarpanels.cfg, do you mean just delete that .cfg file from the Kopernicus folder?

**Comment by Valareos** [comment]
No.  Edit it, and put a // in front of  @name = KopernicusSolarPanel like so

`@PART:FINAL
{
    // This will replace all instances of ModuleDeployableSolarPanel with the Kopernicus version
    // that has proper support for multiple lightsources
    // 
    // If you want to keep your ModuleDeployableSolarPanel, add "useKopernicusSolarPanels = false" to the MODULE node
    // That will stop Kopernicus from replacing it
    @MODULE:HAS[#useKopernicusSolarPanels[*]]
        @useKopernicusSolarPanels,* ^= :F:f:
        @useKopernicusSolarPanels,* ^= :A:a:
        @useKopernicusSolarPanels,* ^= :L:l:
        @useKopernicusSolarPanels,* ^= :S:s:
        @useKopernicusSolarPanels,* ^= :E:e:
    }
    @MODULE:HAS[#name[ModuleDeployableSolarPanel],~useKopernicusSolarPanels[false]]
    {
     //   @name = KopernicusSolarPanel
    }
}`

it turns it into a comment, and keeps it from changing the name. It also means its a simple matter to reverse.

**Comment by Valareos** [comment]
loaded official latest update for Kopernicus. Solar Panels working again. Reccomend this closed.

**Comment by Sigma88** [comment]
happy this was fixed

**Comment by Moonthrower** [comment]
Thanks all!
