### ISSUE TITLE
Kopernicus version error/bug.

### ISSUE THREAD

**Issue by BobTheKerbal** [Kopernicus/Kopernicus#326]
So, I download Kopernicus 1.5.1 on KSP 1.5.1  and follow all the download instructions. But, theres a message that says "Kopernicus won't work on this version of KSP!  Please don't try to load your savegames!" And help on this glitch/bug? 
Heres my logs. https://www.dropbox.com/s/3cpjqto7o8lfvvc/Kopernicus.log?dl=0

**Comment by StollD** [comment]
You downloaded Kopernicus 1.5.0-1, instead of 1.5.1-1. Please download the latest release and try again

**Comment by BobTheKerbal** [comment]
Thank you! I will try this.

**Comment by BobTheKerbal** [comment]
It worked thanks so much!
