### ISSUE TITLE
Kopernicus Failed to Load Planetary System

### ISSUE THREAD

**Issue by nsgallup** [Kopernicus/Kopernicus#327]
I'm getting an issue where I get a notification after the game launches that the planet pack failed to load. When I open a save game all the OPM planets and moons are in fact loaded but the sunlit side of the objects is facing away from the actual direction of the sun? What is going on?

https://drive.google.com/drive/folders/1inZwrUEyN2iMPsJzsIEuO7_lsuMUFWZn?usp=sharing

**Comment by nsgallup** [comment]
Issue resolved, per forum thread.

**Comment by Sigma88** [comment]
Good :tada:
