### ISSUE TITLE
Loading the world takes a lot of time

### ISSUE THREAD

**Issue by Runaan** [Kopernicus/Kopernicus#330]
This took a lot of TIME. PLEASE, FIX THIS PROBLEM ;{

**Comment by Galileo88** [comment]
No logs, no info, no version number, nothing. 

I have no idea if you are even playing KSP. PLEASE FIX THIS PROBLEM!

**Comment by BryceSchroeder** [comment]
Thank you for your feedback @Runaan , but the development team really can't help you without more information. You say that loading "the world" takes a lot of time, but we need to know your specific situation (as reflected in the items @Galileo88 requests above.) Please get them together first. Thanks!

**Comment by Sigma88** [comment]
here's a more detailed list of all the information we need
