### ISSUE TITLE
KSP 1.6.0 Compatibility patch needed

### ISSUE THREAD

**Issue by DJGoo** [Kopernicus/Kopernicus#337]
KSP 1.6.0.2395 has been released as the latest stable version of KSP and boasts a needed performance boost. Kopernicus won't run on the new version making all savegames currently inaccessible to mod users at the moment if there are several other mods requiring Kopernicus.

**Comment by mferrie** [comment]
I'd like to help, but I have no idea how to update a mod. What needs to be done with this project? Also, I downloaded the source yesterday and immediately got over 9000 errors....

**Comment by Sigma88** [comment]
we are working on it, we don't have an ETA yet but as soon as the new version is ready it will be uploaded to github

**Comment by jgilhutton** [comment]
hey my dudes.... it's christmas and new year times of the year so I was surprised when you said you were working on the new release.
Have a nice meal with your families on new year's eve and may the new version of Kopernicus be ready when you think it is the time for it.
Some people doesn't understand that developers have a life outside KSP. 
Greetings from a fellow Kerbaler.
