### ISSUE TITLE
Custom Coronas revert to default Builtin

### ISSUE THREAD

**Issue by CyberHeadSoftware** [Kopernicus/Kopernicus#338]
I am using version 1.5.1-2. In my config I have:

        Corona
		{
		rotation = 0
                speed = -1
                updateInterval = 5
                scaleLimitX = 5
                scaleLimitY = 5
                scaleSpeed = 0.007
				Material
				{
					texture = CyberHead/Vaaps/Textures/Vaaps_corona
					inverseFade = 2.553731
				}
			}

with the rest of the config, of course. (Sorry about the spacing)

However, when I load up KSP, it shows the default corona. I have Kittopia 1.5.1-1 installed, and it says it is using BUILTIN/suncoronanew, the default. How do I fix this?????

**Comment by Sigma88** [comment]
could you show the modulemanager cache file of the install that is giving you problems please?

also, can you upload all other files described [here](https://forum.kerbalspaceprogram.com/index.php?/topic/181547-0/&page=27&tab=comments#comment-2793409)? thanks
