### ISSUE TITLE
he screen (which should contain the drawing of the base) turns black and with the information in the lower right corner of "Loading"

### ISSUE THREAD

**Issue by luxorpt** [Kopernicus/Kopernicus#340]
I was happy with the upgrade, and failed to give the error I reported earlier, however:
At the start of the game, the screen (which should contain the drawing of the base) turns black and with the information in the lower right corner of "Loading" with the planets to rotate; after 1 hour the status remains the same.
Is there any information you can give that helps you diagnose and solve this problem?
If there is any log file, please indicate to send it.
I reinstalled the module, and started to open a window with the recommended errors not to  proceed.
I attach the ksp.log
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/2770219/KSP.log)

**Comment by Sigma88** [comment]
Sorry for not getting back to you at the time, we were probably busy and did not manage to reply you in time.

If you are still experiencing issues feel free to open a new issue, or reopen this one
