### ISSUE TITLE
Kopernicus was not able to load the custom planetary system due to an exeption in the loading process.

### ISSUE THREAD

**Issue by FrenchSpaceWalker** [Kopernicus/Kopernicus#341]
Hello, I would like to install real solar system 1.4.5, I followed the instructions, installed Kopernicus 1.4.5-4, and Module Manager 3.1.3. I didn't install any other mod in my GameData. But by launching KSP, an error message has occurred: "Kopernicus was not able to load the custom planetary system due to an exeption in the loading process" and the mod didn't work ...
Would someone have a solution?

**Comment by StollD** [comment]
The solution is to continue reading the pop-up, noticing that it asks you to upload some files we need for debugging, and then sending us those files.

**Comment by FrenchSpaceWalker** [comment]
Oh, ok thanks! xD

**Comment by zambino12** [comment]
was yours fixed
cuz i got same probelm

**Comment by StollD** [comment]
Aparently it was, since they never replied back with an actual bugreport including logfiles.

So I am closing this
