### ISSUE TITLE
Exception on loading custom planet 

### ISSUE THREAD

**Issue by bungthebadger** [Kopernicus/Kopernicus#343]
Hello there, I'm having some issues (like some other people) as evidenced by the title. The planet mod I'm using is TheWorldBeyond along with all the solar systems it has included (No EVE/Scatter installed onto it). The pictures of the mods I have will be included in the zip folder as well as the logs necessary, thank you for your time.

[Logs-Kopernicus-latest.zip](https://github.com/Kopernicus/Kopernicus/files/2873959/Logs-Kopernicus-latest.zip)

Edit: It seems that even with the deletion of TheOtherWorld, Korpernicus is still giving me the same error so this may do something with Korpernicus itself. I'll give an update to the logs tomorrow as its late for me at the moment.  
______________________________________________________________________________________________________________
Sorry for the wait, it slipped off my mind for a little bit, here's the updated logs without TheOtherWorld: [Logs-Kopernicus-latest.zip](https://github.com/Kopernicus/Kopernicus/files/2897918/Logs-Kopernicus-latest.zip)

**Comment by StollD** [comment]
Sorry for not answering for so long..

It seems that your Kopernicus has issues with loading the ring shaders. I am not sure if this is related to your graphics card not supporting them, or the files getting corrupeted somehow.

Could you try to redownload Kopernicus from the releases tab on GitHub and reinstalling it?

**Comment by bungthebadger** [comment]
Hello there again, sorry that I didn't respond. Here's the log files, I re downloaded Kopernicus as you asked me to and and still gives me the same error. Here are the logs.
[Logs-Kopernicus-latest.zip](https://github.com/Kopernicus/Kopernicus/files/2928781/Logs-Kopernicus-latest.zip)

**Comment by StollD** [comment]
Weird, the error is still the same one (exception message from the code that loads the ring shaders). At this point, the only idea I have is to try running the game using OpenGL (`./KSP_64.exe -force-glcore`) and check if it might be related to DirectX errors. But if that doesn't work I have no idea how it fix it :/

**Comment by bungthebadger** [comment]
Hey there, sorry for the wait again. I tried the commands but they don't seem to work. Here's the log if there's a chance of something that can be remedied. 
[Logs-Kopernicus-latest.zip](https://github.com/Kopernicus/Kopernicus/files/2948826/Logs-Kopernicus-latest.zip)

**Comment by bungthebadger** [comment]
Well, I think it's best to close this issue down until the next update comes out and perhaps it will be solved. Thank you for the help!
