### ISSUE TITLE
korpernicous couldnt load planets due to an exception 

### ISSUE THREAD

**Issue by zambino12** [Kopernicus/Kopernicus#344]
it say it couldnt load the planets.

//===============================================================================================================//
//=====  Kopernicus 1.6.1-1 - (BuildDate: 12.01.2019 15:05:17; AssemblyHash: xI9E/vKfcRZPudv2RTiKGjwp3pg=)  =====//
//===============================================================================================================//
[LOG 21:55:13]: Logger "Kopernicus" was created
[LOG 21:55:13]: Injector.Awake(): Begin
[LOG 21:55:20]: [Kopernicus] RuntimeUtility Started
[LOG 21:55:20]: StarLightSwitcher.Awake(): Begin
[LOG 21:57:06]: Injector.OnDestroy(): Complete
thats is one log 

this is the second,//===============================================================================================================//
//=====  Kopernicus 1.6.1-1 - (BuildDate: 12.01.2019 15:05:17; AssemblyHash: xI9E/vKfcRZPudv2RTiKGjwp3pg=)  =====//
//===============================================================================================================//
[LOG 21:55:20]: Logger "Kopernicus.Runtime" was created
[LOG 21:56:23]: [Kopernicus] Fixed SpaceCenterCamera

pls help meh

**Comment by splat1125** [comment]
buddy i don't know what to say
you aren't providing enough information; for example, what planet mod are you attempting to load?
kopernicus isn't even trying to report any, so it's clearly so messed up that it just doesn't try.

**Comment by DeltaDizzy** [comment]
@zambino12 Can you upload _all_ the files that the popup told you to? As in not just paste them here but upload them to a site like dropbox and link to them.

**Comment by Sigma88** [comment]
here is a more detailed list of all the files we need to help you

https://forum.kerbalspaceprogram.com/index.php?/topic/181547-161-2-backports-kopernicus-kittopiatech/&page=27&tab=comments#comment-2793409
