### ISSUE TITLE
Can't Save/Recover/Return To Space Center

### ISSUE THREAD

**Issue by zbomb** [Kopernicus/Kopernicus#348]
After some research, this issue was found at the end of last year, here is the page where I found information. 
https://forum.kerbalspaceprogram.com/index.php?/topic/152136-ksp-145-galileos-planet-pack-v1631-03-aug-2018/&page=255

I am not using GPP, I am using the Beyond Home mod, its prerequisites, and the Making History expansion, besides that a clean install. An exception is being thrown whenever I land on a planet (incl home planet), where the ship has debris/probe. Then I am unable to save, return to space center, and when on the home planet, I am unable to recover vessel.

The fix found in the thread posted above (Turn Off 'Tidy up debris') seems to work, but I am going to do a bit more debugging

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3011007/KSP.log)

**Comment by DeltaDizzy** [comment]
Remove Making History, it causes this problem.

**Comment by zbomb** [comment]
Is there anyway to remove Making History while still being able to use the parts? I would rather try the workaround I have now than loose parts

**Comment by DeltaDizzy** [comment]
Why yes there is! [Making Less History by DMagic](https://forum.kerbalspaceprogram.com/index.php?/topic/108704-14x-16x-dmagics-modlets-flexible-docking-v70-restock-support-3-12-2019/) disables all MH-added game mechanics while keeping the parts.

**Comment by zbomb** [comment]
Thanks! So far it seems to have fixed the issue

**Comment by marr75** [comment]
This was resolved by #306
