### ISSUE TITLE
Flag problems

### ISSUE THREAD

**Issue by raidernick** [Kopernicus/Kopernicus#349]
This is not a major issue but a very distracting and annoying one, especially if you are trying to record a video(or stream for those who do it). The flag on the flagpole next to the pad seems to have some serious spaz/jumping issues since updating to 1.6. It glitches out, jumping all over, even detaching itself from the pole by several feet and jumping back. This was not an issue in prior versions of ksp with this mod.

I know it's kopernicus causing this and not RSS as any mod that uses kopernicus has the same issue and not specifically RSS itself.

Can you please look into fixing this.

**Comment by Galileo88** [comment]
I have never seen this issue. Try running KSP with only kopernicus and it’s dependencies installed and see if you still see the issue. That will help you narrow down what mod is causing the issue. If it truly is kopernicus, the issue should persist without RSS too.

**Comment by PhineasFreak** [comment]
I was the person who suggested that Kopernicus might be the culprit. It happens both in RSS (custom CB configs) and in 10x stock (Sigma Rescale). And the common link between these two is the CB manager (Kopernicus).

**Comment by Sigma88** [comment]
it could be the result of having a very big planet rather than a bug in kopernicus itself, if that's the case, I doubt there is much that can be done. (other than using smaller planets)

**Comment by PhineasFreak** [comment]
Hmm, that would be the most probable cause. Looks similar to the early KSP versions where the vessel position got jerkier the further from the surface it was (floating point errors?).

The Unity engine version was updated from 5.4.0p4 to 2017.1.3p1 may also has something to do with, as it happens in all later KSP versions (1.4, 1.5, 16).

**Comment by Sigma88** [comment]
I managed to find a fix for this issue, I am not sure if it will be released as part of kopernicus, as part of SD or as a standalone mod.

**Comment by raidernick** [comment]
@Sigma88 if it isn't rolled in to kopernicus for whatever reason, we would add it in to RSS rather than have it be standalone if possible.

**Comment by Sigma88** [comment]
I have already released a standalone plugin, but you can add it into RSS as well

**Comment by Sigma88** [comment]
[this](https://github.com/Sigma88/Sigma-FlagFixer/blob/master/%5BSource%5D/SigmaFlagFixer/SigmaFlagFixer.cs#L8-L26) part handles when to apply the fix

and [this](https://github.com/Sigma88/Sigma-FlagFixer/blob/master/%5BSource%5D/SigmaFlagFixer/SigmaFlagFixer.cs#L27-L35) part is the fix itself

**Comment by Sigma88** [comment]
@StollD  if you think this could fit into kopernicus, let me know where you want me to integrate it in

I know you don't like creating new classes, so I assume I will need to integrate this into an existing class (like runtime utility or whatever)

**Comment by Sigma88** [comment]
this should be fixed now
