### ISSUE TITLE
Ugly seams in ScaledSpace

### ISSUE THREAD

**Issue by CaptRobau** [Kopernicus/Kopernicus#35]
A picture says a thousand words. Had this in old Kopernicus too with some bodies: http://i.imgur.com/L2KByvf.png

**Comment by Teknoman117** [comment]
Is this still happening?

**Comment by CaptRobau** [comment]
Yes it does.

**Comment by Andem6** [comment]
I'm also getting this, But it seems to happen on random bodies without cause or provocation. :/

**Comment by Sigma88** [comment]
since there has been no update in 3 years I'll close this issue, if there are more information feel free to re-open it
