### ISSUE TITLE
1.7 Released, Need an Update

### ISSUE THREAD

**Issue by diveyez** [Kopernicus/Kopernicus#350]
I have tested and tried working at it for 4 hours, its not gonna work without expert help.

**Comment by Mrcarrot1** [comment]
Looking at your profile, you seem like a pretty knowledgeable guy about this sort of thing, so I'll give it to you straight: the mod is intentionally version-locked to avoid causing issues in the versions it wasn't designed for. The update will likely come soon, but the author has a real life and can't do it instantly.

**Comment by DeltaDizzy** [comment]
And here it is! @diveyez Try downloading the latest update and see if it works on 1.7.0.
