### ISSUE TITLE
kopernicus was not able to load the custom planetary system due to an exception

### ISSUE THREAD

**Issue by amxpro** [Kopernicus/Kopernicus#351]
im new to pc and modding in general. I got a pop up and now im here. where do i go to get the information needed

**Comment by DeltaDizzy** [comment]
KSP.log is in KSP's root folder. (The one with the .exe files, GameData, and so on.) Also in that Root Folder is the Logs folder, which contains a folder called Kopernicus. Take that folder, KSP.log, and Output_log.txt (It is located in AppData/LocalLow/Squad/Kerbal Space Program. [This should help you find AppData/LocalLow.](https://answers.microsoft.com/en-us/windows/forum/windows_vista-files/how-do-i-find-appdatalocallow-folders/2e0a0755-6bd4-4fcd-a866-99c0e4da74e4)) and put them all into a zip file (Right-click -> new -> Compressed (Zipped) folder). Upload that here.

**Comment by amxpro** [comment]
I have found output_log and kopernicus file. cant find ksp.log. also when i right click there in no new

**Comment by DeltaDizzy** [comment]
Is there one just called KSP?

**Comment by amxpro** [comment]
no

**Comment by StollD** [comment]
Am Montag, den 22.04.2019, 20:01 -0700 schrieb amxpro:
> no
> 
> 

Go to the folder that contains your KSP installation, then go to
Logs/Kopernicus and upload the file Logs-Kopernicus.zip or Logs-
Kopernicus-latest.zip.

Also reopening this and closing the other duplicated issue you created.

**Comment by amxpro** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3109872/Logs-Kopernicus.zip)

is this right?

**Comment by Sigma88** [comment]
since there has been no update in more than 6 months I'll close this issue, if you still experience this issue feel free to reopen it
