### ISSUE TITLE
kopernicus was not able to load the custom planets because of an exception in the loading process

### ISSUE THREAD

**Issue by guapathecat** [Kopernicus/Kopernicus#355]
what does this mean?
i have the kopernicus in the normal gamedata folder for 1.7 but it doesnt seem to work
how do you get it to work

**Comment by DeltaDizzy** [comment]
Go to your KSP root folder. There should be a folder in it called "Logs" go into it and find the zip file called "Logs-Kopernicus-latest.zip". Upload that file here. Once you do that we can tell you what went wrong.

**Comment by StefanoFrazzetto** [comment]
> 
> 
> Go to your KSP root folder. There should be a folder in it called "Logs" go into it and find the zip file called "Logs-Kopernicus-latest.zip". Upload that file here. Once you do that we can tell you what went wrong.

I just had the same problem.
Here's my log files: https://1drv.ms/u/s!Al8LoHPh4O-ot2jq5IE6w9g68Fxm

**Comment by Sigma88** [comment]
sorry I didn't reply earlier. did you manage to solve your issue or are you still having troubles?
