### ISSUE TITLE
My Kopernicus mod could not load because of an exception during loading

### ISSUE THREAD

**Issue by Entity93039** [Kopernicus/Kopernicus#357]
so I start up ksp and i get this message "Kopernicus was not able to load the custom planetary system due to an exception in the loading process."
i am using module manager and my mods are: kerbal alarm clock, kerbalreusabilityexpansion, kopernicus, modulemanager, nearfuturelaunchvehicles, new horizons(but this won't load because of this problem), spaceX_ITS, spaceyexpanded and spaceylifters. how can i solve this problem and sorry for rambling on for so long. :P 

P.S my kopernicus is 1.7 compatible and im playing on a mac

**Comment by Gameslinx** [comment]
You should upload your KSP log. Also, New Horizons is for 1.3 and probably won't work on 1.7.
