### ISSUE TITLE
kopernicus was not able to load the custom planets because of an exception in the loading process 

### ISSUE THREAD

**Issue by grinches** [Kopernicus/Kopernicus#359]
i am new to manual modding and have been modding ksp. I download the outer planets mod (and all the other mods you need to use outer planets). when i launch the game i get the stated error above. i know nothing about modding and dont even code. i know others have had this problem,

**Comment by Galileo88** [comment]
If you are on the latest version on KSP (1.7.1), Kopernicus will fail to load. This is due to Kopernicus being version locked to KSP version 1.7. If you want to play with Kopernicus and planet packs, you will need to revert back to 1.7.

**Comment by grinches** [comment]
i tried reverting back to 1.7.0 and it didnt work, same error. honestly i think its just me extracting it to the wrong folder. my directory looks like this, D:\Steam storage\steamapps\common\Kerbal Space Program\GameData\Kopernicus-1.7.0-1 
 here is a screen shot and the logs (i think its the right logs)

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3245889/Logs-Kopernicus.zip)
![image](https://user-images.githubusercontent.com/51306480/58776669-37892e00-8591-11e9-975a-18a6fbf0f8ce.png)

**Comment by Sigma88** [comment]
do you have the expansion installed?

I've read on the forums that sometimes when you revert to 1.7.0 the expansion is not reverted properly

**Comment by grinches** [comment]
Its still not working. 

No i dont own any DLC. 

I believe I've installed both Kopernicus and ModuleFlightIntergrator in the right place.
D:\Steam storage\steamapps\common\Kerbal Space Program\GameData\Kopernicus

i still get the same error message after loading. 

[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/3249890/Kopernicus.Runtime.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/3249891/Kopernicus

sorry this is taking so long, idk what to do.

**Comment by Sigma88** [comment]
```
Failed to load Body: Squad/Kerbin: Exception has been thrown by the target of an invocation.
```

there seems to be an issue with your kerbin, could you upload the ModuleManager cachefile as well? that might help us pinpoint the issue, and also the whole Logs folder which contains the file specific for Kerbin's debug

**Comment by tomesdw** [comment]
any word on 1.7.1 compatibility?

**Comment by VedaantAchuthan** [comment]
No. And if you keep asking you won't get any thing.
Have patience Young Padawan, Thomas will do what he must.

**Comment by Galileo88** [comment]
Every time someone asks it gets pushed back another week. ;).

**Comment by grinches** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3255617/Logs-Kopernicus.zip)
[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/3255618/ModuleManager.zip)
i think this is them but i have no idea, if it isnt them tell me how to find them and ill send them here 
thanks for the help!

**Comment by Sigma88** [comment]
the file I need is called **ModuleManager.ConfigCache** and it should be found directly inside the GameData folder

however, looking at the files you provided I noticed this:

```
Mods by directory (sub directories of GameData):
  CTTP.v1.0.4
  FreeIvaV0.0.5
  GameData
  Kerbal_Planetary_Base_Systems-1.6.9
  MechJeb2-2.8.3.0
  ModuleManager-4.0.2
  NearFutureConstruction_1_1_1
  NearFutureSolar_1_0_2
  NearFutureSpacecraft_1_2_4
  Outer_Planets_Mod-1.7
  PlanetShine-0.2.5.2
  SVT.v2.1.4
```

you have all these folders into the GameData folder and I think all of them are installed incorrectly.

when you install manually you should look into the archive for a GameData folder, if you can find one, then you should put the content of that folder into your GameData.

95% of the time just unzipping the archive inside GameData will result in mods not working properly

**Comment by grinches** [comment]
ok ill start doing that from here on out.

[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/3257684/ModuleManager.zip)
i think this is the folder you asked for

**Comment by Sigma88** [comment]
after you check your install and re-run ksp, if you are still having issues here's a guide I wrote some time ago with a list of all the things that we might need you to provide when you have an issue:

https://forum.kerbalspaceprogram.com/index.php?/topic/181547-0/&page=27&tab=comments#comment-2793409

Not every time all those files will be required, but it's a good list to know, to keep track of what might be needed for understanding the issue someone is having
