### ISSUE TITLE
Kopernicus doesn't even try to load

### ISSUE THREAD

**Issue by mferrie** [Kopernicus/Kopernicus#361]
Instead of loading, Kopernicus prints an error to the screen that "Kopernicus will not work in this version of KSP! Do not try to open any of your save games!"

**Comment by VedaantAchuthan** [comment]
DOWNLOAD the new hotfix, 1.7.1-2 and retry.

**Comment by mferrie** [comment]
Thanks!

Sent from Mail for Windows 10

**Comment by mferrie** [comment]
There were no errors during the load processb

**Comment by mferrie** [comment]
![Capture](https://user-images.githubusercontent.com/15007855/59117267-f7200c00-8912-11e9-9341-1743ea1b7164.PNG)
It gave me this error after the game loaded.

**Comment by mferrie** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3266734/KSP.log)

[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3266736/Kopernicus.zip)

[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/3266737/ModuleManager.zip)

**Comment by StollD** [comment]
You have sigma dimensions installed. Please read the changelog again, which states that any plugin that depends on Kopernicus is now dead and will need an update.

**Comment by mferrie** [comment]
So that's what broke it. Thanks, I should have actually read the changelog lol.

**Comment by mferrie** [comment]
![Capture](https://user-images.githubusercontent.com/15007855/59119795-479a6800-8919-11e9-86a9-cafd2ba758a1.PNG)
Still not working..

**Comment by mferrie** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3266862/Logs-Kopernicus.zip)

**Comment by DeltaDizzy** [comment]
Please upgrade to Kopernicus 1.7.1-4.

**Comment by pmborg** [comment]
![Kopernicus1 7 1-4](https://user-images.githubusercontent.com/5012251/59127827-71c34880-8960-11e9-98ab-f71431a03ec6.png)

[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/3267283/KSP.zip)

I am glad to help and I will provide more data if needed.

**Comment by Joker58th** [comment]
> I am glad to help and I will provide more data if needed.

Did you upgrade to 1.7.1-4?  That should fix all the issues.

**Comment by mferrie** [comment]
I did. Kopernicus works, and now I’m waiting for Sigma88 to update Sigma
Dimensions.

**Comment by pmborg** [comment]
Yes, true, now all is solved :)

![Kopernicus1 7 1-4_img2](https://user-images.githubusercontent.com/5012251/59129046-9e2c9400-8963-11e9-96e8-98d66369d480.png)
