### ISSUE TITLE
1.7.1-4 Trajectories Incompatibility

### ISSUE THREAD

**Issue by Maeyanie** [Kopernicus/Kopernicus#363]
It appears that Kopernicus tries to load all .bin files under GameData as cached planets.
This results in it trying to load the Trajectories version-specific executable code (GameData\Trajectories\Plugin\Trajectories.bin and similar) as a cached planet. Unsurprisingly this is not in the right format, and causes KSP to hang on loading.

**Comment by tofof** [comment]
It's not actually Trajectories' fault.

Testing in KSP 1.7.1.2539 with no other mods than those listed:
* Kopernicus 1.7.1-4  + Trajectories official release   ----    loads into game, but (duh) trajectories doesn't work
* Kopernicus 1.7.1-4 + Trajectories after copy/renaming the 16 file to Trajectories17.bin     ----    loads into game, trajectories button appears and I assume it works
* Kopernicus 1.7.1-4  + Trajectories (official OR with 17.bin, makes no difference) + **ModularFlightIntegr﻿ator** 1.2.6.0  ----    hangs on kopernicus\plugins\trajectories.bin during load﻿﻿﻿

**Comment by Gordon-Dry** [comment]
Same as with Kerbalism.

.bin files need to be renamed.

.tbin ? ;)

**Comment by tofof** [comment]
> .bin files need to be renamed.

I mean, they don't, though. Trajectories and Kopernicus are completely compatible with one another. And ModularFlightIntegrator doesn't have any .bin files.

**Comment by DeltaDizzy** [comment]
>I mean, they don't, though. Trajectories and Kopernicus are completely compatible with one another.
ModularFlightIntegrator is a dependency of Kopernicus. When you remove it, Kopernicus fails to do or load or try to load anything at all. It crashes but lets game loading continue.

**Comment by tofof** [comment]
> ModularFlightIntegrator is a dependency of Kopernicus.

Derp. You're correct. Thank you, obviously I had totally missed that.
