### ISSUE TITLE
kopernicus.tmsp.io stops working if you click a link, "topology was destroyed"

### ISSUE THREAD

**Issue by HebaruSan** [Kopernicus/Kopernicus#367]
The wiki page on GitHub contains a small notification to go to https://kopernicus.tmsp.io/ instead:

![image](https://user-images.githubusercontent.com/1559108/60850536-5e193500-a1df-11e9-8fa4-c3ec66f5e2e9.png)

If you open that page and click any link, it stops working, seemingly permanently:

![image](https://user-images.githubusercontent.com/1559108/60850523-4b066500-a1df-11e9-94b7-88364a5e76f6.png)

I tried reloading and starting over in a new tab, and it didn't help. Confirmed it's not a server side problem by opening on another computer; again it worked at first and gave the above error when a link was clicked.

For what it's worth, tested on Chrome on Windows and Firefox on Ubuntu.

**Comment by democat3457** [comment]
kopernicus.tmsp.io is deprecated, use https://kopernicus.github.io/wiki
