### ISSUE TITLE
Lag/latency

### ISSUE THREAD

**Issue by priest81** [Kopernicus/Kopernicus#369]
Hi,

I am technologically inept, so I apologize if this doesn't make sense. with vs. 1.7.1-5 I was able to delete the solar panel .cfg and it allowed kopernicus to work really well.  with 1.7.3-1, I am getting terrible lag on high part count ships, and if I delete the solar panel .cfg...nothing works.  Is there any way to get more FPS? Note, I have no issues with launch lag...it's only on my mun base.

Thanks!

**Comment by Sigma88** [comment]
The fps drop is most likely caused by something other than the solarpanels.

Could you please upload the files listed [here](https://forum.kerbalspaceprogram.com/index.php?/topic/181547-0/&page=27&tab=comments#comment-2793409) ? This should help us figure out what is going wrong in your game

**Comment by priest81** [comment]
I'm in the process of doing that. If I do it wrong, please let me know. In the meantime, Here is a lengthy description of what I have attempted to do to fix the situation, this will be in the folder that I upload. 


I installed 1.7.1-5 a few weeks back, but for some reason my solar panels were not working. I read online and a solution was to modify the solar panel .cfg with some sort of argument on a module, but I didn't understand how to do that. Instead, I just deleted the .cfg, and my solar panels started working again. 

KSP updated late last week and I saw the update for Kopernicus, and so I updated. I noticed an IMMEDIATE performance drop, but only when I am at my mun base, where I had experienced zero issues prior to update. I have no issues with launch or interacting on the Mun at my science outpost. It is only where my large part count structures are.

I uninstalled Kopernicus and Astronomer's Visual which...oddly caused all my solar panels to stop working. I tried reinstalling the old version of Kopernicus and that didn't fix the issue.  If I remove the Solar Panel .cfg, I get a huge boost in performance, but my solar panels stop working. Also, if I destroy all of the vehicles with truss style solar panels, I get my performance back. I also tried various graphical settings changes...but none of them made any difference whatsoever. 

I can only surmize that it has to do with the solar panels as I have zero issues unless I am near a structure with significan solar panels...specifically truss style from the Near Future Electrical.

**Comment by priest81** [comment]
Here is the link to the requested files. It has taken me quite a bit to pare down the 'essential' mods that let my saved game run. I confirmed that this is the minimum mod load by ensuring that I did not experience an FPS drop with all the other mods before I installed Kopernicus. I hope I did this correctly.

https://drive.google.com/open?id=1X_9eo4-8LB3X00PlJbN9Ad7SRmxo41Oc

**Comment by Galileo88** [comment]
I haven't gone in depth with your logs but immediately in your full mod loadout, you have CTTP and not a single mod that utilizes it. CTTP is only textures and none of the other mods depends on it. Having it in there doesn't hurt anything, but it also doesn't do anything at all in your install, so therefore, I recommend removing it.

**Comment by priest81** [comment]
Thank you for your advice. I don't have a lot of experience in this, and so it has been trial and error for me.

**Comment by Sigma88** [comment]
did you manage to find a solution to this issue? or is this still a problem?
