### ISSUE TITLE
KopernicusBuoyancy.FixedUpdate causing FPS drops on Duna

### ISSUE THREAD

**Issue by marr75** [Kopernicus/Kopernicus#370]
I see @StollD has already pushed a commit that removes KopernicusBuoyancy but I thought I'd document my experience with the issue in case any other user has the issue.

I get incredibly low FPS on Duna (but not on Kerbin). I narrowed down the issue to Kopernicus, which was exciting because I know a little about the codebase, and then began profiling. The guilty method according to the profiler was `KopernicusBuoyancy.FixedUpdate`, taking up ~120ms every frame.

**Comment by marr75** [comment]
Can confirm, incorporated the changes to KBuoyancy into the version of Kopernicus I'm running and no further performance issues on Duna.

**Comment by soulassassyn** [comment]
@marr75 I just installed this mod and am having the exact same issue.  Only on Duna... everywhere else seems fine.  What can I do to fix this.  Sorry, I have no coding knowledge and don't really understand how to remove KopernicusBuoyancy

**Comment by democat3457** [comment]
Unfortunately, you'd have to wait for the next update, unless you are able to compile the new Kopernicus code using Visual Studio.

**Comment by soulassassyn** [comment]
> Can confirm, incorporated the changes to KBuoyancy into the version of Kopernicus I'm running and no further performance issues on Duna.

@marr75 are you able to share the changes you made to your version on here somewhere?  I'd love to keep using this mod as it's beautiful but I'm in the middle of a Duna rescue mission and absolutely must be able to play on Duna hahaha.

**Comment by jim123A** [comment]
I Have the same problem to i found out today it was kopernicus.

**Comment by marr75** [comment]
There's a modulemanager hack in the forums. See Jognt's comment at https://forum.kerbalspaceprogram.com/index.php?/topic/181547-173-1-backports-kopernicus-kittopiatech/page/170/&tab=comments#comment-3640869 (and remember to remove when a new version is released).

I'll update my Kopernicus fork, which is trivially easy to find, this weekend because I've gotten a few messages requesting a binary. I'm not going to link to it here or on the KSP forum because I think that runs counter to the maintainers' general wishes.

**Comment by viveleroi** [comment]
@marr75 Doesn't seem like you've been able to update your fork yet. I didn't want to reply here but you have issues disabled there. If you've posted a binary, it's not clear to me where else. Feel free to message me on the KSP forums (viveleroi)

**Comment by Sigma88** [comment]
is this issue still happening? or can it be closed?
