### ISSUE TITLE
kopernicus not working in 1.7.3

### ISSUE THREAD

**Issue by zambino12** [Kopernicus/Kopernicus#371]
says blah ba blah due to exception and i cant find the logs

**Comment by Gameslinx** [comment]
would be nice if your brain started working in ksp and bothered to do a very simple search in your KSP folder but no blame the mod and not yourself

Logs are found in Kerbal Space Program (KSP.log)
Or KSP\Logs\Kopernicus\Latest.zip

**Comment by zambino12** [comment]
> would be nice if your brain started working in ksp and bothered to do a very simple search in your KSP folder but no blame the mod and not yourself
> 
> Logs are found in Kerbal Space Program (KSP.log)
> Or KSP\Logs\Kopernicus\Latest.zip

dude really ur gonna be a fucking dick come on there is no need to be a complete cunt

**Comment by zambino12** [comment]
[LOG 16:48:45]: Logger "Kopernicus" was created
[LOG 16:48:45]: Injector.Awake(): Begin
[LOG 16:48:52]: [Kopernicus] RuntimeUtility Started
[LOG 16:48:52]: StarLightSwitcher.Awake(): Begin
[LOG 17:05:36]: Injector.OnDestroy(): Complete
there i looked in the wrong place ARE U FUICKING HAPPY U CUNTS

**Comment by Gameslinx** [comment]
The irony of your comment. Please be civilised about this and your problem may get solved.

Please send your KSP.log and Kopernicus.log and I will look for the error. Please also tell me what planet mods are installed.

**Comment by zambino12** [comment]
kerbal exoplanets,kerbaluni,and kerbal galaxtremaster and i wasnt trying to be a dick with the issue title shis and im not blaming the mod

**Comment by Gameslinx** [comment]
Please send me the two log files I asked for. 
It's likely those mods are not compatible with each other. Start off with one, and add the next one so you know which ones work together and which ones don't.

**Comment by zambino12** [comment]
this is it i hope [LOG 16:48:52]: Logger "Kopernicus.Runtime" was created
[LOG 16:52:27]: [Kopernicus] Fixed SpaceCenterCamera

**Comment by zambino12** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3438666/KSP.log)

**Comment by Gameslinx** [comment]
Correct log, but you have way too many mods installed for me to reliably traipse through all of that abomination for exceptions.

My advice would be to start over. Pick a planet mod, see if it loads. Then add another. Then add your other mods afterwards. As I'm on mobile I don't have the time to spend half an hour on that log. I might be able to help later but you have far too many mods installed. I can't guarantee the problem is only the planet mod and not a whole host of other issues.

This issue is left open for others to reply, but I'm off for the night.

**Comment by LapisNator101** [comment]
Zambino the issue I a second person found leads to the issue being in firespitter, please post your issue here: https://github.com/snjo/Firespitter/issues/new

**Comment by zambino12** [comment]
> Zambino the issue I a second person found leads to the issue being in firespitter, please post your issue here: https://github.com/snjo/Firespitter/issues/new

wait do i have firesspitter i dont remember adding it

**Comment by LapisNator101** [comment]
yes you have firespitter : [LOG 10:51:52.510] Load(Assembly): mods/Firespitter/Plugins/Firespitter
Both firespitter and FShangarExtender are breaking kopernicus

**Comment by zambino12** [comment]
> yes you have firespitter : [LOG 10:51:52.510] Load(Assembly): mods/Firespitter/Plugins/Firespitter
> Both firespitter and FShangarExtender are breaking kopernicus

huh thats weird because when i look where i placed all of my mods i dont see those two?

**Comment by LapisNator101** [comment]
it's most likely a firespitter.dll file, it will be at the bottom of your gamedata.

**Comment by zambino12** [comment]
> it's most likely a firespitter.dll file, it will be at the bottom of your gamedata.

i dont see ay dll files in my gamedata folder

**Comment by DeltaDizzy** [comment]
> i dont see ay dll files in my gamedata folder

Your KSP.log says that you have ModuleManager.3.0.7.dll in your gamedata.

**Comment by zambino12** [comment]
> > i dont see ay dll files in my gamedata folder
> 
> Your KSP.log says that you have ModuleManager.3.0.7.dll in your gamedata.

yeh but thats not the firespitter dll or the fshangar dll

**Comment by LapisNator101** [comment]
also module manager 3.0.7 is outdated and that is why deltadizzy pointed it out. MM 4.0.2 is the latest version

**Comment by zambino12** [comment]
> also module manager 3.0.7 is outdated and that is why deltadizzy pointed it out. MM 4.0.2 is the latest version

oh well shit i thought i installed the latest one FFS

**Comment by DeltaDizzy** [comment]
You have installed most, if not all of your mods wrong. It looks like they are in `Kerbal Space Program/GameData/mods/`. Mods should be installed directly into gamedata or they will not work.

**Comment by zambino12** [comment]
> You have installed most, if not all of your mods wrong. It looks like they are in `Kerbal Space Program/GameData/mods/`. Mods should be installed directly into gamedata or they will not work.

im confused when im installing mods i goto my ksp folder and put them into the gamedata folder is that not where im supposed to put my mods>?????????????

**Comment by LapisNator101** [comment]
"mods" the folder shouldn't exist it everything in "mods" should be in gamedata

**Comment by zambino12** [comment]
> "mods" the folder shouldn't exist it everything in "mods" should be in gamedata

i dont see a mods folder there in the gamedata folder because when i click the gamedata folder all my mods are there in the gamedata folder not mods so im hella confused

**Comment by LapisNator101** [comment]
can you use the snipping tool to screenshot your gamedata?

**Comment by DeltaDizzy** [comment]
You are putting them inside a mods folder inside GameData.
Your GameData:
```
GameData
|----mods
|--------mod1
|--------mod2
|---------etc.
```
What GameData should look like:
```
GameData
|----mod1
|----mod2
|----etc.
```

**Comment by zambino12** [comment]
> You are putting them inside a mods folder inside GameData.
> Your GameData:
> 
> ```
> GameData
> |----mods
> |--------mod1
> |--------mod2
> |---------etc.
> ```
> 
> What GameData should look like:
> 
> ```
> GameData
> |----mod1
> |----mod2
> |----etc.
> ```

ok i understand that is showing that but im still confused when i look in the ksp.log it shows WAy more mods that i actually have

**Comment by DeltaDizzy** [comment]
Well in that case, try moving all your mods out of the `mods` folder, delete KSP.log, and restart the game. If the error is still there, post the new KSP.log and a screenshot of your gamedata.

**Comment by zambino12** [comment]
> Well in that case, try moving all your mods out of the `mods` folder, delete KSP.log, and restart the game. If the error is still there, post the new KSP.log and a screenshot of your gamedata.

yeah ok but i dont HAVE a mods folder only gamedata folder

**Comment by DeltaDizzy** [comment]
Delete your KSP.log file, restart the game (and let it load until it gets to the main menu), and post the new KSP.log file here.

**Comment by zambino12** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3438746/KSP.log)

**Comment by zambino12** [comment]
> Delete your KSP.log file, restart the game (and let it load until it gets to the main menu), and post the new KSP.log file here.

ok done

**Comment by DeltaDizzy** [comment]
You appear to have moved them out of `mods` and into several new folders. This is just as bad. I think the easiest way forward would be to remove all your mods and start over. You can use this to help:
![](https://i.imgur.com/iM6U0zA.png)

**Comment by zambino12** [comment]
> You appear to have moved them out of `mods` and into several new folders. This is just as bad. I think the easiest way forward would be to remove all your mods and start over. You can use this to help:
> ![](https://camo.githubusercontent.com/4d2f3a42595586a301187a8c4d822b8b4d3b0e01/68747470733a2f2f692e696d6775722e636f6d2f694d3655307a412e706e67)

what about the squad and squad expainsions is that apart of a dlc i dont remeber anymore

**Comment by DeltaDizzy** [comment]
Squad is the base game, keep that where it is. SquadExpansions contains the DLCs, so keep that too.

**Comment by zambino12** [comment]
> > You appear to have moved them out of `mods` and into several new folders. This is just as bad. I think the easiest way forward would be to remove all your mods and start over. You can use this to help:
> > ![](https://camo.githubusercontent.com/4d2f3a42595586a301187a8c4d822b8b4d3b0e01/68747470733a2f2f692e696d6775722e636f6d2f694d3655307a412e706e67)
> 
> what about the squad and squad expainsions is that apart of a dlc i dont remeber anymore

ok i deleted everything and reinstalled them and i still have the same problem

**Comment by DeltaDizzy** [comment]
Alright. Can you post your KSP.log and a screenshot of your gamedata folder?

**Comment by zambino12** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3438766/KSP.log)
![kerbal](https://user-images.githubusercontent.com/47878215/62001068-09b1f880-b0ad-11e9-8969-334100367352.PNG)

**Comment by DeltaDizzy** [comment]
so. TimeControl, SCANsat, and ModuleManager look correct. However, the rest is still wrong. When you install a mod, just drag it into GameData. After that you are done. Do not try to organize anything into folders, just copy them in as-is. Let's start over one more time. If, after reinstalling them again according to what I have just said, yous till have the error, [follow the instructions here](https://forum.kerbalspaceprogram.com/index.php?/topic/110912-how-to-installing-mods/). Now I must leave for the night. I hope you get it working!

**Comment by zambino12** [comment]
> Alright. Can you post your KSP.log and a screenshot of your gamedata folder?

done


> so. TimeControl, SCANsat, and ModuleManager look correct. However, the rest is still wrong. When you install a mod, just drag it into GameData. After that you are done. Do not try to organize anything into folders, just copy them in as-is. Let's start over one more time. If, after reinstalling them again according to what I have just said, yous till have the error, [follow the instructions here](https://forum.kerbalspaceprogram.com/index.php?/topic/110912-how-to-installing-mods/). Now I must leave for the night. I hope you get it working!

but there are all called gamedata or extras thats it
