### ISSUE TITLE
Solar panel charging too much from far-away stars

### ISSUE THREAD

**Issue by Tonas1997** [Kopernicus/Kopernicus#372]
As stated in the title, my solar panels get extremely high charge rates from far-away stars. I'm running KSP 1.6.1 with a now-abandoned, 1.3.1-compatible exoplanet system pack. For reference, this pack has its starts orbiting the Sun, so it doesn't seem to be a reparenting issue.

![screenshot31](https://user-images.githubusercontent.com/43859708/62483375-5da89580-b7af-11e9-9049-4d6d69856054.png)

Here, the panel is tracking Alpha Centauri A, a star with a semi-major axis of 1.908121e+12 meters. You can see, in the upper-right corner, a charge rate of -0.45 EC/s. Alpha Centauri was just _slightly_ above the horizon, resulting in a really shallow receiving angle - and this to bring the point home on just how stupidly high the charge rate is vs. what it should be.

Config for that star, taken from the ModuleManager cache:
`Body
{
	name = AlphaCentauriA
	cacheFile = RealExoplanets/Cache/AlphaCentauriA.bin
	Template
	{
		name = Sun
	}
	Orbit
	{
		referenceBody = AlphaCentauri
		period = 2.52004e+9
		inclination = 235.286
		eccentricity = 0.5179
		semiMajorAxis = 1.610421e+12
		longitudeOfAscendingNode = 192.486
		argumentOfPeriapsis = -17.143
		meanAnomalyAtEpoch = 0
		epoch = -2344386240
		color = 1,1,1,1
	}
	Properties
	{
		displayName = Alpha Centauri A
		description = Alpha Centauri A is a G-type main-sequence star and is the primary star of the Alpha Centauri system.
		sphereOfInfluence = 1.496e+11
		radius = 853378500
		mass = 2.1879e+30
	}
	ScaledVersion
	{
		Light
		{
			sunlightColor = RGBA(255, 255, 255, 255)
			scaledSunlightColor = RGBA(255, 255, 255, 255)
			IVASunColor = RGBA(255, 255, 255, 255)
			luminosity = 2065.84
			sunAU = 123599840256
			sunLensFlareColor = 0.0, 0.0, 0.0, 1.0
			IntensityCurve
			{
				key = 0 0.9 0 0
				key = 8e+9 0.75 0 0
				key = 8e+10 0 0 0
			}
			ScaledIntensityCurve
			{
				key = 0 0.9 0 0
				key = 8e+9 0.75 0 0
				key = 8e+10 0 0 0
			}
			IVAIntensityCurve
			{
				key = 0 0.82 0 0
				key = 8e+9 0.675 0 0
				key = 8e+10 0 0 0
			}
			brightnessCurve
			{
				key = 0 0.105 0 25
				key = 0.01 0.2 0.5 0.5
				key = 1 0.6 0.5 0.5
				key = 5 3 0 0
				key = 10 3 0 0
				key = 50 2 0 0
				key = 200 2 0 0
			}
		}
		Material
		{
			emitColor0 = RGBA(255, 208, 129, 255)
			emitColor1 = RGBA(255, 187, 79, 255)
			sunspotColor = RGBA(114, 53, 24, 255)
			rimColor = RGBA(255, 255, 255, 255)
			rimPower = 1.29
			rimBlend = 2.5
		}
		Coronas
		{
			Corona
			{
				rotation = 3
				speed = 9
				updateInterval = 5
				scaleLimitX = 5
				scaleLimitY = 5
				scaleSpeed = 0.8
				Material
				{
					texture = REX_Textures/PluginData/corona_kg.dds
					inverseFade = 2.553731
				}
			}
		}
	}
}`

As a side note, has the SolarPowerCurve module been deprecated?

Runnning Kopernicus 1.6.1-9

EDIT: yikes, I thought this would format the code block. Sorry!

**Comment by Shiolle** [comment]
Are you running Kerbalism by any chance? I've noticed you have showed the same craft in this [issue](https://github.com/Kerbalism/Kerbalism/issues/87). If you are using sstu-and-solar branch of Kerbalism, it's likely to be their issue.

**Comment by Sigma88** [comment]
for getting a comment block rather than a comment line you should use 3 \`

example:
<pre>
```
yourcode
```
</pre>

**Comment by Tonas1997** [comment]
> Are you running Kerbalism by any chance?

Yep, you're absolutely correct. I found out I had (have!) two separate solar panel issues caused by both Kerbalism and Interstellar Extended; will close the issue here as it has been traced to another mod.
