### ISSUE TITLE
Game not fully starting

### ISSUE THREAD

**Issue by Liontamer45** [Kopernicus/Kopernicus#374]
Whenever I run a mod with a dependence on Kopernicus, the game will not load past the "Loading screen" after the slideshow. I have tried removing the mod with the dependency and it seems to work just fine. But this is not a single mod issue, I've tried it with multiple mods that have this dependency and all of them end up with the same result. Help would be greatly appreciated. I am running the 1.7.3 Kopernicus mod by the way.

Thank you all!

**Comment by democat3457** [comment]
Can you send the Logs-Kopernicus.zip?

**Comment by Sigma88** [comment]
@Liontamer45  sorry I didn't reply earlier, are you still experiencing this issue?

**Comment by Liontamer45** [comment]
I believe so, I haven't tried it in a while, and the game updated so I
couldn't tell you to be honest

**Comment by Sigma88** [comment]
with the current KSP (v1.8.1) there is no kopernicus available, we are working on an update at the moment.

if you are using KSP 1.7.3 you can try Kopernicus 1.7.3-2, this version works fine as long as you install planet packs that are up-to-date 

if you decide to try again and experience other issues feel free to reopen this

**Comment by Liontamer45** [comment]
I'll try the next time I'm off from work, I'll have to find a way to revert
it back to 1.7.3 on steam to try and see if it works. Thanks though!

**Comment by Sigma88** [comment]
There is an optio in steam for signin up to open betas, you can use that to revert to 1.7.3

I think it's something like:

Right click on the game in the library, select properties, choose the "betas" tab, and then choose 1.7.3 from the dropdown menu

**Comment by Liontamer45** [comment]
Alright then, I'll test the 1.7.3-2 Koperenicus tomorrow. I'll respond if
it doesn't work, thank you for your help.

**Comment by Liontamer45** [comment]
just a quick question, where to i drop the mods? in GameData, or the folder marked GameData inside the GameData folder?

**Comment by DeltaDizzy** [comment]
You extract Kopernicus and its dependencies and place then in KSP's GameData Folder.
So KSP's GameData should have:
* Kopernicus
* ModularFlightIntegrator
* ModuleManager
* Squad

**Comment by Liontamer45** [comment]
what are the dependencies that are needed?

**Comment by DeltaDizzy** [comment]
ModularFlightIntegrator and ModuleManager, both of which are bundled with Kopernicus.

**Comment by Liontamer45** [comment]
should i remove the ones i already have in the GameData folder?

**Comment by DeltaDizzy** [comment]
Yes.

**Comment by Liontamer45** [comment]
alright then and should the GameData file inside the GameData file have mods in it? or should i move them out into where i'm placing this stuff?

**Comment by DeltaDizzy** [comment]
all mods should be directly inside the KSP gamedata folder

**Comment by Liontamer45** [comment]
alright then thanks a lot! as you can tell, i'm not very skilled at modding my game XD

**Comment by DeltaDizzy** [comment]
You only get better with practice!

**Comment by Liontamer45** [comment]
you got me there! again, thanks for the help!

**Comment by Liontamer45** [comment]
ok one last thing XD so when i download a mod such as a planet pack or something with multiple folders in the GameData folder, do i move all the folders into the GameData folder of KSP?

**Comment by DeltaDizzy** [comment]
All mod folders should go in KSP's GameData, yes

**Comment by Liontamer45** [comment]
alright then! thank you so much! should i ask for your discord or something if i have anymore questions so that we don't keep taking up a forum thread to just chat?

**Comment by DeltaDizzy** [comment]
SRB-X#6973

**Comment by Liontamer45** [comment]
sent
