### ISSUE TITLE
KSP 1.7.3 says latest Kopernicus is incompatible

### ISSUE THREAD

**Issue by psychonaut25** [Kopernicus/Kopernicus#375]
AVC is warning me that the latest version of Kopernicus is incompatible with KSP 1.7.3, and KSP itself is advising me, "Kopernicus will not work on this version of KSP!  Please don't try to open your savegames!"

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3528539/KSP.log)
Apologies, I know I have a lot of mods installed.  I've only recently updated all the way from 1.3.1 to 1.7.3 and I'm still working through which mods still work, which don't and should be removed, and which I need to manually update rather than through CKAN.

Any help would be appreciated.

**Comment by Poodmund** [comment]
From your log it looks as though you are using Kopernicus VERSION: 1.7.0.1, please remove and install the latest version for your version of KSP.

For KSP 1.7.3, you can grab the latest version, at the moment, here: https://github.com/Kopernicus/Kopernicus/releases/latest

**Comment by psychonaut25** [comment]
Odd, I could swear I already updated to the latest version.  Seems to be working now though, so thanks... onward to updating to the latest Outer Planets Mod!
