### ISSUE TITLE
Kopernicus doesnt work

### ISSUE THREAD

**Issue by NickiPotenzo** [Kopernicus/Kopernicus#376]
I can not understand what is going wrong in the download process. Can you help? 

Files and logs:
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3538655/Logs-Kopernicus.zip)

P. S Pardon me for English, translate through Google)

**Comment by NickiPotenzo** [comment]
I think I understand what needs to be done, now I'll try to do as you said. But I don't think it's gonna work. If I will be able to apply again ?

**Comment by Monniasza** [comment]
Logs: [output_log.zip](https://github.com/Kopernicus/Kopernicus/files/3613551/output_log.zip) and 
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/3613552/KSP.zip)

**Comment by Sigma88** [comment]
we might need more info than that.

[here](https://forum.kerbalspaceprogram.com/index.php?/topic/181547-0/&page=27&tab=comments#comment-2793409)'s a full list of what we might need


also, from your log it seems like you are running KSP from

```C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\```

I would suggest you to make a copy of the KSP install into another folder, windows is known to create issues for mods installed under \'ProgramFiles\'
