### ISSUE TITLE
Kopernikus wont change the solar system

### ISSUE THREAD

**Issue by Fredde104** [Kopernicus/Kopernicus#379]
I just installed ksp 1.6.1 with RSS, rescaled by myself with the corresponding values from "Rescale!". 
The game loads just fine, but on startup I get this message:
![image](https://user-images.githubusercontent.com/54629665/63857912-d234b580-c9a4-11e9-93e5-bad41f926ac2.png)

My GameData directory as well as all versions of my installed mods. I have not used rescale, only the corresponding values for SD. I have also tried both my versions of Kopernikus (1.6.1-2 & 1.6.1-9), and both gives the same result.
![image](https://user-images.githubusercontent.com/54629665/63858498-dd3c1580-c9a5-11e9-9efe-3af5b74298f4.png)

Log file: 
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3551047/Logs-Kopernicus.zip)

**Comment by Sigma88** [comment]
try with SD v0.10.2 rather than v0.10.1, not sure which version of Kopernicus would be better

**Comment by Fredde104** [comment]
This solved my problem, but it broke my clouds..

**Comment by Fredde104** [comment]
Got clouds to work. Isuue solved

**Comment by Sigma88** [comment]
good to hear!
