### ISSUE TITLE
Game doesn't load past loading screen.

### ISSUE THREAD

**Issue by SuperTemich2005** [Kopernicus/Kopernicus#380]
I've backed up my career before installing kopernicus and planet pack
First of all, my KSP ver is 1.7.3, Kopernicus is 1.7.3-1, i've tried CKAN version and manual installation, none of them worked. Here are mods imma using:
Making history DLC
Breaking ground DLC
Graphical mods(EVE, SVT, SVE, Scatterer)
Kopernicus, with New Horizons
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3562740/Logs-Kopernicus.zip)

**Comment by SuperTemich2005** [comment]
All of them is up to date.

**Comment by SuperTemich2005** [comment]
Ah, mind that i've installed the game on W:\ drive. It's "W:\" just because it's funkier than "E:\"

**Comment by SuperTemich2005** [comment]
Ahem, it seems that my game doesnt work because of new horizons planetpack won't work with kopernicus *tech*, tho i thought i am using kopernicus. Maybe i'd close issue if game launch

**Comment by chengyufei** [comment]
i've got the same problem

**Comment by democat3457** [comment]
Please open a new issue, it likely isn’t the same because this issue is so broad. Also, send your logs found in the Logs folder

**Comment by Sigma88** [comment]
logs are not always enough,

sometimes more files might be necessary.

if you want help, [here](https://forum.kerbalspaceprogram.com/index.php?/topic/181547-0/&page=27&tab=comments#comment-2793409)'s a guide of what kind of files we need to look into most issues
