### ISSUE TITLE
im having the same issue that i had before. Koperucius not load because of an exception in the loading process.

### ISSUE THREAD

**Issue by grinches** [Kopernicus/Kopernicus#381]
I had gotten it working not to long ago (not sure how I did)  but now its giving the same error as it had before. 

Tell me any files I need to link and ill do so asap.

**Comment by DeltaDizzy** [comment]
It should give you a list of files in the popup. Please upload those.

**Comment by grinches** [comment]
[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/3586989/ModuleManager.zip)
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/3586990/Logs-Kopernicus.zip)

[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/3586992/ModuleManager.zip)

i think this is all but tell me if i missed something.

**Comment by grinches** [comment]
i had had this problem my first time installing. then i  tried using the OPM visuals mod and i got the same error i had once had before

**Comment by grinches** [comment]
i found the problem thanks for the help tho

**Comment by Aquilux** [comment]
And so he commits the cardinal sin of online help requests: leaving future seekers clueless as to what the solution was, while frustrating them with the fact that one was found but the knowledge is lost to time.

**Comment by DeltaDizzy** [comment]
[You too have tried to grasp at the wisdom of the ancients.](https://xkcd.com/979/)
