### ISSUE TITLE
NullReferenceException when modifying PQS Mods of an existing body

### ISSUE THREAD

**Issue by ThunderousEcho** [Kopernicus/Kopernicus#389]
Here's a config it occurs on:
```
@Kopernicus:AFTER[Kopernicus] {
    @Body[Vall] {
        @PQS {
            Mods {
                VertexHeightMap {
                    index = 2
                    deformity = 1
                }
            }
        }
    }
}
```

and here's the error (from KSP.log):
```
[EXC 20:17:22.593] NullReferenceException: Object reference not set to an instance of an object
	PQSMod_VertexHeightMap.OnVertexBuildHeight (.VertexBuildData data)
	PQS.Mod_OnVertexBuildHeight (.VertexBuildData data, Boolean overrideQuadBuildCheck)
	PQS.GetSurfaceHeight (Vector3d radialVector, Boolean overrideQuadBuildCheck)
	PQS.GetSurfaceHeight (Vector3d radialVector)
	PQS.UpdateVisual ()
	PQS.StartSphere (Boolean force)
	PQS.Start ()
```

I also tried removePQSMods=true and recreating all of the PQS Mods, and that didn't work either.

Also, are you guys looking for contributors?

**Comment by democat3457** [comment]
The VertexHeightMap PQSMod needs to have a `map` specified. It should be the file path to your heightmap. All PQSMods also need an `order` value dictating the order PQSMods are applied in and an `enabled` value dictating whether the PQSMod should be applied.

**Comment by Sigma88** [comment]
if I am understanding what you want to do you are trying to modify an existing PQSMod on vall

specifically [this one](https://github.com/Kopernicus/kittopia-dumps/blob/master/Configs/Vall.cfg#L277-L286)

in order to do that it's not enough to specify the index, you also need the name

so your cfg should be:

```
@Kopernicus:AFTER[Kopernicus] {
    @Body[Vall] {
        @PQS {
            Mods {
                VertexHeightMap {
                    name = _Height
                    index = 1
                    deformity = 1
                }
            }
        }
    }
}
```

index only works for PQSMods that have the same name, also the indexes start from 0 so to edit the second PQSMod named "_Height" you need to use `index = 1`

**Comment by ThunderousEcho** [comment]
Ah, thanks!

**Comment by ThunderousEcho** [comment]
Sigma88, that didn't work. I got the same error.

**Comment by ThunderousEcho** [comment]
Some extra info: Vall appears unchanged in map view, and is invisible in non-map view from a 10km orbit.

**Comment by democat3457** [comment]
I don't think there is actually an `index` value... Your PQSMod should have a `map` path leading to the heightmap file and an `order` value.
```
@Kopernicus:AFTER[Kopernicus] {
    @Body[Vall] {
        @PQS {
            Mods {
                VertexHeightMap {
                    name = _Height
                    map = Path/To/Your/HeightMap.extension
                    offset = 0
                    scaleDeformityByRadius = false
                    deformity = 1000 // Or however much you want it to be
                    order = 95
                    enabled = true
                }
            }
        }
    }
}
```
Do note that this adds another heightmap underneath Vall's original heightmap.

**Comment by ThunderousEcho** [comment]
So, if I want to decrease a heightmap from 1000 to 1, I need to add one of these with deformity -999?

Also, toy solar system was able to edit existing mods- why is this no longer possible?

**Comment by Sigma88** [comment]
>I don't think there is actually an index value
there used to be one, not sure if it was removed.

>So, if I want to decrease a heightmap from 1000 to 1, I need to add one of these with deformity -999?
>Also, toy solar system was able to edit existing mods- why is this no longer possible?

this should be possible, but we have been experiencing bugs with that so this might be the same issue

**Comment by Sigma88** [comment]
is this issue still happening? or can it be closed?

**Comment by ThunderousEcho** [comment]
I haven't checked. Did you change something?

**Comment by Sigma88** [comment]
yes, some of the changes in 1.7.3-2 should have addressed this

**Comment by ThunderousEcho** [comment]
I have not had a chance to check yet, but I still plan to.

**Comment by Sigma88** [comment]
closing this for now because it was addressed in a past update, but feel free to reopen it if there are still issues with our solution
