### ISSUE TITLE
1.8.0

### ISSUE THREAD

**Issue by RusWolf** [Kopernicus/Kopernicus#392]
new branch for 1.8.0  work propertly with Real Solar System mod, but  cannot use  Hi-Res  Textures from RSS. 

if file  /RealSolarSystem/RSS_TerrainDetailPresets.cfg  present,    Kopernicus   show error on main screen, and log file  Kopernicus.log contain string 
"[Kopernicus]: Configuration.Loader: Failed to load Preset: RSS_High"

After deleting /RealSolarSystem/RSS_TerrainDetailPresets.cfg  game start without any errors

---------------------------
typical file /RealSolarSystem/RSS_TerrainDetailPresets.cfg  contain:
@Kopernicus:FOR[RealSolarSystem]
{
	Preset
	{
		name = RSS_High
		displayName = RSS High Res
		PLANET
		{
			name = Kerbin
			minDistance = 8
			minSubdivision = 1
			maxSubdivision = 10
		}
		PLANET
		{
			name = Moon
			minDistance = 8
			minSubdivision = 1
			maxSubdivision = 10
		}
		PLANET
		{
			name = Mercury
			minDistance = 8
			minSubdivision = 1
			maxSubdivision = 9
		}
.....
       }
}

--------------------

i know, 1.8.0 version  in develop,  but maybe this data help you.

**Comment by StollD** [comment]
The Kopernicus.log file will only tell you where to look for the error, it won't tell you the actual issue. If you upload the `Logs/Logs-Kopernicus.zip` thats gets generated after you got the error and closed the game, I can take a look at what is failing exactly.
