### ISSUE TITLE
Scatters animations

### ISSUE THREAD

**Issue by Vortinium** [Kopernicus/Kopernicus#394]
I have a request, I do not know where to put it so i put it in the issues sections.
I really enjoy creating world with Kopernicus and I would like to scatter objects with animation but the scatter system only support .obj files.
It would be really great if we can spawn scatters with animation, think alien plants moving on a planet.
Is it possible to support fbx files in a future release ?

**Comment by JadeOfMaar** [comment]
The solution that I know of is to produce .mu files (KSP part models) and place these using PQSCity. As .mu they will get to contain animations and other neat things like emissive textures, optimized colliders, and maybe even plumes. But setting up coordinates via PQSCity has its own tedious work involved and can make your config file swell up large. Spawning lots of scatter can hurt your CPU. Spawning lots of animated scatter can likely hurt your CPU more.

This isn't a definite yes/no answer but is merely a heads-up so you have an idea of a working alternate means while you wait.

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
