### ISSUE TITLE
[feature request] Cubemaps support for maps

### ISSUE THREAD

**Issue by jrodrigv** [Kopernicus/Kopernicus#396]
This is a request to support cubemaps to load textures instead of just single texture files, this way it would be possible to load surface maps with much higher details.

(EVE repository could be a nice place to look because already support cubemaps for clouds layers, etc)

**Comment by Sigma88** [comment]
I might take a look at this but I can't promise you anything, it would require changing the shaders for the planets and this might cause issues for other mods

**Comment by jrodrigv** [comment]
Thanks @Sigma88 I don't see it as a replacement but as an additional way to define the texture in case that a mod wants to use this approach.

**Comment by Sigma88** [comment]
ok, so we talked a bit about this and we came to the conclusion that it wouldn't be worth to add this into kopernicus for the following reasons:

- ksp requires equirectangular maps so we would need to convert internally from cubemap to equirectangular
- the maximum resolution for any equirectangular map is 16384x8192
- there is a number of free tools that allow you to convert from cubemap to equirectangular

basically, there would be no real gain from using cubemaps over equirectangular maps other than the fact that it would be easier for people that generate their maps directly in the cubemap format.
And in that case, converting those maps to equirectangular is extremely easy and would result in a better efficiency on the kopernicus side

for the records, here is one of the free tools you could use for this purpose:

https://360toolkit.co/convert-cubemap-to-spherical-equirectangular


if you have any other reasons for needing cubemaps let me know

**Comment by jrodrigv** [comment]
Thanks @Sigma88 for the answer. 

I guess than then the best option would be then to do a feature request to KSP Dev team to support Cubemaps ( as EVE already supports for clouds) and thus support much high resolution maps : like the RVE 64k clouds textures or 64k surface map textures, etc

(Off topic: I'm excited to see all your dev commits, really looking forward for a KSP 1.9. Thanks again for all your efforts)

**Comment by Sigma88** [comment]
Yes, the only solution on our side would be to rewrite the shaders in order to use cubemaps. However the code for those shaders is not available since they are custom ksp shaders, so I have no way of knowing how they work.

**Comment by jrodrigv** [comment]
Sounds good. Closing the issue now :)
