### ISSUE TITLE
Problems 1.8.1

### ISSUE THREAD

**Issue by Audric1320** [Kopernicus/Kopernicus#402]
Kopernicus not working in KSP 1.8.1
Someone have a solution ?

**Comment by DeltaDizzy** [comment]
Kopernicus is version locked and has not yet been updated for 1.8.x yet. Either wait for Kopernicus to update or roll back to 1.7.3.

**Comment by Audric1320** [comment]
Okay :'( waiting the update

**Comment by Sigma88** [comment]
I think we can close this issue.
As soon as a new version is released I can notify you if you want
