### ISSUE TITLE
Assitance requested please.

### ISSUE THREAD

**Issue by pslytely-psycho** [Kopernicus/Kopernicus#403]
I don't know how I did it, (I'm new to git) as I was only browsing around and learning how to navigate the various pages looking for information about the latest builds and somehow I apparently 'forked' something up. I now we a Pslytely.Psycho fork of Kopernicus in my browser.
I am the least qualified person to do such a thing and need to find out how to kill it with fire.
BTW, I love this mod and all you who work so hard on it. I am an infant at coding however and never meant to 'branch' this project.

**Comment by DeltaDizzy** [comment]
go to the settings tab at the top (other tabs include Code, Pull Requests, Actions, Projects, etc) and scroll all the way to the bottom to find the delete button.

**Comment by pslytely-psycho** [comment]
Thank you. nOOb mistake!
