### ISSUE TITLE
Kopernicus not compatible with KSP >=1.8

### ISSUE THREAD

**Issue by nufuk** [Kopernicus/Kopernicus#406]
The Loading screen is stuck here and won't do anything further.

![grafik](https://user-images.githubusercontent.com/16987213/71622975-a25b2000-2bd9-11ea-8bed-010c7eded421.png)

**Comment by DeltaDizzy** [comment]
Well firstly Kopernicus is version locked and has not been updated for 1.8 yet, so it wont work regardless.

**Comment by Sigma88** [comment]
happy new year guys 🎉 🎊 🎉 🍾 

when the new kopernicus is released you will find it here:
https://github.com/Kopernicus/Kopernicus/releases

no need to open an issue for this
