### ISSUE TITLE
Reparenting Kerbin using PostSpawnOrbit

### ISSUE THREAD

**Issue by linuxgurugamer** [Kopernicus/Kopernicus#407]
I'm running a 1.8 build of Kopernicus on KSP 1.8.1.  I'm not asking for support exactly, but writing this in case it's a bug.  If not, just say so and I'll be happy.

First, I've been running JNSQ with it for a few weeks, and it's absolutely GREAT!

The problem is with New Horizons.  I'm trying to get it updated with some changes to have it available for 1.8.1

The problem I'm having is that it gets to the main menu, but the menu is unresponsive.  Thinking it was a problem with NH, I tried the same files on a new 1.7.3 install with Kopernicus and it worked fine.

Among other changes, NH has the following fix: https://forum.kerbalspaceprogram.com/index.php?/topic/102776-13-kopernicus-new-horizons-v201-2jun17-its-back/&do=findComment&comment=3345797)

If you would like to test this yourself, you can get the current version of NH for 1.8 from here: https://github.com/linuxgurugamer/New_Horizons/tree/1.8

I've attached all the logs.  I found the following exception which I believe is the cause:

`Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at EventData`2+EvtDelegate[T,U]..ctor (EventData`2+OnEvent[T,U] evt) [0x00022] in <9d71e4043e394d78a6cf9193ad011698>:0 
  at EventData`2[T,U].Add (EventData`2+OnEvent[T,U] evt) [0x00000] in <9d71e4043e394d78a6cf9193ad011698>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.ApplyFlagFixes () [0x00001] in <77d43f76deb543388a275674f1be2a95>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.Start () [0x00026] in <77d43f76deb543388a275674f1be2a95>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object`
[NewHorizonsLog.zip](https://github.com/Kopernicus/Kopernicus/files/4033645/NewHorizonsLog.zip)

**Comment by linuxgurugamer** [comment]
I did a small test by disabling the calls where the above exception was happening (line 885-886 in RuntimeUtility.cs).  This time there was no exception, but the menu was still not accessable

**Comment by Sigma88** [comment]
try removing 
```			PostSpawnOrbit
			{
				referenceBody = NH/Sonnah
			}```
from kerbin, see if that changes anything

**Comment by Sigma88** [comment]
I removed that lines and the NH from your fork works fine for me

I think it might be because PostSpawnOrbit uses the 'name' rather than the 'indentifier' so you might need to change it to 
```
PostSpawnOrbit
{
	referenceBody = Sonnah
}
```

**Comment by linuxgurugamer** [comment]
Thank you @Sigma88 

I hope reports like this aren't a bother to the Kopernicus group.  I didn't know if it was a Kopernicus bug or a NH bug, thank you for finding the problem

**Comment by Sigma88** [comment]
Most bug reports we get are bugs in the way people use kopernicus rather than bugs in kopernicus itself.

I always tell players to report bugs to the planet pack devs rather than here, this would help because this way we don't end up with a thousand bug reports that are all the same.
However if you are a planet pack dev opening an issue here is fine.

And nobody listens to me anyway because we still end up with a thousand duplicate issues that are not even kopernicus' bugs :rofl:

**Comment by Sigma88** [comment]
turns out this is actually a Kopernicus bug

**Comment by Sigma88** [comment]
I just tested this with a simple cfg and I can confirm PostSpawnOrbit doesn't work anymore if you try to reparent Kerbin

```
@Kopernicus:FINAL
{
	@Body[Kerbin]
	{
		PostSpawnOrbit
		{
			referenceBody = Squad/Jool
		}
	}
}```

**Comment by Sigma88** [comment]
thanks @linuxgurugamer  for fixing this issue!

**Comment by Sigma88** [comment]
by the way, could you take a look if you can find a fix for the broken SpaceCenter scene? the sky clearly doesn't work properly but I'm not really sure what is going on there
