### ISSUE TITLE
infinite loading screen

### ISSUE THREAD

**Issue by Epicgamer001** [Kopernicus/Kopernicus#408]
so anyways, i get a planet pack and enter the game. when it gets to the black screen with the solar system in between the launch loading thing and the main menu, it just freezes there. the planets spin around the sun very fast, and i can hear the music in the background. however, i can't do anything with a loading screen in my way!
i have tried multiple solutions. different versions of Kopernicus, different versions of the game to go along with that, verifying KSP files, getting different planet packs, every fix that i could find online, i tried, but still, nothing works. i know it is Kopernicus that causes it because i can get any other mod i have to work, even planet packs. but whenever i install Kopernicus it gets stuck on the loading screen.

**Comment by DeltaDizzy** [comment]
Did the KSP and Kopernicus version numbers match every time? It isnt just the KSP or Kopernicus version that matters, but if they match or not.

**Comment by Epicgamer001** [comment]
yes, they did match

**Comment by Sigma88** [comment]
If it's a big planet pack it might need to generate the cache files for the planets which may take a lot

To help us look into this, please delete the "Logs" folder that you have in your ksp folder (not in GameData, directly into the ksp folder) then run the game with as little mods as possible. Ideally just kopernicus, the planet pack, and all dependancies

Then upload here the zip file you will find in the Logs folder (or in Logs/Kopernicus I can't remember now)

**Comment by Epicgamer001** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4069179/Logs-Kopernicus.zip)
here is the file!

**Comment by Epicgamer001** [comment]
> If it's a big planet pack it might need to generate the cache files for the planets which may take a lot
> 
> To help us look into this, please delete the "Logs" folder that you have in your ksp folder (not in GameData, directly into the ksp folder) then run the game with as little mods as possible. Ideally just kopernicus, the planet pack, and all dependancies
> 
> Then upload here the zip file you will find in the Logs folder (or in Logs/Kopernicus I can't remember now)

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4069181/Logs-Kopernicus.zip)
the file you said you need

**Comment by Galileo88** [comment]
> [LOG 19:24:50]: Exception Was Recorded: Object reference not set to an instance of an object
  at PQSMod_VertexHeightMap.OnVertexBuildHeight

Looks like the body named "Adeon" is failing to load its height map. make sure the height map is present in the correct folder, and check the path in the cfg to also ensure its pointing to the file. check for misspellings as well.

**Comment by Sigma88** [comment]
```
map = TheWorldBeyond/TWB_TraverseSystem/Textures/PluginData/Adeon_Height.png
```

this is the texture that seems to fail loading

**Comment by Epicgamer001** [comment]
> > [LOG 19:24:50]: Exception Was Recorded: Object reference not set to an instance of an object
> > at PQSMod_VertexHeightMap.OnVertexBuildHeight
> 
> Looks like the body named "Adeon" is failing to load its height map. make sure the height map is present in the correct folder, and check the path in the cfg to also ensure its pointing to the file. check for misspellings as well.

![wut3](https://user-images.githubusercontent.com/59853659/72571067-77c4c480-3873-11ea-863f-31c7ef59b6dc.PNG)
seems to be in there. checked config for the planets and it seems to be able to load the heightmap. should i jusr redownlaod the mod? and even in that case, why did no other mods work?

**Comment by Epicgamer001** [comment]
> > > [LOG 19:24:50]: Exception Was Recorded: Object reference not set to an instance of an object
> > > at PQSMod_VertexHeightMap.OnVertexBuildHeight
> > 
> > 
> > Looks like the body named "Adeon" is failing to load its height map. make sure the height map is present in the correct folder, and check the path in the cfg to also ensure its pointing to the file. check for misspellings as well.
> 
> ![wut3](https://user-images.githubusercontent.com/59853659/72571067-77c4c480-3873-11ea-863f-31c7ef59b6dc.PNG)
> seems to be in there. checked config for the planets and it seems to be able to load the heightmap. should i jusr redownlaod the mod? and even in that case, why did no other mods work?

![oof5](https://user-images.githubusercontent.com/59853659/72571307-16e9bc00-3874-11ea-86f2-083e6498bdf2.PNG)

the place where it says to load the heightmap at

**Comment by Sigma88** [comment]
### your install:
![image](https://user-images.githubusercontent.com/12640834/72572802-f47f8f00-38c3-11ea-839e-006269cf1f90.png)

### what the mod expects:
![image](https://user-images.githubusercontent.com/12640834/72572917-5cce7080-38c4-11ea-9bcd-669a5d749458.png)

the directories do not match, you probably installed TWB incorrectly. I don't really know how the installation process of that mod is supposed to work because I have never tried it.

but the folder `TWB_TraverseSystem` should go inside `GameData/TheWorldBeyond/` not inside `GameData/` directly

**Comment by Epicgamer001** [comment]
> ### your install:
> ![image](https://user-images.githubusercontent.com/12640834/72572802-f47f8f00-38c3-11ea-839e-006269cf1f90.png)
> 
> ### what the mod expects:
> ![image](https://user-images.githubusercontent.com/12640834/72572917-5cce7080-38c4-11ea-9bcd-669a5d749458.png)
> 
> the directories do not match, you probably installed TWB incorrectly. I don't really know how the installation process of that mod is supposed to work because I have never tried it.
> 
> but the folder `TWB_TraverseSystem` should go inside `GameData/TheWorldBeyond/` not inside `GameData/` directly

oh, that makes sense. ill try to re-add the mods that way and see if it works

**Comment by Epicgamer001** [comment]
so far cant figure out how to get the planets to appear, but not the issue here. so, im closing this as the game loads now
