### ISSUE TITLE
Kopernicus 1.8 does not appear to spawn the ice sheets at Kerbin Poles in stock system.

### ISSUE THREAD

**Issue by R-T-B** [Kopernicus/Kopernicus#410]
It could be another mod I have loaded, but most of them are official releases
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4082086/Logs-Kopernicus.zip)
 at this point.  I feel the issue may lie with Kopernicus.  I've been toying with it in an experimental save for a while and this is the only proper bug I've noticed, attatching a log.  Sorry, no screenshots, but where you expect there to be an ice shelf there is only ocean.

Sorry for not gathering more data but I thought you could use the heads up.  The build I am using does not incorporate the recent fixes to HazardousOcean, it was built earlier from this tree:

https://github.com/Kopernicus/Kopernicus/tree/8e58c43964ce5e1b11426f0f72773ea311a369c2

I doubt the problem is fixed however.  I see no commits to suggest such.  I looked around myself but have not the slightest clue where it's going wrong.  Hopefully you have a better idea, heh.

**Comment by R-T-B** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4082089/Logs-Kopernicus.zip)

**Comment by Sigma88** [comment]
I have loaded kopernicus on 1.8.1 and this is the result:
<table>
<tr><th>Stock</th><th>Kopernicus</th></tr>
<tr>
<td><img src ="https://user-images.githubusercontent.com/12640834/72972906-8ad41900-3dcc-11ea-9f1d-8977c70bdd82.png" /></td>
<td><img src ="https://user-images.githubusercontent.com/12640834/72972963-a3443380-3dcc-11ea-81d2-c7fc1a08e879.png" /></td>
</tr>
</table>

for reference, the coordinates are 74.5N 67.5W

(74.5, -67.5)

if you can provide a way to reproduce your issue I will look further into it

**Comment by R-T-B** [comment]
Hmmm...  that is odd.

It must be something with the Astronomers config, I am guessing?  I'm unsure what precisely would cause it though, it looks fairly innocent.  Sorry I can't be of more use, but this save game with the issue was deleted and I am presently playing my main game in 1.7.3.  I'd look that direction if you are willing.

**Comment by Sigma88** [comment]
sure, just ping me on discord and I'll pm you a zip file

I will also take a look at this astronomers config, from your description it sounds like an issue with LandControl since that is the PQS_Mod used to generate the icecaps

**Comment by Sigma88** [comment]
yes, it seems like your Kerbin node has a LandControl that probably messes up with the stock one

**Comment by Sigma88** [comment]
given that the texture reference are in the folder
`mainTex = KSPRC/Terrain/pinetree`
I assume this is probably caused by KSPRC, I am still not sure if the behaviour is correct (meaning this would be a bug in KSPRC) or if the behaviour is not what it is supposed to be (meaning this would be a bug in Kopernicus)

**Comment by Sigma88** [comment]
I tested Kopernicus with the LandControl node from your log file, the ice caps loaded fine, so this might be a different issue

**Comment by R-T-B** [comment]
I believe astronomers uses only the textures from KSRPC, the install procedure tells you if using it to through out everything that's not an image.

I will try loading this up for replication tomorrow.  I will try and let you know how it goes.  Would do it now but it's nearly 2am where I am!  Tired, heh.

**Comment by Sigma88** [comment]
to be honest, it looks like both KSPRC and AVP are adding the same nodes to the planet

if you look at the MM cachefile you will see that Kerbin's node has everything in duplicate.

I suppose those two mods are not meant to be used together, if you want to use them together you will need to contact the relative mod authors and ask for one of them to provide compatibility

**Comment by Sigma88** [comment]
# duplicated stuff in the ScaledVersion node
![image](https://user-images.githubusercontent.com/12640834/72977913-bc9dad80-3dd5-11ea-8281-56f39001cf2b.png)
# duplicated stuff in the PQS node
![image](https://user-images.githubusercontent.com/12640834/72977938-cf17e700-3dd5-11ea-90d4-448d0b89951b.png)
# duplicated SpaceCenter node
![image](https://user-images.githubusercontent.com/12640834/72977962-d939e580-3dd5-11ea-9c4c-0f5e6f36c070.png)

**Comment by R-T-B** [comment]
> to be honest, it looks like both KSPRC and AVP are adding the same nodes to the planet
> 
> if you look at the MM cachefile you will see that Kerbin's node has everything in duplicate.
> 
> I suppose those two mods are not meant to be used together, if you want to use them together you will need to contact the relative mod authors and ask for one of them to provide compatibility

I just checked thinking I may have bothced the install procedure.  KSRPC is indeed just image files, though.  SVT is the more likely culprit, as it was not supposed to be installed at all!  Thanks, I feel like a doofus!  Still, I appreciate the help diagnosing my mod stack if nothing else.  Closing.
