### ISSUE TITLE
 Kopernicus crash with Real Solar System

### ISSUE THREAD

**Issue by HoBoIs** [Kopernicus/Kopernicus#418]
I have installed Real Solar System, Realism overhaul, and RP-1, with their recommended mods with CKAN. As Real Solar System's dependency I installed Kopernicus. (And some mods suggested by them) When KSP starts I get a warning:

> Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your savegame is NOT recommended, because the missing planets could corrupt it and delete your progress.
> Please contact the planet pack author or the Kopernicus team about the issue and send them a valid bugreport, including your KSP.log, your ModuleManager.ConfigCache file and the folder Logs/Kopernicus/ from your KSP root directory  

When I want to create a new game or try to load one the screen stays black and the loading icon stays forever. 

Log files: 
[KSP_log.zip](https://github.com/Kopernicus/Kopernicus/files/4128349/KSP_log.zip)

I woud be qreatfull if someone had a solution.

**Comment by Sigma88** [comment]
I can't see anything wrong in your logs, try starting from a clean KSP, add just 
RSS
RSS Textures
Kopernicus
ModularFlightIntegrator
modulemanager

run the game and see if that works, then start adding back the other mods untill you find the bug.

**Comment by HoBoIs** [comment]
It doesn't work. Only if I uninstall RSS too. (I uninstalled everything with ckan so other modd are still in the chache but I don't think it is relevant.) I run KSP 1.7.3.2594 linux if this is relevant.

**Comment by Sigma88** [comment]
hmmmm linux might be an issue since I don't have a way to reproduce it

can you upload the various logs  from your last test?

**Comment by HoBoIs** [comment]
[KSP_log.zip](https://github.com/Kopernicus/Kopernicus/files/4129097/KSP_log.zip)
This is the most recent log (with thiese 5 mods) 
And an additional wierd info: if I press F5 while it shows me the black screen it offers me to choose a save name. After that the loading icon goes away, the upper menu shows up, so I can do time warp too, but the other parts of the screen are black so I can't start building ships. If I press esc the pause menu shows up (as it shoud) but when I try to go back to main menu it freezes. (black with load icon)

**Comment by Sigma88** [comment]
If you try a different planet pack does it work?

**Comment by Sigma88** [comment]
Like gpp or jnsq, assuming gpp is up to date with 1.7.3 (I can't remember)

**Comment by HoBoIs** [comment]
jnsq does the same. gpp's max ksp version is 1.4 so I didn't try that

**Comment by democat3457** [comment]
In the `Kopernicus.log` it says it failed to load the preset `RSS_High`, but in `KSP.log` it says `failed to load Asteroid: RSS_High`

**Comment by Sigma88** [comment]
what happens if you remove the presets?

good catch @democat3457  I managed to miss that somehow

**Comment by HoBoIs** [comment]
I removed everything, and reinstalled KSP. At first it was working, with the 5 mods above, but then I installed RO and RP-1 and it broke. so I uninstalled them, but it still don't work with the same 5 mods it worked fine.

**Comment by democat3457** [comment]
Delete the file `GameData/RealSolarSystem/RSS_TerrainDetailPresets.cfg`

**Comment by HoBoIs** [comment]
Thanks, it seams problem is solved.
