### ISSUE TITLE
Problem with the menu

### ISSUE THREAD

**Issue by rogerwang86** [Kopernicus/Kopernicus#419]
I was stuck in the menu. Game doesn't crash. But all bottoms are failure. My game setting language is Chinese. Maybe that cost problem?

**Comment by LapisNator101** [comment]
No I've been getting the same issue, strange thing is, I got in once when trying my own planet pack, my language in the game is english, I can't post an exact error as their are too many. 
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4155570/KSP.log) I can give you the log, tho.

**Comment by Sigma88** [comment]
can you upload the zip file that is generated by kopernicus in KSP/Logs/
?

**Comment by rogerwang86** [comment]
> can you upload the zip file that is generated by kopernicus in KSP/Logs/
> ?
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4155836/Logs-Kopernicus.zip)
Here you go.

**Comment by StollD** [comment]
Remove all plugins that were not built for 1.8 from GameData. It is pretty much guaranteed that they will cause things to fail, so using them won't be supported.

ModuleManager would actually list the broken dlls in the log, if you wouldn't have an old version of it installed. KSP will load the old and broken version, and you won't get the warnings in the log.

**Comment by rogerwang86** [comment]
> Remove all plugins that were not built for 1.8 from GameData. It is pretty much guaranteed that they will cause things to fail, so using them won't be supported.
> 
> ModuleManager would actually list the broken dlls in the log, if you wouldn't have an old version of it installed. KSP will load the old and broken version, and you won't get the warnings in the log.

THX, problem solved.
