### ISSUE TITLE
Issue with Kopernicus and ToBoldlyGo

### ISSUE THREAD

**Issue by crazyduck33** [Kopernicus/Kopernicus#421]
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/4174634/Kopernicus.log)
[ModuleManager.log](https://github.com/Kopernicus/Kopernicus/files/4174635/ModuleManager.log)
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4174636/KSP.log)

If i use To Boldy Go to generate a Universe i get Errors from Kopernicus for different Planets.

The Error is always the same
"[Kopernicus]: Configuration.Loader: Failed to load Body: Amallon VI: Value cannot be null.
Parameter name: type"

only the planet name change. 
Which Value cannot be null? There is no Parameter with the Name Type.

**Comment by Sigma88** [comment]
We need you to upload the zip file that is generated by kopernicus in your "Logs" folder to get all the informations about this issue

**Comment by crazyduck33** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4174651/Logs-Kopernicus.zip)

Sure

**Comment by eckithebull** [comment]
I also tried to use "To boldly go" and have the same issue. The problem seems to be with planets with atmosphere. TBG "copies" the existent planets and makes "new" ones. When i look into Kopernicus log, it always stops/fails when it loads a planet with atmosphere. I tried this several times with new galaxies and always the first "atmosphere planet" stops the whole mod. I understand when you don't have the time to look for other mods, but maybe you can give a hint what has changed with atmosphere definition.

**Comment by Sigma88** [comment]
Have you reported this to the TBG devs?

**Comment by StoneBlue** [comment]
Sigma88, yes... eckithebull posted on the TBG thread. Not sure how soon a reply wiill be tho. Looks like the dev (seanth) hasnt been on in a couple months, and IIRC, wasnt very active before that. vOv

**Comment by Sigma88** [comment]
From the looks of it this seems to be a TBG issue. However I cannot recall any changes to the atmospheric stuff, so either this issue was present in 1.7.3 as well or it's an issue with 1.8.1 that will probably require changes in TBG.

**Comment by Sigma88** [comment]
I will try to take a closer look when I have some more free time, but if there is no TBG dev at the moment there might be no solution

**Comment by eckithebull** [comment]
Thank you for the answer! It still helps if YOU don't know of changes with the atmosphere handling. Maybe i can figure it out for myself. If so, i let you know.

BTW, without your Kopernicus mod, playing KSP makes no real sense for me! Please continue your epic work to give us a whole galaxy of planets to reach!

**Comment by crazyduck33** [comment]
Its not the Atmosphere , its the VertexHeight. 

If i remove VertexHeightMap,VertexHeightNoise,VertexHeightNoiseVertHeight,VertexSimplexHeightMap
from the TBG galaxy.cfg for one of the not working planets it works fine and create the Planet. 

Are there any Changes how this Values work in 1.8.x ?

**Comment by Sigma88** [comment]
Yes, they need all their values to be defined however the game will crash.

**Comment by Sigma88** [comment]
Well, not the game, but the planets will fail somewhere and everything will just stop and kopernicus will not load the system properly

**Comment by Sigma88** [comment]
Idk how tbg works, but this should be a pretty easy fix

**Comment by crazyduck33** [comment]
Did something changed how this Values are defined, named or work since the update to KSP 1.8.x?

Cause same galaxy.cfg from TBG works with Kopernicus in 1.7.3 in 1.8.x it fails.

**Comment by Sigma88** [comment]
yes there were changes I would assume on stock that now make that fail

I didn't work on that side of the code but I don't see any reason why we would have changed the behaviour of kopernicus just randomly

**Comment by crazyduck33** [comment]
i see in github that there was a commit that changed value type from double to int32 for vertex values. 

Could this the reason why it does not work in ksp 1.8.x? If yes could you give me a hint if this could causes the problem if TBG still work with "double" ?

**Comment by Sigma88** [comment]
I am not sure why those changes were made, I don't think it was me.

I will look into that as soon as I get some free time

**Comment by crazyduck33** [comment]
thanks that woudl be great i currently test around with different values to see if i can find what is missing.

**Comment by crazyduck33** [comment]
ok looks like after removing this part from the TBG config the planet was createt 

"
                VertexHeightOffset﻿
                {
                    enabled = true
                    order = 2
                    offset = -5000 //match up with other deformities
                }﻿﻿
"

**Comment by Sigma88** [comment]
is this resolved?

**Comment by crazyduck33** [comment]
yes it is.

If someone remove the VertexheightOffset from TBG config so its not used during galaxy creation Kopernicus works without problems.

The File that must be changed in TBG is pqsTmp.txt. The entry starts in line 85 and ends in line 90.
If people remove it it works fine with kopernicus.
