### ISSUE TITLE
Create a node

### ISSUE THREAD

**Issue by cjournois** [Kopernicus/Kopernicus#422]
## Hi,
I have an error with my KSP 1.8.1. I have a lot of mod and I really don't know where to go to fix it.

### My mods list:
> KSP: 1.8.1 (Win64) - Unity: 2019.2.2f1 - OS: Windows 10  (10.0.0) 64bit
> ClickThroughBlocker - 0.1.9.5
> TexturesUnlimited - 1.5.9.24
> Toolbar - 1.8.0.5
> USI Tools - 1.3
> ToolbarControl - 0.1.9.4
> Animated Decouplers - 1.4.2
> Antenna Helper - 1.0.7.1
> B9 Part Switch - 2.13
> Bluedog Design Bureau - 1.6.2
> Chatterer - 0.9.98.2686
> CommNetAntennasInfo - 2.4
> Community Category Kit - 4.3
> Community Resource Pack - 1.3
> CommunityTechTree - 3.4
> Contract Configurator - 1.28
> Contract Pack: CommNet Relays - 2.1
> Contract Pack: Kerbal Academy - 1.3.0.1
> Contract Pack: Bases and Stations - 3.7.0.1
> Contract Pack: Tourism Plus - 1.5.2
> CryoEngines - 1.1
> CryoTanks - 1.4
> AdvancedTextures - 1.8.1
> DeployableEngines - 1.0
> DiRT - 1.8
> DistantObjectEnhancement - 2.0.2
> DynamicBatteryStorage - 2.1
> Environmental Visual Enhancements - 1.8.0.2
> Eve-Optimized-Engines - 2.0.3
> Firespitter - 7.15
> HeatControl - 0.5
> HideEmptyTechTreeNodes - 1.1.2
> ImprovedChaseCamera - 1.6.4
> JanitorsCloset - 0.3.7
> Kronometer - 1.7.1.1
> JNSQ - 0.9
> KAS - 1.5.7239.36651
> KerbalAtomics - 1.1
> Kerbal Engineer Redux - 1.1.7.1
> Kerbalism - 3.5
> Kerbalism - 3.5
> Kerbal Joint Reinforcement - 4.1.15
> KerbalKonstructs - 1.8.1.15
> Kerbal Inventory System - 1.24.7279.41031
> Kopernicus - 1.8.1.1
> KSP-AVC Plugin - 1.4.1.1
> Lights Out - 0.3.0.1
> ModularFlightIntegrator - 1.2.7
> Docking Port Alignment Indicator - 6.8.5
> NearFutureAeronautics - 1.0.4
> NearFutureConstruction - 1.2.1
> NearFutureElectrical - 1.1
> NearFutureExploration - 1.0.4
> NearFutureLaunchVehicles - 1.3
> NearFutureProps - 0.6.1
> NearFuturePropulsion - 1.2
> NearFutureSolar - 1.1
> NearFutureSpacecraft - 1.3
> Kerbal Planetary Base Systems - 1.6.10
> PlanetShine - 0.2.6.3
> ProbesBeforeCrew - 2.8
> RealPlume - Stock - 3.0.1
> ReStock - 1.0.3
> ReStockPlus - 1.0.3
> RetractableLiftingSurface - 0.2
> SCANsat - 1.1.8.14
> StageRecovery - 1.9.2.1
> StationPartsExpansionRedux - 1.3
> Surface Mounted Lights - 1.15.7274.38376
> TAC Fuel Balancer - 2.21.5.1
> Tracking Station Evolved - 1.0.5
> Kerbal Alarm Clock - 3.12
> Alternate Resource Panel - 2.9.3
> Transfer Window Planner - 1.7.2
> Tundra Exploration - 1.7.1
> Tundra Technologies - 1.7.1
> Malemute Rover - 1.3
> Waypoint Manager - 2.8.1
> Kerbal Actuators - 1.7.1
> World Stabilizer - 0.9.7

### My error:
When I create a node, my game throw a lot of errors and sometimes a  crash happen in the next minutes. In all cases my game is buged after, i suppose it is due to the spam of the errors and it can't do another treatment.

![beforeNode](https://user-images.githubusercontent.com/44445341/74610677-a5f92680-50f5-11ea-9950-63ba7fefc08a.png)
![afterNode](https://user-images.githubusercontent.com/44445341/74610678-a8f41700-50f5-11ea-8cd0-bddbe2c64b04.png)

#### Firsts lines of errors:
```
[LOG 19:44:00.793] SCREENSHOT!!
[EXC 19:44:04.728] NullReferenceException: Object reference not set to an instance of an object
	SoftMasking.SoftMask.UpdateMaskParameters () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	SoftMasking.SoftMask.OnEnable () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.GameObject:SetActive(Boolean)
	KSP.UI.Screens.Flight.NavBallBurnVector:LateUpdate()
[EXC 19:44:04.778] TypeLoadException: Could not resolve type with token 01000030 (from typeref, class/assembly Kopernicus.RequireConfigType, Kopernicus.Parser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
	System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.RuntimeType.IsDefined (System.Type attributeType, System.Boolean inherit) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	SoftMasking.MaterialReplacer.IsMaterialReplacerType (System.Type t) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	SoftMasking.MaterialReplacer+<>c.<CollectGlobalReplacers>b__3_1 (System.Type t) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].MoveNext () (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
	System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].ToList () (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
	System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
	SoftMasking.MaterialReplacer.get_globalReplacers () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	SoftMasking.SoftMask..ctor () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Object:Instantiate(GameObject)
	KSP.UI.Screens.Flight.NavBallBurnVector:UpdateDVStageMarkers()
	KSP.UI.Screens.Flight.NavBallBurnVector:LateUpdate()
[EXC 19:44:04.885] NullReferenceException: Object reference not set to an instance of an object
	SoftMasking.SoftMask.SoftMasking.ISoftMask.GetReplacement (UnityEngine.Material original) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	SoftMasking.SoftMaskable.GetModifiedMaterial (UnityEngine.Material baseMaterial) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.UI.Graphic.get_materialForRendering () (at <22fd67f59718453e9250a6de1843ef8b>:0)
	UnityEngine.UI.Graphic.UpdateMaterial () (at <22fd67f59718453e9250a6de1843ef8b>:0)
	UnityEngine.UI.Image.UpdateMaterial () (at <22fd67f59718453e9250a6de1843ef8b>:0)
	UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at <22fd67f59718453e9250a6de1843ef8b>:0)
	UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at <22fd67f59718453e9250a6de1843ef8b>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Canvas:SendWillRenderCanvases()
[EXC 19:44:04.886] NullReferenceException: Object reference not set to an instance of an object
	SoftMasking.SoftMask.UpdateMaskParameters () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	SoftMasking.SoftMask.OnWillRenderCanvases () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.Canvas.SendWillRenderCanvases () (at <995dfdbde1cd400b889d70b872baaaf8>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[...]
```

[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/4210571/Logs.zip)

**Comment by cjournois** [comment]
### Delete and launch:
- Kerbal Konstructs (with OSSNTR)
- Textures Unlimited

#### Same problem

**Comment by cjournois** [comment]
### I found a fix ...

I delete **KEX-EVAFootprints-1.7.0-1**

#### And i have no error yet ;)

**Comment by cjournois** [comment]
I found a fix ...

I delete KEX-EVAFootprints-1.7.0-1
I have no idea how i missed this mod, a lost day ...
And i have no error yet ;)

**Comment by Sigma88** [comment]
all the KEX mods have not been updated to 1.8.1 

it is very likely that they will give problems
