### ISSUE TITLE
Solar panels generate twice as much power as they should

### ISSUE THREAD

**Issue by Carnildo** [Kopernicus/Kopernicus#427]
With Kopernicus 1.8.1-1, Module Manager 4.1.3, and Modular Flight Integrator 1.2.7 installed in an otherwise-stock KSP 1.8.1 with Breaking Ground, solar panels generate twice as much power as they say they do.  For example, if a SP-W 3x2 panel shows an "Energy Flow" level of 1.6, the "Electric Charge" value in the "Resources" panel will be going up by 3.2 EC per second.

**Comment by Sigma88** [comment]
I managed to reproduce the issue and I have already proposed a change that should fix it

**Comment by Sigma88** [comment]
Nope, need more time to fix this properly

**Comment by Sigma88** [comment]
#429  should fix this issue for good

**Comment by R-T-B** [comment]
Multistar math is fixed, so closing.
