### ISSUE TITLE
IMPORTANT: GAME MENU BUTTONS IN 1.8.1 DO NOT WORK

### ISSUE THREAD

**Issue by Snipdog26** [Kopernicus/Kopernicus#430]
HELP.

**Comment by nathan88fox** [comment]
I can confirm this issue. It is happening to me aswell.

**Comment by nathan88fox** [comment]
https://gyazo.com/c62907a780b8fcfd285290186cde4412

**Comment by DeltaDizzy** [comment]
![](https://cdn.discordapp.com/attachments/293387889126014976/696897458768314458/report.png)

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
