### ISSUE TITLE
Loading Screen Issue

### ISSUE THREAD

**Issue by nathan88fox** [Kopernicus/Kopernicus#431]
I am having an issue with my loading screen to access the facility view/menu after you open a game. I have isolated it to Kopernicus and I believe it might be relating to this screenshot I took. 
https://gyazo.com/c62907a780b8fcfd285290186cde4412

**Comment by nathan88fox** [comment]
To better clarify, I do not have a planetary system mod.

**Comment by DeltaDizzy** [comment]
You should probably do as the screenshot says and send the logs. It popup does not mention this, but all of the mentioned files can be found in the "Logs" folder inside your main KSP folder.

**Comment by nathan88fox** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4441638/Logs-Kopernicus.zip)

**Comment by nathan88fox** [comment]
I believe that might be it I'm not sure.

**Comment by DeltaDizzy** [comment]
Thats it, and what mods do you have that affect Eve? (the planet)

**Comment by nathan88fox** [comment]
[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/4441646/Logs.zip)

Here is a zip of the "Logs" under Kerbal Space Program

**Comment by nathan88fox** [comment]
All the mods I have right now are the EVE mod, SVE mod, Scatterer, and "Distant Object Enhancement".

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
