### ISSUE TITLE
Issue with loading my planet pack

### ISSUE THREAD

**Issue by BrotherBilo** [Kopernicus/Kopernicus#432]
I am trying to use Kopernicus to install the Real Solar system mod, I'm using correct versions and I have the requirements for RSS, However It isn't working. This is because at launch, KSP gives me a pop up saying something on the lines of "Kopernicus was not able to load the custom planetary system due to an exception in the loading process." Can someone Please tell me what I'm doing wrong or explain the correct way of using Kopernicus to get such mods in my game. It would be a major help, as I have been scratching my head wondering what I had been doing wrong for days now.

**Comment by BrotherBilo** [comment]
I've seen other reports about this issue but no really solution for the problem as I do have a Planet adding mod installed.

**Comment by DeltaDizzy** [comment]
The popup should say something about logs. Please upload those files.

**Comment by BrotherBilo** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4454015/Logs-Kopernicus.zip)

**Comment by DeltaDizzy** [comment]
Can you show me a screenshot of your GameData folder, including the address bar?

**Comment by BrotherBilo** [comment]
![ice_screenshot_20200409-011541](https://user-images.githubusercontent.com/63385517/78860231-aaf49b00-79ff-11ea-9ccf-aaa960213e66.png)
![ice_screenshot_20200409-011351](https://user-images.githubusercontent.com/63385517/78860242-b2b43f80-79ff-11ea-960c-4f3a5dee667a.png)
![ice_screenshot_20200409-011327](https://user-images.githubusercontent.com/63385517/78860410-235b5c00-7a00-11ea-9c37-de65397fc2b1.png)

**Comment by BrotherBilo** [comment]
The last two screenshots are not in order

**Comment by DeltaDizzy** [comment]
1. You didnt install modulemanager properly it should be just the dll file that comes with kopernicus)
2. You should never create container folders inside GameData (like "Kopernicus Gamedata" and "GameData" in your screenshot for example.)
3. You seem to have extracted a mod's innards directly into GameData ("Icons", "Plugins", "Agencies", and "Flags")

Fix your GameData structure and it should work.

**Comment by BrotherBilo** [comment]
Can you screenshot what a correct Gamedata folder would look like as a reference?

**Comment by BrotherBilo** [comment]
![ice_screenshot_20200409-014309](https://user-images.githubusercontent.com/63385517/78861725-81d60980-7a03-11ea-827d-17bf9dab586b.png)
Also it does seem that i do have Module Manager but I'm looking into this right now

**Comment by BrotherBilo** [comment]
Also on an unrelated note, how do i fix pink lines piercing my spacecraft, like this as an example 
![ice_screenshot_20200410-000730](https://user-images.githubusercontent.com/63385517/78961405-54e72c80-7abf-11ea-8936-c8e7b96bd0bb.png)

**Comment by DeltaDizzy** [comment]
That comes from outdated versions of PlanetShine.

**Comment by BrotherBilo** [comment]
Okay thanks. May you please send a screenshot of a proper Gamedata/Kopernicus folder that would serve as a reference for me to reorganize and get my planet pack to work?

**Comment by DeltaDizzy** [comment]
Here is an example with only Minor Planets Expansion installed.
![](https://cdn.discordapp.com/attachments/293387889126014976/698035673885835264/unknown.png)
This is what the Kopernicus folder has in it:
![](https://cdn.discordapp.com/attachments/293387889126014976/698036040174403604/unknown.png)

**Comment by BrotherBilo** [comment]
Thanks i'm going to be trying this now

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
