### ISSUE TITLE
Using Jool template prohibits making surfaces work on planets

### ISSUE THREAD

**Issue by Astatine5985** [Kopernicus/Kopernicus#433]
So I tried to make a surface for jool, and used a %PQS noded to make one. The PQS node generated a surface which isn't possible to get a landed status with a vessel(the surface is fully colidable and landable but landing on it won't give you landed status for your vessel it still says flying low for some reason) 
Looked up in the log file and found "hasSolidSurface = False" I think usinng jool template forces this output.
So, is there a property setting that enables the hasSolidSurface when using a jool template? If there isn't could you fix it that it is possible to add working solid surface to planets using jool template and jool it self?

**Comment by R-T-B** [comment]
Is this still happening, and is there a way around it if so or is it intended behavior? (Asking other Kopernicus devs the latter part of that question).

**Comment by Astatine5985** [comment]
> Is this still happening, and is there a way around it if so or is it intended behavior? (Asking other Kopernicus devs the latter part of that question).

It still happens but there are ways getting around it

**Comment by R-T-B** [comment]
Thanks for getting back to  me.  Not sure if we'll fix or not, but it's good to know the status.
