### ISSUE TITLE
Kopernicus doesn't load KerbalGalaxy 3

### ISSUE THREAD

**Issue by Chri7s** [Kopernicus/Kopernicus#434]
So I installed Kopernicus with KerbalGalaxy3 but it won't load the planetary system - I looked up the logs but could not find the issue, any way you guys can help me?

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4509542/Logs-Kopernicus.zip)

**Comment by RJVB09** [comment]
It looks like KerbalGalaxy3 is 1.7.x only, so you'll have to wait until it updates.
Or you can switch to 1.7 with kopernicus 1.7.x

**Comment by Chri7s** [comment]
That, I forgot to check, thank you!
