### ISSUE TITLE
Can't load Kopernicus in 1.9.1

### ISSUE THREAD

**Issue by xXDarkNovaXx** [Kopernicus/Kopernicus#436]
I can't load the mod in 1.9.1 I also tried to do an override via AVC but it didn't work
Is there anything I can do to work around it or fix it?
I need the Mod för use other Mods

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4566978/Logs-Kopernicus.zip)

![Screenshot_229](https://user-images.githubusercontent.com/22129313/80853408-f4b45800-8c30-11ea-941c-42e78195d89f.png)

![Screenshot_228](https://user-images.githubusercontent.com/22129313/80853305-0ba67a80-8c30-11ea-8663-a57398af31b3.png)

**Comment by democat3457** [comment]
It's not meant for 1.9.1 use. You either have to wait for a new release or build it yourself (not recommended)

**Comment by Dexter9313** [comment]
> [...] build it yourself (not recommended)

What do you expect to happen when built against 1.9.1 ?

**Comment by haltwise** [comment]
@Dexter9313 it's been working pretty well for me after just rebuilding locally against 1.9.1. My entire RSS/RO/RP1 modset has been way more stable this way than it was on 1.8, actually. Haven't left Earth yet, though, so there may be problems with other bodies.

**Comment by Dexter9313** [comment]
@haltwise Did you build the master branch or the PanelsFix2 branch ?

**Comment by Dexter9313** [comment]
I tested OPM after rebuilding against 1.9.1. I noticed normal maps on gas planets and no atmosphere rendering. I didn't investigate much but using scatterer and EVE "fixed" everything at least visually. I could land on Tekto so the ground is there.

**Comment by kingcosmo** [comment]
@haltwise is there a doc on building Kopernicus manually?  I'd like to try building for 1.9.1 also.

**Comment by democat3457** [comment]
download and install visual studio and the necessary libraries, download kopernicus from source from github, open the sln file in kopernicus, build project @kingcosmo

**Comment by Burn-E99** [comment]
If you can't get the build to work on your machine, I've built it and tested it with Galileo's Planet Pack and it seems to be working just fine.  Download it from [here](https://burne99.com/downloads/).

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
