### ISSUE TITLE
modded planets not loading (ksp 1.8.1)

### ISSUE THREAD

**Issue by volcanohyena** [Kopernicus/Kopernicus#437]
I was trying to install the mod Interstellar Adventure (Revived) on ksp 1.8.1 and it said that kopernicus was incompatible with my current version. So I got another version of kopernicus which led to the planets not loading again.
here is my log for when I loaded it
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4592774/KSP.log)
the kopernicus mods I used were 'Kopernicus' (which came with Galaxies unbound) and 'Kopernicus Expansion' (which came with interstellar adventure)

**Comment by democat3457** [comment]
Kopernicus Expansion does not work on 1.8.1, therefore throwing an error. (i.e., Interstellar Adventure (Revived) is not compatible with 1.8.1 :/) You can try removing Kopernicus Expansion and seeing if that works, but it won't be the full experience - you'd have to downgrade to 1.7.3.

**Comment by LapisNator101** [comment]
As far as I know Interstellar adventure revived doesn't need kopernicus Expansion, however,  IA-Revived 1.2.9 is completely broken in 1.7.3 and up so you have to click the changelog button in spacedock and download IA-Revived 1.2.1 and once downloaded fix the sigismunda folder typo.
![Capture](https://user-images.githubusercontent.com/52894956/81322984-9086ff00-9049-11ea-9599-ae69d4faecdc.JPG)

**Comment by democat3457** [comment]
Thank you for the clarification :heart:

**Comment by volcanohyena** [comment]
thanks! I managed to find a working copy of kopernicus for 1.8 though and it works fine with the planet mods

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.
