### ISSUE TITLE
Recompile for 1.9.1

### ISSUE THREAD

**Issue by Vaughnzo** [Kopernicus/Kopernicus#439]
Does anyone here have a recompiled version of Kopernicus that that they could send me that works with KSP 1.9.1? Thanks!

**Comment by Burn-E99** [comment]
I've built it on my machine and tested with Galileo's Planet Pack and it seems to be working. Download it from [here](https://burne99.com/downloads/).

**Comment by smatass4132** [comment]
hey thanks this worked for me for the outer planets mod

**Comment by Vaughnzo** [comment]
> I've built it on my machine and tested with Galileo's Planet Pack and it seems to be working. Download it from [here](https://burne99.com/downloads/).

**Comment by Vaughnzo** [comment]
Thanks for the kopernicus it worked thanks so much
