### ISSUE TITLE
Object reference not set to instance of an object

### ISSUE THREAD

**Issue by warhammercasey** [Kopernicus/Kopernicus#441]
Made a new 1.8.1 RP-1 game and KSP will load, then when it gets to the title screen, I can hear the music in the background but its stuck on the black screen with the little loading animation with the solar system in the corner. Checking KSP.log kopernicus is constantly spitting out this:
`[EXC 02:59:46.124] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <0882401b48d84227ad9c2bbcf4ce8401>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4681049/KSP.log)

**Comment by RJVB09** [comment]
I'm not sure but, an infinite/stuck loading screen most of the time means that a file path is incorrect.

**Comment by R-T-B** [comment]
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.
