### ISSUE TITLE
Cubemaps?

### ISSUE THREAD

**Issue by Its-Just-Luci** [Kopernicus/Kopernicus#442]
Is there any way we could get cubemap support for kopernicus? Currently the file size limit on DDS images (and therefore ksp) is 16k resolution, allowing cubemaps would raise this to over 64k resolution.

**Comment by DeltaDizzy** [comment]
This has been asked already in https://github.com/Kopernicus/Kopernicus/issues/396, and the gist of it is that it has zero benefits without rewriting the planet shaders to use them.

**Comment by R-T-B** [comment]
If that's the case, I don't see a need then.  I'm going to declare this a "wontfix-enhancement" and close as part of a broader cleanup.
