### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by patrik12340** [Kopernicus/Kopernicus#443]
Hello!
When i try to load the game with after kerbin and the other required mods for it tha game writes the massage in the title i tried it on 2 different versions of the game and coudn't get it to work (i don't have money for it atm so its torrented) 

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4770028/Logs-Kopernicus.zip)

**Comment by democat3457** [comment]
It appears that you installed the mods incorrectly. Inside each folder that has a version name, there is a GameData folder. Put the contents of that folder inside your actual GameData folder.

**Comment by patrik12340** [comment]
oh sry than i'm just a retard anyway thx for help i will try it in a moment and get back to you :)

**Comment by Slimey489** [comment]
i also have this issue but i have installed seemingly correctly
[Uploading KSP.log…]()

**Comment by R-T-B** [comment]
Closing as invalid as part of a broader cleanup.  If you still have issues, please reopen another bug report.
