### ISSUE TITLE
cant get after kerbin to work

### ISSUE THREAD

**Issue by robot12457** [Kopernicus/Kopernicus#444]
i know im probably doing it wrong but ive looked and cant find any help, i get the "exception in the loading process" error. her are my files  
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/4841322/Logs-Kopernicus.zip)

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4841327/KSP.log)

**Comment by DeltaDizzy** [comment]
You didnt install After Kerbin correctly. It does not go inside the Kopernicus folder.
