### ISSUE TITLE
why kopernicus need ultra shader

### ISSUE THREAD

**Issue by dogevspenguin** [Kopernicus/Kopernicus#445]
i want kopenicus to be change=able

**Comment by crazyduck33** [comment]
Modified my version of Kopernicus so it does not need Ultra Shader setting anymore. Could not find any bugs with reverting this.

**Comment by DeltaDizzy** [comment]
If you want to use Kopernicus on 1.9, use Kopernicus Continued.

**Comment by democat3457** [comment]
https://github.com/prestja/Kopernicus/releases link btw

**Comment by dogevspenguin** [comment]
How to modified the mod
?

**Comment by R-T-B** [comment]
The latest release no longer have this issue, just look at config/Kopernicus_Config.cfg to change the requirement.
