### ISSUE TITLE
Exception in the loading process

### ISSUE THREAD

**Issue by Unkwn-43** [Kopernicus/Kopernicus#446]
I've seen that I'm not the first one to get this error, however, Kopernicus was working fine a few days ago. I had the Extrasolar mod installed and everything was fine, the secondary system loaded in and whatnot. I then decided I wanted to install the Beyond Home planet pack to replace the stock system and Kopernicus came up with the "exception" error. I then removed beyond home, but it still gave me the error! Even when I remove both planet packs, Kopernicus still gives me the error and I get an infinite loading screen when going into settings or loading a save. I've tried every single version of Kopernicus and nothing works except outright removing it. Another thing I changed was removing Astronomer's Visual Pack while installing beyond home, but I am pretty sure this has nothing to do with it.
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4910727/KSP.log)

**Comment by democat3457** [comment]
Looks like Anger from Beyond Home is loading incorrectly. Can you send the log for when you removed the planet packs?

**Comment by Unkwn-43** [comment]
So I started the game sans planetpacks and Kopernicus seems to get an error while loading Moho. 
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/4914769/Kopernicus.log)
(Moho log in Kopernicus) [Moho.Body.log](https://github.com/Kopernicus/Kopernicus/files/4914771/Moho.Body.log)
If needed, here is the KSP log
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/4914772/KSP.log)

**Comment by Unkwn-43** [comment]
As an added note, the error occurs while trying to load Moho also occurs when loading anger from beyond home. Kopernicus just says "argument cannot be null" and terminates itself before loading anything.

**Comment by democat3457** [comment]
> So I started the game sans planetpacks and Kopernicus seems to get an error while loading Moho.
> [Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/4914769/Kopernicus.log)
> (Moho log in Kopernicus) [Moho.Body.log](https://github.com/Kopernicus/Kopernicus/files/4914771/Moho.Body.log)
> If needed, here is the KSP log
> [KSP.log](https://github.com/Kopernicus/Kopernicus/files/4914772/KSP.log)

Sigma Dimensions appears to be modifying the planetary system, try removing that? Also, I'm pretty sure the Dimensions folder goes inside the Sigma folder.

**Comment by DeltaDizzy** [comment]
> Also, I'm pretty sure the Dimensions folder goes inside the Sigma folder.

That is correct.

**Comment by Unkwn-43** [comment]
It was either sigma dimensions or sigma skybox, but after removing those it worked.
