### ISSUE TITLE
How to modified kopernicus to not require ultra shader

### ISSUE THREAD

**Issue by dogevspenguin** [Kopernicus/Kopernicus#448]
As the title i seen some one do this

**Comment by DeltaDizzy** [comment]
Why modify Kopernicus when you could just get [Kopernicus Continued for 1.9.1](https://forum.kerbalspaceprogram.com/index.php?/topic/194936-191-kopernicus-continued/)?

**Comment by dogevspenguin** [comment]
No in KC it require ultra shader but i want to use low

**Comment by democat3457** [comment]
Kopernicus 1.9.1 and 1.10 no longer requires ultra shader, although it's greatly discouraged.

**Comment by R-T-B** [comment]
Yep, you don't need to modify the game, just modify config/Kopernicus_Config.cfg.  Should be easy.
