### ISSUE TITLE
Can't load planets.

### ISSUE THREAD

**Issue by Tequhella** [Kopernicus/Kopernicus#449]
Hi !
I'm using the mod Event Horizon but it doesn't works. I found that Kopernicus couldn't load Izetta properly. It seems the problem is with the shaders or something like that, but I have no idea where to fix it. And also for some reasons, my Event Horizon logs disappeared without saying anything ! Fortunately, I was able to get Izetta logs before that happened. The only mod I downloaded that changes planets environment is EVE but when I removed it I still got the same error.
I know my Kopernicus is not a stable because it's a version for KSP 1.10, but I'm sure there's something to be done to fix it.

[Izetta.Body.log](https://github.com/Kopernicus/Kopernicus/files/5003782/Izetta.Body.log)

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/5003778/Logs-Kopernicus.zip)

**Comment by DeltaDizzy** [comment]
Any issues with Kopernicus Continued should be reported to it's devs, this repo will likely see no further activity.

**Comment by Tequhella** [comment]
Yes you're right ! I'll see with them. Thx for answering.

**Comment by democat3457** [comment]
Btw opened issue at R-T-B/Kopernicus#16

**Comment by R-T-B** [comment]
Fixed long ago.
