### ISSUE TITLE
DLC?

### ISSUE THREAD

**Issue by Kerbinator-CN** [Kopernicus/Kopernicus#453]
Breaking Ground DLC features?
~~*For example, planting ice volcanoes on Enceladus?*~~

**Comment by R-T-B** [comment]
I've got to be entirely honest, I'm not entirely sure how to go about implementing them.  Anyone able to advise?  I assumed they were already supported at a basic level, honestly, but could be wrong.

**Comment by Kerbas-ad-astra** [comment]
I dug around in this and discussed my findings in #397.  The short version is that you can place Breaking Ground features on other planets with a Module Manager patch, but:

1. You will only be able to add ROCs (the internal name for the BG surface scatter features) that come from the planet's template (e.g. Enceladus uses the Mun as a template, so you could give it Mun Craters and Mun Rocks but not Vall Cryovolcanoes) unless you also install [MyRocksAreBiggerThanYours](https://github.com/StollD/MyRocksAreBiggerThanYours) -- it's a simple plugin, and there was some discussion of bringing it into Kopernicus, but currently it's an external dependency.
2. If a ROC_DEFINITION has a CELESTIALBODY block for a planet that doesn't exist, no ROCs show up anywhere, so be sure to use NEEDS blocks on those patches if they're distributed separately from their planet pack, for whatever reason.  (At least, this was the case in KSP 1.9.1; I haven't tested it in 1.10.1 yet, but I don't see anything in the changelog that suggests this has changed.)
3. It is not possible to add ROCs to celestial bodies that have ```cbNameLater``` defined.  (@Gordon-Dry, this is yet another reason to move away from it, in addition to KSP-RO/RealSolarSystem#170.)

**Comment by R-T-B** [comment]
Thanks.  I appreciate the write up.  This is on the long end of things on the todo list but it is certainly something we eventually want to do.

**Comment by R-T-B** [comment]
MyRocksAreBiggerThanYours is now integrated, so closing this.
