### ISSUE TITLE
ksp 1.8.1-1 not compactable with ksp 1.8 msg is displayed

### ISSUE THREAD

**Issue by viratsrivastava** [Kopernicus/Kopernicus#455]

**Comment by R-T-B** [comment]
You are running 1.8, or 1.8.1?  1.8.1-1 will only work with 1.8.1.

**Comment by viratsrivastava** [comment]
You are right!!! I used it on 1.8.0 my fault u can close the request
Thankyou for your valuable time

**Comment by R-T-B** [comment]
No problem!  Happy gaming!
