### ISSUE TITLE
Kopernicus doesnt work KSP 1.9

### ISSUE THREAD

**Issue by jamesbreith** [Kopernicus/Kopernicus#456]
Hey there everyone, I am confused to how Kopernicus doesnt work because I can't use Real Solar System. Can anyone  help me please?

**Comment by R-T-B** [comment]
I would need an error log from your install to even begin helping.  You can find it in <Wherever you installed KSP>/Logs/Kopernicus as a zip file.

**Comment by jamesbreith** [comment]
//===============================================================================================================//
//=====  Kopernicus 1.8.1-1 - (BuildDate: 04.02.2020 00:53:47; AssemblyHash: +LqVDbbqu0wsYVbmwpiAVPy7Vaw=)  =====//
//===============================================================================================================//
[LOG 14:23:46]: Logger "Kopernicus" was created
[LOG 14:23:46]: Injector.OnDestroy(): Complete

**Comment by jamesbreith** [comment]
Should i need to update Kopernicus?

**Comment by 7ranceaddic7** [comment]
Yeah, stable is 1.9.1-3

**Comment by R-T-B** [comment]
correct.  

I'm seeing a few people downloading the wrong version, which of course, does not work.  You may want to try CKAN or similar if keeping up to date is hard for you.

It is a mod management tool:

https://github.com/KSP-CKAN/CKAN/releases
