### ISSUE TITLE
Kopernicus not working in new update

### ISSUE THREAD

**Issue by apple1ad** [Kopernicus/Kopernicus#457]
It says its not compatible, {installed with CKAN}

here is the log

"

//==================================================================================================================================//
//=====  CKAN Release-grade Kopernicus 1.9.1-1 - (BuildDate: 19.08.2020 01:05:59; AssemblyHash: YgB/7aQARaQTGdG6zKzlkzh/DT0=)  =====//
//==================================================================================================================================//
[LOG 21:54:20]: Logger "Kopernicus" was created
[LOG 21:54:20]: Injector.OnDestroy(): Complete

"

**Comment by R-T-B** [comment]
You are on release 1.9.1-1 which had a few bugs.  I would try updating to 1.9.1-3 (latest) and see if it helps.

If it doesn't, a more complete collection of logs may be found in the install directory under logs/Kopernicus, usually in a zip file.  Post that.
