### ISSUE TITLE
Flicker and lag on small "Potatoroid" bodies

### ISSUE THREAD

**Issue by R-T-B** [Kopernicus/Kopernicus#460]
See issue on dead repo https://github.com/prestja/Kopernicus/issues/26

It still applies here.

**Comment by parkerman-com** [comment]
so it has never been fixed

**Comment by R-T-B** [comment]
Unfortunately no as the root cause is unknown.  It could be a stock game issue.  We are tracking it but until we understand it it's hard to fix.

**Comment by R-T-B** [comment]
Is this still an issue?  I'm not sure the genuine status of this bug.  Feedback appreciated.

**Comment by R-T-B** [comment]
Assuming fixed.  Someone comment if this is still relevant.
