### ISSUE TITLE
JSNQ Not working

### ISSUE THREAD

**Issue by joey-lg** [Kopernicus/Kopernicus#461]
It throws an error saying that it couldn't load the pack due to an exception.

here are the logs.
[ModuleManager.ConfigCache.txt]

(https://github.com/Kopernicus/Kopernicus/files/5348711/ModuleManager.ConfigCache.txt)

[Aden.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348735/Aden.Body.log)
[Airmed.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348736/Airmed.Body.log)
[Amos.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348737/Amos.Body.log)
[Belisama.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348738/Belisama.Body.log)
[Bop.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348739/Bop.Body.log)
[Brovo.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348740/Brovo.Body.log)
[Caireen.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348741/Caireen.Body.log)
[Celes.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348742/Celes.Body.log)
[Cernunnos.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348743/Cernunnos.Body.log)
[Dak.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348744/Dak.Body.log)
[Damona.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348745/Damona.Body.log)
[Dres.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348746/Dres.Body.log)
[Duna.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348747/Duna.Body.log)
[Epona.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348748/Epona.Body.log)
[Grannus.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348749/Grannus.Body.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/5348750/Kopernicus.log)
[Kopernicus.Runtime.log]

(https://github.com/Kopernicus/Kopernicus/files/5348751/Kopernicus.Runtime.log)
[Nodens.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348752/Nodens.Body.log)
[RAB-58E.Body.log](https://github.com/Kopernicus/Kopernicus/files/5348753/RAB-58E.Body.log)
[Rosmerta.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348754/Rosmerta.Body.log)
[Sirona.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348755/Sirona.Body.log)
[Sucellus.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348756/Sucellus.Body.log)
[Taranis.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348758/Taranis.Body.log)
[Toutatis.Body.log]

(https://github.com/Kopernicus/Kopernicus/files/5348759/Toutatis.Body.log)
Sorry for all the bandwidth clutter.

I hope you can figure it out through all of this text.

**Comment by R-T-B** [comment]
You are running Kopernicus 1.8.1, which is no longer maintained.  That MAY be the issue, but it should still work even though it's old.  You also don't just have JNSQ but other bodies present.  I imagine that the fact you have Grannus plus other bodies is the origin of your issue.  I do not believe these are compatible with JNSQ, which is a system replacement.  They are designed for the stock kerbin system.

**Comment by R-T-B** [comment]
Closing due to a lack of info.  Feel free to reopen this if you are still having trouble and were just absent for a bit.
