### ISSUE TITLE
Problem with loading custom planetary system.

### ISSUE THREAD

**Issue by HyperGod325** [Kopernicus/Kopernicus#463]
Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your save game is NOT recommended, because the missing planets could corrupt it and delete your progress.
My KSP is in 1.9.1 and I have the Outer Planets Mod. Could anyone help me with this problem?

**Comment by R-T-B** [comment]
We'll need your log files to continue.  You can generally find a zip of them in your game install folder /Logs/Logs-Kopernicus.zip
