### ISSUE TITLE
ScatterColliders not colliding

### ISSUE THREAD

**Issue by Keith-OHara** [Kopernicus/Kopernicus#464]
Between releases 1.9.1-9 and 1.9.1-10, 
The configuration [here](https://forum.kerbalspaceprogram.com/index.php?/topic/183468-more-terrain-scatters-anyone/&do=findComment&comment=3578281) and [here](https://forum.kerbalspaceprogram.com/index.php?/topic/195127-*) no longer makes Scatters solid.

On the 'bleeding edge' fork [here](https://github.com/R-T-B/Kopernicus/releases) release 36 is that last for which the configurations above make Scatterers solid

**Comment by R-T-B** [comment]
Interesting.  I will investigate this and hope to fix it by next release.

**Comment by R-T-B** [comment]
This should be fixed in latest stable, please test.

**Comment by Keith-OHara** [comment]
1.9.1-11 errors "can't add component 'MeshRenderer' to Scatter because such a component is already added" (with or without the configuration file to enable ScatterColliders).  Some Scatters get only the default pink block rendering, Scatters stop appearing when more should appear, and they do not get collidrs.

**Comment by Keith-OHara** [comment]
I see you saw the error messages and compiled a 1.9.1-12
That looks like it should work, as it has the code in ScatterCollider.cs from release -9
Good luck with it.

**Comment by Keith-OHara** [comment]
I checked that at least trees and Mun-boulders do get functioning colliders (with the enabling configuration file) with the 1.9.1-12 release package (as they did with release 38 on the 'bleeding edge' fork).  Looks good.

**Comment by R-T-B** [comment]
Yep, the mesh collider thing was actually a regression from a botched revert.  Fortunately, I gameplay tested and caught it fairly quickly.  Probably should do that before the stable release next time though. ;)
