### ISSUE TITLE
Kopernicus was not able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by Gridlock9** [Kopernicus/Kopernicus#466]
I'm running ksp 1.7.3 with the AfterKerbin mod  but this message pops up even if I try to use an older version of kopernicus.

Here are the files the message said were required:
[Files Required.zip](https://github.com/Kopernicus/Kopernicus/files/5537993/Files.Required.zip)

**Comment by R-T-B** [comment]
You will need to use a very old Kopernicus for 1.7.3 support, as it was before I even joined as a developer.  That means my ability to help is limited, but I will at least locate the correct version for you.  Try this one:

https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.7.3-2

**Comment by Gridlock9** [comment]
That one is the one I'm using, I also tried with 1.7.3-1 but the same message popped up

**Comment by R-T-B** [comment]
I'm on a phone at work right now so my ability to look at your logs is limited but I will do so in a few hours.

Things to check while you wait:

Try the bundled Kopernicus and MFI in AfterKerbin, maybe?

Ensure you don't somehow have two Kopernicus installs, etc.

I will look at your log files soon if none of that helps.

**Comment by Gridlock9** [comment]
Ok, thanks! I'll check the things

**Comment by Gridlock9** [comment]
Everything is in order, the installation is where it's supposed to be and the other 3 mods I have are not a problem since, without them, the same message pops up. I tried a different MFI install but it keeps happening.

**Comment by R-T-B** [comment]
Thanks for checking all that, I am home from work and examining your logs on a proper PC now.

**Comment by R-T-B** [comment]
It looks like the origin of the crash is most likely an incorrect version of Scatterer.  Please confirm this is the version you are using, it was the last to support 1.7.3:

https://github.com/LGhassen/Scatterer/releases/tag/0.0540

**Comment by Gridlock9** [comment]
I'll try changing scatterer, I've got the version that was linked in the AfterKerbin Readme. But that'll be tomorrow as I'm in Europe.

**Comment by Gridlock9** [comment]
Changed scatterer and the same happened.
Here's a screenshot of the gamedata folder and the gamedata folder inside the game data folder
![image](https://user-images.githubusercontent.com/61946662/99147619-bb01e680-2682-11eb-8ef6-6730a784fb32.png)
![image](https://user-images.githubusercontent.com/61946662/99147626-c35a2180-2682-11eb-9894-8a88646accb0.png)

**Comment by Gridlock9** [comment]
I might have solved it. I installed it through ckan and then did everything else manually. I had tried doing it totally through ckan but it stayed in the save loading phase for eternity.

**Comment by Gridlock9** [comment]
It worked! Thanks so much for the help. Great mod, I'm thinking of making my very own planet.

**Comment by R-T-B** [comment]
Glad to hear it!  Sorry for the slow replies, I develop more than visit the forums. ;)  Glad you worked it out!
