### ISSUE TITLE
Getting Issue: Kopernicus Will Not work with this version of KSP

### ISSUE THREAD

**Issue by TheEpicWatermelon** [Kopernicus/Kopernicus#467]
Hello,

I have the Real Solar System mod and whenever I load KSP there is some text that displays which says Kopernicus will not work with my version of KSP. And then when I get into the game the real solar system mod does not work. I am wondering if there is a fix for this issue?

Thanks.

**Comment by TheEpicWatermelon** [comment]
Here is my log.

[Player.log](https://github.com/Kopernicus/Kopernicus/files/5576864/Player.log)

**Comment by R-T-B** [comment]
You are running KSP 1.10.1.  The stable release does not support this yet.  There is a beta release which is stable other than lacking a few features for planet devs for 1.10.  Find it here:

https://github.com/R-T-B/Kopernicus/releases

Don't let the name fool you, this is a beta branch but it is nearly 100% stable at the moment (the only bugs are listed in the release notes).  We are just waiting on a few small fixes and comet support for planet authors.

**Comment by TheEpicWatermelon** [comment]
Ah, thank you!
