### ISSUE TITLE
Problem loading kopernicus

### ISSUE THREAD

**Issue by FFX1234** [Kopernicus/Kopernicus#468]
After trying to run KSP
AssemblyLoader: Exception loading 'Kopernicus': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <9d71e4043e394d78a6cf9193ad011698>:0

**Comment by R-T-B** [comment]
Can I get your full KSP.log file, and perhaps a screenshot of your gamedata directory?  That error alone doesn't tell me everything I need to help.

**Comment by FFX1234** [comment]
Here is the screenshot
![gamedata kerbal](https://user-images.githubusercontent.com/75160844/100499171-f8de2f00-3199-11eb-9e46-19abcd301956.png)
KSP.log
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5610376/KSP.log)

**Comment by R-T-B** [comment]
Just to be sure all is in order, what is the exact Kopernicus download you are using?  You are running 1.8 so I want to be sure you are using a version intended for 1.8.
