### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by Lieutenant-Lettuce** [Kopernicus/Kopernicus#469]
When I try to launch kerbal space program with kopernicus I get that error and when I try to play the game and it finished loading in the loading screen doesn't go away and I get stuck
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5662389/KSP.log)
[output_log.txt](https://github.com/Kopernicus/Kopernicus/files/5662390/output_log.txt)

**Comment by R-T-B** [comment]
That looks like you are running KSP 1.3.1?  That won't work with the latest releases.  You'll have to try to find a Kopernicus release from around that time frame.  I don't know which release that'd be, it was before I joined on.

From your log:

"Kerbal Space Program - 1.3.1.1891 (WindowsPlayer x64) en-us"

**Comment by StollD** [comment]
That log is ridiciolusly out of date.

```
Log started: Sat, Mar 03, 2018 01:23:44
```

**Comment by R-T-B** [comment]
Good catch.

**Comment by Lieutenant-Lettuce** [comment]
Ok, I just got an updated one. Hope I didnt mess something up
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5667887/KSP.log)

**Comment by R-T-B** [comment]
[LOG 17:15:14.020] [Kopernicus] Running Kopernicus 1.10.1-46 on KSP 1.10.1

Try running the latest build 50.  I think I remember this being a bug re compatability with other mods around build 46.

**Comment by Lieutenant-Lettuce** [comment]
To be honest I don't know how to do that :/

**Comment by R-T-B** [comment]
How are you installing Kopernicus now?  Manually or with CKAN?  If manually, just install this here:

https://github.com/R-T-B/Kopernicus/releases/download/UBE-release-50/KopernicusBE_1101_Release50.zip

Otherwise, just do a CKAN Update.

**Comment by Lieutenant-Lettuce** [comment]
Ok i just tried it with the updated kopernicus and it still doesn't work

**Comment by R-T-B** [comment]
Thank you for trying that.  I'll take another look at your log here, and update as soon as I find something.

**Comment by R-T-B** [comment]
It looks like you have some odd interactions between Scansat and ContractConfigurator.  One of them may be out of date perhaps, and generating further issues?

If updating those to the latest fails, please post a screenshot of your gamedata directory's contents and I'll try to help you further.

**Comment by Lieutenant-Lettuce** [comment]
I updated both of them and it is still happening.
![1](https://user-images.githubusercontent.com/75703240/101714961-6ec28000-3a4f-11eb-8d0c-80d492c463aa.PNG)
![2](https://user-images.githubusercontent.com/75703240/101714965-708c4380-3a4f-11eb-9c63-2b300a56fe55.PNG)

**Comment by Lieutenant-Lettuce** [comment]
sorry if that's hard to read

**Comment by R-T-B** [comment]
That's fine, I get it...  big mod list hard to fit lol.

Of that list, the only mod I can see that is known to cause problems is KSP-AVC.  I'd delete that folder, and try again.  It's around time for me to call it a day here, if that does not work I'll look at this again tomorrow.  Otherwise, the advice is basically remove mods until you find the conflicting one, and report back.  I know, that's painful, so if you just want to wait for my help, I don't blame you.

I hope just removing KSP-AVC does the trick.  Any instance of the miniavc.dll should also be removed, if found.  That plugin is obsolete and known to cause issues (it was an old autoupdate plugin whose server no longer works). 

You might just try doing a search for "avc.dll" in gamedata and deleting anything you find.

**Comment by Lieutenant-Lettuce** [comment]
Just finished deleting all of the avc.dll files and it is still not working :/

**Comment by R-T-B** [comment]
Everything you've done so far is good, so don't feel lost.  I have confidence we'll beat this tomorrow.

Over the evening (going to bed here), can I get a fresh KSP.log from you to see what (if anything) has changed in the logs?

**Comment by R-T-B** [comment]
As a final thought, this does appear to be rooted in the multistar logic somewhere.  If you are using only a single star system, you can try deleting GameData/Kopernicus/SolarPanels.cfg to revert to single star solar logic, and it may fix whatever is ailing you.

**Comment by Lieutenant-Lettuce** [comment]
I am installing it manually, and I am replacing all of the files. also, when you say that it is rooted in multistar logic, would having mods like real exoplanets count as other star systems?
also here is the updated log
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5674779/KSP.log)

**Comment by R-T-B** [comment]
multistar means more than one body that actually is a lightsource.  If you aren't using more than one single star, you can safely try deleting solarpanels.cfg.

I will look at your log soon, had a very busy work day today, sorry.  Thanks for understanding.

**Comment by Lieutenant-Lettuce** [comment]
because of 1.11 I got a new log
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5718098/KSP.log)

**Comment by R-T-B** [comment]
Ok, I finally have some time to go over this.  Thank you for being so patient.

Looks like for that one, you need a 1.11 Kopernicus, and also a 1.11 Kerbalism.  Please try the following release for both:

https://github.com/Kerbalism/Kerbalism/releases/tag/3.12

https://github.com/R-T-B/Kopernicus/releases/download/UBE-release-55/KopernicusBE_111_Release55.zip

**Comment by Lieutenant-Lettuce** [comment]
Just installed it, and it still doesn't work.

**Comment by R-T-B** [comment]
hmmm...  odd.  Can I get another screenshot of your gamedata folder?  Sorry I'm kind of drawing a blank on this one and hoping to spot something.

**Comment by R-T-B** [comment]
PS:  At work now but will work on this with your log and hopefully screenshot when I get home.  I really hope to finally solve this.

**Comment by Lieutenant-Lettuce** [comment]
![6](https://user-images.githubusercontent.com/75703240/102699828-dcfc0500-41fc-11eb-8008-cf585b84ed8e.PNG)
![7](https://user-images.githubusercontent.com/75703240/102699830-dec5c880-41fc-11eb-8978-bbd9dbe7026f.PNG)

**Comment by R-T-B** [comment]
Appreciate that.  I am tracking a bug right now related to how Kopernicus interacts with third party solar panels that is really similar.  May need a fix on my end, if that is the issue.  Do any of your mods add or replace stock solar panels?

Besides that theory, I will be looking at the log file in just a moment here, and will post my findings.

**Comment by Lieutenant-Lettuce** [comment]
ibh im not sure what mods add/replace solar panels. can you give some examples of ones that do?

**Comment by R-T-B** [comment]
NearFutureSolar is the biggest one.  Maybe that's not the origin of this though.  I think there might be more evidence in your log I missed at first, just a moment to confirm it and I will post my ideas.

**Comment by R-T-B** [comment]
It appears the error in this log is actually centered around RealChute.  Can you confirm if removing just that mod removes your error messages?

**Comment by Lieutenant-Lettuce** [comment]
I tried removing RealChute and then tried updating it and still not working

**Comment by R-T-B** [comment]
> I tried removing RealChute and then tried updating it and still not working

hmmm...  can you post the latest log without realchute present?

**Comment by Lieutenant-Lettuce** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5720375/KSP.log)

**Comment by R-T-B** [comment]
Thank ye kindly.  I am looking at it now.

**Comment by R-T-B** [comment]
We have made progress.  The install is functioning well enough the CompatabilityChecker is now telling us what mods are causing issues, which'll make this way easier:

[LOG 17:35:02.282] [CompatibilityChecker] Running checker version 5 from 'RealFuels'
[WRN 17:35:02.284] [CompatibilityChecker] Incompatible mods detected: RealFuels

Looks like RealFuels either needs an update, or removal.  Beyond that you should be good to go.

**Comment by Lieutenant-Lettuce** [comment]
I just tried removing real fuels and then FAR in 1.11 and it still doesn't work, so now I'm going to revert to 1.10.1 and try that

**Comment by R-T-B** [comment]
Ok.  If you still have issues, post your latest log after the instructions for 1.10.  I'll check up on it again, though likely tomorrow.

This is a really weird bug.  I'm appreciative you've brought it to my attention, and sorry I haven't been able to solve it yet.  Hopefully soon!

**Comment by Lieutenant-Lettuce** [comment]
It works now. switching back to 1.10.1 fixed it.

**Comment by R-T-B** [comment]
Good, as more mods update, I expect 1.11 will be possible for you soon.
