### ISSUE TITLE
Copernicus not working in 1.11

### ISSUE THREAD

**Issue by questiothing** [Kopernicus/Kopernicus#470]

**Comment by democat3457** [comment]
how is it not working? (and fyi its __K__ opernicus)

**Comment by questiothing** [comment]
![](https://i.gyazo.com/5fe678a032ea34659362e85e7aae3274.png)

**Comment by democat3457** [comment]
Are you using the 1.11.0 version found on https://github.com/R-T-B/Kopernicus/releases?

**Comment by questiothing** [comment]
oh. I used the version on this page. Thanks
