### ISSUE TITLE
Kopernicus 1.8.1-23  Failed to load Body: Ceres: Exception

### ISSUE THREAD

**Issue by FliXis24** [Kopernicus/Kopernicus#473]
Hello! I get an exception almost every time I load the game. Also, very often a black screen when trying to enter a setup or when loading a game.

[LOG 15:01:12]: [Kopernicus]: Configuration.Loader: Failed to load Body: Ceres: Exception has been thrown by the target of an invocation.

**Comment by R-T-B** [comment]
It seems the 1.8.3 release I posted has some bugs.  I will try to fix this today, thanks for the report.

You can revert to 1.8.1-1 (not a typo) in the meantime.

**Comment by R-T-B** [comment]
This should be fixed in next release being pushed to CKAN now.  Feel free to reopen if not.
