### ISSUE TITLE
[improvement] Tracking for non-sun/vessel objects for beamed power setups

### ISSUE THREAD

**Issue by NachtRaveVL** [Kopernicus/Kopernicus#475]
When using Kopernicus with KSPI-E's beamed power modules, it would be useful if Kopernicus SolarPanel modules were able to track on items that weren't just KopernicusStar.Stars items.

Take for instance a beamed power network where the best direction that the panel should be aimed at could be another vessel capable of beaming power to it. In this fashion you could align the panel such that you get the best angle to such a power source, entirely separate from The Sun.

I took a peak at the tracking code, and it doesn't seem like it would too terribly complicate such, but who knows. Would be awesome to see more flexibility to where it could auto-detect beam emitters on other vessels and use that to populate the Select Tracking Body dropdown.

**Comment by democat3457** [comment]
sounds cool, but mod compat sounds out of scope for the base mod

**Comment by R-T-B** [comment]
Yes, my advice would be to the mod author to clone the KopernicusSolar code and make his own module to override Kopernicus.  To be clear we would completely authorize and welcome such an effort, and the license allows it, but the base mod has no need for such a feature so we won't be adding it.
