### ISSUE TITLE
Don't use reflection to reach into MM to trigger its already confusing Nyan Cats

### ISSUE THREAD

**Issue by HebaruSan** [Kopernicus/Kopernicus#478]
This is gross:

https://github.com/Kopernicus/Kopernicus/blob/704ec69568944db39bca1adb11507bd6c651c5cf/src/Kopernicus/Constants/CompatibilityChecker.cs#L101-L112

Those are _**private variables:**_

https://github.com/sarbian/ModuleManager/blob/838677db5f2d2c17c1ce653489a3caa974110009/ModuleManager/ModuleManager.cs#L32-L33

Kopernicus needs a good way to get the user's attention and signal to them that it isn't going to work when it's running on an incompatible game version.

That should **not** mean _violating another mod's encapsulation_ to borrow a visual that otherwise means one of the following:

- It's April 1
- It's February 22

Tagging @DasSkelett and @R-T-B as an FYI.

**Comment by HebaruSan** [comment]
I would not blame @sarbian at all if he opted to rename the `nyan` and `nCat` variables to punish this.

**Comment by R-T-B** [comment]
FYI, this is old code that has existed a long time and not my doing.  I agree with the premise.  We will be removing this in next release.  I always felt the nyan cats were silly.  (I actually maintain a private MM-fork that removes them, because I feel that strongly about it.)

FWIW, we have done this for literally years preceding now according to git history, so I would assume Sarbian is both well aware and doesn't feel a need to "punish" us.  I would furthermore discourage the use of that philosophy in modding.

**Comment by HebaruSan** [comment]
> FYI, this is old code that has existed a long time and not my doing.

Yup, to be clear, I had no intention of accusing you specifically about this; I know it's very old code. Thanks for taking a look!

> I would assume Sarbian is both well aware and doesn't feel a need to "punish" us. I would furthermore discourage the use of that philosophy in modding.

Fair enough, I'll delete that reply.

**Comment by R-T-B** [comment]
Appreciate you pointing this out as I was unaware it actully accessed another mods private variables.  It's already iffy enough when we do that with KSP, but there is no excuse for that with modding.  Just bad practice.

**Comment by HebaruSan** [comment]
I also see this as an opportunity to improve the compatibility alert notification. Maybe you could put a giant red Image with 0.25f alpha channel over the whole screen, so everything is tinted at startup?

**Comment by R-T-B** [comment]
I have several ideas.  The only reason I am not releasing it immediately is

a.) to play with what works best

and 

b.)  April 1st gives us a little time to think.

**Comment by R-T-B** [comment]
I've been very busy, but I am pushing a basic simple change to remove the Nyan cats across all branches today.  (been in BE for a day or so now).

**Comment by Poodmund** [comment]
You're a monster.

**Comment by R-T-B** [comment]
> 
> 
> You're a monster.

A cat sits on my face every morning preventing work from being done, I'm pretty sure that's all the cat I ever need.
