### ISSUE TITLE
Issues with installing Kopernicus

### ISSUE THREAD

**Issue by WarpPrime** [Kopernicus/Kopernicus#479]
I'm trying to install Kopernicus. I downloaded the zip file according to [here](https://github.com/Kopernicus/Kopernicus/issues/292). I didn't get anything in the zip except for Kopernicus-master, GameData folder nowhere to be found. What am I doing wrong?

**Comment by DasSkelett** [comment]
Sounds like you installed the source code archive. You need to download a release zip instead:
https://github.com/Kopernicus/Kopernicus/releases/latest

Pick the one matching your current KSP version, Kopernicus is version-locked, so there's no chance it would work on a different one.

**Comment by WarpPrime** [comment]
Oops. I found the file in build/KSP1XXXXX.

**Comment by DasSkelett** [comment]
No, that's not what you want. It's missing the acutal DLL and maybe more.

Again, you don't want the source code archive. Delete it again and everything you've put into GameData from it.

Go to https://github.com/Kopernicus/Kopernicus/releases/latest, "Assets" and download the zip for your KSP version and install _that one_.
![latest-release](https://user-images.githubusercontent.com/28812678/109727145-1ca77b80-7bb4-11eb-8f42-5d6d7d5e8e42.png)
