### ISSUE TITLE
Persistent crash to desktop in career mod and achieving orbit

### ISSUE THREAD

**Issue by Paul-kingtiger** [Kopernicus/Kopernicus#48]
Hello,
I am getting an CTD when achieving orbit in career mode.  This is repeatable in KScale2 and 64K so I suspect it is a Kopernicus issue rather than an issue with the config files (KScale2 is very light).

To reproduce:
Start a career mode game with some starting science points.
Unlock a liquid fuel engine and tank (not required but makes it easier)
Launch a simple craft into orbit (I use the infinite fuel cheat to make it easier)
Various automatic contracts and records are reached during launch, but on completing the circularize burn to achieve orbit the game crashes.  Note you can achieve any altitude sub orbital, this only happens when your Pe is high enough for stable orbit.

Tested on Kopernicus 0.9

**Comment by ThomasKerman** [comment]
Weird, it works for me...
Could we please see your Logs? (Kopernicus-Logs in KSPRoot/Logs and output_log.txt / Player.log)

**Comment by Paul-kingtiger** [comment]
This morning I can only get it to crash intermittently.
Logs are available here:
http://1drv.ms/1BDAwyn

/Kerbal Space Program/Kopernicus Issue #48.zip

**Comment by Paul-kingtiger** [comment]
Getting the same crashes with 0.1

**Comment by tunafield** [comment]
I attached a debugger and it looks like it's running into an infinite loop inside WaypointManager.ChooseRandomPositionNear:

```
>	Void PQSLandControl:OnVertexBuildHeight (VertexBuildData)+0x332 at :-1	
 	Void PQS:Mod_OnVertexBuildHeight (VertexBuildData)+0x2f at :-1	
 	Double PQS:GetSurfaceHeight (Vector3d)+0x48 at :-1	
 	Void FinePrint.WaypointManager:ChooseRandomPositionNear (Double, Double, Double, Double, String, Double, Boolean, Random)+0x1ce at :-1	
 	Boolean FinePrint.Contracts.SurveyContract:Generate ()+0x460 at :-1	
 	Contract Contracts.Contract:Generate (Type, ContractPrestige, Int32, State)+0x50 at :-1	
 	Contract Contracts.ContractSystem:GenerateContract (Int32, ContractPrestige, Type)+0x44 at :-1	
 	Contract Contracts.ContractSystem:GenerateContract (Int32, ContractPrestige)+0x39 at :-1	
 	Boolean Contracts.ContractSystem:GenerateContracts (Int32, ContractPrestige, Int32)+0x9 at :-1	
 	Void Contracts.ContractSystem:RefreshContracts ()+0xaa at :-1	
 	Void Contracts.ContractSystem:OnReputationChanged (Single, TransactionReasons)+0x1 at :-1	
 	Void EventData`2:Fire (Single, TransactionReasons)+0x9f at :-1	
 	Single Reputation:AddReputation (Single, TransactionReasons)+0x143 at :-1	
 	Void Contracts.Contract:AwardCompletion ()+0x158 at :-1	
 	Void Contracts.Contract:SetState (State)+0xd2 at :-1	
 	Void Contracts.Contract:OnParameterStateChange (ContractParameter)+0x77 at :-1	
 	Void Contracts.Contract:ParameterStateUpdate (ContractParameter)+0x2 at :-1	
 	Void Contracts.ContractParameter:SetComplete ()+0x6e at :-1	
 	Void FinePrint.Contracts.Parameters.RecordTrackingParameter:OnProgressed (ProgressNode)+0x6d at :-1	
 	Void EventData`1:Fire (Object)+0x9e at :-1	
 	Void ProgressNode:Complete ()+0x59 at :-1	
 	Void KSPAchievements.RecordsAltitude:OnVesselSituationChange (HostedFromToAction`2)+0x6e at :-1	
 	Void EventData`1:Fire (HostedFromToAction`2)+0x9e at :-1	
 	Void Vessel:updateSituation ()+0x1b0 at :-1	
 	Void Vessel:LateUpdate ()+0x3a at :-1	
```

It looks like Fine Print was integrated into Kerbal at some point so I'm not sure how to view the latest source. https://github.com/Arsonide/FinePrint/blob/master/Source/WaypointManager.cs has a while loop that continues as long as GetSurfaceHeight() < 0, so maybe that's part of the problem?

**Comment by NathanKell** [comment]
So, we thought this was due to OnDemand (thanks to a tipoff from @Arsonide ) . Sadly, it appears to not be due to OnDemand, since @Paul-kingtiger is still getting the hang->oom->crash with OnDemand turned off.

@tunafield  that section is repeated, right? i.e. GetSurfaceHeight() keeps running (with what it calls under it) infinitely, all triggered by ChooseRandomPositionNear ?

If that's the case, the other way to work around this is to set AllowGround = False in all instances in Contracts.cfg. If that fixes the issue, then that confirms the source of the infinite loop, and we can look in Kopernicus as to why that might be failing.

**Comment by NathanKell** [comment]
If that does fix the issue, here's something else to try.
1. Revert to original Contracts.cfg
2. Increase
TrivialHomeNearbyRange = 2000
SignificantHomeNearbyRange = 4000
ExceptionalHomeNearbyRange = 6000

each by a lot, say a factor of 100. See if that helps.

**Comment by Paul-kingtiger** [comment]
I'm set AllowGround = False and launched to Orbit 5 times without crashing.
I then put it back to stock and changed the NearbyRange by a factor of 100 and launched to Orbit twice without crashing, so it looks like we're on the right track.

**Comment by NathanKell** [comment]
Great. I would say go with the latter solution. It will make early-campaign near-KSC survey contracts hard, but at least it will work.

**Comment by Paul-kingtiger** [comment]
Nathan, do you know what do those values mean?  It might help me tweak the values for the best effect.

**Comment by NathanKell** [comment]
The hang is from the ground survey waypoint generator failing because it can find no terrain within searchRadius of a given location (KSC) where the terrain is >0 height, i.e. above sea level.
The first fix would be to simply turn off all ground surveys.
The second fix is to increase the search radius (the homeNearbyRange) at all three contract levels.

**Comment by lOmicronl** [comment]
So the search origin remains at the old KSC's location deep underground if the planet scale is increased? Then the amount you need to increase this by would depend on your planetary scale increase, right? With bigger rescales requiring bigger values.

**Comment by NathanKell** [comment]
No, it's done off KSC's latitude and longitude.
(Even if it were done off the KSC transform, it would be fine--if the transform were screwed, your Space Center view would fail :P )

**Comment by lOmicronl** [comment]
Are the other distance values in that contract relevant?

		TrivialRange = 2000
		SignificantRange = 4000
		ExceptionalRange = 6000
		MinimumTriggerRange = 500
		MaximumTriggerRange = 15000

I'm not sure what they represent / what makes them different from the "HomeNearby" values, but the thought comes to mind that the contract needs to be able to find surface spots on other resized planetary bodies too (unless you want a hang the first time it randomly tries to generate a Mun survey mission). Are the above the values responsible for that?

For now, I increased all the HomeNearby values to five times default, and didn't crash. It successfully generated one trivial survey contract, but the waypoint is discouragingly far away: https://dl.dropboxusercontent.com/u/44754370/screenshot62.png
