### ISSUE TITLE
Change Kerbol's SOI from Infinite to Finite

### ISSUE THREAD

**Issue by WarpPrime** [Kopernicus/Kopernicus#480]
I want to make an interstellar star system using Kopernicus. The syntax for creating an object has nothing about SOI's. How do I change Kerbol's SOI, and how to I make an object that orbits nothing?

**Comment by R-T-B** [comment]
I do not believe you can make an object that orbits nothing.  It's kind of against the laws of physics.

As for Kerbol's SOI, I'm not sure I can actually do much about the root SOI's infinite nature.  I think it may be a stock game limitation.
