### ISSUE TITLE
Not work con 1.11.2

### ISSUE THREAD

**Issue by UnixAngel** [Kopernicus/Kopernicus#481]
the latest release not work yet on the version 1.11.2

**Comment by R-T-B** [comment]
It should.  I am using it on KSP 1.11.2 now.  Are you sure you have the latest?  If so, can I see you ksp.log?

**Comment by nased0** [comment]
I have the same problem with KSP 1.11.2.
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/6310051/KSP.log)
`[LOG 11:53:50.911] [BICH] Starting up! - Beyond Home by Gameslinx - ARR
[LOG 11:53:50.911] [BICH] BICH stands for Beyondhome Installation Checker. If you're reading this, you're evaluating what went wrong or stumbled across it when something else went wrong.
[LOG 11:53:50.911] [BICH] Thank you for using Beyond Home. Below you can find out what went wrong (or right!)
[LOG 11:53:50.911] [BICH] GameData directory is G:/Steam/steamapps/common/Kerbal Space Program/GameData/
[LOG 11:53:50.911] 
[LOG 11:53:50.911] [BICH] Displaying errors, warnings and notices below:
[LOG 11:53:50.911] [BICH]   - RAM meets or exceeds requirement
[LOG 11:53:50.911] [BICH]   - VRAM meets or exceeds the requirement
[LOG 11:53:50.911] [BICH]   - EVE is not installed
[LOG 11:53:50.922] 
[LOG 11:53:50.922] [BICH] Checking for Kopernicus and KSP version match...
[LOG 11:53:50.922] 
[LOG 11:53:50.922] [BICH] Exception: There were the following errors in the Beyond Home installation:
[LOG 11:53:50.922] [BICH] <color=#00F200>Recommended RAM: 5GB  -  Installed RAM: 65
<color=#00F200>Recommended VRAM: 1GB  -  Installed VRAM: 8
NOTICE: Environmental Visual Enhancements is not installed!

[LOG 11:53:50.922] [BICH] Detected KSP validation path as G:/Steam/steamapps/common/Kerbal Space Program/readme.txt
[LOG 11:53:50.922] [BICH] Detected Kopernicus validation path as G:/Steam/steamapps/common/Kerbal Space Program/GameData/Kopernicus/Plugins/Kopernicus.version
[LOG 11:53:50.923] [BICH]   - Kopernicus and KSP version mismatch!
[LOG 11:53:50.923] [BICH] Shutting down InstallationChecker, its task is done! ´┐ŻNot all those who wander are lost...´┐Ż
[LOG 11:53:50.923] 
[LOG 11:53:50.923] 
[LOG 11:53:50.923] ----------------------------------------------------------------------------------
[LOG 11:53:50.924] [MFIManager] FlightIntegrator is active. Deactivating it
[LOG 11:53:50.924] [MFIManager] Current active VesselModule : 
[MFIManager]  AxisGroupsModule active=True order=999
[MFIManager]  CometVessel active=True order=999
[MFIManager]  FlightIntegrator active=False order=0
[MFIManager]  CommNet.CommNetVessel active=True order=999
[MFIManager]  ModularFI.ModularFlightIntegrator active=True order=0

[LOG 11:53:50.976] [CompatibilityChecker] Running checker version 5 from 'MechJeb2'
[WRN 11:53:50.978] [CompatibilityChecker] Incompatible mods detected: Kopernicus`

**Comment by R-T-B** [comment]
Thank you for the report.

If you are using the latest release, this may be a bug with the beyond home installation checker dll.  Removing just that dll may get you going.

Alternatively, you may be running an obsolete version.  Double check that you are running latest release.

**Comment by nased0** [comment]
It is the latest version of Beyond Home 1.4.0 and KSP on Steam updates automatically.
Removing InstallChecker.dll from BeyondHome directory didn't help.
IMO it is a version number mismatch problem.

**Comment by R-T-B** [comment]
Are you using the latest Kopernicus?

You may need to update.  Here, I will provide a link to the latest build for 1.9.0-1.11.2:

https://github.com/Kopernicus/Kopernicus/releases/download/release-38/Kopernicus-1.11.1-38.zip

**Comment by nased0** [comment]
Now it works, thanks!
Previously i tried Kopernicus-1.9.1-1RC_HF4

**Comment by R-T-B** [comment]
Ah!  That tells me what was wrong.  That version is very old.

The new versions support a very large version range.  Glad you got it working, enjoy!

**Comment by nased0** [comment]
I downloaded it from the Beyond Home forum:
https://forum.kerbalspaceprogram.com/index.php?/topic/182708-191-110x-beyond-home-150-supports-parallax/
https://github.com/prestja/Kopernicus/releases

**Comment by R-T-B** [comment]
Ah his link is out of date to an old build / old developer.

I will inform him, thanks.
