### ISSUE TITLE
Not able to load custom planetary system due to exception in the loading process

### ISSUE THREAD

**Issue by manskirtbrew** [Kopernicus/Kopernicus#482]
Last night, 3/31, started getting this message at startup. I have not made any changes to my install since adding Advanced-Flybywire on 3/27.

I just downloaded and installed Kopernicus-1.11.1-38.zip to be sure, and the problem persists.

I would have originally installed Kopernicus on 3/19 with EVE, SVT, and Scatterer.

[LOG 10:32:35]: [Kopernicus]: Configuration.Loader: Loaded Body: Sun
[LOG 10:32:36]: [Kopernicus]: Configuration.Loader: Loaded Body: Moho
[LOG 10:32:38]: [Kopernicus]: Configuration.Loader: Loaded Body: Eve
[LOG 10:32:39]: [Kopernicus]: Configuration.Loader: Loaded Body: Gilly
[LOG 10:32:39]: [Kopernicus]: Configuration.Loader: Failed to load Body: Squad/Kerbin: Default constructor not found for type UnityEngine.Material
[LOG 10:32:41]: [Kopernicus] RuntimeUtility Started

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/6244393/Logs-Kopernicus.zip)

**Comment by R-T-B** [comment]
I was worried for a moment the old April fools cat display on module manager might be what you are reporting, but this looks like a genuine error in your logs.

Since no one else is experiencing similar, my first suggestion would normally be to remove advanced-flybywire...  but I am doubtful that is the issue, as I use that same mod.

More likely you have some kind of install corruption.  Can you verify the install integrity with steam?  That might fix your issue.  Report back if not.

**Comment by manskirtbrew** [comment]
Thanks for the quick response. No foolin' here, I promise.

Trying removing flybywire...same issue.

Verifying install with Steam...71 files failed to validate and will be reacquired! What have you done, Steam?

Oh damn. Didn't fix the issue though. Same error in the Kopernicus log, install now verifies 100%.

Okay, removing all other mods but Kopernicus. Ah, that fixed it. Adding them back in to see who's conflicting.

Huh. It's StockVisualTerrain. Which is weird, because I've been running it since 3/19, and didn't start seeing an issue until just last night.

Well, I'm open to suggestions if you'd like me to try anything else to diagnose it.

**Comment by R-T-B** [comment]
Yeah, SVT seems to be buggy in newer Kopernicus versions.  A lot of the textures it provides are actually worse than stock though, so I have not bothered to fix it.

If you are interested, I made a rerelease of said mod using just the parts that are better (basically just scaled space, AKA high flight and orbit) here:

https://forum.kerbalspaceprogram.com/index.php?/topic/200062-181-1111-stock-visual-terrain-svo-scaledversion-only/

Should load fine.

**Comment by manskirtbrew** [comment]
I am interested, thank you. Installed and working fine. Cheers.
