### ISSUE TITLE
Mod not compatible for 1.8/1.9

### ISSUE THREAD

**Issue by Minecrafter6818** [Kopernicus/Kopernicus#483]
Hello! The mod which I am using is somehow not working, I don't know if I installing it wrong or theres something wrong. 
Proof of mod not working: 
![image](https://user-images.githubusercontent.com/82376844/114379203-69ea1600-9b80-11eb-844b-aa5ad49ee5ab.png)

I went to other versions like 1.9 and its still saying its still incompatible.

In logs it dose say something about a token could not be resolved here: 
![image](https://user-images.githubusercontent.com/82376844/114380431-fb0dbc80-9b81-11eb-969f-1ecf134170c9.png) 

If I using this wrong then can you tell me how to install it right? I do have all of it on the GameData folder.

Thank you!
-Minecrafter6818

**Comment by R-T-B** [comment]
Hello, where are you getting your download from?  I will link the latest for 1.8 and the latest for 1.9/1.9+.

1.8:

https://github.com/Kopernicus/Kopernicus/releases/download/release-38/Kopernicus-1.8.1-38.zip

1.9/1.9+:

https://github.com/Kopernicus/Kopernicus/releases/download/release-38/Kopernicus-1.11.1-38.zip

Release page:

https://github.com/Kopernicus/Kopernicus/releases

Try those.

**Comment by Minecrafter6818** [comment]
Hello! i had a try on KSP but a error showed up with this: 
![image](https://user-images.githubusercontent.com/82376844/114525965-7765d580-9c3e-11eb-8ded-850cb5f80d81.png)
Heres the entire KSP log:



[LogFile.zip](https://github.com/Kopernicus/Kopernicus/files/6302501/LogFile.zip)
Its the same for 1.8 as well.
(needed it on a .zip due to it being large)
thanks for your help!

**Comment by R-T-B** [comment]
Most likely a mod incompatability.  I will look at your logfile and brb with some more information.

**Comment by R-T-B** [comment]
The error is coming from this plugin:

D:\my data\steam\steamapps\common\Kerbal Space Program\GameData\DiscordRP_1.0.3\GameData\DiscordRP\Plugins\DiscordRP.dll

I don't know what that plugin does, so my only advice would be to remove it.  Then you should load fine.

**Comment by Minecrafter6818** [comment]
Hello! thank you for the response
Yes I forgot about the mod being installed as it didn't work, I uninstalled the mod.
there were some problems reinstalling and stuff but that isnt related to the mod.
After a while it works!
I am increadbly thankful for helping me, please stay safe and have a good day.
