### ISSUE TITLE
Compatibility with 1.11.2

### ISSUE THREAD

**Issue by mrmcnuggetboi** [Kopernicus/Kopernicus#484]
Would it be possible to make Kopernicus work with 1.11.2? Module Manager is producing errors even though all mods except Kopernicus have been removed.

**Comment by R-T-B** [comment]
It does work with 1.11.2...  Are you using this release?

https://github.com/Kopernicus/Kopernicus/releases/download/release-39/Kopernicus-1.11.1-39.zip
