### ISSUE TITLE
Can't Modify the Parameters of the sun

### ISSUE THREAD

**Issue by Peter-JY** [Kopernicus/Kopernicus#487]
I want to change the Sun's mass and radius, but Kopernicus don't load it.
I checked my .cfg with Sun.cfg in RealSolarSystem, which has changed the Sun's radius and GM. There is only some diffierences between the numbers.
I also tried to put Sun.cfg and another my own planet as Kerbin, but it can't run as well.

Maybe the issue is in Kopernicus.
If not, is there any possibility to make it possible to change the Sun just with Kopernicus and some configs?

Here are the .cfgs I tried.
[HR5756.cfg and Ikrinas.cfg](https://github.com/Kopernicus/Kopernicus/files/6628747/HR5756.Ikrinas.cfg.zip)

**Comment by R-T-B** [comment]
Unfortunately, I am not really much of a config expert, despite being the chief dev!

But regardless, I will try to help.

In my personal game, I have a file that modifies the suns radius to work around a bug in rescale.  This file may help you as a template, as it both does what it should and looks slightly different than yours.  Maybe model it around this, just ignoring the parts you don't really need?

Hope it is helpful.
[Sun.zip](https://github.com/Kopernicus/Kopernicus/files/6642948/Sun.zip)

**Comment by Peter-JY** [comment]
Thank you very much, but..... 
The file _Sun.zip_ is empty, and there isn't any file in it. Maybe you sent a wrong file to me. Would you mind sending it to me again?

**Comment by R-T-B** [comment]
oops... lol.

Try this:
[Sun.zip](https://github.com/Kopernicus/Kopernicus/files/6644544/Sun.zip)

**Comment by R-T-B** [comment]
Closing as part of a broader cleanup due to age (and the fact that I don't really see a bug here, more an old design choice).
