### ISSUE TITLE
Kopernicus causing Ksp to get stuck on black loading screen with planets orbiting. ( KSP RSS 1.11 )

### ISSUE THREAD

**Issue by Baguette420** [Kopernicus/Kopernicus#491]
I'm having an issue with the latest release of Kopernicus where KSP gets stuck on the black loading screen with the planets orbiting around next to where it says loading. The main menu music is playing and the loading animation plays but it never gets past that point. I have tried Ksp 1.10 and 1.11 with RSS but it dosent load. I tried Uninstalling it and game loads fine. Its always worked fine on an older release in my  KSP RSS 1.8.1 save and my normal 1.10 save with a planets pack installed. This is what the KSP log keeps throwing out:
NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.GetNearest (CelestialBody body) (at <5ee65b8e6625486c8b402b261332b4f9>:0)
	Kopernicus.Components.KopernicusStar.GetBrightest (CelestialBody body) (at <5ee65b8e6625486c8b402b261332b4f9>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility.AtmosphereLightPatch (CelestialBody body) (at <5ee65b8e6625486c8b402b261332b4f9>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility.LateUpdate () (at <5ee65b8e6625486c8b402b261332b4f9>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Obj

Im gonna try an older version to see if it works

**Comment by R-T-B** [comment]
Can you post a screenshot of your gamedata?

This is likely some other mod interacting with Kopernicus, since no one else has reported this.

**Comment by opeag1345** [comment]
i have this problem too

**Comment by jrodrigv** [comment]
@R-T-B I can confirm that I'm experiencing the very same issue.

In my case I'm using: KSP 1.12.2, latest Kopernicus release, Real Solar System and latest Module Manager.

I have attached the full log, but summarizing, it seems to start here the problem when executing KopernicusStar.Start() during loading.

`[LOG 19:01:01.263] [Kopernicus] Generating default Kopernicus_Config.cfg
[WRN 19:01:01.271] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[EXC 19:01:01.282] IndexOutOfRangeException: Index was outside the bounds of the array.
	Kopernicus.Components.KopernicusStar.Start () (at <d504c2aecaea4315a6dc0040212faedb>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

Looking at the exception and the code, maybe it is related with this line? And there is not LightShifter components?

```
 protected override void Start()
        {
            // Get the LightShifter
            shifter = sun.scaledBody.GetComponentsInChildren<LightShifter>(true)?[0];
```


Then from that point forward, it just enters in a infinity loop of exceptions: that looks like this:

```
 at Kopernicus.Components.KopernicusStar.GetNearest (CelestialBody body) [0x00062] in <d504c2aecaea4315a6dc0040212faedb>:0 
  at Kopernicus.Components.KopernicusStar.GetBrightest (CelestialBody body) [0x0000a] in <d504c2aecaea4315a6dc0040212faedb>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.PatchTimeOfDayAnimation () [0x00012] in <d504c2aecaea4315a6dc0040212faedb>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.OnLevelWasLoaded (GameScenes scene) [0x0000a] in <d504c2aecaea4315a6dc0040212faedb>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.<Awake>b__5_1 (GameScenes s) [0x00000] in <d504c2aecaea4315a6dc0040212faedb>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <cd473063d3a2482f8d93d388d0c95035>:0 
```



[KSP.log](https://github.com/Kopernicus/Kopernicus/files/7192542/KSP.log)
he

**Comment by R-T-B** [comment]
I will look into this.  RSS could need additional handling.  This error usually occurs when no star is set to emit light...  but I am assuming that is not the case.

**Comment by jrodrigv** [comment]
> UPDATE: Can anyone identify a build where this worked correctly? It seems to be bugging out on certain bodies and thus failing to load the Sun.

Sure I will continue doing more testing to see if I can do find the root cause.  Could Scatterer cause this problem?

**Comment by R-T-B** [comment]
No, it's not scatterer.  I think it might be an incompatability with the RealSolarSystem.dll and KSP 1.12 honestly.  Maybe an earlier version may work?

**Comment by jrodrigv** [comment]
Thanks for the feedback. I will check RSS code and configuration

**Comment by jrodrigv** [comment]
Ok, this issue can be closed. It is not a Kopernicus issue but a bad RSS installation.  Everything is working fine now

**Comment by R-T-B** [comment]
Since it seems to be a common mistake, can you elaborate on what exactly was wrong?

**Comment by jrodrigv** [comment]
> Since it seems to be a common mistake, can you elaborate on what exactly was wrong?

Sure, the root cause of the problem is that I was missing some of the textures from RSS-Textures. RSS is divided in two mod folders, the RealSolarSystem folder and the RSS-Textures. 

Due to the missing textures, Jupiter was not loaded properly and I think then the Sun was not even loaded, causing the exception loop with the KopernicusStar.GetNearest

**Comment by R-T-B** [comment]
Since it seems to be a common mistake, can you elaborate on what exactly was wrong.
