### ISSUE TITLE
KSP getting stuck on Black loading screen when loading a save with Kopernicus for KSP 1.11.2

### ISSUE THREAD

**Issue by RenZoc-FN** [Kopernicus/Kopernicus#492]
Hi RTB, I installed kopernicus since I wanted to install the planet pack GU (Galaxies Unbound) and I installed Kopernicus and GU for the mod to work and I was stuck in the black loading screen.  I tried uninstalling Kopernicus and I loaded into my saved game. My Other Mods are: Stock Visual Enhancements, Environmental Visual Enhancements, Scatterer,  Kerbal Engineer Redux, Kerbal Alarm Clock, Mechjeb 2, Waterfall, Better Time Warp, Camera Tools, Chatterer, and the Toolbar mod for the Better Time Warp mod to work.
Can you help me with this issue?

@R-T-B

**Comment by R-T-B** [comment]
If you could post your KSP.log file from your game root, I can see if I can help.  Thank you.

**Comment by RenZoc-FN** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/6826415/KSP.log)

**Comment by R-T-B** [comment]
Thanks.  A bit busy today but will take a solid look at this soon, most likely some time tomorrow.

**Comment by DasSkelett** [comment]
Kopernicus wasn't installed when this log was created.
You should probably upload one with Kopernicus installed, getting stuck at the loading screen, so @R-T-B can see what's going on.

**Comment by RenZoc-FN** [comment]
sorry for the mistake, I will reinstall Kopernicus and upload the KSP.log file, thanks for the suggestion.

**Comment by RenZoc-FN** [comment]
this is the KSP.LOG with Kopernicus installed:
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/6827289/KSP.log)

**Comment by DasSkelett** [comment]
You didn't restart KSP in between. The log files start at the exact same time, the second log file has a long gap between 17:49:58.598 (where the first one ends) and 21:42:51.773.

This might very well be the cause of your problem. You need to restart KSP whenever you do changes to GameData, i.e. installing, updating or uninstalling mods. Otherwise it won't pick up the changes, or only partially, and will be very broken.

**Comment by RenZoc-FN** [comment]
Github is not allowing me to upload the file, can you let me know how to upload it, first time it allowed me now it is not

**Comment by DasSkelett** [comment]
Maybe it's too big, try zipping it and uploading the zip.

**Comment by RenZoc-FN** [comment]
I added the KSP.log file to a mega file, I think you will have to download it.
mega link: https://mega.nz/file/vlQggBIY#5mOznZqyunKISrG73n9LT28AGBR6GEujEql0UHuBo3I

(I have Kopernicus and GU installed and I kept it on the black screen for about 7 min)

**Comment by RenZoc-FN** [comment]
[KSP.log file.zip](https://github.com/Kopernicus/Kopernicus/files/6835011/KSP.log.file.zip)

I compressed the folder and put in the KSP.log file with Kopernicus and GU Installed and on the black screen, just in case you can't download it from mega.

**Comment by R-T-B** [comment]
Thanks, I will take a look at this when I get home from work later today.  Sorry about the delay.

**Comment by RenZoc-FN** [comment]
thanks for replying back, you can take your time, just only use the KSp.log file that i provided in the zip since the older ones either don't GU or Kopernicus. (Thanks for your active support!)

**Comment by R-T-B** [comment]
Ok, finally got around to looking at this.

It looks like a gas giant is failing to load and throwing the whole loading process off, but it's hard to say which one.  Can you provide the Logs/Logs-Kopernicus.zip zip file that the game generates on a run with this bug?

It should tell me more.

**Comment by RenZoc-FN** [comment]
Here is the file you requested for: 
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/6837077/Logs-Kopernicus.zip)

**Comment by R-T-B** [comment]
The logs indicate Jool is failing to load.

I would advise starting with a fresh install, as that is usually caused by install corruption.  Re-add your mods one by one until it breaks, and report back if it does.  Hopefully it won't.

**Comment by RenZoc-FN** [comment]
Hi RTB, Sorry I didn't respond, it was night for me when you replied, I am trying 1.12 version of KSP, I will install one mod and then another one, and see what breaks it. I am installing the 1.12.0-48 version of Kopernicus.

**Comment by RenZoc-FN** [comment]
I only installed Kopernicus and it worked, I loaded into the game. Now I will try GU.

**Comment by RenZoc-FN** [comment]
I installed GU with kopernicus and both mods loaded properly.

**Comment by RenZoc-FN** [comment]
I installed EVE and the Astronomers Visual Pack for the configs and it works perfectly as expected, I will try and download one more mod.

**Comment by RenZoc-FN** [comment]
Hi RTB, I installed all my mods expect for Better Time Warp, Mechjeb and Kerbal Alarm Clock. But Kopernicus, GU and all my other mods work perfectly. BTW, this is on KSP 1.12.0.3140. Thanks for your active Support and hope Kopernicus will continue to be more popular. 

Thanks, 
RZ.

**Comment by R-T-B** [comment]
No problem!  I'd still load KAC by the way, the built in alarm clock is stuck on stock time scales, and it has some other bugs.  KAC fortunately still works fine.

I'd guess you just had some freak install corruption.  It happens. :)
