### ISSUE TITLE
KSP 1.12.2 - Space station gets filled in with concrete 

### ISSUE THREAD

**Issue by Nubbie** [Kopernicus/Kopernicus#494]
**KSP version:** 1.12.2
**Making history:** 1.12.1
**Breaking ground:** 1.7.1

Tried downloading this mod to use it with Parallax, however, I'm not sure if something is wrong as it looks a bit weird and the whole station got filled with concrete
Removing this mod fixed the issue 

I do however have some other mods and some are outdated

Sorry to bother but any clue what could be wrong?

Attaching a pic to compare with and without the mod + my mod list
![Compare](https://user-images.githubusercontent.com/17282384/128105201-f35a0cbf-39ca-480a-9f09-5cbc1e86a896.png)
![Mod list](https://user-images.githubusercontent.com/17282384/128104912-2a9c043c-92b7-4100-9388-6bed3148410c.png)

**Comment by R-T-B** [comment]
Thanks for attatching the mod list, it's helpful information.  My bet is one of the older mods is replacing the KSC ground texture.  The only way to identify which is to remove them one by one until this behavior stops, but if I had to guess, my bet would be on something in KSRPC.

**Comment by Nubbie** [comment]
@R-T-B Seems like you're right, it was KSPRC which made the textures weird
Tried to quickly figure out why but couldn't - only used the mod to make lights and some other improvements appear on Kerbin 😄 
Thanks!
