### ISSUE TITLE
Not work on 1.11.2

### ISSUE THREAD

**Issue by DJBrooksie** [Kopernicus/Kopernicus#495]

**Comment by DJBrooksie** [comment]
I downloaded parallax and was looking for 1.11.2 kopernicus and stumbled on this link https://github.com/Kopernicus/Kopernicus/issues/481

**Comment by DJBrooksie** [comment]
Ok 


ill try to fix it on my own

**Comment by democat3457** [comment]
dafuq
well did you download the 1.11.2 version

**Comment by R-T-B** [comment]
1.12.1 builds work on 1.11.x and even 1.10.x and 1.9.x...  it confuses people sometimes.  Just FYI.
