### ISSUE TITLE
KSP loading freezes when reaching "Loading Part Upgrades"

### ISSUE THREAD

**Issue by CAPFlyer** [Kopernicus/Kopernicus#496]
I've verified this by downloading Kopernicus Release 59 and all prior to Release 40 just to check.  All have the same result.  KSP loads fine when Kopernicus is not installed.

Screenshot of frozen screen & Log file 
![Frozen Loading Screen](https://user-images.githubusercontent.com/4055953/129839230-5344cdf9-f998-4fe7-b28c-e90b53e42ba8.jpg)
- 
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/7004601/KSP.log)

**Comment by R-T-B** [comment]
This particular bug looks like a corrupted install in your log.  Can you provide a screenshot of your gamedata folder, maybe your Kopernicus folder contents as well?

**Comment by CAPFlyer** [comment]
I doubt it's a problem with the Kopernicus install as I have re-installed it several times since the problem started.  Did the last several manually just to make sure it wasn't CKAN.  The common factor is that if I remove Kopernicus, KSP loads normally.  I install any version of Kopernicus, and I get the issue.  First thing I did was a full clean install of KSP to verify that it wasn't an issue with KSP.

**Comment by CAPFlyer** [comment]
The only reason I hesitate to post a screenshot of the Gamedata folder is that it's pretty heavily modded, I have several dozen addons installed so it'd take a bunch of screenshots to show everything.

**Comment by CAPFlyer** [comment]
Also, I did verify the file integrity of KSP via Steam after the latest install just to be sure after the clean install that all was well.

**Comment by CAPFlyer** [comment]
Well, I guess I have to eat my words.  I did another clean install of KSP then started loading in the addons and Kopernicus wasn't it.  I'm still not sure where this error is happening all of a sudden, but it only started with this newest build of KSP.

**Comment by svenhakvoort** [comment]
For anyone running into this, make sure your harmony version is the latest bundled with kopernicus (double check the Harmony.version file with the Harmony release page). For me I was still on an old version which caused this error
