### ISSUE TITLE
Doesn't work on 12.2?

### ISSUE THREAD

**Issue by ybm202** [Kopernicus/Kopernicus#497]
Hi,

I would like to use this on my 1.12 KSP, but it seems, that when I have Kopernicus installed, I'll just see the Loadind-Screen. Just black with the planets in the right corner! I guess the problem is the "ModularFlightIntegrator" but I don't really know! Does someone know how to fix it?

Best
Yann

**Comment by R-T-B** [comment]
KSP 1.12 typically does that when duplicate dlls are present somwwhere.  You'll need to find which dlls you have that have the same name (in GameData) and remove one.

**Comment by ybm202** [comment]
Thank you for the quick answer and the tip! I'll try immediately.

**Comment by Myridium** [comment]
Also having this issue. There are no DLLs in GameData.

**Comment by DasSkelett** [comment]
> There are no duplicate DLLs in GameData, nor could there be because files cannot have the same name...

They could be in different subfolders from different mods though, which is what this is about. Don't only look into top level GameData, but also every subdirectory recursively (or better: use the search function).
Most likely it's `Kopernicus.Parser.dll`, which is redistributed by a bunch of mods like Kronometer (which itself is sometimes bundled in planet packs like JNSQ).

**Comment by Myridium** [comment]
My problem turned out to be due to a different mod. It would be more helpful if Kopernicus provided error information in-game.

**Comment by DasSkelett** [comment]
> It would be more helpful if Kopernicus provided error information in-game.

That's hard to do if it fails to load...
For broken planet configs it already does so (with more information available in the KSP.log).

**Comment by Myridium** [comment]
> > It would be more helpful if Kopernicus provided error information in-game.
> 
> That's hard to do if it fails to load...
> For broken planet configs it already does so (with more information available in the KSP.log).

Sometimes it loaded to the main menu with an error message, but it did not mention this `KSP.log` file. That would have been helpful.
