### ISSUE TITLE
[Unconfirmed] Kopernicus causes RocManager.Instance to be null

### ISSUE THREAD

**Issue by gotmachine** [Kopernicus/Kopernicus#499]
I'm trying to track a bug that happen intermittently with Kerbalism.

The first time our `ScenarioModule.OnLoad()` code is executed, we are referring to`ROCManager.Instance`.
To be precise, this is called when a game is loaded for the first time, after being selected/created in the KSP main menu.

For some of our users, this call to `ROCManager.Instance` occasionally returns null, despite them having the Breaking Grounds expansion installed. I'm unable to reproduce the issue, but this has been reported many times. It seems that every user that report this have Kopernicus installed.

I suspect that this might be caused by Kopernicus.
`RocManager` is a singleton `MonoBehaviour` added to the `ROCManagement` gameobject, itself a child of the `PSystem` root gameobject (which has the `PSystemManager` and `PSystemSetup` components)

`RocManager.Instance` is a static property affected by `RocManager.Awake()`. The method begins with a silly piece of code :
```cs
        if (Instance != null)
        {
            UnityEngine.Object.DestroyImmediate(base.gameObject);
            Instance = null;
            return;
        }
```
I'm not sure what the intent was, but in effect, if `RocManager` is re-instantiated, this would cause the original instance to be inaccessible through the `RocManager.Instance` static property, and the new instance to be destroyed.

I'm not familiar with the Kopernicus inner workings, but would it be possible that it cause a re-instantiation of the `PSystem` object/prefab ? That could explain the issue, although the fact that it isn't consistently reproducible is quite strange.

**Comment by R-T-B** [comment]
I am closing this as part of a broader cleanup since you have a workaround.  If this becomes an issue in a larger way, feel free to reopen.
