### ISSUE TITLE
Kerbals clipping into terrain on Kopernicus planets

### ISSUE THREAD

**Issue by Nikola-Mihajlovski** [Kopernicus/Kopernicus#504]
![screenshot27 (Custom)](https://user-images.githubusercontent.com/80640339/141812202-661aad2a-9d66-4423-9437-fdd6f8d9e72f.png)

If I walk around with a kerbal on a kopernicus planet (any planet pack) the kerbal sinks into the ground until it explodes. I can sometimes get the kerbal out of the ground by jumping, but sometimes this causes them to explode as well
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/7539888/KSP.log)
.
[ModuleManager.log](https://github.com/Kopernicus/Kopernicus/files/7539891/ModuleManager.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/7539895/Kopernicus.log)

**Comment by R-T-B** [comment]
See the release notes.  This is a known stock-code level bug and potential work arounds are listed in them.  It is more problematic the more distant you get from the system root.

**Comment by Nikola-Mihajlovski** [comment]
> See the release notes. This is a known stock-code level bug and potential work arounds are listed in them. It is more problematic the more distant you get from the system root.

Alright thanks
