### ISSUE TITLE
Regression:  Land Scatters can be appear at incorrect vertical elevations when Kopernicus manages them.

### ISSUE THREAD

**Issue by R-T-B** [Kopernicus/Kopernicus#505]
As described.  This is a regression of an old issue, and needs investigation.

**Comment by democat3457** [comment]
Sounds like a perfect time for `git bisect`

**Comment by R-T-B** [comment]
Indeed,  I am learning this now, lol.

**Comment by R-T-B** [comment]
This is ALMOST fixed by release 67, but there are still mixed reports of a few floating scatters in scenarios where the user either teleports, or uses a rover over a long, multi-km distance.  I will need to investigate that.

**Comment by R-T-B** [comment]
Release-68 closes (and fixes) this.
