### ISSUE TITLE
Extremely slow performance.

### ISSUE THREAD

**Issue by pack7df** [Kopernicus/Kopernicus#507]
When i'm in KSC or in fligh and is day light, it is extreme slow... less than 1fps, When is night everything seems to work fine.
on VBA, SPH or tracking station everything works fine. 

Steps to reproduce:
Delete all, and install RP1 express install (https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1) by cjan,
It installs the release #67. 

After downgrade to release #59 everything works fine again. I didn't test the release from 60 to 66.

My Graphic Card is AMD Radeon R7 M265.

I hope it could help you.

**Comment by R-T-B** [comment]
hmmm.  i have heard a few reports like this, all with latest release and all from AMD users.  The last release bumped up the shadow map size in an attempt to fix the shadow glitches, but I am guessing the AMD driver does not appreciate the size I choose.  I will make a hotfix soon addressing this.  Watch for it in next release.

The reason it works fine in night, is there are very few shadows at night time, heh.

**Comment by pack7df** [comment]
ok

**Comment by R-T-B** [comment]
The performance should be sufficiently optimized now that I am closing this.  Feel free to comment if it's still unacceptable to you.
