### ISSUE TITLE
Clouds mod and the mod itself broken 

### ISSUE THREAD

**Issue by Xev88gaming** [Kopernicus/Kopernicus#508]
Cant remember if its EVE or AVP But everytime i have this on it says that it was unable to load something idk but it also removes the clouds that the other mods i have on add. anything im doing wrong? please help!

**Comment by R-T-B** [comment]
Kopernicus does not actually do anything with clouds or visuals in the stock config, so it's unlikely to be a bug with us.

The most likely origin of your issue is scatterer.  The latest version is broken with a lot of mods that depend on it.  You might try reverting.
