### ISSUE TITLE
Kopernicus cannot load KSRSS

### ISSUE THREAD

**Issue by duuuno** [Kopernicus/Kopernicus#509]
Hello! Hope this is the right place to submit this.
I've installed KSRSS, Kopernicus, and some other mods that can be seen in a screenshot below. 

GameData Folder
![Screenshot from 2021-12-17 22-59-57](https://user-images.githubusercontent.com/96318578/146617467-3a3ad84a-cbf2-4712-8546-2d46b5bd0604.png)

In-menu screenshot
![Screenshot from 2021-12-17 23-13-37](https://user-images.githubusercontent.com/96318578/146618746-230cbfbd-caf0-4f1e-b8a2-bded6dd4f8b6.png)

Relevant files
[Kopernicus.log.txt](https://github.com/Kopernicus/Kopernicus/files/7738259/Kopernicus.log.txt)
[KSP.log.txt](https://github.com/Kopernicus/Kopernicus/files/7738261/KSP.log.txt)
[MMPatch.log.txt](https://github.com/Kopernicus/Kopernicus/files/7738262/MMPatch.log.txt)
[ModuleManager.ConfigCache.txt](https://github.com/Kopernicus/Kopernicus/files/7738264/ModuleManager.ConfigCache.txt)
[ModuleManager.log.txt](https://github.com/Kopernicus/Kopernicus/files/7738265/ModuleManager.log.txt)

**Comment by R-T-B** [comment]
I saw a similar issue on another bug...  it seems maybe JanitorsCloset is to blame?  Could you try removing that and see if it loads then?

If it does not, I will continue to help you of course.  But if it does, I would very much like to determine why it breaks Kopernicus, and would be in touch with said author.

**Comment by R-T-B** [comment]
After consulting with LinuxGuruGamer, maintainer of JanitorsCloset, it looks like you also need [SpaceTuxLibrary](https://github.com/linuxgurugamer/SpaceTuxLibrary/releases).

After that I believe it should work.

**Comment by R-T-B** [comment]
Closing because it's due to a missing dependency.
