### ISSUE TITLE
unable to charge a save or create one

### ISSUE THREAD

**Issue by mkc905** [Kopernicus/Kopernicus#513]
i have looked in the kopernicus log and it seems that it cant load something about moho but i don't know how to fix it :/
i put all the files below that the bug report asked me to sent.
plz help me 😢 

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/8190655/KSP.log)
[module manager cache + log kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/8190663/module.manager.cache.%2B.log.kopernicus.zip)

**Comment by mkc905** [comment]
i finally fixed it, the moho file had disappeared i just reinstalled the game and it fixed the prob

**Comment by HeronFord** [comment]
4
