### ISSUE TITLE
kerbin color abnormal

### ISSUE THREAD

**Issue by Aebestach** [Kopernicus/Kopernicus#514]
![contrast_1](https://user-images.githubusercontent.com/64588584/157481326-d17ebbf7-b226-46d1-94f8-1338484e2f9a.jpg)
![contrast_2](https://user-images.githubusercontent.com/64588584/157481354-6544bbba-511c-42a4-8adb-88ebe4b5c131.jpg)

Hi,another.
When I use Scatterer and kopernicus, Kerbin planet color has changed, and I am not very clear from which MOD problem (because I use Scatterer and kopernicus separately, there is no problem).
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/8216259/KSP.zip)
[Logs.zip](https://github.com/Kopernicus/Kopernicus/files/8216262/Logs.zip)

**Comment by Aebestach** [comment]
Scatterer V0.0831 
Kopernicus Release-85

**Comment by Aebestach** [comment]
![Mod List](https://user-images.githubusercontent.com/64588584/157483613-cac3d291-8085-4fe4-92d3-ae4c41febb50.jpg)

**Comment by R-T-B** [comment]
Thank you for these details.  I've been aware of some defects in the Ultra shader support of Kopernicus vs stock since I took over the project, but I haven't found a fix yet.  This sounds suspiciously like that.  Are you by chance using the Ultra shader?

I'll look into this again but as I have no leads as of  now, no promises for a speedy fix.

**Comment by Aebestach** [comment]
![work](https://user-images.githubusercontent.com/64588584/157565459-5e952710-105f-4830-8ef6-c924908a5861.png)
All of these options is set to 1 in Scatterer, then the problem is resolved.

**Comment by Aebestach** [comment]
However, in normal conditions, the color will become a bit dark.

**Comment by Aebestach** [comment]
![pic](https://user-images.githubusercontent.com/64588584/157567922-37aeff8b-cb3d-4ee8-8ba9-6052b0ffe81b.jpg)

**Comment by Aebestach** [comment]
I don't know if there is a Ultra shader, I use the default settings.

**Comment by R-T-B** [comment]
Can you post your settings.cfg in addition to what you have already provided?

It may help me understand what you are seeing.

**Comment by Aebestach** [comment]
[settings.zip](https://github.com/Kopernicus/Kopernicus/files/8219998/settings.zip)

**Comment by R-T-B** [comment]
Thanks for that.  In the KSP settings, I can see your shader was set to ultra.

I moved it to the setting lower that is advised, "high" and reuploaded your settings.cfg.  (You can also do this in the in-game KSP settings at main menu).

Try this and see if it improves your problem for now:

[settings.zip](https://github.com/Kopernicus/Kopernicus/files/8226311/settings.zip)

**Comment by Aebestach** [comment]
Currently, it is no problem.

**Comment by R-T-B** [comment]
> I tried it, the problem still appeared.

Darn.  I'm unsure what to say then, perhaps update your GPU drivers?  This should not be happening.

I'll run some more tests on my end and see if I can't replicate your issue.  Will update.

**Comment by Aebestach** [comment]
scatterer is installed correctly.
![screenshot](https://user-images.githubusercontent.com/64588584/157999416-3c56172d-215d-4f05-90fb-d21a14fb559b.png)
This is the result of my previous enquiry and I'll try to do so.

**Comment by Aebestach** [comment]
[Log.zip](https://github.com/Kopernicus/Kopernicus/files/8236848/Log.zip)
This is the log file after I reinstalled it, please check it out.
I tried rolling back the GPU driver and reinstalling scatterer and Kopernicus and the problem still reappeared.

**Comment by Aebestach** [comment]
![1](https://user-images.githubusercontent.com/64588584/158000394-137d9ccd-3b92-4559-953d-1a8c67820097.png)
By writing this cfg file, the problem has not reappeared yet.
```
@Kopernicus:FOR[KcalbelohSystem]
{
    @Body[Kerbin]
    {
        @ScaledVersion
        {
            @type = Atmospheric
            @Material
            {
                @Color = 1.5,1.5,1.5,1
            }
        }
    }
}
```

**Comment by Aebestach** [comment]
Then there is another problem.
It's that when you're close to the vessel there are no shadows, and when you're far away, the shadows are obvious. (especially when the scatterer is set to low)
![Snipaste_2022-03-12_11-00-11](https://user-images.githubusercontent.com/64588584/158001255-690b27f9-1b93-4204-b268-19eff9dba05c.jpg)
![Snipaste_2022-03-12_11-00-20](https://user-images.githubusercontent.com/64588584/158001256-5d75dcfe-7e75-4f60-a7c0-1a8abe6632c3.jpg)
This problem is alleviated when I set it to HIGH.

**Comment by R-T-B** [comment]
The shadows bug is known.  We are tracking it here:

https://github.com/Kopernicus/Kopernicus/issues/501

As for the rest, I don't know what causes it, but I am inclined to believe it is some issue with the newer scatterer.  I will leave this open just in case though, to keep an eye on things.

**Comment by Aebestach** [comment]
The problem of colour anomalies can only be solved by changing the configuration of the scatterer or by downgrading the scatterer version.

**Comment by Aebestach** [comment]
"use scatterer long distance shadows" is open.
Still, when I'm a bit away from my vessel, it comes up.
But for now it's playable and doesn't affect it much.

**Comment by R-T-B** [comment]
The shadows bug should now be fixed without scatterer and we discussed your other issue, so I am closing this for now as part of a broad "issue cleanup" to focus my efforts.  Feel free to open a new issue if there are still concerns.
