### ISSUE TITLE
planetary system error

### ISSUE THREAD

**Issue by HeronFord** [Kopernicus/Kopernicus#515]
kopernikus says its not able to load the custom planetary system that I have installed

**Comment by R-T-B** [comment]
I would need your ksp.log file to diqgnose further.  Find it in your ksp install directory (may be wise to zip it first)

**Comment by HeronFord** [comment]
hold on

**Comment by HeronFord** [comment]
idk how to put the file in it says >is not included in the list<

**Comment by R-T-B** [comment]
Uploading it here may end up being a pain.  Do you have another file host you can try?  Maybe dropbox, google drive, or something like that?

**Comment by HeronFord** [comment]
k lemme see

**Comment by HeronFord** [comment]
its gonna take a while to put it into the drive

**Comment by HeronFord** [comment]
here https://drive.google.com/file/d/1R00zv2QKjRgdWgYmWL3cWlsasSnY7Ven/view?usp=sharing

**Comment by R-T-B** [comment]
Sorry for the delay, been a bit busy.  Will look at this today or tomorrow worst case.

**Comment by R-T-B** [comment]
Ok finally got to have a look at your log (thanks for taking the time to upload it).

The log is repeating a lot of errors from a mod folder in gamedata called "Launchers Pack"  I'm not entirely sure what mod that is, but Kopernicus is likely just telling you your game is unstable due to this.  Maybe removing that would be enough?

If you still have issues after attempting that, tell me the planatary mod you are trying to load, and maybe I can help diagnose by trying it myself.

**Comment by HeronFord** [comment]
alright

**Comment by HeronFord** [comment]
I started up a new fresh one with it
and it says in the log that 2 cannot create config from file and 1 says config in file.
WRN 1. CityLights.cfg) Cannot create config from file. :Expansion_StellarAdventures:
WRN 2. Version1.2.cfg) config in file. :System_AlphaCentauri:
WRN 3. CityLights.cfg) Cannot create config from file. :System_AlphaCentauri:

**Comment by HeronFord** [comment]
WRN 4. Config in file. Kerbal Space Program\GameData\GU_Core\GU\Version1.2.cfg' contains no data.
WRN 5. Cannot create config from file. Kerbal Space Program\GameData\System_AlphaCentauri\GU\_Systems\_AlphaCentauri\_EVE\CityLights\CityLights.cfg
WRN 6. Cannot create config from file. Kerbal Space Program\GameData\Expansion_StellarAdventures\GU\_Systems\_StellarAdventures\_EVE\CityLights\CityLights.cfg

**Comment by HeronFord** [comment]
im gonna sleep

**Comment by R-T-B** [comment]
Yeah, sorry our schedules aren't overlapping too well.

Take a rest, I'll take another look at the log for potential issues and get back to you briefly here.

**Comment by R-T-B** [comment]
closing due to issue age as part of an issue cleanup...  If you still need help please open a new issue.
