### ISSUE TITLE
Kopernicus unloads PQS of body in current scene

### ISSUE THREAD

**Issue by georgedorn** [Kopernicus/Kopernicus#516]
I'm driving across Armstrong in Beyond Home, and the vehicle I'm driving to suddenly falls through the ground.  I checked the log, and find:

`[LOG 23:05:15.648] [OD] <--- OnDemandStorage.DisableBodyPQS destroying Armstrong`

This is off by itself, not in the flood of body removal that happens on a scene change.  17 seconds later, it loads Armstrong again, so when I fast-switch to the plummeting vessel and try to fly out of the interior, I crash into the ground from below...

It seems like an obvious sanity check would be to see if the current vessel is using a map before unloading it.  I'm not sure how viable that is given how event-driven this all is; I had a brief look at the code that does this but I'm not sure how to get the current vessel from within those event handlers.

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/8345062/KSP.log)

**Comment by R-T-B** [comment]
OnDemandStorage needs a real rework anyways, it does all sorts of odd unloads and reloads it shouldn't.  But yes a sanity check here would obviously be appropriate.  I'll consider this for next release, provided I can interpret enough of how OnDemandStorage works (I didn't write it, unfortunately, and am learning as I go).

Technically this should never happen, but I think the easiest fix is just a sanity check, like you said, rather than trying to chase down the origin cause.

**Comment by georgedorn** [comment]
Well, I attempted a fix, throwing this into `PQSMod_OnDemandHandler.cs`:

```
            if (FlightGlobals.ActiveVessel && FlightGlobals.currentMainBody.name == sphere.name)
            {
                Debug.Log("[OD] Not Disabling PQS of " + sphere.name + " as it is in this scene.");
                // stop it from trying again; this isn't accurate, 
                _isLoaded = false;
                return;
            }
```

But while that does seem to stop it from being unloaded, I've tested without this fix on a similar scene and can't make it happen again.  So while this check might still be a good idea, it's not the cause of the bug, sadly.

Or it is, but only when a vesel is parked on specific chunks of terrain?  Not being able to reproduce my own bug is deeply frustrating.

**Comment by R-T-B** [comment]
I don't really know.  The whole system is kind of a convuluted mess.  I think your attempted fix is probably as good idea as any, and I may borrow it for next release if you don't mind. (with credit, of course).

**Comment by georgedorn** [comment]
Feel free, I'm just not sure it actually fixes anything.  I can't be sure it _doesn't_ fix anything, either, so...

One thing I noticed is that opting to not remove the PQS causes the `LateUpdate()` function to be called every few hundred milliseconds.  I suspect that's the check at the top, thus my setting `_isLoaded = False` to make it bail early from the function, but it'd be better to figure out how to make the event handler system to stop calling it completely.

Or maybe this is just normal and it already constantly spams that function at all times; I'm not a game dev.

**Comment by R-T-B** [comment]
LateUpdate is supposed to fire regularly, it's some sort of Unity thing related to Monobehaviors.  I wouldn't worry about it as long as you shortcut it to not unload the present body.

I've got some time now and will push a test build to beta testers.  I would expect a release shortly.

**Comment by georgedorn** [comment]
Ah, good, I look forward to the improved version;  I wanted a mechanism for comparing objects and not just strings, because just comparing strings felt a bit fragile.  But I couldn't figure out how to get from a `CelestialBody` to whatever the PQS sphere object is.

Of course, if a creator of a system mod names two bodies the same thing, there's probably a hundred other things that would break anyway.

**Comment by R-T-B** [comment]
Confession time:  I use string comparisons sometimes internally, so yeah, probably a few things would break if someone really went using identical names.

**Comment by R-T-B** [comment]
This has been working well for a bit, so closing for now.  If anyone is still having this issue they can comment here and I'll gladly reopen this.
