### ISSUE TITLE
Kopernicus loading error

### ISSUE THREAD

**Issue by Grootmaster47** [Kopernicus/Kopernicus#519]
I installed Kopernicus in order to load the Parallax mod, and when the game loaded, it told me that there had been an "exception in the loading process" and told me that my custom planetary pack couldnt be loaded, but I play with the stock solar system, only having KER, Mechjeb and a few graphic mods installed. This is also a new install on a new PC, and the exact same mods worked on my old PC without any trouble.

Link to the KSP.log, ModuleManager.ConfigCache and Kopernicus folder: https://1drv.ms/u/s!AtUOdKukw2jJsCdbLdo2knRopEHL?e=cRpMZk

**Comment by R-T-B** [comment]
Hello.

Kopernicus is not the origin of your error, it is however informing you of an error it is detecting with your Principia setup.  It looks like you installed the Principia-StockTextures zip but not the base Principia mod.  Both are needed.  If you correct that, I'm sure it will load ok.  Thanks!

**Comment by Grootmaster47** [comment]
Thank you very much, i thought i had it installed, but apparantly, i forgot it. Thanks!
