### ISSUE TITLE
The Inland KSC, "Baikerbanur", is completely messed up

### ISSUE THREAD

**Issue by Shaddatic** [Kopernicus/Kopernicus#521]
I went over and found that it looked like only the main building existed. 

I took a closer look and found that all 3 models (VAB, Launch Pad, & Dish) all spawned inside each other in the wrong spot. If I had to guess, all 3 models are linked with different translation positions and Kopernicus ignores the translations leading to all of them spawning inside each other at the base position.

I didn't see anyone else report this, I hope my explanation helps! I might be completely wrong on what caused it, but that's how it appears to me!

**Comment by R-T-B** [comment]
Interesting...  tested on a stock + Kopernicus only install and it still happens, right?  If so, this is the most major bug to be missed in some time...  Thank you very much for the report.  I will see about fixing it as soon as I can identify why it occurs.

**Comment by Shaddatic** [comment]
Yes, only Kopernicus! Glad to be of help!

**Comment by R-T-B** [comment]
I've looked into this.  It does appear the inland KSC is delivered as multiple components and Kopernicus just sticks them all in the same spot, oblivious to this.  Fixing it will take some fine tuning and may not make it into next releaee but it is now on our radar.

**Comment by R-T-B** [comment]
Pinning this as it's one of the few remaining actual bugs.

Sadly, I have no idea how to fix it.  Feedback welcome.

**Comment by R-T-B** [comment]
Fixed in release 146.
