### ISSUE TITLE
[RSS/RO] Phobos running away

### ISSUE THREAD

**Issue by Capkirk123** [Kopernicus/Kopernicus#522]
After a particularly eventful Phobos mission, I have compiled all Phobos-related bugs here

1. Orbits which encounter Phobos do not stay still. If I set up a flyby of Phobos, my orbit will constantly shift at a few hundred m/s unless I enter timewarp. I have to set up an encounter and immediately timewarp to SoI change, or I lose it

2. Once in orbit of Phobos, exiting timewarp causes my position around Phobos to jump around. All orbital elements stay the same except LAN

3. Upon landing on Phobos, Phobos began attempting to "run away", deviating heavily from the correct orbit. This was visible in both map view and flight view, with Phobos visibly above the wrong part of Mars. My probe on the surface of Phobos was fine though, Phobos ground behaved normally, it was just dragged along with Phobos. Upon taking off and leaving Phobos SoI, my probe immediately jumped thousands of kilometers to the "correct" position above Mars. Phobos stayed in the incorrect position, far from it's orbit lines. Once again, this was both in the map and flight screen, MechJeb target window agreed that Phobos was on the opposite side of Mars. Returning to the Space Center returned Phobos to the correct position.

I have seen 1 and 2 before, 3 is new
1 and 2 happen every time from what I can tell
Deimos functions completely normally. A half dozen probes have only shown this behavior with Phobos.

EDIT:
Installing the Kopernicus watchdog fixes all of these

**Comment by R-T-B** [comment]
FYI: I'm leaving this around as a reminder that we need a better fix for these issues than the watchdog, but am glad it is working for the time being.

**Comment by R-T-B** [comment]
The watchdog is finally replaced with something better, so closing this.
