### ISSUE TITLE
Solar panel output is doubled

### ISSUE THREAD

**Issue by Metatheria** [Kopernicus/Kopernicus#524]
In the right click menu, the "Energy flow" value is half what the actual output of the solar panels is.
Here is an example: 
![image](https://user-images.githubusercontent.com/70017671/169822538-715653dd-a783-419b-bfca-2e96b157c96e.png)

And here is the electric charge actually being produced (this panel is the only source in the ship):
![image](https://user-images.githubusercontent.com/70017671/169822636-5d0097ff-886d-4a40-9ba9-18b393a9b29b.png)

I suspect Kopernicus is adding its custom solar panel output to the stock game panel output instead of replacing it.

**Comment by R-T-B** [comment]
Interesting.  This is with the latest build (stable release 90) and the correct multistar cfg file I assume?

I will run some tests to confirm when I get home.

**Comment by R-T-B** [comment]
Yeah, I was unable to replicate this.  With the multistar cfg I got the performance expected tracking the sun in the stock system.  I expect you are either running an out of date version or I am missing some detail of your configuration...  you'll have to elaborate in the latter case.

**Comment by Metatheria** [comment]
Turns out it was a conflict with some other mods, I was unable to replicate with a clean install. Sorry!

**Comment by R-T-B** [comment]
not a problem, thanks for updating me!
