### ISSUE TITLE
Giving me pop up message saying it was skipped during loading

### ISSUE THREAD

**Issue by Milipanda** [Kopernicus/Kopernicus#526]
![Screenshot 2022-06-02 191136](https://user-images.githubusercontent.com/106787993/171767903-8402e2a2-5407-4e94-8240-e3f2c1afb423.png)
It says this whenever I try booting it up on version 1.12.1 despite it being made for this version

**Comment by R-T-B** [comment]
The version number is somewhat misleading.  Technically 1.12.1 will run on 1.12.x, 1.11.x, and 1.9.x, meaning any minor version in all those releases.

I'd need a log file to diagnose what is wrong in your situation.  You should be able to find a KSP.log in your install root, upload that.

**Comment by R-T-B** [comment]
closing as outdated.
