### ISSUE TITLE
Conflict with Strategia

### ISSUE THREAD

**Issue by OperativeLoop** [Kopernicus/Kopernicus#527]
Looks like the KopernicusWatchdog body is not playing nicely with Strategia. 

[EXC 08:56:35.788] ArgumentException: 'KopernicusWatchdog' is not a valid CelestialBody.
	ContractConfigurator.ConfigNodeUtil.ParseCelestialBodyValue (System.String celestialName) (at <ef0243a06f2841fe9bf57034a334902e>:0)
	ContractConfigurator.ConfigNodeUtil.ParseSingleValue[T] (System.String key, System.String stringValue, System.Boolean allowExpression) (at <ef0243a06f2841fe9bf57034a334902e>:0)
	System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
	Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
	System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
	ContractConfigurator.ConfigNodeUtil.ParseValue[T] (ConfigNode configNode, System.String key, System.Boolean allowExpression) (at <ef0243a06f2841fe9bf57034a334902e>:0)
	ContractConfigurator.ConfigNodeUtil.ParseValue[T] (ConfigNode configNode, System.String key, T defaultValue) (at <ef0243a06f2841fe9bf57034a334902e>:0)
	Strategia.CurrencyOperationByBody.OnLoadFromConfig (ConfigNode node) (at <ad1f24c047af4716ace30351b02ea8a1>:0)
	Strategies.StrategyEffect.LoadFromConfig (ConfigNode node) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	Strategies.Strategy.AddEffect (Strategies.StrategyEffectConfig cfg) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	Strategies.Strategy.SetupConfig (Strategies.StrategyConfig cfg) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	Strategies.Strategy.Create (System.Type type, Strategies.StrategyConfig config) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	Strategies.StrategySystem.LoadStrategies (System.Collections.Generic.List`1[T] stratNodes) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	Strategies.StrategySystem+<OnLoadRoutine>d__27.MoveNext () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
)

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/8834019/KSP.log)

**Comment by R-T-B** [comment]
Yes, we produced a fork to fix this until we can finally end the watchdogs lifecycle in the hopefully near future.

Fork here:

https://github.com/R-T-B/Strategia/releases

More on the watchdog eventual endgame goals here:

https://forum.kerbalspaceprogram.com/index.php?/topic/200143-181-1122-kopernicus-stable-branch-last-updated-june-3rd-2022/&do=findComment&comment=4141016

**Comment by R-T-B** [comment]
This is fixed with release-98, no longer requiring custom work arounds like I advised above.  Please update and all should be well.
