### ISSUE TITLE
Kopernicus would not change the color of the KSC ground and also would skip its Material subnode

### ISSUE THREAD

**Issue by RMSpace** [Kopernicus/Kopernicus#528]
https://drive.google.com/file/d/1Oc0fT4ZGxn_TELQzcS2M-fenrAXwi_nM/view?usp=sharing

For some reason, the material subnode on the SpaceCenter node would be skipped by Kopernicus. Is this a glitch or a Heisenbug?

**Comment by R-T-B** [comment]
Other mods use the material subnode and successfully change grass color.  I am still trying to determine why yours does not, but as a start, you have to have isHomeWorld set to true.

**Comment by R-T-B** [comment]
This was fixed via helping the user with his configs.
