### ISSUE TITLE
I teleported to one of my planets, then teleported back to Kerbin, and got this bug.

### ISSUE THREAD

**Issue by RMSpace** [Kopernicus/Kopernicus#529]
![Screenshot (212)](https://user-images.githubusercontent.com/95692784/174291024-7b81bf03-578d-4502-9a5e-0a8e3edf32c6.png)

**Comment by R-T-B** [comment]
This should be fixed post release-123ish

**Comment by R-T-B** [comment]
Talked with user, think he is experiencing the stock unfixable teleport/hyperedit bug.

Leaving open for a bit just in case.
