### ISSUE TITLE
Not sure if this is related but here is part of my 1.7G log file from singl session 

### ISSUE THREAD

**Issue by byt3c** [Kopernicus/Kopernicus#530]
My game is getting pretty slow when reloading ships. I have two motherships around 800-1k parts with docked rovers and shuttles which seem strange as game gets seriously slowed down with each ship switch. 

I found my log files to be pretty big so there might be a clue what is going on. I'm not sure it is kopernicus related, but I decided to give it a try and ask where should i search further.

This repeats for hundreds of MB, and there are places w where log changes a bit 

[LOG 00:09:34.922] [KSPI]: searching fuelModes for alternative for fuel type Uranium Oxide
[WRN 00:09:34.922] [KSPI]: failed to find sufficient resource for FissionNTR
[LOG 00:09:34.922] [KSPI]: searching fuelModes for alternative for fuel type Plutonium TWR
[WRN 00:09:34.922] [KSPI]: failed to find sufficient resource for FissionTWR
[EXC 00:09:34.927] NullReferenceException
	VehiclePhysics.VPWheelCollider.set_steerAngle (System.Single value) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 00:09:34.928] NullReferenceException
	VehiclePhysics.VPWheelCollider.set_steerAngle (System.Single value) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 00:09:34.928] NullReferenceException
	VehiclePhysics.VPWheelCollider.set_steerAngle (System.Single value) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 00:09:34.934] NullReferenceException: Object reference not set to an instance of an object
	ScaledSpaceFader.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 00:09:34.964] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 00:09:34.965] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 00:09:34.965] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

this section repeats for some MB

then different ones are separated similarly like this : 

[EXC 01:05:36.967] NullReferenceException
	VehiclePhysics.VPWheelCollider.set_steerAngle (System.Single value) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:36.968] NullReferenceException
	VehiclePhysics.VPWheelCollider.set_steerAngle (System.Single value) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:36.968] NullReferenceException
	VehiclePhysics.VPWheelCollider.set_steerAngle (System.Single value) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:36.971] NullReferenceException: Object reference not set to an instance of an object
	ScaledSpaceFader.Update () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:37.001] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:37.001] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:37.002] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 01:05:37.002] NullReferenceException
	VehiclePhysics.VPWheelCollider.UpdateWheelCollider (UnityEngine.WheelCollider wheelCol) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VPWheelCollider.FixedUpdateVehicle () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdateVehicleBehaviours () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	VehiclePhysics.VehicleBase.FixedUpdate () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by byt3c** [comment]
![obraz](https://user-images.githubusercontent.com/38114978/175383817-b8551ded-71c5-4990-9ab1-1ba69b9d2a8d.png)

**Comment by byt3c** [comment]
[persistent.zip](https://github.com/Kopernicus/Kopernicus/files/8970369/persistent.zip)
This is my current save game.

**Comment by byt3c** [comment]
[Uploading KSP.log…]()
head of my latest log

**Comment by byt3c** [comment]
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/8970692/KSP.zip)
Here is my latest head of log file

**Comment by R-T-B** [comment]
Thanks for the additional data.

As I said before, this does not appear to be a Kopernicus bug but there is absolutely no reason I can't try to help.  I just need the answer to some basic questions.

For starters:  What is in the "_LOCAL" folder above?

**Comment by byt3c** [comment]
Thank you very much for assistance. As for folder, It has TweakScale folder inside. I probably tried that mod before but it was causing problems. I'll try to remove that.
There is a mod that adds Vulture star system to  the game. I sent probe several "years" ago there, maybe it is getting close and starts to trigger some errors. 
[Dune.zip](https://github.com/Kopernicus/Kopernicus/files/8973556/Dune.zip)

**Comment by byt3c** [comment]
[ERR 12:33:02.205] Exception handling event onProtoVesselLoad in class <>c:System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at UBI.FetchUBIs (CelestialBody body) [0x00000] in <e9185897764f4f3095459d7f11df6538>:0 
  at UBI.GetBodies (System.String ubi, CelestialBody[] localBodies) [0x00022] in <e9185897764f4f3095459d7f11df6538>:0 
  at UBI.GetBody (System.String ubi, CelestialBody[] localBodies) [0x00000] in <e9185897764f4f3095459d7f11df6538>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.TransformBodyReferencesOnLoad (GameEvents+FromToAction`2[A,B] data) [0x00025] in <e9185897764f4f3095459d7f11df6538>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility+<>c.<Awake>b__5_2 (GameEvents+FromToAction`2[A,B] d) [0x00000] in <e9185897764f4f3095459d7f11df6538>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 

[EXC 12:33:02.206] NullReferenceException
	UBI.FetchUBIs (CelestialBody body) (at <e9185897764f4f3095459d7f11df6538>:0)
	UBI.GetBodies (System.String ubi, CelestialBody[] localBodies) (at <e9185897764f4f3095459d7f11df6538>:0)
	UBI.GetBody (System.String ubi, CelestialBody[] localBodies) (at <e9185897764f4f3095459d7f11df6538>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility.TransformBodyReferencesOnLoad (GameEvents+FromToAction`2[A,B] data) (at <e9185897764f4f3095459d7f11df6538>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility+<>c.<Awake>b__5_2 (GameEvents+FromToAction`2[A,B] d) (at <e9185897764f4f3095459d7f11df6538>:0)
	EventData`1[T].Fire (T data) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(FromToAction`2)
	ProtoVessel:.ctor(ConfigNode, Game)
	FlightState:.ctor(ConfigNode, Game)
	Game:.ctor(ConfigNode)
	GamePersistence:LoadGameCfg(ConfigNode, String, Boolean, Boolean)
	MainMenu:OnLoadDialogPipelineFinished(ConfigNode, String)
	<>c__DisplayClass83_0:<OnLoadDialogFinished>b__0(ConfigNode)
	KSPUpgradePipeline:Process(ConfigNode, String, LoadContext, Callback`1, Callback`2)
	MainMenu:OnLoadDialogFinished(String)
	LoadGameDialog:ConfirmLoadGame()
	LoadGameDialog:OnButtonLoad()
	UnityEngine.EventSystems.EventSystem:Update()
[ERR 12:33:02.214] Exception handling event onProtoVesselLoad in class <>c:System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at UBI.FetchUBIs (CelestialBody body) [0x00000] in <e9185897764f4f3095459d7f11df6538>:0 
  at UBI.GetBodies (System.String ubi, CelestialBody[] localBodies) [0x00022] in <e9185897764f4f3095459d7f11df6538>:0 
  at UBI.GetBody (System.String ubi, CelestialBody[] localBodies) [0x00000] in <e9185897764f4f3095459d7f11df6538>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility.TransformBodyReferencesOnLoad (GameEvents+FromToAction`2[A,B] data) [0x00025] in <e9185897764f4f3095459d7f11df6538>:0 
  at Kopernicus.RuntimeUtility.RuntimeUtility+<>c.<Awake>b__5_2 (GameEvents+FromToAction`2[A,B] d) [0x00000] in <e9185897764f4f3095459d7f11df6538>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 

[EXC 12:33:02.215] NullReferenceException
	UBI.FetchUBIs (CelestialBody body) (at <e9185897764f4f3095459d7f11df6538>:0)
	UBI.GetBodies (System.String ubi, CelestialBody[] localBodies) (at <e9185897764f4f3095459d7f11df6538>:0)
	UBI.GetBody (System.String ubi, CelestialBody[] localBodies) (at <e9185897764f4f3095459d7f11df6538>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility.TransformBodyReferencesOnLoad (GameEvents+FromToAction`2[A,B] data) (at <e9185897764f4f3095459d7f11df6538>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility+<>c.<Awake>b__5_2 (GameEvents+FromToAction`2[A,B] d) (at <e9185897764f4f3095459d7f11df6538>:0)
	EventData`1[T].Fire (T data) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(FromToAction`2)
	ProtoVessel:.ctor(ConfigNode, Game)
	FlightState:.ctor(ConfigNode, Game)
	Game:.ctor(ConfigNode)
	GamePersistence:LoadGameCfg(ConfigNode, String, Boolean, Boolean)
	MainMenu:OnLoadDialogPipelineFinished(ConfigNode, String)
	<>c__DisplayClass83_0:<OnLoadDialogFinished>b__0(ConfigNode)
	KSPUpgradePipeline:Process(ConfigNode, String, LoadContext, Callback`1, Callback`2)
	MainMenu:OnLoadDialogFinished(String)
	LoadGameDialog:ConfirmLoadGame()
	LoadGameDialog:OnButtonLoad()
	UnityEngine.EventSystems.EventSystem:Update()

**Comment by byt3c** [comment]
now after some updates i have a lot of these

**Comment by R-T-B** [comment]
Looks like some planet is missing it's reference body maybe?

I hate to say this, but at this point I might just start from scratch, and install your mods one by one to find what is breaking things.  I know that's painful, sorry.

**Comment by byt3c** [comment]
I don't want to bother you too much. If you tell me how i might try it myself. I love KSP and might help you with code :)

**Comment by R-T-B** [comment]
Heh, I appreciate the offer but as far as helping with Kopernicus it's quite the nightmare project for a novice (no offense).  I get lost in this codebase at times still. ;)

If you need help with "starting from scratch" with your mods though, I can post a quck guide.  Just let me know. :)
