### ISSUE TITLE
Kopernicus leaves the game on a constant loading screen 

### ISSUE THREAD

**Issue by PlatinumParakeet** [Kopernicus/Kopernicus#536]
When Kopernicus is installed, it stays on the black loading screen with the solar system in the corner and I can never get to the menu.  Nothing seems to appear in logs. I'm not sure if it's an issue with kopernicus itself or my pc. I've found no solution to this anywhere else and I don't know where else to go.

**Comment by R-T-B** [comment]
Hello.  Usually that is a symptom of an incorrect install.  Can you show me your Kopernicus subfolder in gamedata, like a screenshot?  Maybe I can then understand what happened.

**Comment by PlatinumParakeet** [comment]
Here are some photos of the subfolder. I've never really installed many mods before this so i'm still learning.

![image](https://user-images.githubusercontent.com/113246375/189524631-51b4a984-3b69-4830-b30e-f2e53fd60e85.png)
![image](https://user-images.githubusercontent.com/113246375/189524642-914f28f6-d2b8-4b54-ab5b-2b3455af3ef7.png)
![image](https://user-images.githubusercontent.com/113246375/189524649-bd4ce924-c9d7-4c7a-bddc-a97d7337fb8d.png)
![image](https://user-images.githubusercontent.com/113246375/189524653-8edddd06-aea7-4910-9235-bc74f1c0bf81.png)
![image](https://user-images.githubusercontent.com/113246375/189524656-d2dd5cc5-5679-4bbd-b964-33679056a1e7.png)
![image](https://user-images.githubusercontent.com/113246375/189524662-ccd0b3c0-4fa9-4bb3-bdfd-564ec8b5912b.png)
![image](https://user-images.githubusercontent.com/113246375/189524667-8b9bd939-1099-46e0-8461-fc0c277fb618.png)

**Comment by R-T-B** [comment]
That does appear correct so far (good job!).  I would then ask you to upload your KSP.log file, found in the "Kerbal Space Program" install directory root.

If I get those details, I can say for sure what is going on.

**Comment by PlatinumParakeet** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/9542893/KSP.log)

**Comment by R-T-B** [comment]
I see you have more than one ModuleManager installed, as per this line in the logfile:

ModuleManager.4.1.3.dll
ModuleManager.4.2.1.dll
ModuleManager.4.2.2.dll

I would remove all of them except the latest (ModuleManager4.2.2.dll) from gamedata, and try again.

**Comment by PlatinumParakeet** [comment]
Nope, that hasn't worked. I'll try reducing how many mods I have.

**Comment by R-T-B** [comment]
That would be my advice.  Something somewhere is causing a conflict or incompatibility, and trial and error may be the best way to sort out who.

If you are still struggling, I can take another look this evening, as well.

**Comment by Gameslinx** [comment]
You have a lot of junk in GameData that looks like the internals of mods. Stuff like "FX, Graphics, Localization, Objects, FuelTank" it's a complete mess, and that's probably stopping you from loading

**Comment by R-T-B** [comment]
I am closing tickets older than mid October in hopes the last bugfix release helped you.  If you are still experiencing the issue, please feel free to reopen this and I will prioritize your request.
