### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process 

### ISSUE THREAD

**Issue by ZiiMs** [Kopernicus/Kopernicus#538]
Not quite sure why this suddenly broke. It was working yesterday then today it just stopped working. Anytime I try to load or open settings it just loads forever. I do use a lot of mods but it was working until today.

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/9560252/Logs-Kopernicus.zip)

**Comment by ZiiMs** [comment]
It was having issues with Spectra, removing it solved it.

**Comment by XKaLage** [comment]
how to do it?

**Comment by R-T-B** [comment]
I am closing tickets older than mid October in hopes the last bugfix release helped you.  If you are still experiencing the issue, please feel free to reopen this and I will prioritize your request.
