### ISSUE TITLE
  Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by linus127** [Kopernicus/Kopernicus#539]
I tried to load the game and then it told me that kopernicus wasnt able to load. So I removed all my mods and installed them again five times in the last days but it dont want to work. I also deleted ksp and reinstalled it again and now i need your help. So i ask you to help me.
 
 
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/9636112/KSP.log)
 And i think this is not the way to upload the ksp.log but i hope you can open it

**Comment by R-T-B** [comment]
You did fine re the upload.  I'm presently a bit busy with some side projects but I will take a look at your log in a day or two.  Sorry for the delay.

**Comment by linus127** [comment]
no problem. take your time. you also can look in a week or something.

**Comment by R-T-B** [comment]
Thank you for understanding.  Will look as soon as able (just got a new puppy so a bit sidetracked to say the least lol).

**Comment by linus127** [comment]
This is understandable. Raising a puppy is not easy. I hope it won't be too exhausting that you also have to worry about my problems. 😅

**Comment by linus127** [comment]
Hi it's Linus here,
It's been a month since I wrote this Issue. And I just wanted to ask if you found the problem in the Ksp.log.

**Comment by R-T-B** [comment]
Thank you for your patience,

I'll give your log a look tonight.  I just forgot about this on my queue, honestly.  Apologies there!

**Comment by R-T-B** [comment]
This looks to me like a corrupt install.  If you are on steam, you can try validating your game file integrity (google can help you with this).  Otherwise, a full reinstall and reapplication of your mods may be called for.

**Comment by R-T-B** [comment]
Also, this is just an afterthought, but you may find errors similar to this if you do not install the KSPHarmony dependency on newer kopernicus builds.

**Comment by linus127** [comment]
I have tried everything now and am now desperate. I even completely uninstalled and reinstalled the mods and the game. I even repeated this on the second hard drive but the game did not work with the mods.

**Comment by R-T-B** [comment]
I'll take another look right now.  This is a very odd case indeed.  I must be missing something.

**Comment by linus127** [comment]
![image](https://user-images.githubusercontent.com/114140295/199342297-4fabffb6-8ecb-4f48-8888-e2d74693b021.png)
Thanks for the help and sorry for the late reply. Here is the screenshot.

**Comment by R-T-B** [comment]
ok, thanks for that.  I'm going back throughh your logfile with this new data, hope to have more info within 24 hours,

**Comment by R-T-B** [comment]
Sorry for the delay, but I think I figured it out.

You have rss and parallax installed, I do not believe these are compatible without a  lot of work and a seperate pack of some kind.  I would either research what is wrong there, or remove one of the incompatible mods.  You should then load fine.

Sorry for the wild goose chase.

**Comment by linus127** [comment]
That was the problem. I deleted the parallax folder and the game worked again. I don't know how to thank you but I am eternally grateful to you. I really really appreciate your help. Thank you ☺️🙏

**Comment by R-T-B** [comment]
Oh, no worries!  Just glad we got it working after a month and a half lol.
