### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by 13187949038** [Kopernicus/Kopernicus#540]
I encountered an exception. When I tried to open the Kerbal Space Program, Kopernicus told me that loading failed and asked me to check the ksp.log file

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/9640124/KSP.log)

This is not the format of the KSP log file correctly, but I hope you can open him and help me solve the problem. Thank you very much.

This is my KSP root directory information: tree.log
And my Kerbal Space Program runs in Archlinux

[tree.log](https://github.com/Kopernicus/Kopernicus/files/9640134/tree.log)

**Comment by 13187949038** [comment]
Which file do you need to tell me, before solving the problem, I will not open the Kerbal Space Program.
Thanks

**Comment by R-T-B** [comment]
I apologize for the delay in response, I am currently quite busy with some work outside of github (training a new puppy, as mentioned elsewhere).  As such it may be a few days before I can respond to support requests.

But just FYI, the data I need to respond is here, you did fine.  I just need to find time, lol.

**Comment by RacerX285** [comment]
Bump.  I have the same problem. I'm running ~100 mods fine through CKAN. I can run with EVE, Scatterer, Kopernicus v1.12.1-139 AND Galaxies Unbound A Stellar Odyssey v1.3 just fine...

But when I try to actually install any of the standard planet packs from StarCrusher96; I get a log with thousands of Kopernicus "nullreferenceexceptions".  When I had them all loaded there was a specific exception referencing the planet Alva, so I left the Alpha Centauri system out. Same problem.  Here is a typical exception instance:

==============================================================================
[EXC 12:22:19.071] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.GetLocalTimeAtPosition (Vector3d wPos, CelestialBody cb) (at <af3bde20e44f42d59ddd5d4c4a02d8cf>:0)
	Sun.GetLocalTimeAtPosition (System.Double latitude, System.Double longitude, CelestialBody body) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	DayNightGameObjectSwitch+<UpdateObjects>d__17.MoveNext () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	DayNightGameObjectSwitch:Update()
==============================================================================

I would upload my KSP log but it ends up at 142MB thanks to this. Any help is appreciated!

**Comment by R-T-B** [comment]
Is this still an issue?  Working through my support backlog for one final bugfix release, and would like to know.

**Comment by R-T-B** [comment]
Closing as part of a broader cleanup due to inactivity. Reopen if you still have this issue or need more support.
