### ISSUE TITLE
Shader/Shadow glitch

### ISSUE THREAD

**Issue by raidernick** [Kopernicus/Kopernicus#542]
There is a glitch with EnableKopernicuShadowManager. When this is turned on the shadows look correct when you are zoomed close to the craft, but once you zoom past a certain point an odd shadow effect appears on the individual parts. It almost looks like an inverse shadow where it's being cast on itself from the opposite side of the mesh.

The image on the left shows what the shadows _should_ look like and the right shows what they look like when you zoom out past a certain point.
![alt tag](https://i.imgur.com/pjoceS9.png)

I can confirm that this issue is not related to scatterer or EVE as the issue remains even if those are not installed.

**Comment by R-T-B** [comment]
Replying to this to remind myself we need to look at this before the next release.

**Comment by raidernick** [comment]
How goes the work on fixing this? @R-T-B

**Comment by R-T-B** [comment]
Unfortunately, I'm not quite sure what's causing it, so work is slow.  But I have an expert in such things who is going to take a look soon, so hopefully we'll get some results before next release.

**Comment by R-T-B** [comment]
I had an epiphany just now.

Could it be the old (bugged) stock shadows are running alongside our ShadowManager?

Is there a way to disable stock shadows to test that idea?

**Comment by R-T-B** [comment]
Ok, I think I narrowed this issue down.  I don't see it on a stock install barebones, at least not anymore.  I DO get something very similar when I have TUFFX installed and have either ambient occulusion or HDR turned on.  Is it possible you are using anything similar?

Out of the box though, I am unable to replicate this issue, at least not with the latest builds.  If you are still having this issue with a stock install + Kopernicus, post your game settings.cfg please (Not Kopernicus_Config.cfg, the game root settings.cfg one).

**Comment by raidernick** [comment]
I'm not using any post processing. I originally encountered the issue on a barebones RSS/RO install but made sure to test it on a full stock install and that was the image i first posted there. I have not tested it on stock since then, but I can confirm that the issue is still there on a base RSS/RO install(nothing extra but the required mods to run that install). 

Even if it didn't exist in stock, it's still kind of a major issue to be happening on a base rss/ro install as the user base for that is so large and it requires kopernicus to work.

Here is my settings file: https://pastebin.com/5swsjXxd

**Comment by raidernick** [comment]
Actually, now that I think about it, the issue is super visible on any parts using the specular shader from the unity part tools. The stock parts are very flat looking and a lot of mod parts use specular or bumped specular, including my own. When these parts are used the shadow bug looks horrendous, it's extremely dark and abrupt changing compared to it's visibility on the stock parts.

**Comment by R-T-B** [comment]
Yes, I agree something is happening and I'm not dismissing the bug, so have no concern there.  I'm just trying to narrow down where.

I had a thought it could be the stock shadows interfering, and I still want to test that theory.  Can you try the following settings.cfg?  It's the same one you provided, just with stock shadows disabled entirely.  Maybe it will look more normal?  If so I can force that when the Kopernicus shadow manager is on.

[settings.zip](https://github.com/Kopernicus/Kopernicus/files/10857543/settings.zip)

**Comment by R-T-B** [comment]
If anyone is experiencing this issue, please try the settings file above.  I need someone who experiences the issue to test for me, since I can't replicate it anymore for whatever reason.

**Comment by raidernick** [comment]
Sorry it took me so long to get back to you, I tried that settings file and it did not make a difference. The issue is still there.

**Comment by R-T-B** [comment]
darn, it could just be my particular parts aren't showing it well...  hmmm...  I will try some other parts in the near future.

Can I get a KSP.log from you, as well?  Feel free to delete any existing one and generate a fresh one.  It should let you upload it in a .zip file.  It is located in your install root.

**Comment by R-T-B** [comment]
Just want you to know I was able to see it with some Restock parts so you aren't crazy...  it seems more minor on my rig but it's there.  Maybe your gpu shows it worse?  A logfile would tell me more there.

This will be a priority for next release.

**Comment by R-T-B** [comment]
Release-163 contains a rewrite of the shadow cascades system that drives ShadowManager.  I'm curious if it has improved things.

**Comment by raidernick** [comment]
It's actually worse with the latest release. The shadows now look like the bad "stock" shadows and the problem with zooming in and out and them disappearing/changing abruptly is still there.

**Comment by R-T-B** [comment]
> It's actually worse with the latest release. The shadows now look like the bad "stock" shadows and the problem with zooming in and out and them disappearing/changing abruptly is still there.

You can try setting the shadow range to something higher, say, 50000, in the settings GUI.  That is what scatterer used with this same system IIRC.  I chose the low setting because most people prefer sharp details up close but it may be a stylistic thing.

**Comment by raidernick** [comment]
I just tried that and it still has the same problem. The shadows look "stock like" and pop in/out abruptly just at a further distance. Extremely close up the shadows look fine, zoom out a bit and the ugly "stock" shadows show up and they stay there until you zoom out enough where they abruptly disappear. Then zoom out a bit more and the entire rocket turns black. Then zoom out even more and the shadows abruptly disappear entirely.

**Comment by R-T-B** [comment]
Are you by chance on OpenGL?  That would be the case if on Mac or Linux.

If not, I do have some ideas to improve this.  The system we use now is largely made with help from blackrack of Scatterer, and I'll be running my ideas by him, but expect another attempt to fix this in the next few days.  Feel free to use whatever build is "least bad" for you in the interim.

**Comment by raidernick** [comment]
I'm using DX11. Here is an image showing the 4 stages of weird shadows as you start from zoomed far in to zoomed out.

https://i.imgur.com/m8lVwtt.png

**Comment by R-T-B** [comment]
I actually think I might know what's going on.  If you have a second, I'll be posting a debug build in a moment for testing.  If not, you can check it out tomorrow.  Thank you very much for all the details.

**Comment by R-T-B** [comment]
Here is a dev build to test when you are able, I think it may massively help:

[Kopernicus-1.12.1-164dev.zip](https://github.com/Kopernicus/Kopernicus/files/10975953/Kopernicus-1.12.1-164dev.zip)


You should probably set a higher range for the proper affect than stock 10000, btw.

**Comment by raidernick** [comment]
I think you might have fixed it. I need to do more extensive testing to be sure the shadows are actually still working though. Those weird artifacts and pop in/out aren't there anymore but I'm not 100% sure the shadows are working at all still. There's shadows on the ground but I'm not sure self shadows are working.

**Comment by raidernick** [comment]
It appears to be fixed. All of the terrible looking shadows and gone. Now the only thing I have a question about is what the shadow range limit should be set to. Using the default 10k seems to produce a bit of weirdness/flickering of the shadows when zooming in and out(nothing like it was before though). Setting it to something like 50k stops that entirely but the quality of the shadows overall doesn't seem as good.

**Comment by R-T-B** [comment]
> It appears to be fixed. All of the terrible looking shadows are gone. Now the only thing I have a question about is what the shadow range limit should be set to. Using the default 10k seems to produce a bit of weirdness/flickering of the shadows when zooming in and out(nothing like it was before though). Setting it to something like 50k stops that entirely but the quality of the shadows overall doesn't seem as good.

I'm experimenting with it myself.  I don't have a firm answer yet but I released it with a default of 50000, which is more or less OK and a massive improvement.  Let me know if you find a better preset!

Leaving this open for proper discussion and feedback.
