### ISSUE TITLE
Kopernicus

### ISSUE THREAD

**Issue by Rahditte-Lintang-Aditaprama** [Kopernicus/Kopernicus#544]
I was stuck in the menu. Game doesn't crash. But all bottoms are failure. My game setting language is Russian. Maybe that cost problem?

**Comment by R-T-B** [comment]
I am closing tickets older than mid October in hopes the last bugfix release helped you.  If you are still experiencing the issue, please feel free to reopen this and I will prioritize your request.

PS:  Russian should be fine, but if you switch to another language and the bug vanishes, then we may (still) have an issue.  Please reopen this if so.
