### ISSUE TITLE
Kopernicus not loading rss with ro installed, "exeption in the loading process"

### ISSUE THREAD

**Issue by Armuax** [Kopernicus/Kopernicus#545]
As described in the title, kopernicus fails to load rss, log files and modlist attached.
Ksp is running 1.10

[RSS-RP1 Modlist.txt](https://github.com/Kopernicus/Kopernicus/files/9727842/RSS-RP1.Modlist.txt)
[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/9727795/Kopernicus.zip)
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/9727804/KSP.zip)
[ModuleManager.zip](https://github.com/Kopernicus/Kopernicus/files/9727816/ModuleManager.zip)

**Comment by R-T-B** [comment]
I am closing tickets older than mid october in hopes the last bugfix release helped you.  If you are still experiencing the issue, please feel free to reopen this and I will prioritize your request.
