### ISSUE TITLE
Kopernicus cause Kerbin's surface to be too bright colored

### ISSUE THREAD

**Issue by nikobrf** [Kopernicus/Kopernicus#547]
Oh well, it seems that from space, Kerbin's colors get so brightned that it looks like a toy. Vegetation for example goes from dark green to very very bright green, and the desert goes for a too bright yellow too.
![2022-10-16](https://user-images.githubusercontent.com/115946049/196063035-28e033a9-0945-4128-9d5e-1ae07fbd641a.png)

**Comment by R-T-B** [comment]
Suppport backlog time:  Sorry this took so long to answer:

I believe this is a result of Kopernicus terrain colors setting going wonky.  Try the colorfix.cfg that is atatched to the release and see if it changes the behavior, maybe...

**Comment by R-T-B** [comment]
This should be fixed as of latest release-144.
