### ISSUE TITLE
kopernicus fail and RealSolarSystem

### ISSUE THREAD

**Issue by WorthyCargo** [Kopernicus/Kopernicus#548]
I have installed Real Solar System, Realism overhaul, As dependency of Real Solar System I installed Kopernicus. (And some modifications suggested by them) When KSP starts, I get a warning the same as user Hobols

“Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your savegame is NOT recommended, because the missing planets could corrupt it and delete your progress.
Please contact the planet pack author or the Kopernicus team about the issue and send them a valid bugreport, including your KSP.log, your ModuleManager.ConfigCache file and the folder Logs/Kopernicus/ from your KSP root directory‘’

Log files:
[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/9825398/Kopernicus.zip)

Help please :(

**Comment by AffanSher** [comment]
Downgrade Parallax to 1.3.1 including the stock textures.

**Comment by R-T-B** [comment]
> Downgrade Parallax to 1.3.1 including the stock textures.

this is the solution.
