### ISSUE TITLE
Kopernicus crash with Real Solar System

### ISSUE THREAD

**Issue by blackbeard76** [Kopernicus/Kopernicus#552]
I have installed Real Solar System, Realism overhaul, and RP-1, with their recommended mods with CKAN. As Real Solar System's dependency I installed Kopernicus. (And some mods suggested by them) When KSP starts I get a warning:

    Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your savegame is NOT recommended, because the missing planets could corrupt it and delete your progress.
    Please contact the planet pack author or the Kopernicus team about the issue and send them a valid bugreport, including your KSP.log, your ModuleManager.ConfigCache file and the folder Logs/Kopernicus/ from your KSP root directory

When I want to create a new game or try to load one the screen stays black and the loading icon stays forever.

Copy & Pasted from another post with my same issue, but I think I've narrowed it down to something to do with Ceres but dont know what to do from here.

Log : [Kopernicus log.txt](https://github.com/Kopernicus/Kopernicus/files/10046985/Kopernicus.log.txt)

**Comment by R-T-B** [comment]
I've run into this before.  I believe you need an older version of Parallax to use with RSS.  I want to say the last release before they added scatters?

Try that.

**Comment by blackbeard76** [comment]
That seems to have worked, I had to revert to Parallax 1.3.1 just before they added scatters as you suggested. 

Thank you for taking the time to respond.

**Comment by R-T-B** [comment]
Not a problem, glad I could help.  I try to respond when the answer is something I know off the top of my head like that... ;)
