### ISSUE TITLE
CKAN Data

### ISSUE THREAD

**Issue by Swany6mm** [Kopernicus/Kopernicus#553]
CKAN updated it's data today and told me Kopernicus had an update. Now, when I try and install through CKAN, I get the below error

`CKAN.InvalidModuleFileKraken: Kopernicus 2:release-1.12.1-139: C:\Users\<MyProfile>\AppData\Local\CKAN\downloads\downloading\41C4F207-Kopernicus-2-release-1.12.1-139.zip has length 1077014, should be 1074657
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)`
   
   Wasn't sure if I needed to report it here or with CKAN?

**Comment by R-T-B** [comment]
Oh.  That's a consequence of the recent "hotpatch" I did.  I forgot about how this would upset CKAN.  I will inform them so a fix can be made.  Thanks for the report, I will avoid doing this in the future.

**Comment by Swany6mm** [comment]
Thanks for the fast reply and actioning :) It's much appreciated

**Comment by HebaruSan** [comment]
The metadata has been updated already, so clicking Refresh in CKAN should fix this:

https://github.com/KSP-CKAN/CKAN-meta/commit/bb93eb73c0ffdcc724456256c024b105a64bf8d8

That's probably what I'd recommend. Trying to mess with it more than that would just break things for people who've _already_ clicked Refresh and have it working.

**Comment by R-T-B** [comment]
Ah ok, sounds good then.  Thanks for weighing in.

I obviously will avoid such methods in the future for patches, instead generating a new version, however minor.
