### ISSUE TITLE
KSP getting stuck on Black loading screen when loading a save with Kopernicus and RSS for KSP 1.12.4

### ISSUE THREAD

**Issue by RenZoc-FN** [Kopernicus/Kopernicus#554]
Hi, I had this **same issue on 1.11.2** and RTB helped me resolve it. I stopped playing for a little bit and I uninstalled ksp. I recently reinstalled ksp on the newest version(1.12.4) and decided to try out RSS(Real solar system). I installed it using CKAN and once the game loaded, a warning popped up. I first ignored it and created a new save and loaded it. And I waited, and waited, and waited for 15 min before I closed KSP, same thing happened when I tried loading settings.

![image](https://user-images.githubusercontent.com/83088103/205415768-c8d1e408-b18c-400a-acd5-ebcbddacee28.png)

I have tried reinstalling ksp but that did not work. I have uploaded my kopernicus logs and KSP log since that's what was requested last time. Can you help with this issue?

Gamedata folder:
![image](https://user-images.githubusercontent.com/83088103/205415835-35240e0c-c0e7-42cd-9b3b-f3fd3e784eae.png)
![image](https://user-images.githubusercontent.com/83088103/205415852-9a13b613-eb3d-4bbd-8d33-92a9d8af4854.png)
![image](https://user-images.githubusercontent.com/83088103/205416015-da8a5f09-13b3-4031-8575-eb2903e9cd7d.png)

[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/10145356/Logs-Kopernicus.zip)
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/10145359/KSP.zip)

Thanks

**Comment by R-T-B** [comment]
Hello.

In this case the issue is RSS requires an older version of Parallax.  Downgrading that to last major version should work.

**Comment by RenZoc-FN** [comment]
Hi, The latest version of parallax 2.04, should I install 2.03?

**Comment by R-T-B** [comment]
1.3.1 I believe.  You want the previous major release, with no scatters.

**Comment by RenZoc-FN** [comment]
Ok, I will try installing that version of Parallax.

**Comment by RenZoc-FN** [comment]
Hi, I installed parallax version 1.3.1 and everything works fine. Thank you very much for your help(again)!
