### ISSUE TITLE
Beyond Home planet pack not loading

### ISSUE THREAD

**Issue by Dracolupus314** [Kopernicus/Kopernicus#555]
I am trying to run the Beyond Home planet pack, and it keeps having an exception in the loading progress. This is my first time I am encountering this error, and it hasn't gone away by deleting the folders for both Kopernicus and Beyond Home and re-installing. I have attached the files and folders that the warning told me to.  My game folder doesn't contain any file named ModuleManager.Configcache, so I don't know how to include that file here. Thank you! 

[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/10179879/Kopernicus.zip)
[KSP.log.zip](https://github.com/Kopernicus/Kopernicus/files/10179917/KSP.log.zip)

**Comment by Dracolupus314** [comment]
I am using 1.3 for parallax. Specially, 1.3.1.

**Comment by nased0** [comment]
I had the same problem with Parallax-1.3.0 and Beyond Home. Switched to Parallax-1.0.1 and it's working fine.

**Comment by R-T-B** [comment]
Oh?  That's interesting.  OP, this may be worth a try...

**Comment by Dracolupus314** [comment]
I tried it, and it did not fix the issue. I have previously gotten the instance to run with beyond home and all the mods I have (using parallax 1.3.1) , which is why this more confusing

**Comment by nased0** [comment]
Uninstall Parallax Stock Textures.
I'm using also Scatterer 0.831.0.0.
I replaced both Parallax and Scatterer from my backup, when KSP crashed.

**Comment by Dracolupus314** [comment]
As I remember, I don't have stock textures installed. In fact, every time I open the game, it gives me the warning that stock textures are not installed, but I can ignore the warning if using a custom planet pack

**Comment by nased0** [comment]
Manually delete Parallax and Scatterer folders from the GameData, and then install them from the GitHub release, not from the CKAN.

**Comment by Dracolupus314** [comment]
No luck. Same error, and in fact, it gave me so many DLL errors that they started overlapping so as to be illegible.

**Comment by Dracolupus314** [comment]
I figured it out- I have been trying to run sigma dimensions for an upscale, and it was giving me an error with an incompatible dll. I removed that mod, and it worked. I will spend some time experimenting with a version that doesn't cause such issues in the future. Thank you for all your help!
