### ISSUE TITLE
Real Solar Systems not loading

### ISSUE THREAD

**Issue by AffanSher** [Kopernicus/Kopernicus#556]
Get an error : Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process, in the main menu. Tried to load into a new game but it will not go past the loading screen.
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10189616/KSP.log)

**Comment by R-T-B** [comment]
See https://github.com/Kopernicus/Kopernicus/issues/554 for a potential fix.

**Comment by AffanSher** [comment]
Yup, that worked.
I feel like they should include this in the RealSolarSystem instructions, right now it just says "Install Parallax" and support there told me to keep parallax updated instead of downgrading.
