### ISSUE TITLE
Kopernicus unable to load custom Plantet Issue.

### ISSUE THREAD

**Issue by CaptainHarvey** [Kopernicus/Kopernicus#558]
![image](https://user-images.githubusercontent.com/120464486/207305231-6e4bd6d2-6981-4c36-adaa-97fcd7bf8dfa.png)
Hi guys attached my gamedata folder, can i please have some help with the game not loading properly?

**Comment by R-T-B** [comment]
What is in the "Extras" folder?

Also, it would help if you'd post your "KSP.log" file, located in the install directory (one directory up from gamedata).

**Comment by CaptainHarvey** [comment]
Extra's had nothing in there so that has been deleted, it seemed to hold a mod file which has now been placed in the gamedata, i will reupload a pic 
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10222523/KSP.log)

![image](https://user-images.githubusercontent.com/120464486/207461991-ca8c8083-2589-4e89-ae6d-2c8cf11e5c29.png)

**Comment by R-T-B** [comment]
In the "Source" directory there seems to be some old mods or modules being loaded that aren't very happy.  I'm also suspicious of the "Ships" folder...  I'd move both of those out of GameData if you want to keep them.

If you still have trouble after that, try validating your game files via steam, or if lacking steam, backing up the mods, reinstalling the game and copying the mods back in.

**Comment by CaptainHarvey** [comment]
Well, sorted those files out, loaded in a fresh flight and still stock, everything on the game is maxed out etc im at a loss, even after a fresh install nothing is loading.. bit stuck haha
