### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by P0STI88** [Kopernicus/Kopernicus#561]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10417341/KSP.log)
![Screenshot (37)](https://user-images.githubusercontent.com/113863022/212472508-19264f66-1f5e-4299-b4b0-4f5e14a877b8.png)
[ModuleManager.ConfigCache and kopernicus logs.zip](https://github.com/Kopernicus/Kopernicus/files/10417347/ModuleManager.ConfigCache.and.kopernicus.logs.zip)

**Comment by R-T-B** [comment]
This is because we dropped support for KSP 1.11.x and below.  You can either upgrade to a KSP 1.12.x release, or use the last supported Legacy release Kopernicus, which I will link:

https://github.com/Kopernicus/Kopernicus/releases/tag/release-139

**Comment by Machine-Maker** [comment]
I'm not sure if this is something you do, or something ckan has to take care of, but release 140 and 141 are marked as compatible with 1.9.0-1.12.99 on ckan which led me to have this issue. release 142 and up are properly marked as >1.12.

**Comment by R-T-B** [comment]
Thanks for the information!  This is obviously a mistake.  I'll see if we can't get the release metadata updated.
