### ISSUE TITLE
Kopernicus not working with StellarADventures

### ISSUE THREAD

**Issue by Duckywarry** [Kopernicus/Kopernicus#564]
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/10708358/KSP.zip)

**Comment by R-T-B** [comment]
The chief issue seems to be that your Kopernicus install is broken somehow. It seems to be missing it's shaders directory, as indicated here:

"[ERR 15:26:09.951] Unable to open archive file: D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/Kopernicus/Shaders/kopernicusshaders-windows.unity3d

[ERR 15:26:09.951] Failed to read data for the AssetBundle 'Shaders\kopernicusshaders-windows.unity3d'."

you might try reinstaling Kopernicus. If that fails, you might try the game installed from scratch, if that's not too painful, and readd mods individually to see what happens.

EDIT: It also appears you have a gamedata folder within your gamedata, that should never be the case. remove that, please.

**Comment by Duckywarry** [comment]
Thank you so much! I finally got it working again!
