### ISSUE TITLE
Kopernicus not working even if it says everything is good

### ISSUE THREAD

**Issue by Propain287** [Kopernicus/Kopernicus#566]
KSP opens with the Kopernicus error saying custom planetary system wasn't able to load I checked the Kop logs, KSP logs, and nothings out of the ordinary. I run many mods but this didn't start happening till I tried installing Event horizon Mod into KSP which some planets were causing issue so I deleted them since all I wanted was a cool blackhole to traverse to. Yet even after Kopernicus logs said everything booted up the error message would still pop up. And if I tried loading into a world or going into settings I would be faced with a infinite loading screen. Please help 
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10711440/KSP.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/10711483/Kopernicus.log)

**Comment by R-T-B** [comment]
The chief issue seems to be that your Kopernicus install is broken somehow.  It seems to be missing it's shaders directory, as indicated here:

"[ERR 15:26:09.951] Unable to open archive file: D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/Kopernicus/Shaders/kopernicusshaders-windows.unity3d

[ERR 15:26:09.951] Failed to read data for the AssetBundle 'Shaders\kopernicusshaders-windows.unity3d'."

you might try reinstaling Kopernicus.  If that fails, you might try the game installed from scratch, if that's not too painful, and readd mods individually to see what happens.

**Comment by R-T-B** [comment]
Your log files are completely empty.

As I can't help more than general advise without logs, all I can advise is a few tips to check for common mistakes:

1.)  Check for nested/additional gamedata directories inside gamedata.  This should NEVER happen and will always produce errors.

2.)  If you can't generate logs for some reason, please try reinstalling the game, starting from scratch, adding mods one by one.

**Comment by Propain287** [comment]
This is very very strange since there is things inside the logs I have but for some reason there is nothing in the logs I sent do you know how I can fix that?

**Comment by Propain287** [comment]
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/10711808/Kopernicus.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/10711809/Kopernicus.log)
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10711811/KSP.log)
Im trying the logs I found again

**Comment by Propain287** [comment]
The second Kop log works the KSP one dosent il try and fix that

**Comment by Propain287** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10711816/KSP.log)

**Comment by Propain287** [comment]
Alright I found the issue apparently the size of my KSP log is too big to message

**Comment by R-T-B** [comment]
Try deleting the ksp.log file and letting it regenerate with a game run.  It should still have what I need and be much smaller.  Zipping it may also help.

**Comment by Propain287** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10713488/KSP.log)
When I deleted it and let KSP re do it it shrunk enough to put into here. I'm also very sorry for taking a long time to respond

**Comment by R-T-B** [comment]
It's no issue I take a while sometimes too, real life and all that  :)

I will loom at your log now and update you in a few minutes.

**Comment by R-T-B** [comment]
The core issue you are experiencing is liste below:

`[EXC 03:32:25.865] Exception: Reference body for "EventHorizon/Magia_Masso" could not be found. Missing body name is "Magister".
	Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (ConfigNode node) (at <e835cf01640d49ea96cdd7999f0dce52>:0)
	Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.ConfigParser.Parser.CreateObjectFromConfigNode[T] (ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.Injector.Awake () (at <e835cf01640d49ea96cdd7999f0dce52>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	Kopernicus.Injector:Awake()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(GameScenes)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)`

Honestly, it looks like you are missing (or failing to load) body "Magister."  I can't really diagnose further without knowing the planet pack you are using.  Also, if you could fetch the log for Magister from <KSPINSTALL>/Logs/Kopernicus, it should be a small text file somewhere in there named something like "Magister".  Thanks.

**Comment by Propain287** [comment]
I removed the planet Magister since it was causing problems before because a value was null when it wasn't supposed to be I also removed 3 other planets for the exact same reason

**Comment by R-T-B** [comment]
Well that's your issue.  When you remove a planet, you have to remove any bodies orbiting it too.  It looks like "EventHorizon/Magia_Masso" orbits Magister.

**Comment by Propain287** [comment]
So remove Magia and its fixed?

**Comment by Propain287** [comment]
Il have a look into that Thank you very much R-T-B you've been a great help

**Comment by Propain287** [comment]
I fixed it I FINALLY FIXED IT THANK YOU AGAIN RTB

**Comment by R-T-B** [comment]
> I fixed it I FINALLY FIXED IT THANK YOU AGAIN RTB

No problem.  Glad I could help. :)
