### ISSUE TITLE
Kopernicus was not able to...

### ISSUE THREAD

**Issue by KatharineRosewood** [Kopernicus/Kopernicus#568]
This zip file contains my ksp.log, my modulemanager.configcache, and my logs/kopernicus folder.
[logs.zip](https://github.com/Kopernicus/Kopernicus/files/10774116/logs.zip)

The error said i had to send these things to the kopernicus dev team in an issue to get help.

**Comment by KatharineRosewood** [comment]
I might have figured it out. For everyone who gets this error while using Galaxies Unbound, try installing everything and then deleting all GU folders and manually installing GU.

**Comment by thekingren** [comment]
Hey, I can't load the game and this has only started to happen when I downloaded new kopernicus 
KSP.log

**Comment by thekingren** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10777776/KSP.log)

**Comment by R-T-B** [comment]
Have you tried the above?

If your issue is not related to this GU mod issue, please make a new issue and I'll look into it.  Also, if you know your previous "working" Kopernicus version details like that can be useful.

Thanks.
