### ISSUE TITLE
KSP not loading

### ISSUE THREAD

**Issue by thekingren** [Kopernicus/Kopernicus#569]
KSP won't load for me I have a screenshot of the message

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10777779/KSP.log)
![Screen Shot 2023-02-19 at 2 44 15 PM](https://user-images.githubusercontent.com/125828255/219971565-6c108db6-9c0c-478e-a6bf-133209435e78.png)

**Comment by R-T-B** [comment]
Hello, thanks for making a new issue.  Looking at your logfile now and will update,

**Comment by R-T-B** [comment]
First and foremost this is not a Kopernicus error, but Kopernicus reporting an error happening somewhere else that is likely to negatively effect it.

Not to worry, we can still help.  Lets start with some general install hygiene type stuff.  Can I see a screenshot of your gamedata folder?

**Comment by R-T-B** [comment]
Closing due to user inactivity.  Simply comment if you are back to reopen this.
