### ISSUE TITLE
Kopernicus suddenly printing an error

### ISSUE THREAD

**Issue by Fezak928** [Kopernicus/Kopernicus#570]
Hi, I was having issues with Parallax changing the ground colors of Kerbin to the latest body I've been to, tried several solutions and then I think I've made something worse because Kopernicus is giving me this error at the main menu.
![imagen_2023-02-21_135912478](https://user-images.githubusercontent.com/80782936/220351053-54d1a04c-d5de-435f-ba80-9bfb459af55c.png)

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10793740/KSP.log)

Also saw a similar issue someone had, hoping it is similar. So I am also sending a screenshot of my gamedata folder, just in case.
![image](https://user-images.githubusercontent.com/80782936/220353907-b24c815a-ffe0-4a26-b7c3-03ecf22d1d69.png)
![image](https://user-images.githubusercontent.com/80782936/220354040-07f7f7d8-4356-49a6-8ab5-724656634413.png)
![image](https://user-images.githubusercontent.com/80782936/220354075-11caec9d-eafb-49e5-8ad6-7d7cca77fdaf.png)
![image](https://user-images.githubusercontent.com/80782936/220353981-d6ce704f-b578-4623-b6f3-4caae94e4440.png)

**Comment by R-T-B** [comment]
Without knowing what precisely you did between the colors issue, and this error message (separate issues I believe), this will be hard to diagnose.  The log honestly pretty much just says Kerbin failed to load.  Did you by chance make any changes there?  What, precisely can you remember?  Any details will help.

**Comment by Fezak928** [comment]
No, not that I know off. I suppose it was installing the troubleshooting file from Parallax that might have caused this because I uninstalled the game and the mods, reinstalled everything again without that troubleshooting file and Kopernicus isn't giving me that error anymore. The ground changing colors still happen and I still assume that gotta do with Parallax because that doesn't happen without it. I already asked about it to see if I can find a solution to that problem.

**Comment by R-T-B** [comment]
Can I see this "troubleshooting settings.cfg" file?  Is there a link somewhere?  If there is an issue with it I'd like to let GamesLinx know, since a lot of his users are also my users by proxy.

**Comment by Fezak928** [comment]
Sure, but sorry that I can't send the file itself, but I can send the link of the download.
https://mega.nz/file/JEEgTZ5a#BDhp8Vm8WvcbYd3lO2VCIg_3_8xr1I4ns8-He8pQ_PY

It's the one that comes for the tanked FPS. 
![image](https://user-images.githubusercontent.com/80782936/220409020-0d6d1bf7-bd6c-435a-ba85-d75b15f06b3d.png)

**Comment by R-T-B** [comment]
Thanks, that's great.  I'll look into this tomorrow.

**Comment by R-T-B** [comment]
Closing as part of broader cleanup.
