### ISSUE TITLE
No Idea What Happened But is A Bug With The kcalbeloh  System

### ISSUE THREAD

**Issue by TTaxer** [Kopernicus/Kopernicus#571]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10796652/KSP.log)

**Comment by R-T-B** [comment]
Thanks for the report, evening here but will look at this tomorrow morning.

**Comment by TTaxer** [comment]
Thanks RTB
But I Have Infact Fixed It

> Thanks for the report, evening here but will look at this tomorrow morning.

**Comment by R-T-B** [comment]
Glad to hear it!
