### ISSUE TITLE
ksrss fails to load

### ISSUE THREAD

**Issue by 24afortenbacker** [Kopernicus/Kopernicus#572]
i have only kopernicus and ksrss downloaded but it still fails
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10842835/KSP.log)
[ModuleManager.ConfigCache.txt](https://github.com/Kopernicus/Kopernicus/files/10842836/ModuleManager.ConfigCache.txt)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/10842841/Kopernicus.log)
[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/10842842/Kopernicus.Runtime.log)
<img width="370" alt="Screenshot 2023-02-27 at 1 24 04 PM" src="https://user-images.githubusercontent.com/68517890/221650600-80b01fd9-5d4f-4d2c-85ca-1f29f2631819.png">

**Comment by R-T-B** [comment]
Kopernicus dropped support for 1.11.x, 1.10.x, and 1.9.x with release-140.  The last release to properly support older versions than 1.12.x was release-139.  You can download that here:

https://github.com/Kopernicus/Kopernicus/releases/tag/release-139

OR (and I'd advise this if it's possible) update your KSP install if possible for the latest bugfixes.

**Comment by R-T-B** [comment]
Closing issue as this is a scenario we won't fix, and workarounds have been provided.
