### ISSUE TITLE
I got an error when i installed Parallax and the components needed

### ISSUE THREAD

**Issue by Theoyeah** [Kopernicus/Kopernicus#573]
![image](https://user-images.githubusercontent.com/97792861/222969178-d62fadd3-93e2-4dd7-83f3-f8a9b82354ea.png)
[ModuleManager.ConfigCache.txt](https://github.com/Kopernicus/Kopernicus/files/10892138/ModuleManager.ConfigCache.txt)
![image](https://user-images.githubusercontent.com/97792861/222969319-769cb959-5c52-49f2-b445-8cf7cd99eb5f.png)
i also have tantares

**Comment by Theoyeah** [comment]
sadly i can't upload the file

**Comment by Theoyeah** [comment]
i can't access the settings tooo

**Comment by R-T-B** [comment]
Your mods should be in Kerbal Space Program/GameData, not with the "English" subdirectory in between.

Did Epic Games install it like that, or is this some organizational thing you did?  I may have to add support for the Epic Games version if it is the former.

**Comment by Theoyeah** [comment]
like that ?
![image](https://user-images.githubusercontent.com/97792861/223154771-b48bee18-70cf-47b5-bd13-d8792e0973d0.png)

**Comment by Theoyeah** [comment]
Nvm, found the problem and i no longer get problems, tho i need to find why when i try to play it puts me in a infinite loading
