### ISSUE TITLE
All surface features are missing with rel 158

### ISSUE THREAD

**Issue by basilicofresco** [Kopernicus/Kopernicus#576]
Hi! 
I just noticed that all the surface features (eg. baobabs on Kerbin) disappear as soon you update Kopernicus to v1.12.1-158. Kopernicus to v1.12.1-157 will not cause the issue.

I tested it on a clean installation with just these components:
- KSP 1.12.5.3190 (win x64) en-us
- Making History 1.12.1
- Breaking Ground 1.7.1
- Kopernicus v1.12.1-158
- Module Manager v4.22
- Moduar Flight Integrator v1.2.10.0
- Harmony v.2.2.1.0

**Comment by R-T-B** [comment]
Thanks, this was a major "my bad" that turned out to be nothing more than a typo.  Was a PITA to diagnose, but release-159 fixes this.  Closing.
