### ISSUE TITLE
Stuck loading between main menu and space center scene on v163

### ISSUE THREAD

**Issue by monoamin** [Kopernicus/Kopernicus#577]
After installing the new release 163 the game will not load past the main menu. 
The task manager shows cpu load and ram usasge oscillating back and forth as if some workload cannot be finished.
Upon reverting to 162, everything works fine again.

I will gladly provide logs and other info, let me know what is needed.

**Comment by R-T-B** [comment]
Yes, a KSP.log from your install directory would be helpful if you could.

Thanks for the report, this sounds pretty urgent.  Can you also get me a list of mods in case there is some kind of conflict, since I didn't notice this in stock testing?

**Comment by Calvin-13** [comment]
I can also confirm this is happening. I noticed logspam from Parallax, but I am unsure if that is the cause of the issue. Have the two been tested together?

**Comment by R-T-B** [comment]
> I can also confirm this is happening. I noticed logspam from Parallax, but I am unsure if that is the cause of the issue. Have the two been tested together?

I run it with parralax in my personal save so that's not it.

I could really use a log file from someone who failed to load.

**Comment by Calvin-13** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10975881/KSP.log)

**Comment by R-T-B** [comment]
> [KSP.log](https://github.com/Kopernicus/Kopernicus/files/10975881/KSP.log)

Thank you, that narrowed it down nicely.  It's a conflict with EVE City Lights of all things!  I can work around this though, no need to expect EVE to change anything.  It will be fixed in a hotfix.  Expect it in a few.

**Comment by R-T-B** [comment]
Can you guys test this and confirm if it works to fix the issue?  This is a release candidate for release:
[Kopernicus-1.12.1-164RC1.zip](https://github.com/Kopernicus/Kopernicus/files/10976005/Kopernicus-1.12.1-164RC1.zip)

**Comment by monoamin** [comment]
Currently trying the release candidate, will let you know.

**Comment by R-T-B** [comment]
Interesting.  It's late now but I promise to investigate this fully in the morning.

**Comment by lingfors** [comment]
I also can't load into the game using version 163 or 164. I attached the log from 164.

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/10976957/KSP.log)

**Comment by monoamin** [comment]
Game is currently loading, will let you know asap.

**Comment by monoamin** [comment]
165 fixed it.

Thank you, you rock!
