### ISSUE TITLE
New issue with blackhole system Kcalbeloh (Infinite loading screens when playing in right version for mod 1.12.3)

### ISSUE THREAD

**Issue by Propain287** [Kopernicus/Kopernicus#578]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/11024796/KSP.log) 

[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/11024801/Kopernicus.log)

Il be off for the night so when I get on il check if you have anything posted on this issue

**Comment by R-T-B** [comment]
You appear to be missing Dres, which is required for something you have installed:

[EXC 21:25:08.061] Exception: Reference body for "Ceric" could not be found. Missing body name is "Dres".
	Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (ConfigNode node) (at <7981cbd9dbf4428c8014b657e006cad0>:0)
	Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.ConfigParser.Parser.CreateObjectFromConfigNode[T] (ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.Injector.Awake () (at <7981cbd9dbf4428c8014b657e006cad0>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	Kopernicus.Injector:Awake()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(GameScenes)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

**Comment by Propain287** [comment]
Well Dres I don't really need at all Il just get rid of Ceric and what ever might be hooked to it too Il get back to you if it works or not.
