### ISSUE TITLE
How to install Planet Packs?

### ISSUE THREAD

**Issue by BraveCaperCat2** [Kopernicus/Kopernicus#581]
Can someone tell me how to install planet packs?
i know how to install the mod (according to #292) but how do I install planet packs for Kerbal Space Program?

There is also ABSOLUTELY NO DOCUMENTATION FOR INSTALLING THEM (I did a google search.)

**Comment by R-T-B** [comment]
They should be installed seperately, as folders in gamedata.  Most planet packs should come with their own instructions.

**Comment by BraveCaperCat2** [comment]
> They should be installed separately, as folders in gamedata. Most planet packs should come with their own instructions.

none of the planet packs have any instructions.

**Comment by R-T-B** [comment]
Can you link the planet pack you are interested in?

**Comment by BraveCaperCat2** [comment]
> Can you link the planet pack you are interested in?

unfortunately - I don't have a link to it anymore - but most of the planet packs on [Curseforge](https://beta.curseforge.com/kerbal/search?search=planet+pack&page=1&class=ksp-mods&sortType=1&pageSize=50) should have this problem.
Such as [This One](https://beta.curseforge.com/kerbal/ksp-mods/boris-system-planetary-pack) which has a very minimal description and absolutely no installation instructions - none of the ones I was looking at had any instructions either.

**Comment by R-T-B** [comment]
Closing as part of a broader cleanup.  I would advise the user to find mods on KSP Forums where the documentation for install is more likely to exist.
