### ISSUE TITLE
"Unable to load custom planets due to an exception" when using Other Worlds Reboot

### ISSUE THREAD

**Issue by Taggart1993** [Kopernicus/Kopernicus#582]
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/11184453/Kopernicus.log)
[MiniAVC-V2.log](https://github.com/Kopernicus/Kopernicus/files/11184454/MiniAVC-V2.log)
[ModuleManager.log](https://github.com/Kopernicus/Kopernicus/files/11184456/ModuleManager.log)
Github doesn't want to load my ksp.log or ModuleManager.ConfigCache files.

**Comment by R-T-B** [comment]
I'm sorry I missed this for so long, slipped through the cracks it seems.  Are you still having trouble?  If so, please delete your ksp.log and regenerate it with one run of the game.  That trick may make it uploadable.  Also try zipping it.

If you no longer are having this issue, feel free to ignore this and I'll cleanup this issue in a few days.
