### ISSUE TITLE
LandClasses Latitude/Longitude Ranges need more decimal points

### ISSUE THREAD

**Issue by Nightside101010** [Kopernicus/Kopernicus#585]
I'm building cities with scatters. When setting latitudeRange and longitudeRange in LandClasses, the game doesn't seem to read values beyond 2 decimal places. 
Acceptable values for the are decimals between 0 and 1.
At Kerbin's equator this is a distance of about 38km per "0.01" increment. This is way too course to define city outlines.

Would it be possible to allow 4 or 5 decimal places to allow for sub-km specificity?

![image](https://github.com/Kopernicus/Kopernicus/assets/20480557/7955aafa-cdb8-4ef6-a160-6a8e970611ab)

**Comment by R-T-B** [comment]
As I mentioned elsewhere:  I think this is limited by KSP-side stock code, so it will be hard to fix.  Not impossible, but something I can't afford to do right now with so much pending on the next release.

I will leave this open though, as a future feature request that I may some day do.

**Comment by R-T-B** [comment]
I just did some digging in KSP's code, and it looks as though this has the potential to maybe be our fault.  I don't see anything in the stock code yet limiting us to two decimal places, BUT, there is a place in the Kopernicus code that downsamples lat/long coordinates to two decimal places IF the allowedBiomes parameter is used.  Are you using that, by chance?  If so, that limit is there for performance reasons, but it shouldn't be affecting scatters outside of biome placement.  We may have a bug on our hands.  Further investigation needed.

**Comment by Nightside101010** [comment]
Awesome thank you!
I’ll give it a try tonight

**Comment by R-T-B** [comment]
There might still be some limits to what you can do stock code wise, but I have some ideas to get around them.  Do let me know your outcome.

**Comment by R-T-B** [comment]
Closing as I can only assume this was accomplished.
