### ISSUE TITLE
Due to loading issue Kopernicus can't load planets?

### ISSUE THREAD

**Issue by Tadpole899** [Kopernicus/Kopernicus#586]
I'm trying to use the Kcalbeloh System mod but every time I open it Kopernicus say's it didnt work due to an exception in the loading process. Logs attached below. If you need any other files or anything let me know.

[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/11645009/Kopernicus.Runtime.log)
[SeraRing.Asteroid.log](https://github.com/Kopernicus/Kopernicus/files/11645010/SeraRing.Asteroid.log)
[Stock.Asteroid.log](https://github.com/Kopernicus/Kopernicus/files/11645011/Stock.Asteroid.log)
[SunorcSystemBelt.Asteroid.log](https://github.com/Kopernicus/Kopernicus/files/11645012/SunorcSystemBelt.Asteroid.log)
[AccretionDisk.Asteroid.log](https://github.com/Kopernicus/Kopernicus/files/11645013/AccretionDisk.Asteroid.log)
[AcioreRing.Asteroid.log](https://github.com/Kopernicus/Kopernicus/files/11645014/AcioreRing.Asteroid.log)
[AralcSystemBelt.Asteroid.log](https://github.com/Kopernicus/Kopernicus/files/11645015/AralcSystemBelt.Asteroid.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/11645016/Kopernicus.log)
[Suluco.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645017/Suluco.Body.log)
[Sunorc.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645018/Sunorc.Body.log)
[Tot.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645019/Tot.Body.log)
[Uleg.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645020/Uleg.Body.log)
[WH3141A.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645021/WH3141A.Body.log)
[WH3141B.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645022/WH3141B.Body.log)
[Aciore.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645023/Aciore.Body.log)
[Ahtpan.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645024/Ahtpan.Body.log)
[Anneheg.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645025/Anneheg.Body.log)
[AralcA.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645026/AralcA.Body.log)
[AralcB.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645027/AralcB.Body.log)
[AralcSystem.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645028/AralcSystem.Body.log)
[Arorua.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645029/Arorua.Body.log)
[Dipuc.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645030/Dipuc.Body.log)
[Efil.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645031/Efil.Body.log)
[Elad.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645032/Elad.Body.log)
[Enots.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645033/Enots.Body.log)
[Eulb.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645034/Eulb.Body.log)
[Iomena.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645035/Iomena.Body.log)
[Kcalbeloh.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645036/Kcalbeloh.Body.log)
[Maelg.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645037/Maelg.Body.log)
[Mehtna.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645038/Mehtna.Body.log)
[Meiuqer.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645040/Meiuqer.Body.log)
[Noi.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645041/Noi.Body.log)
[Noira.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645042/Noira.Body.log)
[Norihc.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645043/Norihc.Body.log)
[Noyreg.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645044/Noyreg.Body.log)
[Onrefni.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645045/Onrefni.Body.log)
[Rouqea.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645046/Rouqea.Body.log)
[Sedah.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645047/Sedah.Body.log)
[Sera.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645048/Sera.Body.log)
[Simeht.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645049/Simeht.Body.log)
[SimeSystem.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645050/SimeSystem.Body.log)
[Simetra.Body.log](https://github.com/Kopernicus/Kopernicus/files/11645051/Simetra.Body.log)

**Comment by R-T-B** [comment]
KSP.log from install directory root please.

**Comment by Tadpole899** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/11646471/KSP.log)

here

**Comment by R-T-B** [comment]
Ok, had a long day at work but will look at your complete bug report in the next few hours.  Will update.

**Comment by Tadpole899** [comment]
Ok, thank you

**Comment by R-T-B** [comment]
Actually, this one was really easy, so here's your answer:

This appears to be an issue with the latest mod alpha:

In your log, we have the following:

[ERR 12:29:56.110] ADDON BINDER: Cannot resolve assembly: RunSharp, Culture=neutral, PublicKeyToken=be9f22c3116c2290

This indicates we are missing a file, RunSharp.dll.  It appears the author removed this file in the last release, believing it to not be needed.  Guess it is!

Fortunately, we can just download the last releases version of this file, and get it running again.  I will point you to it.

https://github.com/jcyuan06/Kcalbeloh-System/raw/90bc97d01a6e6c81de07bf4546537d9735d2123c/GameData/KopernicusExpansion/Plugins/RunSharp.dll

Put this file in GameData/KopernicusExpansion/Plugins please.  You should then be able to load.

I will inform the mod author of this bug.

**Comment by Tadpole899** [comment]
Ok, thank you, I will give that a try

**Comment by Tadpole899** [comment]
I put the file in Gamedata/KopernicusExpansion/Plugins and got the same error again.

**Comment by R-T-B** [comment]
Post a new logfile please.  KSP.log in particular.

**Comment by Tadpole899** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/11648323/KSP.log)

**Comment by R-T-B** [comment]
Not abandoning you, just consulting with the mod author in an attempt to figure this out.  Will update.

**Comment by jcyuan06** [comment]
Hi there! I'm the planet mod author and I think you need to remove RSSKopernicusSettings.cfg in your GameData folder. It is only needed when RSS is installed.

**Comment by Tadpole899** [comment]
ok, I will give that a try

**Comment by Tadpole899** [comment]
Worked perfectly! Many thanks to both of you
