### ISSUE TITLE
exeption in loading proccess

### ISSUE THREAD

**Issue by genericusername69420** [Kopernicus/Kopernicus#588]
I have tried every thing and this mod refuses to load. I'm not sure if its an issue with the way I downloaded these mods or the version. Here is what I see some of the times when I try loading it
![ACA773BD-7513-4E1C-B0BD-29142258F443](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/assets/132831588/172803a8-ea00-48c2-a834-e92ec9331d69)
looking in ksp.log there are quite a few errors here are some of them

_Texture resolution is not valid for compression: 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\_Systems\_AlphaCentauri\_PluginData\Rav_Color.png' - consider changing the image's width and height to enable compression_

there is a texture error for about every texture in my system mods

the models seem to load fine until i see this 

_BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "strutCube/cubestrut"_

and this one like a million times

_WheelCollider requires an attached Rigidbody to function._

then this one

_BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Prop_05/copter_med/mount/blades"_

then i see errors like this for the rest of the log

_ NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.GetBrightest (CelestialBody body) (at <c0ad2ab5086d46cab183caf2d24c8e95>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility.AtmosphereLightPatch (CelestialBody body) (at <c0ad2ab5086d46cab183caf2d24c8e95>:0)
	Kopernicus.RuntimeUtility.RuntimeUtility.LateUpdate () (at <c0ad2ab5086d46cab183caf2d24c8e95>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)_

the log ends after about 800 000 lines

please help my 3.7 total braincells have imploded at the sight of all these errors

is it normal to have an 800 000 line log?

**Comment by R-T-B** [comment]
You can delete the ksp.log file and regenerate it by running the game one time to trim its size.

That said, without a proper log, my guess is improper mod install somewhere, or corrupted KSP base installation.  Once you are able to upload a (hopefully smaller) KSP log I will be able to advise further.

**Comment by genericusername69420** [comment]
Ok so i deleted the old log and the new one is only 16 000 lines long 

here are some of the errors i got this time

immediately there were three at the very start

 _Config in file 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\Version1.3.cfg' contains no data._
_Config in file 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GU\Version1.3.cfg' contains no data._
_Cannot create config from file 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GU\_Systems\_AlphaCentauri\_EVE\CityLights\CityLights.cfg'._

My theory is the lack of stuff in the config files are causing these issues but i don't know how to get them back

next it said this 4 times

_ADDON BINDER: Cannot resolve assembly: EVEManager, Culture=neutral, PublicKeyToken=null
_
 
then the log repeats the first three errors later on

then it says this for almost every texture in the mod
_Texture resolution is not valid for compression_

weirdly some assets load just fine but about half are completely missing

it also fails at loading all the missions in the mod

fails to load some squad expansion banners and some of its missions

fails to load most of the banners for just about everything

and then the same _WheelCollider requires an attached Rigidbody to function._

also _BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Prop_05/copter_med/mount/blades"_

a lot of these are errors from before

_ unrecognized trailer: ',*' on: GU/Configs/GU_Patches/Rescale_Sigma/2.5x/@EVE_CLOUDS[*]:LAST[GU]:HAS[@GU_GENERAL_Settings:HAS[#Scale[2.5]]],*_

_ [Part]: Cannot have ModuleCargoPart and ModuleInventoryPart on same Part [CargoStorageUnit'. Removed ModuleCargoPart_

there are a few other errors. if you want i could send the whole KSP.log file

it then says this a lot _ NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <c0ad2ab5086d46cab183caf2d24c8e95>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)_

also king of weird when i found some stray code in the middle of the log _OBJECT
{
	body = Elius
	deactivateDistance = 175000
}

[LOG 17:17:44.371] [EVE CloudsManager]: Unable to parse config node:
OBJECT
{
	name = Jool-Aurora1
	body = Jool
	speed = 0,70,0
	detailSpeed = 1000,3000,0
	altitude = 15000
	settings
	{
		_DetailScale = 1
		_UVNoiseScale = 0.5
		_UVNoiseStrength = 0.015
		_UVNoiseAnimation = 0.05,0.02
		_DetailDist = 1E-07
		_Color = 255,255,255,55
		_MainTex
		{
			value = GU/EVE/Textures/Aurora2
		}
		_DetailTex
		{
			value = GU/EVE/Textures/detailaurora
		}
		_UVNoiseTex
		{
			value = GU/EVE/Textures/uvnoise1
		}
	}
	layer2D
	{
		macroCloudMaterial
		{
			_MinLight = 0.75
		}
	}
}
_

then says this for the rest of the log like before

_NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <c0ad2ab5086d46cab183caf2d24c8e95>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)_

**Comment by R-T-B** [comment]
Yes, I would need the whole KSP.log file to determine exactly what is happening.  But honestly, you may be better off starting with a fresh install + using CKAN to manage it.  What you'd do is grab a list of the mods you have, uninstall ksp and completely remove it's directory (backup any saves if needed), then reinstall and use CKAN to ensure your mods are installed correctly.

Here is a link to CKAN if you want to try this.  Yes, Kopernicus supports this:

https://forum.kerbalspaceprogram.com/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1280-dyson/

**Comment by genericusername69420** [comment]
Thanks! 
i did not even need to look at the log the fresh install worked perfectly.
