### ISSUE TITLE
Remote Version File Lists incorrect laest version of copernicus

### ISSUE THREAD

**Issue by Java-12-Aero** [Kopernicus/Kopernicus#589]
The remote version file [Here](https://raw.githubusercontent.com/Kopernicus/Kopernicus/master/build/KSP19PLUS/GameData/Kopernicus/Plugins/Kopernicus.version) for Kopernicus Lists the latest version as 1.12.1-**174**, yet the latest available release version on github is 1.12.1-**173**. This causes modulemanager to erroneously assume there is an update for the mod.

**Comment by R-T-B** [comment]
Thank you, I will correct this right now.

**Comment by R-T-B** [comment]
Fixed with: https://github.com/Kopernicus/Kopernicus/commit/2d508130d0334afb861b97adbf174a40be754c48

It seems what happened were some local dev files leaked before they were ready (in this case just the version file).  Thank you very much for reporting this.
