### ISSUE TITLE
Remote Version File is leaking

### ISSUE THREAD

**Issue by Java-12-Aero** [Kopernicus/Kopernicus#593]
title, Module Manager was picking up update 176 before the version was available, remote version file was again showing new version before update was available.

**Comment by Java-12-Aero** [comment]
Correction: Addon version checker, not MM is pulling it

**Comment by R-T-B** [comment]
It was probably reading the prerelease files from the RCs we did.  I'll avoid bumping the version at the repo on those in the future.  Thanks for the notice.
