### ISSUE TITLE
Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by mario-head** [Kopernicus/Kopernicus#594]
This is similar to #279, only I have a ton of planetary system mods installed under Galactic Neighborhood. I will post the KSP.log (Zipped due to file size limits) file below as well as any other requested files. Please pardon any stupidity in advance.
[KSP.zip](https://github.com/Kopernicus/Kopernicus/files/12250695/KSP.zip)

**Comment by R-T-B** [comment]
For starters your EnvironmentalVisualEnhancements install is out of date.  I would delete that folder, and grab a new release from the current maintainer here:

https://github.com/LGhassen/EnvironmentalVisualEnhancements/releases/

After that a new logfile post if you still have issues, which you may.  But we have to take this one bite at a time.

**Comment by R-T-B** [comment]
Aha, now we are getting somewhere with the logs!

Yes, I'm at work but can still offer tips here and there on what your log files say.  Right now it's telling me this:

`[LOG 09:08:00.091] [Kopernicus]: texture does not exist! C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/GalacticNeighborhood/Textures/Maps/RedGiant.dds
[WRN 09:08:00.102] Cannot find preset 'Default' for pqs 'Sido'
[WRN 09:08:00.102] CelestialBodyTransform: Cannot find CelestialBody.`

Basically you are missing the above texture, "RedGiant.dds"  Any idea where that may be?

Are you installing that last GalacticNeighborhood zip produced from here?

https://github.com/Sigma88/Galactic-Neighborhood/releases

If not, please remove what you have and try that.

Keep in mind this planet pack is very old, like ancient, so while we do attempt to retain backwards compatibility as far as loading there may be portions that need coaxing to load, or just look dated/weird.  I'll do my best to help regardless.

**Comment by mario-head** [comment]
Based on a File Explorer search, it doesn't exist. I'm even searching the folders and I don't even see a Textures Folder (I have two folders for GN that were installed from the download iirc, Galactic Neighborhood and Galactic Neighborhood-master).

I downloaded Galactic Neighborhood from the github page, yes. I chose it because it seemed to be the most up-to-date plugin for integrating multiple systems. I can delete it and change it out if there's a more recent version that works better?

**Comment by R-T-B** [comment]
Great, looks like we are finally getting somewhere!  I've got to catch a ride home but I will look at these shortly.

**Comment by R-T-B** [comment]
This seems to be the next issue:

[EXC 20:25:08.780] Exception: Reference body for "Lemoni" could not be found. Missing body name is "Rhea".

Unsure what that means in regards to your planet pack.

**Comment by mario-head** [comment]
That seems to be for the Sido Urania System planet pack. Both bodies are listed in the zipped folder in GN's PluginData folder, so I don't know what the issue is (It explicitly said not to unzip the folders). I'll try redownloading.

Another potential issue, some of these zipped planet packs have Kopernicus folders. I'm not sure if that means they're prepackaged with Kopernicus and that's creating conflicts or it's for dependency reasons.

**Comment by mario-head** [comment]
Redownloading Sido's didn't fix the issue. I've also decided I'll open up the log and take a look, and the sheer amount of warnings for SXT Continued is awfully disturbing. I went and followed some instructions based on adding textures and deploying it but that doesn't seem to have fixed anything. That's a secondary issue in this case, however.

**Comment by R-T-B** [comment]
Glad you are learning to read the logs, thats a great skill and will help speed things along.

Yeah, you certainly do not want more than one Kopernicus install.  It used to be popular to bundle it with mods but people stopped doing that long ago because of issues like this.

If you could list the mods you want to load, maybe I could get them in a working form, and zip them for you to just install all at once, correctly.  I know, learning is great and all, but I'm sort of with you on the sheer quantity of errors.  Sometimes it'd just best to just start over.

Don't worry about it being quite a "shopping list", I'm mainly asking about the planet packs and I'm pretty good at getting things working quickly.

**Comment by mario-head** [comment]
My playthrough is primarily focused on space stations and probes, so the list won't be too extensive:
[x] Science! Continued
DMagic Orbital Science
Kerbal Planetary Base Systems
KSP Recall
Near Future Mods (For some reason only one of them ever seems to actually install but I install them through CurseForge so I don't really know for certain)
Station Science
Stockalike Station Parts Expansion Redux
TweakScale
Harmony Modding Library
EVE-Redux
HabTech2
Kerbal Konstructs
Modular Kolonisation Systems
Modular Flight Integrator
SXT Continued
LonesomeRobot's Aeronautics: Station Parts (I had removed this originally cause it was causing Loading Part Upgrade issues but if you're able to get it working I'd be super appreciative!)

Planet Packs via Galactic Neighborhood
Arkas
Kronkus
Boris System
Chani Planet Pack
Farlo Planetary Pack
Galileo's Planet Pack
Grannus Expansion Pack
Kerbol Plus Remade
Keridani Star System
Kolyphemus
New Horizons
Other Worlds Reboot
Outer Planets Mod
Sentar Expansion
Sido's Urania Planet Pack
Sentar Expansion
Suthe Planet Overhaul
Trans-Keptunian
Uncharted Lands

**Comment by R-T-B** [comment]
Ok, I should have something done by tomorrow or this evening, thanks. :)

**Comment by R-T-B** [comment]
Ok, was able to get everything working with the notable exception of anything Galactic Neighborhood related.  That's an old mod, and Sigma has left it in a state that does not appear to work with modern releases.  The last release it was known to work with was 1.7.3, which was quite a while ago!  Worse, he left the mods with licenses that do not permit us to update them, so not much can be done there.

The good news everything else works fine.  I can advise some conventional planet packs for you if you'd just like some exploring to do.  I included Granus Expansion pack, which adds another high quality star system to explore, to get you started.

Will upload momentarily

**Comment by R-T-B** [comment]
Please try the following link to get your file, and extract the contents into your GameData folder:

https://glacialsoftware.net/ModRequest2023

I apologize in advance that my host is quite slow, but nowhere is going to really let me upload a gigabyte sized collection of mods like that for free, lol.

Happy space trails.  Will close this in a few days if all is well.

**Comment by mario-head** [comment]
All is working! The only issue I see is that only Grannus appears. I'm not sure why that is, but I'm still considering this a success given whatever magic you worked in. Thank you so much!

**Comment by R-T-B** [comment]
It only appears because I wasn't able to get Galactic Neighborhood in general working.  You'll have to find more conventional planet packs.

If you are looking for another interstellar planet pack that is high quality, I can highly advise this one:  https://forum.kerbalspaceprogram.com/topic/203753-1125-kcalbeloh-system-planet-pack-v112-a-journey-to-a-black-hole-july-29-2023/

It may need some part mods though, pretty high gravity around that black hole. ;)

Have fun!

**Comment by mario-head** [comment]
Galactic Neighborhood wasn't a planet pack, rather a mod that bundle other planet packs and reworked them to be other systems in the game. Like I said, I only used it because I didn't know of any similar mods that were more recent. If there're any alternatives you know of that are still compatible, I'd be grateful to try them out. Other than that, all's going well!
