### ISSUE TITLE
M2 related load issues

### ISSUE THREAD

**Issue by Jerryw09** [Kopernicus/Kopernicus#597]
I was trying to install Parallax, and I've got all the files needed to be installed but once booted up to the menu screen this error appears, no matter which version of Kopernicus I used it was this same error. I was asked to upload a copy of ModuleManager.ConfigCache but I can't seem to find that file inside the logs of Kopernicus so I've uploaded the other logs inside the same folder. 
https://mega.nz/file/Ft43FQqC#l1EVAolJQkjQf1HEUCQDIcpulbQ6CTuR8q0VxmKIXos 

<img width="302" alt="Screen Shot 2023-08-25 at 14 11 28" src="https://github.com/Kopernicus/Kopernicus/assets/95949383/5f88506b-a701-4156-a740-2f658e73015a">

**Comment by R-T-B** [comment]
Sorry for the delay in getting to this help request, I am looking at it now.

**Comment by R-T-B** [comment]
You are running on an Apple M2, which has known issues with the latest release of Kopernicus (see https://github.com/Kopernicus/Kopernicus/issues/575).  I can possibly help you work around those issues, but beyond that, you are running KSP 1.10.1, which is unsupported by our project.  Please update to 1.12.x and try again.  From there we may be able to get things working.  Feel free to post here if you need further help.

**Comment by R-T-B** [comment]
I am closing this for now but feel free to post if you still need help and I will reopen it.

**Comment by Jerryw09** [comment]
I tried the 1.10x version and It didn't seem to work,and Once I comment it will automatically close this issue so I'm not sure how I am able to reply to you when this issue is still opend

**Comment by R-T-B** [comment]
I'll reopen it for you.

**Comment by Jerryw09** [comment]
Here are the logs

**Comment by R-T-B** [comment]
Very good, I will look through this now.

**Comment by R-T-B** [comment]
So I did some digging, and it looks like it was THIS close to loading, but got hung up early on by some odd errors.  I will post them here and see if maybe you can make heads or tails of them?  I bolded the interseting bits.

`[WRN 12:26:06.565] LSM: ** WARNING - Game Database Loader is not where expected.
**[ERR 12:26:06.570] LSM: ERROR: Unable to access folder '/Applications/Kerbal Space Program/Safari.app/meme loading/':  Could not find a part of the path '/Applications/Kerbal Space Program/Safari.app/meme loading'.**

**[EXC 12:26:06.602] UnauthorizedAccessException: Access to the path '/Applications/Kerbal Space Program/dumb tips' is denied.**
	System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
	System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.IO.StreamReader..ctor (System.String path) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	(wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
	LoadingScreenManager.LoadingScreenManager.LoadCustomTips () (at <b0afa667b53243babbb6e96bf6e6ce96>:0)
	LoadingScreenManager.LoadingScreenManager.ModifyLoadingScreens () (at <b0afa667b53243babbb6e96bf6e6ce96>:0)
	LoadingScreenManager.LoadingScreenManager.Start () (at <b0afa667b53243babbb6e96bf6e6ce96>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)`

**Comment by Jerryw09** [comment]
That file is used for the custom loading screen, and the location should
have been */Applications/Kerbal Space Program/meme loading *not this:
*/Applications/Kerbal
Space Program/Safari.app/meme loading/,*who puts files inside the app
folder?

**Comment by R-T-B** [comment]
Well that's the origin of the problem now, I'm guessing.  Some of those paths are wrong.  Can't tell you much more than that.  Perhaps try removing that plugin, and reinstalling if needed?

**Comment by Jerryw09** [comment]
I've removed both that "memeloading" folder and the plugin itself and it
still has this error Here's the logs

**Comment by R-T-B** [comment]
You can try that of course, but there are still a lot of strange errors in your log file.  I can't guarantee anything will work with the install having so many errors, and I wouldn't know where to begin honestly.

In your situation, I know it's painful, but it may just be easiest to start from scratch, as in a fresh install.

**Comment by R-T-B** [comment]
Closing as part of a broader cleanup.  Feel free to reopen if you have new data on this issue.
