### ISSUE TITLE
Not able to load the custom planetary system due to an exception in the loading process

### ISSUE THREAD

**Issue by letouo** [Kopernicus/Kopernicus#598]
[ModuleManager.log](https://github.com/Kopernicus/Kopernicus/files/12471953/ModuleManager.log)
[MMPatch.log](https://github.com/Kopernicus/Kopernicus/files/12471954/MMPatch.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/12471955/Kopernicus.log)
[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/12471956/Kopernicus.Runtime.log)
[Gilly.Body.log](https://github.com/Kopernicus/Kopernicus/files/12471957/Gilly.Body.log)
[Kerbin.Body.log](https://github.com/Kopernicus/Kopernicus/files/12471959/Kerbin.Body.log)
[Moho.Body.log](https://github.com/Kopernicus/Kopernicus/files/12471960/Moho.Body.log)
[Sun.Body.log](https://github.com/Kopernicus/Kopernicus/files/12471961/Sun.Body.log)
[Eve.Body.log](https://github.com/Kopernicus/Kopernicus/files/12471962/Eve.Body.log)

My KSP.Log was too big to fit in here it is a total of 35 MG which seems to be a different problem

I never had a problem like this one before but all of a sudden I have this problem.

Help is greatly appriciated.

**Comment by letouo** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/12472585/KSP.log)

**Comment by R-T-B** [comment]
You are failing to load Kerbin.

It's possible this is due to the default on OnDemand changing in newer releases.  Basically, we turn it off by default now, which improves performance in genera, lbut if you run out of ram, bad things can happen.

To turn it back on:

1.) Find the Kopernicus_Config.cfg file.  It should be here:

<KSPINSTALL>/GameData/Kopernicus/Config/Kopernicus_Config.cfg

2.) Open with notepad or similar.

3.)  Change "UseOnDemandLoader = False" to "UseOnDemandLoader = True"

4.) Retest and report black, please.

**Comment by letouo** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/12476070/KSP.log)
problem still there here is the log

**Comment by R-T-B** [comment]
I see you have parallax.  Can you try temporarily removing that, as install issues with parallax can get falsely reported as a Kopernicus bug.

If you find removing it helps, try reinstalling it again paying careful attention to the directions, because you messed up somewhere (happens lol).

**Comment by letouo** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/12478410/KSP.log)
I should mention I am using Ckan to download parallax. kopernicus is a dependency of parallax so I have to download it with parallax. I uninstalled parallax and it automatically uninstalled kopernicus with it and there was no error.

**Comment by Jerryw09** [comment]
I was trying with CKAN to install but ckan says that Kopernicus conflicts and doesn't let me install so I've came across manually installing

> [KSP.log](https://github.com/Kopernicus/Kopernicus/files/12478410/KSP.log) I should mention I am using Ckan to download parallax. kopernicus is a dependency of parallax so I have to download it with parallax. I uninstalled parallax and it automatically uninstalled kopernicus with it and there was no error.

**Comment by R-T-B** [comment]
Ah I see.  If you are using CKAN an error is unlikely from parallax.

Can you try using steam to validate your games install?  Should be under game properties (right click the game in steam) then "installed files" submenu.  It should check for install damage and repair it.

If it finds nothing or does not fix the issue, not all hope is lost, but I may need a day or two to go over the logs in detail to figure it out.  Worry not, I will schedule time for you in that case.  Just let me know if it is required.

**Comment by letouo** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/12501268/KSP.log)
Here are the logs after I verified the game files. incase it helps

**Comment by R-T-B** [comment]
Sorry this is taking so long to work out.  I will try to take a look and hopefully have an answer for you over this weekend.

**Comment by R-T-B** [comment]
There is a folder in your gamedata I don't recognize, called "Custom".  Do you have any idea what mod that is associated with / what it's purpose is?  I'm in the middle of parsing your log and somewhat puzzled by it.

**Comment by letouo** [comment]
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/12505513/KSP.log)
Same error occured even when I removed the custom folder. I assume it was the Custom flags mod since it had a folder inside if called flags. thats all it had in it nothing else.

**Comment by R-T-B** [comment]
Ok, I am still poking through it, you may be right that that was a false lead and it was just the CustomFlags mod.

I think the core issue is parallax failing to load, but I am unsure why.  I will continue to look through it and update you shortly with some more ideas.

**Comment by R-T-B** [comment]
I can honestly say I've never seen an issue like this one, lol.  Sorry, I know it's no fun.

At this point I am kind of at a loss.  I tried a bunch of theories on a local install to reproduce what you have going on and none of them ended up doing this.  At this point, I would ask for screenshots of the following folders to try to see what's happening:

GameData
GameData\Parallax
GameData\Parallax_StockTextures
GameData\Kopernicus

Just post the screenshots here as jpgs, they should be permitted to upload by clicking the bottom of a post.

**Comment by R-T-B** [comment]
So parallax IS in fact installed correctly.  I suspected as much, given you use CKAN.

I honestly don't know what is erroring out here, but I have never seen it before.  I'm sorry I don't have a solution.  Let me check with some buddies of mine and see if they can't make heads or tails of this.  Will update.

**Comment by letouo** [comment]
Id like to thank you for going through all this effort. I often have problems like these when it comes to tech. I would like to say 1 thing that might be very important. When I downloaded Parallax and stuff my system language was English. I then changed it to Japanese. This shoudnt mess up anything but it actually messed up quiet some problems in my system. For example Quixel mixer (A programme to add textures to models) Didnt allow me to log in. I had this problem for 2 days untill I changed my system language back to English and allowed me to log in. However my parallax after changing still is broken. I tried to load up a game despite the error but It keept loading into the game and nothing happend. anyways I dont know much about coding but this is the most I could do. Thank you for your work.

**Comment by R-T-B** [comment]
Yeah, that likely is part of it.  Do not know how it relates but it is likely.

Could you try something on a hunch?  Try deleting settings.cfg.  This will erase all your settings so maybe make a list but might allow you to load if it is in fact, language related.

**Comment by letouo** [comment]
![image](https://github.com/Kopernicus/Kopernicus/assets/134716558/958d185c-7ef2-4a83-93cb-29c071cd466b)
I got this problem before but I fixed it by doing what it says
However I think after doing that I started getting the main error.

**Comment by letouo** [comment]
It finally works now. This was a very very very strange bug. But atleast we fixed it. Thank you for your help.
