### ISSUE TITLE
kopernicus was unable to load

### ISSUE THREAD

**Issue by TTVOmegaGaming119** [Kopernicus/Kopernicus#599]
kopernicus fails to load the sun and i have no idea why i have no mods modify the sun in any way
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/12966787/Logs-Kopernicus.zip)

**Comment by R-T-B** [comment]
You are running release-139 and KSP 1.10.1.  While that technically should work, we no longer offer bugfixes/updates on builds that are older than 1.12.x.  That being said, I can still offer some general ideas about how to fix this (if it's possible).

1.) Make sure all mods you are running are able to work with 1.10.x.  If there are any you can't validate, remove them one by one to locate the problem mod, it should be the last one you removed before the game sucesfully loads.  You can then put your other mods back in.

2.) You can also use steam to validate game integrity, in the event the game may be corrupt.  That would be done via right clicking on a game and going through it's "properties" menu.

3.) If at all possible, move to 1.12.x.  Nearly all major mods these days work with that, and you'll likely have less issues.

**Comment by TTVOmegaGaming119** [comment]
i updated to 1.12 and it still fails to load the sun and i have no mods affecting the sun in anyway

**Comment by TTVOmegaGaming119** [comment]
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/13057008/Logs-Kopernicus.zip)

**Comment by R-T-B** [comment]
I'll look at this in a few hours, thanks for updating.

**Comment by R-T-B** [comment]
The primary error that is triggering an error cascade (ending in yes, the Sun not loading) is a repeating error that looks something like this:

`[WRN 13:27:24.149] [Part]: Cannot add ModuleCargoPart as this Part 'bluedog.Apollo.AARDV.Cargo.Block1' already has a ModuleInventoryPart PartModule and they are mutually exclusive.
[EXC 13:27:24.161] InvalidOperationException: Sequence contains no matching element
	System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
	OreToParts.UtilitiesHelper.GetPartInfo (Part part, System.String moduleName) (at <5ad7bb99397d4750b2786706bb92319c>:0)
	OreToParts.OreToParts.OnAwake () (at <5ad7bb99397d4750b2786706bb92319c>:0)
	PartModule.Awake () (at <4b449f2841f84227adfaad3149c8fdba>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Object:Instantiate(GameObject)
	PartLoader:CreatePartIcon(GameObject, Single&)
	PartLoader:ParsePart(UrlConfig, ConfigNode)
	<CompileParts>d__56:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

A lot of part packs are spitting this out.  Honestly, I'm not sure where to begin.  If I were you, I might start with a fresh install, and use a mod manager like CKAN that ensures you have the right dependencies for your mods.

**Comment by TTVOmegaGaming119** [comment]
I've tried fresh install of both version 1.10 and 1.12 it throws the same error everytime and I always use ckan

**Comment by TTVOmegaGaming119** [comment]
I've spent a good 10+ hours just trying to get it to work I've never had any problems before I completely reinstalled the game and mods after not playing a few months I'm using roughly the same exact mods as well I tried removing all the custom planet mods still same error

**Comment by R-T-B** [comment]
It looks a lot like some residual data is corrupt or something, and sticking around between installs.

Are you being sure to remove the KSP folder completely from your computer after uninstall before you "start fresh?"

If so, please post a logfile with just Kopernicus and I will try to look into what is happening.

**Comment by TTVOmegaGaming119** [comment]
Yes I completely wiped it I'll have to try that tomorrow as I won't be home
till late tomorrow

**Comment by TTVOmegaGaming119** [comment]
so i got it to work with just kopernicus now gonna go through and reinstall all my mods in chunks to see what happens
