### ISSUE TITLE
Kopernicus was unable to load due to an exception during loading (KSP v1.11.1.3066, Kopernicus v1.12.197)

### ISSUE THREAD

**Issue by marcusdechant** [Kopernicus/Kopernicus#609]
Hello, I am experiencing issues loading Kopernicus, its the only mod loading, since I was running into issues with my entire suite of mods. Same old issue most have with Kopernicus acting awry during loading. I double checked the file structure to make sure it was correct.

![file structure](https://github.com/Kopernicus/Kopernicus/assets/103396632/61e1fd93-72a7-48c7-accc-1a423889086d)
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/13998521/KSP.log)
[Logs-Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/13998522/Logs-Kopernicus.zip)

what exactly do the exceptions in KSP.log mean? Specifically at [09:08:54.415], this seems to be the source of a cascading issue with loading.

**Comment by R-T-B** [comment]
It seems that the logs directory is unable to be written to, in this case it's failing to delete logs from the last run.  (Seperate enchancement note:  That really should not crash the game.)

For solving your issue, this is likely permissions related with windows somehow.  The easiest way I am aware of to fix this is probably just to delete the Logs directory.  It will be remade.  You should be able to find it in your Kerbal Space Program install directory.  It will be a directory called just "Logs."  Don't worry about anything inside it, they are just temporary log files.

After deleting it, please try rerunning.  If you still get an error, please post logs again and maybe a screenshot of your KSP install directory root (not GameData, beneath it).

Good luck.

**Comment by R-T-B** [comment]
Also of note:  We no longer support the latest releases on anything but 1.12.x.  The last release to support 1.11.x was https://github.com/Kopernicus/Kopernicus/releases/tag/release-132

It's a bit old but should still load most things ok.  Let me know if you need any further help.  Honestly upgrading to 1.12.x if possible is probably not a bad idea.

**Comment by marcusdechant** [comment]
Updated to 1.12.1. I deleted the Logs folder so it could be remade. Loaded up with only Kopernicus and no error what so ever! Thank you so much for taking the time to help me!

**Comment by marcusdechant** [comment]
Updated to 1.12.1 and everything works! I also deleted the Logs folder and everything is working correctly! Thank you so much for taking the time to help me!
