### ISSUE TITLE
Homeworld Arctic Ice Cap Issues

### ISSUE THREAD

**Issue by YWMKerman** [Kopernicus/Kopernicus#612]
I'm making Mars with an ocean and an atmosphere, but I noticed that Kopernicus seems to have forcibly added ice caps to the North Pole of the home world? (I'm pretty sure there is no ice cap at the North Pole in my Mars Height map)？
![IMG_9764](https://github.com/Kopernicus/Kopernicus/assets/78585019/375d6c64-71de-4c00-bcf3-545c565ddac2)
![IMG_9763](https://github.com/Kopernicus/Kopernicus/assets/78585019/c9727b16-180e-471a-8604-1680184b072d)
![IMG_9765](https://github.com/Kopernicus/Kopernicus/assets/78585019/19ebb2fb-b3a2-4b81-bf58-e6c9962d155b)

**Comment by R-T-B** [comment]
It must be something included in the template you used.  A PQSMod is likely the origin.  Ask around the Kopernicus discord, I'm not the best with configs but I am sure someone there will know what needs to be removed.
