### ISSUE TITLE
Infinite Loading Screen - Bug

### ISSUE THREAD

**Issue by martimcabral** [Kopernicus/Kopernicus#622]
Can't load any "new planets mod" due to Kopernicus doesn't even let the game go to the main menu.

[KSP.log](https://github.com/Kopernicus/Kopernicus/files/15472151/KSP.log)

on the KSP.log is being repeatedly writing:

[EXC 15:15:22.708] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <d2c45c7c4e8b4de19e9255b6fe9afa44>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by R-T-B** [comment]
Sorry for the delay.

It appears to be failing on the body "Nissee" which I think is part of OPM.  I see you also have Kcalbeloh installed.  It's probably an incompatability between these two, if I had to guess.  Try one or the other perhaps?

**Comment by martimcabral** [comment]
Now I only have Kopernicus installed. Everytime I start the game and after, verify the game files there is always 1 file missing.

![1](https://github.com/Kopernicus/Kopernicus/assets/83667953/a2844681-1781-4375-bd51-f3dae2a67f79)
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/15485264/KSP.log)

Installed Mods:
![modsins](https://github.com/Kopernicus/Kopernicus/assets/83667953/ffef3555-1a0e-4b9a-a616-d8f5b6c63700)

**Comment by randomguyingithub** [comment]
I guess he has another copy of opm inside that mysterious gamedata/gamedata folder.
![nRxKdIg80Z](https://github.com/Kopernicus/Kopernicus/assets/13596387/9a7161ea-80ba-44c3-98a9-163c3eadfd4b)
![notepad++_2405292250_kFuGN](https://github.com/Kopernicus/Kopernicus/assets/13596387/2e9356e0-feef-45f2-81f4-34b2c84a07ac)
Please delete that folder, reinstall opm in ckan just in case and try again.

**Comment by R-T-B** [comment]
> I guess he has another copy of opm inside that mysterious gamedata/gamedata folder.

Yep, that'll do it.  Delete that and retry.  Can't believe I missed that, lol.

**Comment by martimcabral** [comment]
The problem was solved. I had to delete the OPM folder that has in /GameData/GameData/OPM not in /GameData/OPM
