### ISSUE TITLE
Ksp not loading with kopernicus

### ISSUE THREAD

**Issue by Flight1386** [Kopernicus/Kopernicus#623]
when ever i try to load my game with kopernicus it does not load.

**Comment by Flight1386** [comment]
ive noticed at the end of the ksp.log file it repeats 

[EXC 09:50:53.368] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <16ec8083439241fd9832c29d0980bf5a>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by R-T-B** [comment]
I would need your KSP.log file from your game root to help you.

**Comment by Flight1386** [comment]
[KSPlog.zip](https://github.com/user-attachments/files/15572875/KSPlog.zip)

**Comment by R-T-B** [comment]
Thank you.  I will take a look at this as soon as I get off work, 3-4 hours from now approx.

**Comment by R-T-B** [comment]
Sorry for the delay, this seems to be your chief issue:

`[EXC 22:46:41.000] Exception: Reference body for "Irmir" could not be found. Missing body name is "Orim".
	Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (ConfigNode node) (at <e90e22fa52304913b87a71fe72842c04>:0)
	Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.ConfigParser.Parser.CreateObjectFromConfigNode[T] (ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.Injector.Awake () (at <e90e22fa52304913b87a71fe72842c04>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	Kopernicus.Injector:Awake()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(GameScenes)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)`

**Comment by Turn1thotseize** [comment]
I am also getting this error on booting KSP, game loads fully before black screening. I went through the log files and found an error telling me im missing a body called abyss: i have no extra planet mods loaded so im not sure where that has come from. 
Below is the log from the first warning i found, im not familiar with coding so im not really sure what to do with this info, so some guidance would be nice.  ill include my entire log as a TXT in case im completely off.
[KSP.log](https://github.com/user-attachments/files/16195742/KSP.log)

[WRN 10:40:28.497] Cannot find preset 'Default' for pqs 'Abyss'
[WRN 10:40:28.498] CelestialBodyTransform: Cannot find CelestialBody.
[EXC 10:40:28.504] Exception: Failed to load Body: Abyss
	Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (ConfigNode node) (at <6093f964291d41c7b236b90f913c8c8e>:0)
	Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.ConfigParser.Parser.CreateObjectFromConfigNode[T] (ConfigNode node, System.String configName, System.Boolean getChildren) (at <b81c7e09ce34479e9d3831f2ed50b754>:0)
	Kopernicus.Injector.Awake () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	Kopernicus.Injector:Awake()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(GameScenes)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
[WRN 10:40:28.510] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[LOG 10:40:28.512] [AddonLoader]: Instantiating addon 'ToolbarButton' from assembly 'Kopernicus'
[LOG 10:40:28.512] [AddonLoader]: Instantiating addon 'ShadowMan' from assembly 'Kopernicus'
[LOG 10:40:28.512] [AddonLoader]: Instantiating addon 'RenderTypeFixer' from assembly 'Kopernicus'
[LOG 10:40:28.512] [AddonLoader]: Instantiating addon 'AtmosphereFixer' from assembly 'Kopernicus'
[LOG 10:40:28.512] [AddonLoader]: Instantiating addon 'SinkingBugFix' from assembly 'Kopernicus'
[LOG 10:40:28.513] [AddonLoader]: Instantiating addon 'SystemHeat' from assembly 'SystemHeat'
[LOG 10:40:28.513] [AddonLoader]: Instantiating addon 'Waterfall' from assembly 'Waterfall'
[LOG 10:40:29.436] [Agent]: Found 19 agent mentality types
[LOG 10:40:29.439] [AgentList]: 29 agents parsed and loaded.
[LOG 10:40:29.548] [UIMasterController]: HideUI
[ERR 10:40:29.587] [PQS]: PQS Abyss already marked as started during Start() method. This is probably wrong!

[WRN 10:40:29.595] Cannot find preset 'Default' for pqs 'AbyssOcean'
[LOG 10:40:29.597] [SystemHeat][Settings]: Started loading
[LOG 10:40:29.597] [SystemHeat][Settings]: Located settings file
[LOG 10:40:29.599] [SystemHeat][Settings]: Loading coolant types 
[LOG 10:40:29.600] [SystemHeat][Settings]: Loaded coolant Basic Coolant: Density 1000, heat Capacity 4
[LOG 10:40:29.600] [SystemHeat][Settings]: Loaded coolant types
[LOG 10:40:29.600] [SystemHeat][Settings]: Finished loading
[LOG 10:40:29.600] [Waterfall][Asset Library]: Started loading
[LOG 10:40:29.600] [Waterfall][Asset Library]: Loading models
[LOG 10:40:29.600] [Waterfall][Asset Library]: Loaded 12 models
[LOG 10:40:29.600] [Waterfall][Asset Library]: Loading textures
[LOG 10:40:29.601] [Waterfall][Asset Library]: Loaded 27 textures
[LOG 10:40:29.601] [Waterfall][Asset Library]: Loading shaders
[LOG 10:40:29.602] [Waterfall][Asset Library]: Loaded 11 shaders
[LOG 10:40:29.602] [Waterfall][Asset Library]: Finished loading
[LOG 10:40:29.755] [CelestialBody]: Kerbin's solar day length is 1d, 0h, 0m long. sidereal day length is 5h, 59m, 9s long
[LOG 10:40:29.935] [TUFX-ERROR] Could not locate camera for scene: LOADING
[LOG 10:40:29.935] [TUFX] Active camera was null.  Skipping profile setup for scene: LOADING
[LOG 10:40:34.676] [UIMasterController]: HideUI
[LOG 10:40:34.682] [HighLogic]: =========================== Scene Change : From LOADING to MAINMENU =====================
[LOG 10:40:35.971] [AddonLoader]: Instantiating addon 'ContractDefs' from assembly 'KSP'
[LOG 10:40:35.999] [AddonLoader]: Instantiating addon 'ToolbarButton' from assembly 'Kopernicus'
[LOG 10:40:35.999] [AddonLoader]: Instantiating addon 'ShadowMan' from assembly 'Kopernicus'
[LOG 10:40:35.999] [AddonLoader]: Instantiating addon 'RenderTypeFixer' from assembly 'Kopernicus'
[LOG 10:40:35.999] [AddonLoader]: Instantiating addon 'AtmosphereFixer' from assembly 'Kopernicus'
[LOG 10:40:35.999] [AddonLoader]: Instantiating addon 'RuntimeUtility' from assembly 'Kopernicus'
[LOG 10:40:36.011] [AddonLoader]: Instantiating addon 'SinkingBugFix' from assembly 'Kopernicus'
[LOG 10:40:36.011] [AddonLoader]: Instantiating addon 'StarLightSwitcher' from assembly 'Kopernicus'
[LOG 10:40:36.012] [AddonLoader]: Instantiating addon 'MainMenuFixer' from assembly 'Kopernicus'
[LOG 10:40:36.021] [AddonLoader]: Instantiating addon 'SystemHeat' from assembly 'SystemHeat'
[LOG 10:40:36.022] [AddonLoader]: Instantiating addon 'Waterfall' from assembly 'Waterfall'
[EXC 10:40:36.034] NullReferenceException
	(wrapper dynamic-method) PQS.PQS.ResetSphere_Patch0(PQS)
	PSystemSetup.SetPQSInactive (System.Boolean keepActiveInFlight) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	(wrapper dynamic-method) PSystemSetup.PSystemSetup.SetMainMenu_Patch0(PSystemSetup)
	PSystemSetup.OnLevelLoaded (GameScenes level) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	PSystemSetup.OnSceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 10:40:36.823] [GameParameters]: Loaded custom parameter class CommNetParams.
[LOG 10:40:36.824] [GameParameters]: Loaded custom parameter class MissionParamsGeneral.
[LOG 10:40:36.824] [GameParameters]: Loaded custom parameter class MissionParamsFacilities.
[LOG 10:40:36.824] [GameParameters]: Loaded custom parameter class MissionParamsExtras.
[LOG 10:40:36.825] [GameParameters]: Loaded custom parameter class AdvancedParams.
[LOG 10:40:36.827] [GameParameters]: Loaded custom parameter class BdbCustomParams.
[LOG 10:40:36.827] [GameParameters]: Loaded custom parameter class SystemHeatGameSettings_NuclearFuel.
[LOG 10:40:36.827] [GameParameters]: Loaded custom parameter class SystemHeatGameSettings_Boiloff.
[LOG 10:40:36.827] [GameParameters]: Loaded custom parameter class SystemHeatGameSettings_ReactorDamage.
[LOG 10:40:36.827] [GameParameters]: Loaded custom parameter class TUFXGameSettings.
[LOG 10:40:36.836] Setting difficulty preset
[LOG 10:40:36.847] [ReflectionUtil]: Found 40 types with UpgradeModule attribute in 16 assemblies.
[WRN 10:40:36.870] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[LOG 10:40:36.885] [SystemHeat][Settings]: Started loading
[LOG 10:40:36.885] [SystemHeat][Settings]: Located settings file
[LOG 10:40:36.886] [SystemHeat][Settings]: Loading coolant types 
[LOG 10:40:36.887] [SystemHeat][Settings]: Loaded coolant Basic Coolant: Density 1000, heat Capacity 4
[LOG 10:40:36.887] [SystemHeat][Settings]: Loaded coolant types
[LOG 10:40:36.887] [SystemHeat][Settings]: Finished loading
[LOG 10:40:36.887] [Waterfall][Asset Library]: Started loading
[LOG 10:40:36.887] [Waterfall][Asset Library]: Loading models
[LOG 10:40:36.888] [Waterfall][Asset Library]: Loaded 12 models
[LOG 10:40:36.888] [Waterfall][Asset Library]: Loading textures
[LOG 10:40:36.888] [Waterfall][Asset Library]: Loaded 27 textures
[LOG 10:40:36.888] [Waterfall][Asset Library]: Loading shaders
[LOG 10:40:36.889] [Waterfall][Asset Library]: Loaded 11 shaders
[LOG 10:40:36.889] [Waterfall][Asset Library]: Finished loading
[LOG 10:40:36.889] [ModuleManager] Total loading Time = 230.650s
[EXC 10:40:36.892] IndexOutOfRangeException: Index was outside the bounds of the array.
	Kopernicus.Components.KopernicusStar.Start () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 10:40:36.897] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 10:40:36.946] [ScenarioTypes]: List Created 24 scenario types loaded from 16 loaded assemblies.
[WRN 10:40:36.958] File 'C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/KSP_x64_Data/../Missions/MissionScoreInfo.cfg' does not exist
[LOG 10:40:36.960] [TUFX] Detected change of active camera; recreating post-process objects.
[LOG 10:40:36.960] [TUFX] Enabling profile: Default-MainMenu.  Current GameScene: MAINMENU
[LOG 10:40:36.960] [TUFX] Setting HDR for camera: Landscape Camera to: False
[LOG 10:40:36.960] [TUFX-ERROR] Layer was null when attempting to update AA mode.
[LOG 10:40:36.998] [TUFX] Profile enabled: Default-MainMenu
[LOG 10:40:36.998] [ApplicationLauncher] Awake False
[LOG 10:40:37.000] [ApplicationLauncher] SpawnSimpleLayout: VerticalTopDown
[LOG 10:40:37.009] [UiApp] Awake: 
[LOG 10:40:37.010] [ApplicationLauncher] OnSceneLoadedGUIReady: scene MAINMENU ShouldBeVisible() True ShouldBeOnTop() True iIsPositionedAtTop True
[ERR 10:40:37.013] Exception handling event onLevelWasLoadedGUIReady in class <>c:System.NullReferenceException: Object reference not set to an instance of an object
  at Kopernicus.RuntimeUtility.StarLightSwitcher+<>c.<Start>b__2_1 (GameScenes scene) [0x00005] in <6093f964291d41c7b236b90f913c8c8e>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <4b449f2841f84227adfaad3149c8fdba>:0 

[EXC 10:40:37.013] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.RuntimeUtility.StarLightSwitcher+<>c.<Start>b__2_1 (GameScenes scene) (at <6093f964291d41c7b236b90f913c8c8e>:0)
	EventData`1[T].Fire (T data) (at <4b449f2841f84227adfaad3149c8fdba>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	EventData`1:Fire(GameScenes)
	<FireLoadedEventGUIReady>d__47:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[EXC 10:40:37.014] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 10:40:37.071] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 10:40:37.077] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 10:40:37.081] [UIApp] Adding  to Application Launcher
[LOG 10:40:37.084] [ApplicationLauncher] SetHidden: 
[EXC 10:40:37.086] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 10:40:37.108] [ShadowMan][Debug] Kopernicus.ShadowMan setup done
[LOG 10:40:37.109] [MessageSystem] OnAppInitialized
[LOG 10:40:37.109] [MessageSystem] Reposition 0.0632308 37758
[EXC 10:40:37.110] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <6093f964291d41c7b236b90f913c8c8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by R-T-B** [comment]
Hello, you say you have no planet pack loaded?  Can I see a screenshot of your gamedata?  Or am I misunderstanding?

**Comment by Turn1thotseize** [comment]
Hello! yes, i don't have a planet pack installed, im trying to get kopernicus working as a prereq for parallax. Im trying to replicate Matt lownes recent graphics loadout. heres my gamedata:
![Game Data](https://github.com/user-attachments/assets/a8f7d876-ccb4-41a2-8d34-e9d8936aa504)

**Comment by Turn1thotseize** [comment]
Solved- i looked around and found that configs had a set of planets that weren't loading properly, so i removed them to a separate folder and the game made it to start screen.
