### ISSUE TITLE
Drills dont work at interstellar locations as they never register ground contact

### ISSUE THREAD

**Issue by EnderiumSmith** [Kopernicus/Kopernicus#627]
When using drills on objects larger than an asteroid they never register ground contact for some reason. Distance from origin and the size of the drill seem to affect this. In some cases like closer in Cercani this seem to randomly go in and out. Around stars from GU that are at 1/100 scale it doesnt work at all from the start.

Best solution is to simply remove the check so the drills only check if the ship is landed

**Comment by R-T-B** [comment]
Interesting.  I'll look into this for next release.

You are using the latest release I assume?

**Comment by R-T-B** [comment]
Can I get a KSP.log from you following the problem?

I think I have a fix that could work and would be more elegant than just locking it to the landed state, but I would like some data from a live run of the issue to confirm.

Thanks.

**Comment by EnderiumSmith** [comment]
yes im using the latest, i didnt get the sinking bug this time despite being further out. Also i found out that simply removing the impact transform from the cfg fixes it even with another bug that causes ships to load high up in the air.

An yes i do mean on-rails asteroids

**Comment by R-T-B** [comment]
Interesting.  We will look into this.

**Comment by R-T-B** [comment]
Also you may try this experiment, it extends the collider fix to vessels (which asteroids are):

[Kopernicus-1.12.1-207dev.zip](https://github.com/user-attachments/files/16256237/Kopernicus-1.12.1-207dev.zip)

Please backup your save before running an untested beta like this, though.  I do not think it will cause you issues, but can't be too careful.

**Comment by EnderiumSmith** [comment]
i notticed the bug with versions way before 199. I found 190 to fix the sink on terrain bug at the time when the latest was like 193. The drill bug seems to be only tangentially related, it sort of worked then because the system was closer to the origin, but at 1/100 scale it never works

**Comment by R-T-B** [comment]
Yeah, I was unable to replicate it in my install, but I am admittedly just hyperediting around.  I will leave this open to remind me to look into this.

**Comment by R-T-B** [comment]
This should be fixed in modern builds, comment to reopen if it is not.
