### ISSUE TITLE
Kopernicus won't load (harmony mismatch)

### ISSUE THREAD

**Issue by baroneight** [Kopernicus/Kopernicus#628]
Kopernicus is failing to load for me.   From the KSP.log:
```
[ERR 01:48:21.064] ADDON BINDER: Cannot resolve assembly: 0Harmony, Culture=neutral, PublicKeyToken=null

[ERR 01:48:21.065] AssemblyLoader: Exception loading 'Kopernicus': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <4b449f2841f84227adfaad3149c8fdba>:0 

Additional information about this exception:

 System.IO.FileNotFoundException: Could not load file or assembly '0Harmony, Version=2.2.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```
Poking around in the Kopernicus code (Kopernicus.csproj), it looks like it wants Harmony 2.2.2.0 as a dependency, but the version of Harmony included is 2.2.1.0.   2.2.1.0 also appears to be the latest version available from the upstream github repo for harmony.

**Comment by R-T-B** [comment]
This is a bug caused by VertexHeightOblate IIRC, updating that mod should fix it.

**Comment by baroneight** [comment]
How weird.  I don't have VertexHeightOblate, or at least not explicitly .  The only planet pack I have is OPM.  Is VertexHeight embedded in something else?

**Comment by baroneight** [comment]
This commit is the one where the dependency in Kopernicus.csproj changed from 2.2.1.0 to 2.2.2.0:
https://github.com/Kopernicus/Kopernicus/commit/663f34e20cdc33b5c84c1afb17de1c1c4241d09f

**Comment by R-T-B** [comment]
That's strange.  That's just the upstream harmony we use to build Kopernicus, but I know for a fact it works with the last release of KSPHarmony (2.2.1) because that's how I play.

Can I see your complete KSP.log?  If you don't have VertexHeightOblate or a leftover folder from it somewhere (OPM would not do this) then this is new to me, and I certainly want to look into it.

PS:  Sometimes the KSP.log doesn't clear between runs, and can grow huge.  Try deleting it and running the game once to get a fresh one if it seems absurdly large, and then zipping it for good measure.  It should then upload to any file host.

**Comment by JonnyOThan** [comment]
Similar issues have been caused by installing BepinEx in ksp1.  Don’t do that.

**Comment by baroneight** [comment]
I apologize in advance for the sheer volume of mods, I am sure you're right and it is some other mod.  Appreciate the help.  This is with Kopernicus-1.12.1-206 installed 
[KSP.log](https://github.com/user-attachments/files/16258108/KSP.log)

**Comment by R-T-B** [comment]
no worries, I will look at this soon and update you.

**Comment by JonnyOThan** [comment]
@baroneight im not sure what this would have to do with harmony but you have tweakscale rescaled and KSP-recall installed which conflict.  I’d suggest cleaning out all your mods and using CKAN which should have prevented that.

**Comment by baroneight** [comment]
Thanks for the ksp-recall/tweakscale conflict.

Ok, took your advice and built up GameData from scratch (move everything to temp folder and move back a few at a time) and found the offender.  I had a library in my root folder called KEX-Wormholes.dll
Not sure how I ended up with that in my root folder, but my downloads has KEX-Wormholesbeta8.zip.  So apparently at one point I had KopernicusExpansion and didn't clean up properly?  Regardless, I think given that I only have OPM as a planet pack, I think the expansion isn't needed. 

Thank you for the help, apologies for the noise!
