### ISSUE TITLE
I think something went wrong...

### ISSUE THREAD

**Issue by MikusikSE** [Kopernicus/Kopernicus#629]
Well first of all sorry for my english in here but i kinda suck at this language, But the issue is kinda... idk how to even explain that, i did the instalation like 3 times and it didn't work anytime, just wanted to get newer version of paralax and general mod reinstall, then i finaly got the Parallax loading (the info above center of loading screen) and when i loaded up the test save this happend
![Zrzut ekranu 2024-07-16 215749](https://github.com/user-attachments/assets/f7df8124-130c-4cb5-88b8-1a68c81eb017)
if anyone can help me with instaling this to work please repley to my issue :(

**Comment by R-T-B** [comment]
Please post your KSP.log file.  It can be found whereever you installed KSP.  If it's too big, try zipping it, and/or deleting it and letting it regenerate.  Without it I can't really tell where you messed up, but I am happy to try and help if you can provide it.

**Comment by MikusikSE** [comment]
I fixed that issue but still cant install the copernicus no matter what, could we contact on discord by any chance if you have time?

**Comment by R-T-B** [comment]
I'd still need a KSP.log.  Discord wouldn't help much.

**Comment by MikusikSE** [comment]
alr gimme second

**Comment by MikusikSE** [comment]
Nvm i fixed everything just got the install craped by something else, And also i love how much efffort you put into helping people even if they are so dumb like me, honesty greate work!

**Comment by R-T-B** [comment]
lol no worries.  And you aren't dumb, just learning.  No one starts knowing everything!

Closing issue.
