### ISSUE TITLE
Rings, lockRotation = true [Not working]

### ISSUE THREAD

**Issue by Vphurple-Izumi** [Kopernicus/Kopernicus#632]
As the title says lockRotation when set to  true, does not lock the rotation of the rings, they keep spinning with the planet's rotation

**Comment by Vphurple-Izumi** [comment]
@Body[Jool]
	{
		Rings
		{
			Ring
			{
			    innerRadius = 1400
			    outerRadius = 2700
				texture = StockVisualEnhancements/Textures/Jool_ring.dds
				color = 1,1,1,1
				unlit = true
				angle = 7
				lockRotation = true
			}
		}

**Comment by R-T-B** [comment]
I will look into this, thanks.  Since I am unfamiliar with the ring code, it may not make it into next release but its on my radar now and will be fixed.

**Comment by Vphurple-Izumi** [comment]
Oh, there is no rush, I just wanted it to be known :3, keep up the good work :O

**Comment by R-T-B** [comment]
This should be fixed in the per-christmas release, any day now, just FYI.

**Comment by R-T-B** [comment]
Closing, as we fixed this.

**Comment by Vphurple-Izumi** [comment]
Okay so this is a problem once again lockRotation = true is no longer working in 227 :C
