### ISSUE TITLE
Problems with SolarPanels compatibility in multi-star mode

### ISSUE THREAD

**Issue by Aebestach** [Kopernicus/Kopernicus#633]
There are two special solar panel modules in NearFutureSolar and UniversalStorage2, ModuleCurvedSolarPanel and USSolarSwitch, which are not replaced by KopernicusSolarPanel, so they cannot correctly identify the sun in multi-star mode.

**Comment by R-T-B** [comment]
Can't believe this has not been reported before, certainly needs fixing.  It looks like we may need to code a custom module since these are not based on ModuleDeployableSolarPanel like most modules.  I'll look into this when I next get some time to work.

**Comment by Aebestach** [comment]
I also found this problem when using WeatherDrivenSolarPanel. Perhaps KOP can refer to [kerbalism](https://github.com/Kerbalism/Kerbalism/blob/f5cd99c13274599f9f8964dc162cc887e4ac85ac/src/Kerbalism/Modules/SolarPanelFixer.cs#L32) to solve this problem.

**Comment by R-T-B** [comment]
Kerbalism uses its own multistar SolarPanel logic IIRC.  It won't be of much use here because of deep integration with Kerbalism itself.

**Comment by Aebestach** [comment]
If I understand correctly, kerbalism is a separate solar panel power generation model, which has an abstract class SupportedPanel to support all solar panel modules including ModuleDeployableSolarPanel.
https://github.com/Kerbalism/Kerbalism/blob/f5cd99c13274599f9f8964dc162cc887e4ac85ac/src/Kerbalism/Modules/SolarPanelFixer.cs#L841

So can KOP also be written in this way? If this is to be achieved, the entire KopernicusSolarPanel code may need to be _rewritten_.

I am curious to ask how you think, I would like to learn from it and use it in WDSP. (But everything will wait until you have time)

**Comment by R-T-B** [comment]
We did a cost analysis and actually, there are only really two problematic modules I can find, ModuleCurvedSolarPanel  in NFS, and of course the US2 module you listed which is based on the same code.  Supporting both with the same module should be fairly trivial.  As such, to save time, I am just going to implement support for these directly rather than doing a whole rewrite.  Then we can focus on other feature requests (some of which I'm sure you know about lol) in the coming month.

**Comment by R-T-B** [comment]
Test build for this issue and NearFutureSolar:
[Kopernicus-1.12.1-207dev.zip](https://github.com/user-attachments/files/16397465/Kopernicus-1.12.1-207dev.zip)

Please test if you have time.  I think it should work and be (hopefully) bugfree!

US2 may need some coordination from the current maintainer to fix, it's hard to say.  It has a lot of options I can't just replace, so I'll have to touch bases with them before I can approach that one.

**Comment by Aebestach** [comment]
There seems to be a problem. The four solar panels are generating electricity normally, but the star cannot be selected.

**Comment by R-T-B** [comment]
I was under the impression ModuleCurvedSolarPanel was for static panels that do not need tracking, so I did not add that portion.

May need to tune that.

I may ping you on discord to discuss/test this futher, if you don't mind.

**Comment by R-T-B** [comment]
We have added support for NFS with release-207.

I will keep this open to track other modules that need custom support.

**Comment by Aebestach** [comment]
In the RSS+RO+Kcalbeloh environment, KOP cannot choose multiple stars

**Comment by R-T-B** [comment]
Thanks for your PR and work on this, considering this closed as of release-209.
