### ISSUE TITLE
Kopernicus won't work properly, stuck on infinite loading screen when I try to create a world, etc.

### ISSUE THREAD

**Issue by AndrewthepikaDev** [Kopernicus/Kopernicus#640]
When I try to load a world or go to Settings, my game is stuck on an infinite loading screen. When I launch the game, it says that Kopernicus cannot load my custom planetary system due to an "exception in the loading process". Here is the custom planetary data (I am using Outer Planets and extensions, and [Other Worlds](https://github.com/pkmniako/OtherWorlds_Public)), and my KSP.log file.

[Alnes.Body.log](https://github.com/user-attachments/files/16737055/Alnes.Body.log)
[BetterJool.Body.log](https://github.com/user-attachments/files/16737056/BetterJool.Body.log)
[Encethys.Body.log](https://github.com/user-attachments/files/16737057/Encethys.Body.log)
[Hale.Body.log](https://github.com/user-attachments/files/16737058/Hale.Body.log)
[Hypo.Body.log](https://github.com/user-attachments/files/16737059/Hypo.Body.log)
[I3-Egin.Body.log](https://github.com/user-attachments/files/16737060/I3-Egin.Body.log)
[Karen.Body.log](https://github.com/user-attachments/files/16737061/Karen.Body.log)
[Klip.Body.log](https://github.com/user-attachments/files/16737062/Klip.Body.log)
[Kopernicus.log](https://github.com/user-attachments/files/16737063/Kopernicus.log)
[Kopernicus.Runtime.log](https://github.com/user-attachments/files/16737064/Kopernicus.Runtime.log)
[Masmar.Body.log](https://github.com/user-attachments/files/16737065/Masmar.Body.log)
[Meto.Body.log](https://github.com/user-attachments/files/16737066/Meto.Body.log)
[Neidon.Body.log](https://github.com/user-attachments/files/16737067/Neidon.Body.log)
[Nissee.Body.log](https://github.com/user-attachments/files/16737068/Nissee.Body.log)
[Ovok.Body.log](https://github.com/user-attachments/files/16737069/Ovok.Body.log)
[Phabus.Body.log](https://github.com/user-attachments/files/16737070/Phabus.Body.log)
[Plock.Body.log](https://github.com/user-attachments/files/16737071/Plock.Body.log)
[Polta.Body.log](https://github.com/user-attachments/files/16737072/Polta.Body.log)
[Priax.Body.log](https://github.com/user-attachments/files/16737073/Priax.Body.log)
[Ryla.Body.log](https://github.com/user-attachments/files/16737074/Ryla.Body.log)
[Sarnus.Body.log](https://github.com/user-attachments/files/16737075/Sarnus.Body.log)
[Slate.Body.log](https://github.com/user-attachments/files/16737076/Slate.Body.log)
[Tal.Body.log](https://github.com/user-attachments/files/16737077/Tal.Body.log)
[Tekto.Body.log](https://github.com/user-attachments/files/16737078/Tekto.Body.log)
[Thatmo.Body.log](https://github.com/user-attachments/files/16737079/Thatmo.Body.log)
[Urlum.Body.log](https://github.com/user-attachments/files/16737080/Urlum.Body.log)
[Vizak.Body.log](https://github.com/user-attachments/files/16737081/Vizak.Body.log)
[Wal.Body.log](https://github.com/user-attachments/files/16737082/Wal.Body.log)

**Comment by R-T-B** [comment]
KSP.log from your install root as well please.

If it is too big tp upload,try deleting it and letting it regenerate.  Zipping may help as well.

**Comment by AndrewthepikaDev** [comment]
[KSP.log](https://github.com/user-attachments/files/16737750/KSP.log)

**Comment by R-T-B** [comment]
`[LOG 11:57:35.547] [Kopernicus]: texture does not exist! C:/Users/Andrewthepika/OneDrive/Desktop/haha/Kerbal Space Program/KSP_x64_Data/../GameData/OPX-NeidonPlus/Textures/PluginData/Gryspar_Biome.png
[LOG 11:57:36.895] [Kopernicus]: texture does not exist! C:/Users/Andrewthepika/OneDrive/Desktop/haha/Kerbal Space Program/KSP_x64_Data/../GameData/OPX-SarnusPlus/Textures/PluginData/Ovok_Biome.dds
[LOG 11:57:38.257] [Kopernicus]: texture does not exist! C:/Users/Andrewthepika/OneDrive/Desktop/haha/Kerbal Space Program/KSP_x64_Data/../GameData/OPX-SarnusPlus/Textures/PluginData/Empty_Biome.png
[LOG 11:57:38.296] [OD] Adding for body I3-Egin map named  of path = OPX-SarnusPlus/Textures/PluginData/Egin_Color.dds
[EXC 11:57:38.309] Exception: Failed to load Body: I3-Egin`

These lines in your log seem to indicate your main issue.

**Comment by AndrewthepikaDev** [comment]
So what do I do to fix it?

**Comment by R-T-B** [comment]
From this I would suggest a reinstall of the mods NeidonPlus and SarnusPlus, I think?  Its hard to say exactly because I am unfamiliar with these mods.  You may have to ask the mod author and/or remove them.

**Comment by AndrewthepikaDev** [comment]
They are addons to the Outer Planets mod, enhancing Sarnus and Neidon, respectively.

**Comment by R-T-B** [comment]
Well the issue is for whatever reason, they are missing files.

But that may not even be the show stopper.  The showstopper is whatever body is named "I3-Egin" is failing to load.  I have no idea what that body is, but something is catastriphically broken with it.

**Comment by AndrewthepikaDev** [comment]
I have removed the Outer Planets addons and a planet pack called Strange New Worlds, and I will attempt to see if it will work.

**Comment by AndrewthepikaDev** [comment]
It works, but whenever I add an interstellar planet pack, it stops working. Is there any fix?

**Comment by R-T-B** [comment]
People have played sucesfully with interstellar planet packs, so I am unsure what exactly you have going on.  Logs may help.

**Comment by AndrewthepikaDev** [comment]
Which log should I send?

**Comment by AndrewthepikaDev** [comment]
NVM it works...

**Comment by Pluspython68** [comment]
I'm having the same issue, but no system packs have been installed yet. Only parallax. 
[Uploading KSP.log…]()
