### ISSUE TITLE
Rings rotation config messed up.

### ISSUE THREAD

**Issue by Destroyer457735** [Kopernicus/Kopernicus#641]
Ive been working on a planet pack for quite a while but ran into an issue : the rings rotation are a little messed up.
lockrotation, rotationPeriod, dont do anything and longitudeOfAscendingNode does somthing other than its supposed to.
The rings seem to just be stuck to the parent bodys rotation.

I can give logs or configs if needed.

**Comment by R-T-B** [comment]
No need for logs, I have heard this reported before.  I'm not good at the shader code that manages this unfortunately but I can get some other eyes on it.  Leaving this open to track.

**Comment by Destroyer457735** [comment]
Thanks!

**Comment by YWMKerman** [comment]
This problem still occurs on my PC and I still haven't solved it. My AfterSolarSystem was still normal in July, but later I changed my PC and downloaded the latest version of Kopernicus to run ASS. I found that my ring had a similar problem, but I rolled back the Kopernicus version and it couldn't be solved.  I tried reinstalling KSP, 000_Harmony, but it still didn't work

**Comment by Destroyer457735** [comment]
Well im glad that its not just me. Hope it gets fixed sometime cause that would be really helpful for my planet pack.
No pressure, keep up the good work!

**Comment by YWMKerman** [comment]
I have found the right version of Kopernicus, version 204.  In this version, Ring is locked correctly.

**Comment by R-T-B** [comment]
This will be fixed in the soon to be coming december release, so closing (this issue is duplicate now anyways so only leaving one open).

**Comment by Destroyer457735** [comment]
> This will be fixed in the soon to be coming december release, so closing (this issue is duplicate now anyways so only leaving one open).

Thanks for the update! Can't wait!
