### ISSUE TITLE
Orbit lines

### ISSUE THREAD

**Issue by Dimimon1** [Kopernicus/Kopernicus#650]
How to fix orbit lines? JNSQ 10x Rescale
![20241018194427_1](https://github.com/user-attachments/assets/eb2e341a-6d1f-4b4e-96aa-7b1ab9f92bb8)
![20241020163836_1](https://github.com/user-attachments/assets/53304065-983f-4622-a893-1f3084e1868d)
![20241020163840_1](https://github.com/user-attachments/assets/00b22465-c2dc-40b9-8abd-ea5f87e6e548)

**Comment by YWMKerman** [comment]
Open 3Dorbit
![image](https://github.com/user-attachments/assets/9e890f0a-282c-4025-8054-b48e4d4025d6)

**Comment by Dimimon1** [comment]
> Откройте 3Dorbit: Вам нужно написать отдельный файл конфигурации, чтобы включить эту функцию. ![изображение](https://private-user-images.githubusercontent.com/78585019/379697016-9e890f0a-282c-4025-8054-b48e4d4025d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODIyNjYsIm5iZiI6MTcyOTc4MTk2NiwicGF0aCI6Ii83ODU4NTAxOS8zNzk2OTcwMTYtOWU4OTBmMGEtMjgyYy00MDI1LTgwNTQtYjQ4ZTRkNDAyNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE0NTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMzM3ZWQ5NTVkNjgxOWE4MDAyOWZlNWZmMTgwNDRiY2Y0ZDJhYjc2MGUxYzY4ZDllZGNiYzMwMmY5NTExOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CMjOU_nqXcwvm7cMXqqUl93ImCL7XQs5FbuPfF8i4JY)

i love u, thanks
