### ISSUE TITLE
kopernicus don't work with parallax continued

### ISSUE THREAD

**Issue by olm349** [Kopernicus/Kopernicus#653]
[ModuleManager.zip](https://github.com/user-attachments/files/17835744/ModuleManager.zip)
[ModuleManager.zip](https://github.com/user-attachments/files/17835746/ModuleManager.zip)
[Logs-Kopernicus.zip](https://github.com/user-attachments/files/17835800/Logs-Kopernicus.zip)

**Comment by R-T-B** [comment]
I would try validating your game files in steam.  It looks like some kind of stock file corruption, it's failing to load around Moho.

**Comment by olm349** [comment]
everything works! Thanks for still supporting kopernikus
