### ISSUE TITLE
Error upon startup even after reinstalling everything related to Kopernicus

### ISSUE THREAD

**Issue by NotSoCommonSense** [Kopernicus/Kopernicus#654]
![Screenshot 2024-12-17 181553](https://github.com/user-attachments/assets/11873bd5-3ed6-409c-9a47-f4d327115dc3)
![Screenshot 2024-12-17 181501](https://github.com/user-attachments/assets/2b6353b9-da82-4a53-90a1-701df146113c)
[KSP.txt](https://github.com/user-attachments/files/18174788/KSP.txt)
[Kopernicus.log](https://github.com/user-attachments/files/18174789/Kopernicus.log)

I started having this issue after the game crashed when I loaded a Mun space station. I had absolutely no problems for several months before that and didn't add or remove any mods at all really. I even loaded my Duna space station right beforehand and it worked perfectly fine. Also validated files in Steam several times.

**Comment by Destroyer457735** [comment]
What does the inside of your kopernicus folder look like? When opening it do you see game data?

**Comment by NotSoCommonSense** [comment]
> What does the inside of your kopernicus folder look like? When opening it do you see game data?
![Screenshot 2024-12-18 112245](https://github.com/user-attachments/assets/f80c10f1-76ae-40d8-9b0e-f93746d6361b)
This is what I see

**Comment by NotSoCommonSense** [comment]
Even after uninstalling EVERY other mod (except dependencies) it still spits out that error. It seems like it's failing to load Moho.
[Kopernicus.log](https://github.com/user-attachments/files/18193292/Kopernicus.log)
[KSP.log](https://github.com/user-attachments/files/18193297/KSP.log)

**Comment by R-T-B** [comment]
Things like this usually are the result of a broken dependency install somehow.  That said everything looks correct in the screenshots above...  very weird.

I'd try using CKAN to manage your mods if able to do so.  Sometimes it can catch things human eyes miss.

**Comment by NotSoCommonSense** [comment]
I am using CKAN. Never installed a mod manually. Tried several times to reinstall Kopernicus + dependencies with CKAN to no avail. (Yes I did purge from cache before reinstalling)

**Comment by R-T-B** [comment]
That's even more odd.  I will look at this in more detail tomorrow morning some time and try to figure out why you are having this issue.  Stay tuned, as I may request more data.

**Comment by R-T-B** [comment]
Are you by chance using the new parallax 2.0 version?  If so make sure you have the KSP burst depedency, I do not believe CKAN knows about it yet:

https://github.com/KSPModdingLibs/KSPBurst/releases

**Comment by NotSoCommonSense** [comment]
I did try to use Parallax 2.0 some time ago but it didn't work, that was like several weeks ago though.

And regardless, I don't understand how it would stop Kopernicus from loading a stock planet (Moho) also with everything else uninstalled. Verified files too.

I'm contemplating doing a complete reinstall of the game, but I'll wait for your thoughts

**Comment by R-T-B** [comment]
Your log shows files left in GameData from parallax.

My advice would be to go into GameData and ensure only the "Squad" folder and if applicable "SquadExpansion" folder are present.  Then work from there.

Because of how Parallax loads with a planets PQS if it is installed but not working it would fail on the first planet with a real surface, Moho.  It does kind of add up.

**Comment by NotSoCommonSense** [comment]
It's fixed!!!

I removed all the folders except Squad, then reinstalled Kopernicus, then reinstalled my mods from a .ckan file I made. Everything is working as intended now, I can go to all my crafts etc.

Thanks for the help, I greatly appreciate it!
