### ISSUE TITLE
Terrain glitches when timewarping in Space Center scene and launching through launchpad (might only occur when Kerbin is reparented)

### ISSUE THREAD

**Issue by magico13** [Kopernicus/Kopernicus#75]
I'm the developer for Kerbal Construction Time and I keep seeing reports of KCT and New Horizons not working together and causing tons of terrain glitches (which then get blamed on KCT). I determined that it is actually a Kopernicus bug that appears to happen when you timewarp at high rates while in the space center scene (might just require a large displacement of Kerbin, since the more you timewarp the worse it gets) and then launch a craft without first changing the scene (by clicking the launchpad or runway, perhaps by clicking on a vessel that's near KSC but I haven't tested that). It seems to happen only when Kerbin is reparented, as I could reproduce it in New Horizons and Alternis Kerbol, but not with just Kopernicus.

I also reported it on the forum [here](http://forum.kerbalspaceprogram.com/threads/114649-1-0-4-Kopernicus-Beta-%280-2-4%29-July-24?p=2117647&viewfull=1#post2117647), and on the New Horizons thread [here](http://forum.kerbalspaceprogram.com/threads/114092-1-0-4-Kopernicus-New-Horizons-v1-6-3-6Aug15-Polished%21?p=2116821&viewfull=1#post2116821) but nobody seemed to notice it. Those posts have pictures and a log file.

The problem also appears to happen if you load the game, then a save, and launch immediately without timewarping or changing scenes.

If you need any other info, let me know.

For the time being I'm advising everyone who uses KCT with New Horizons to timewarp in the Tracking Station, then switch back to the Space Center to launch.

**Comment by ArnePeirs** [comment]
Have you tested it with a pack that doesn't reparent Kerbin

**Comment by magico13** [comment]
Only got a chance to test with KScale2 and with just Kopernicus and didn't have it happen with those. I don't really ever use Kopernicus for anything, and only a few of KCT's users do, so I didn't spend more than a few hours trying to figure this out.

**Comment by Olympic1** [comment]
I tried it with OPM, Trans-Keptunian and Other_Worlds and it doesn't create any terrain glitches. Then I tried it with New Horizons and Alternis Kerbol and I got terrain glitches like magico already explained. So it definitely only occurs when Kerbin is reparented.

**Comment by ThomasKerman** [comment]
Well, that is one of theese "when Kerbin is reparented".issues....
Unfortunately, I can't find a reason why the Game does this weird stuff. I've tried to debug the whole PSystem-Transform, but no results. I guess the answer is somewhere in theese classes, who are deserialized on start. I'm sorry, but I can't fix this a the moment. :(

**Comment by ThomasKerman** [comment]
Someone should try this again, with the new PostSpawnOrbit functionality.

**Comment by Sigma88** [comment]
I haven't experienced this in a long time

**Comment by Sigma88** [comment]
I think it's safe to close this issue

If any of you has reasons why this should not be closed, speak now or forever hold your peace. 😆
