### ISSUE TITLE
Rings let orbits dissappear

### ISSUE THREAD

**Issue by Olympic1** [Kopernicus/Kopernicus#80]
Title says it all

When viewing from above the rings:
![Only half of orbit](http://i60.tinypic.com/9gx1c0.jpg)

When viewing from under the rings:
![Only half of orbit](http://i57.tinypic.com/9h8g42.jpg)

**Comment by Sigma88** [comment]
yeah, rings are rendered over the orbits.
I've noticed that too :)
I wasn't sure and I didn't have the time to check properly, but I think it's something similar to the EVE clouds issue

**Comment by ThomasKerman** [comment]
Fixed: https://github.com/Kopernicus/Kopernicus/commit/5264f67ea3c95b8f071b4f2675af118969e8a3cf
