### ISSUE TITLE
Possibility of a download without the examples?

### ISSUE THREAD

**Issue by Dazpoet** [Kopernicus/Kopernicus#82]
Hi there!

I'm wondering if it would be possible to supply a version in your releases that does not include all the examples? I find myself downloading ~44MB but the part I want is only ~500KB (the Kopernicus folder inside GameData).

I've no idea how hard/easy such a thing would be but I thought I'd throw it out there :)

**Comment by Sigma88** [comment]
http://forum.kerbalspaceprogram.com/threads/114649-1-0-4-Kopernicus-Beta-%280-3-1%29-August-23?p=2159323&viewfull=1#post2159323

**Comment by Dazpoet** [comment]
Seems I wasn't alone in this line of thought, seeing as it's coming soon I'll close this, thanks!
