### ISSUE TITLE
finalizeOrbits overwrites custom sphereOfInfluence

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#84]
when finalizeOrbits is used any body that has it's sphereOfInfluence set in the config will have it's SoI recalculated

this may add some issues (not only with sigmabinary) but also with mods that set their SoI

for example New Horizon has two planets on really close orbits (around a third body) and sets the SoI in order to avoid overlapping SoIs

**Comment by ThomasKerman** [comment]
Fixed: https://github.com/Kopernicus/Kopernicus/commit/e70b466964c6bd20bca962a72d31cf990d0f32c5

**Comment by Sigma88** [comment]
:+1:  thomas you're the best :)

**Comment by Tellion** [comment]
merci :)
