### ISSUE TITLE
Cannot Start RSS Game With Particular RSS config epoch

### ISSUE THREAD

**Issue by Arrowstar** [Kopernicus/Kopernicus#85]
In the RSS Kopernicus config file, if you change the Epoch entry to "Epoch = -2524614641.784" and start KSP, you will not be able to start a new game of KSP. Try this on a clean install of KSP that has not been started and that has no existing save games.

**Comment by Arrowstar** [comment]
Submitted per NathanKell

**Comment by NathanKell** [comment]
@ThomasKerman, @Arrowstar just asked whether it might be due to int overflows. While epoch itself is a double, plenty of stuff ingame is based off signed ints, so that might be a place to look (though AFAIK even if UT goes over 67 years, just the text displays freak, everything else is fine).

**Comment by NathanKell** [comment]
I have not been able to find anything in stock KSP to die from that, though I need to write a quick plugin to verify that. @Arrowstar I don't suppose you recall what the logs show, both in the output log from KSP and from Kopernicus's logs?

**Comment by Arrowstar** [comment]
I don't, sorry. Since I can't even really start a game, I didn't think to look. Can you reproduce this on your system?

**Comment by NathanKell** [comment]
@Arrowstar sorry, got sidetracked _again_. Apologies for, evidently, not being in time. :(

**Comment by ThomasKerman** [comment]
Has this issue been resolved or is it still present? (Pinging @NathanKell and @Arrowstar )

**Comment by Arrowstar** [comment]
I would imagine it is still present unless someone can demonstrate they've taken steps to resolve it.

**Comment by Sigma88** [comment]
@Arrowstar  I use the Epoch feature in my mod [SASS](https://github.com/sigma88/stockalike) and it works fine.
are you sure it is still broken for RSS?

**Comment by Sigma88** [comment]
@NathanKell  any idea if this is still a bug?

**Comment by Sigma88** [comment]
I'm fairly sure this has been solved
If not feel free to reopen it
