### ISSUE TITLE
View distance for new bodies

### ISSUE THREAD

**Issue by NathanKell** [Kopernicus/Kopernicus#89]
@Raidernick reports that distant bodies in RSS aren't visible, even though bodies at longer distances in stock KSP are.

AFAIK (and from digging) Kopernicus doesn't mess with any draw distances, so the stock one should be maintained. Any ideas?

**Comment by ThomasKerman** [comment]
As per IRC, this code stops to render a planet as soon as it is smaller than one pixel, while ignoring the FlightCameras FOV settings. That is not something Kopernicus can change unfortunately.

**Comment by NathanKell** [comment]
Scaled space fader is just a component on the CB which Kopernicus can certainly replace. Also there's a multiplier added in 1.1 so you don't even need to replace the component, just change the multiplier.

**Comment by ThomasKerman** [comment]
Oh awesome! I will add that then :]

**Comment by Sigma88** [comment]
I guess we can close this right? :D
