### ISSUE TITLE
Trying to convert a number to an int32 fails when number is too big

### ISSUE THREAD

**Issue by linuxgurugamer** [Kopernicus/Kopernicus#93]
There was a posting this morning where someone asked for help.  It was obvious after looking at the log files that the numeric parser is failing because the number being parsed is larger than the largest possible int32 value:

[LOG 06:55:36]: Inner Exception Was Recorded: Value is too large
  at System.Int32.Parse (System.String s) [0x00000] in <filename unknown>:0 

You may want to put a try/catch around it

**Comment by ThomasKerman** [comment]
I'll do that for 0.5 ;)

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/Kopernicus/Kopernicus/commit/d6aeb447957ca20470d00a2bd45fa6e1d658049d

Sorry, took me a while to do it
