### ISSUE TITLE
maximum viewing distance

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#99]
maximum viewing distance of the map view camera seems to check only for bodies that have "referenceBody = Sun"

so if I make a Sun-Jool binary, the max camera distance will be the distance from Kerbol to the barycenter (which has name = Sun)

This may be an issue if someone wants to make a planet pack that changes the Stock system to orbit around a binary star, with the two star orbiting close together and the rest of the planets orbiting far away

**Comment by ThomasKerman** [comment]
Added an override for max view distance with https://github.com/Kopernicus/Kopernicus/commit/5db5e133b44827172aa12cfbe76d2ee74b1dc1f8

A recursive function for this would bring so many bugs... But this could  create some funny config possibilities
